"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { FormSheet } from "@/components/form-sheet";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import type { ApiError,FoodDish,FoodPlaceDetail,FoodPlaceStatus,TasteRating } from "@/lib/types";

const ratingLabels:Record<TasteRating,string>={love:"喜欢",good:"还不错",neutral:"一般",dislike:"避雷"};
const statusLabels:Record<FoodPlaceStatus,string>={frequent:"常吃",occasional:"偶尔吃",paused:"暂时不点",avoid:"避雷",closed:"已关闭"};
const emptyDish={name:"",category:"",rating:"" as TasteRating|"",recommended:false,notes:""};

export function FoodPlaceDetailView({id}:{id:number}){
  const router=useRouter();
  const[data,setData]=useState<FoodPlaceDetail|null>(null),[notFound,setNotFound]=useState(false),[panel,setPanel]=useState<"place"|"dish"|null>(null),[editingDish,setEditingDish]=useState<FoodDish|null>(null),[placeDraft,setPlaceDraft]=useState({name:"",branch:"",category:"",rating:"" as TasteRating|"",status:"occasional" as FoodPlaceStatus,notes:""}),[dishDraft,setDishDraft]=useState(emptyDish),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const response=await fetch(`/api/food/places/${id}`);if(response.status===404){setNotFound(true);return;}if(response.ok){const next=await response.json() as FoodPlaceDetail;setData(next);setPlaceDraft({name:next.place.name,branch:next.place.branch,category:next.place.category,rating:next.place.rating??"",status:next.place.status,notes:next.place.notes});}},[id]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  async function savePlace(event:FormEvent){event.preventDefault();setSaving(true);setError("");const response=await fetch(`/api/food/places/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...placeDraft,rating:placeDraft.rating||null})});setSaving(false);if(!response.ok){setError(((await response.json())as ApiError).error);return;}setPanel(null);setNotice("店铺信息已更新");await load();}
  function openDish(item?:FoodDish){setEditingDish(item??null);setDishDraft(item?{name:item.name,category:item.category,rating:item.rating??"",recommended:item.recommended,notes:item.notes}:emptyDish);setError("");setPanel("dish");}
  async function saveDish(event:FormEvent){event.preventDefault();setSaving(true);setError("");const response=await fetch(editingDish?`/api/food/dishes/${editingDish.id}`:`/api/food/places/${id}/dishes`,{method:editingDish?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...dishDraft,rating:dishDraft.rating||null})});setSaving(false);if(!response.ok){setError(((await response.json())as ApiError).error);return;}setPanel(null);setEditingDish(null);setNotice(editingDish?"菜品已更新":"菜品已添加");await load();}
  async function removeDish(item:FoodDish){if(!confirm(`删除「${item.name}」？有关联饮食记录时只会归档。`))return;const response=await fetch(`/api/food/dishes/${item.id}`,{method:"DELETE"});if(response.ok){const result=await response.json() as{action:"deleted"|"archived"};setNotice(result.action==="archived"?"菜品已归档，历史饮食记录保持不变":"菜品已删除");await load();}}
  async function removePlace(){if(!data||!confirm(`删除「${data.place.name}」？有关联饮食记录时会归档并标记为已关闭。`))return;const response=await fetch(`/api/food/places/${id}`,{method:"DELETE"});if(response.ok){const result=await response.json() as{action:"deleted"|"archived"};if(result.action==="deleted")router.push("/food/places");else{setNotice("店铺已归档并标记为已关闭，历史记录保持不变");await load();}}}
  if(notFound)return <div className="page"><div className="empty-state"><h2>店铺不存在</h2><Link className="button secondary" href="/food/places">返回店铺库</Link></div></div>;
  if(!data)return <div className="page"><div className="empty-state compact-empty"><p>正在读取店铺…</p></div></div>;
  const{place,dishes,recentFoodLogs}=data;
  return <div className="page food-place-detail-page"><PageHeader eyebrow="FOOD · 店铺库" title={place.name} description={place.branch||undefined} action={<button className="button secondary" onClick={()=>setPanel("place")}><Icon name="edit"/>编辑</button>}/>
    {notice&&<p className="form-notice">{notice}</p>}
    <section className="food-place-profile"><div className="food-place-tags">{place.category&&<span>{place.category}</span>}{place.rating&&<span className={`rating-${place.rating}`}>{ratingLabels[place.rating]}</span>}<span>{statusLabels[place.status]}</span></div>{place.notes&&<p>{place.notes}</p>}<small>{place.lastVisitedAt?`最近吃过：${new Date(place.lastVisitedAt).toLocaleString("zh-CN")}`:"还没有关联的饮食记录"} · 共 {place.visitCount} 次</small></section>
    <section className="food-place-section"><div className="section-heading"><div><span className="eyebrow">DISHES</span><h2>菜品</h2></div><button className="button primary compact" onClick={()=>openDish()}><Icon name="plus"/>新增菜品</button></div>{dishes.length?<div className="food-dish-list">{dishes.map(dish=><article className={`food-dish-row rating-${dish.rating??"none"}`} key={dish.id}><button className="food-dish-copy" onClick={()=>openDish(dish)}><strong>{dish.recommended&&<span className="recommended-mark">荐</span>}{dish.name}</strong><span>{[dish.category,dish.rating?ratingLabels[dish.rating]:"未评价",dish.eatCount?`吃过 ${dish.eatCount} 次`:""].filter(Boolean).join(" · ")}</span>{dish.notes&&<small>{dish.notes}</small>}</button><button className="row-icon-button danger" aria-label={`删除 ${dish.name}`} onClick={()=>void removeDish(dish)}><Icon name="trash"/></button></article>)}</div>:<div className="empty-state compact-empty"><p>还没有记录这家店的菜品。</p></div>}</section>
    <section className="food-place-section"><div className="section-heading"><div><span className="eyebrow">RECENT</span><h2>最近关联的饮食</h2></div></div>{recentFoodLogs.length?<div className="food-place-log-list">{recentFoodLogs.map(log=><article key={log.id}><time>{new Date(log.occurredAt).toLocaleDateString("zh-CN")}</time><div><strong>{log.title}</strong>{log.foodDishName&&<span>{log.foodDishName}</span>}</div><small>{log.rating?ratingLabels[log.rating]:""}</small></article>)}</div>:<div className="empty-state compact-empty"><p>还没有 Food Record 关联到这家店。</p></div>}</section>
    <div className="food-place-detail-actions"><Link className="section-link" href="/food/places">返回店铺库 <Icon name="arrow"/></Link><button className="danger-text" onClick={()=>void removePlace()}>删除或归档店铺</button></div>
    {panel==="place"&&<FormSheet title="编辑店铺" onClose={()=>setPanel(null)} formId="food-place-edit-form" submitLabel="保存修改" busy={saving}><form id="food-place-edit-form" className="editor-card compact-editor" onSubmit={savePlace}><div className="form-grid"><label className="field"><span>店铺名称</span><input required value={placeDraft.name} onChange={event=>setPlaceDraft({...placeDraft,name:event.target.value})}/></label><label className="field"><span>分店 / 门店</span><input value={placeDraft.branch} onChange={event=>setPlaceDraft({...placeDraft,branch:event.target.value})}/></label><label className="field"><span>品类</span><input value={placeDraft.category} onChange={event=>setPlaceDraft({...placeDraft,category:event.target.value})}/></label><label className="field"><span>总体评价</span><select value={placeDraft.rating} onChange={event=>setPlaceDraft({...placeDraft,rating:event.target.value as TasteRating|""})}><option value="">未评价</option>{Object.entries(ratingLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>状态</span><select value={placeDraft.status} onChange={event=>setPlaceDraft({...placeDraft,status:event.target.value as FoodPlaceStatus})}>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field wide"><span>备注</span><textarea rows={4} value={placeDraft.notes} onChange={event=>setPlaceDraft({...placeDraft,notes:event.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}</form></FormSheet>}
    {panel==="dish"&&<FormSheet title={editingDish?"编辑菜品":"新增菜品"} onClose={()=>setPanel(null)} formId="food-dish-form" submitLabel={editingDish?"保存修改":"添加菜品"} busy={saving}><form id="food-dish-form" className="editor-card compact-editor" onSubmit={saveDish}><div className="form-grid"><label className="field"><span>菜名</span><input required autoFocus value={dishDraft.name} onChange={event=>setDishDraft({...dishDraft,name:event.target.value})}/></label><label className="field"><span>品类</span><input value={dishDraft.category} onChange={event=>setDishDraft({...dishDraft,category:event.target.value})}/></label><label className="field"><span>评价</span><select value={dishDraft.rating} onChange={event=>setDishDraft({...dishDraft,rating:event.target.value as TasteRating|""})}><option value="">未评价</option>{Object.entries(ratingLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field checkbox-field"><input type="checkbox" checked={dishDraft.recommended} onChange={event=>setDishDraft({...dishDraft,recommended:event.target.checked})}/><span>推荐这道菜</span></label><label className="field wide"><span>备注</span><textarea rows={4} value={dishDraft.notes} onChange={event=>setDishDraft({...dishDraft,notes:event.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}</form></FormSheet>}
  </div>;
}
