"use client";
import { SearchableSelect } from "@/components/searchable-select";
import { drinkRecordName } from "@/lib/drink-display";
import { ToastNotice, showActionToast } from "@/components/action-toast";

import { FoodDeleteAction } from "../../food-delete-action";
import Link from "next/link";
import { DrinkRecordEditor, temperatureLabels, tasteLabels as drinkTasteLabels } from "../../../drinks/drink-ui";
import { placeSupports, placeServiceLabels } from "@/lib/place-menu";
import type { FoodPlace } from "@/lib/types";
import { foodRecordDisplay } from "@/lib/food-record-display";
import { useRouter } from "next/navigation";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { FormSheet } from "@/components/form-sheet";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import { PlaceSuggestionFields } from "../place-location-fields";
import type { DrinkLog,DrinkInputSuggestions,ApiError,FoodDish,FoodPlaceDetail,FoodPlaceStatus,TasteRating } from "@/lib/types";

const ratingLabels:Record<TasteRating,string>={love:"喜欢",good:"还不错",neutral:"一般",dislike:"避雷"};
const statusLabels:Record<FoodPlaceStatus,string>={frequent:"常去",occasional:"偶尔去",paused:"暂时不去",avoid:"避雷",closed:"已关闭"};
const emptyDish={kind:"food" as "food"|"drink",name:"",category:"",rating:"" as TasteRating|"",recommended:false,notes:""};

export function FoodPlaceDetailView({id}:{id:number}){
  const router=useRouter();
  const [editingDrink,setEditingDrink]=useState<DrinkLog>();
  const [drinkSuggestions,setDrinkSuggestions]=useState<DrinkInputSuggestions>({names:[],brands:[]});
  async function openDrink(log:DrinkLog){setEditingDrink(log);try{const response=await fetch("/api/drinks/suggestions");if(response.ok)setDrinkSuggestions(await response.json());}catch{/* Suggestions are optional. */}}
  const[data,setData]=useState<FoodPlaceDetail|null>(null),[notFound,setNotFound]=useState(false),[panel,setPanel]=useState<"place"|"dish"|null>(null),[editingDish,setEditingDish]=useState<FoodDish|null>(null),[placeDraft,setPlaceDraft]=useState({serviceType:"food" as FoodPlace["serviceType"],name:"",branch:"",city:"",location:"",category:"",rating:"" as TasteRating|"",status:"occasional" as FoodPlaceStatus,notes:""}),[dishDraft,setDishDraft]=useState(emptyDish),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const response=await fetch(`/api/food/places/${id}`);if(response.status===404){setNotFound(true);return;}if(response.ok){const next=await response.json() as FoodPlaceDetail;setData(next);setPlaceDraft({serviceType:next.place.serviceType??"food",name:next.place.name,branch:next.place.branch,city:next.place.city??"",location:next.place.location??"",category:next.place.category,rating:next.place.rating??"",status:next.place.status,notes:next.place.notes});}},[id]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  async function savePlace(event:FormEvent){event.preventDefault();setSaving(true);setError("");const response=await fetch(`/api/food/places/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...placeDraft,rating:placeDraft.rating||null})});setSaving(false);if(!response.ok){setError(((await response.json())as ApiError).error);return;}setPanel(null);setNotice("店铺信息已更新");await load();}
  function openDish(item?:FoodDish,kind:"food"|"drink"="food"){setEditingDish(item??null);setDishDraft(item?{kind:item.kind??"food",name:item.name,category:item.category,rating:item.rating??"",recommended:item.recommended,notes:item.notes}:{...emptyDish,kind});setError("");setPanel("dish");}
  async function saveDish(event:FormEvent){event.preventDefault();setSaving(true);setError("");const response=await fetch(editingDish?`/api/food/dishes/${editingDish.id}`:`/api/food/places/${id}/dishes`,{method:editingDish?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...dishDraft,rating:dishDraft.rating||null})});setSaving(false);if(!response.ok){setError(((await response.json())as ApiError).error);return;}setPanel(null);setEditingDish(null);setNotice(`${dishDraft.kind==="drink"?"饮品":"菜品"}${editingDish?"已更新":"已添加"}`);await load();}
  async function removeDish(item:FoodDish){
    if(saving)return;setSaving(true);
    try{const response=await fetch(`/api/food/dishes/${item.id}`,{method:"DELETE"});if(!response.ok)throw new Error(`无法删除${item.kind==="drink"?"饮品":"菜品"}，请重试`);const result=await response.json() as{action:"deleted"|"archived"};setPanel(null);setEditingDish(null);setNotice(`${item.kind==="drink"?"饮品":"菜品"}${result.action==="archived"?"已归档，历史记录保持不变":"已删除"}`);await load();}finally{setSaving(false);}
  }
  async function removePlace(){
    if(!data||saving)return;setSaving(true);
    try{const response=await fetch(`/api/food/places/${id}`,{method:"DELETE"});if(!response.ok)throw new Error("无法删除店铺，请重试");const result=await response.json() as{action:"deleted"|"archived"};setPanel(null);if(result.action==="deleted"){showActionToast("店铺已删除","deleted");router.push("/food/places");}else{setNotice("店铺已归档并标记为已关闭，历史记录保持不变");await load();}}finally{setSaving(false);}
  }
  if(notFound)return <div className="page"><div className="empty-state"><h2>店铺不存在</h2><Link className="button secondary" href="/food/places">返回店铺库</Link></div></div>;
  if(!data)return <div className="page"><div className="empty-state compact-empty"><p>正在读取店铺…</p></div></div>;
  const{place,dishes,recentFoodLogs,recentDrinkLogs,drinkMenu}=data;
  const isDrinkMenu=dishDraft.kind==="drink";;
  return <div className="page food-place-detail-page"><PageHeader eyebrow="FOOD · DRINKS · 店铺库" title={place.name} description={[place.city,place.location,place.branch].filter(Boolean).join(" · ")||undefined} action={<button className="button secondary" onClick={()=>setPanel("place")}><Icon name="edit"/>编辑</button>}/>
    {notice&&<ToastNotice message={notice} onShown={() => setNotice("")} />}
    <section className="food-place-profile"><div className="food-place-tags">{place.category&&<span>{place.category}</span>}{place.rating&&<span className={`rating-${place.rating}`}>{ratingLabels[place.rating]}</span>}<span>{placeServiceLabels[place.serviceType??"food"]}</span><span>{statusLabels[place.status]}</span></div>{place.notes&&<p>{place.notes}</p>}<small>{place.lastVisitedAt?`最近到访：${new Date(place.lastVisitedAt).toLocaleDateString("zh-CN")}`:"还没有关联的饮食记录"}{placeSupports(place,"food")&&` · 吃过 ${place.foodVisitCount??place.visitCount} 次`}{placeSupports(place,"drink")&&` · 喝过 ${place.drinkVisitCount??0} 次`}</small></section>
    {placeSupports(place,"food")&&<><section className="food-place-section"><div className="section-heading"><div><span className="eyebrow">DISHES</span><h2>菜品</h2></div><button className="button primary compact" onClick={()=>openDish()}><Icon name="plus"/>新增菜品</button></div>{dishes.length?<div className="food-dish-list">{dishes.map(dish=><article className={`food-dish-row rating-${dish.rating??"none"}`} key={dish.id}><button className="food-dish-copy" onClick={()=>openDish(dish)}><strong>{dish.recommended&&<span className="recommended-mark">荐</span>}{dish.name}</strong><span>{[dish.category,dish.rating?ratingLabels[dish.rating]:"未评价",dish.eatCount?`吃过 ${dish.eatCount} 次`:""].filter(Boolean).join(" · ")}</span>{dish.notes&&<small>{dish.notes}</small>}</button><button className="row-icon-button" aria-label={`编辑 ${dish.name}`} onClick={()=>openDish(dish)}><Icon name="edit"/></button></article>)}</div>:<div className="empty-state compact-empty"><p>还没有记录这家店的菜品。</p></div>}</section></>}
    {placeSupports(place,"drink")&&<><section className="food-place-section"><div className="section-heading"><div><span className="eyebrow">DRINK MENU</span><h2>饮品菜单</h2></div><button className="button primary compact" onClick={()=>openDish(undefined,"drink")}><Icon name="plus"/>新增饮品</button></div>{drinkMenu.length?<div className="food-dish-list">{drinkMenu.map(dish=><article className={`food-dish-row rating-${dish.rating??"none"}`} key={dish.id}><button className="food-dish-copy" onClick={()=>openDish(dish)}><strong>{dish.recommended&&<span className="recommended-mark">荐</span>}{dish.name}</strong><span>{[dish.category,dish.rating?ratingLabels[dish.rating]:"未评价",dish.eatCount?`喝过 ${dish.eatCount} 次`:""].filter(Boolean).join(" · ")}</span>{dish.notes&&<small>{dish.notes}</small>}</button><button className="row-icon-button" aria-label={`编辑 ${dish.name}`} onClick={()=>openDish(dish)}><Icon name="edit"/></button></article>)}</div>:<div className="empty-state compact-empty"><p>还没有记录这家店的饮品菜单。</p></div>}</section></>}
    {(placeSupports(place,"food")||recentFoodLogs.length>0)&&<><section className="food-place-section"><div className="section-heading"><div><span className="eyebrow">RECENT</span><h2>最近关联的饮食</h2></div></div>{recentFoodLogs.length?<div className="food-place-log-list">{recentFoodLogs.map(log=>{const display=foodRecordDisplay(log);return <article key={log.id}><time>{new Date(log.occurredAt).toLocaleDateString("zh-CN")}</time><div><strong className="user-content">{display.title}</strong>{display.dishes.length>0&&<div className="food-linked-dishes">{display.dishes.map(dish=><span className="user-content" key={dish.id}>{dish.name}</span>)}</div>}</div><small>{log.rating?ratingLabels[log.rating]:""}</small></article>;})}</div>:<div className="empty-state compact-empty"><p>还没有 Food Record 关联到这家店。</p></div>}</section></>}
    {(placeSupports(place,"drink")||recentDrinkLogs.length>0)&&<><section className="food-place-section"><div className="section-heading"><div><span className="eyebrow">DRINKS</span><h2>最近关联的饮品</h2></div></div>{recentDrinkLogs.length?<div className="food-place-log-list">{recentDrinkLogs.map(log=><article key={log.id}><time>{new Date(log.occurredAt).toLocaleDateString("zh-CN")}</time><div><button className="food-dish-copy" onClick={()=>void openDrink(log)}><strong className="user-content">{drinkRecordName(log)}</strong><span>{[log.volumeMl?`${log.volumeMl} ml`:"",log.sugarLevel,log.temperature?temperatureLabels[log.temperature]:""].filter(Boolean).join(" · ")}</span></button></div><small>{log.rating?drinkTasteLabels[log.rating]:""}</small></article>)}</div>:<div className="empty-state compact-empty"><p>还没有饮品记录关联到这家店。</p></div>}</section></>}
    {editingDrink&&<DrinkRecordEditor record={editingDrink} suggestions={drinkSuggestions} onClose={()=>setEditingDrink(undefined)} onSaved={load} onDeleted={load}/>}
    <div className="food-place-detail-actions"><Link className="section-link" href="/food/places">返回店铺库 <Icon name="arrow"/></Link></div>
    {panel==="place"&&<FormSheet title="编辑店铺" onClose={()=>setPanel(null)} formId="food-place-edit-form" submitLabel="保存修改" busy={saving}><form id="food-place-edit-form" className="editor-card compact-editor" onSubmit={savePlace}><div className="form-grid"><label className="field"><span>店铺名称</span><input required value={placeDraft.name} onChange={event=>setPlaceDraft({...placeDraft,name:event.target.value})}/></label>{placeDraft.serviceType!=="drink"&&<label className="field"><span>分店 / 门店</span><input value={placeDraft.branch} onChange={event=>setPlaceDraft({...placeDraft,branch:event.target.value})}/></label>}<PlaceSuggestionFields values={placeDraft} onChange={patch=>setPlaceDraft({...placeDraft,...patch})}/><div className="field"><span>总体评价</span><SearchableSelect label="总体评价" searchable={false} value={placeDraft.rating} onValueChange={(value) =>setPlaceDraft({...placeDraft,rating:value as TasteRating|""})} options={[{value:"",label:"未评价"},...Object.entries(ratingLabels).map(([value,label])=>({value:value,label:label}))]}/></div><div className="field"><span>状态</span><SearchableSelect label="状态" searchable={false} value={placeDraft.status} onValueChange={(value) =>setPlaceDraft({...placeDraft,status:value as FoodPlaceStatus})} options={[...Object.entries(statusLabels).map(([value,label])=>({value:value,label:label}))]}/></div><label className="field wide"><span>备注</span><textarea rows={4} value={placeDraft.notes} onChange={event=>setPlaceDraft({...placeDraft,notes:event.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}<FoodDeleteAction label="删除或归档店铺" description={`确定删除「${place.name}」？有关联饮食或饮品记录时会归档并标记为已关闭，历史记录会保留；否则永久删除。`} onDelete={removePlace} disabled={saving}/></form></FormSheet>}
    {panel==="dish"&&<FormSheet title={isDrinkMenu?(editingDish?"编辑饮品菜单":"新增饮品菜单"):(editingDish?"编辑菜品":"新增菜品")} onClose={()=>setPanel(null)} formId="food-dish-form" submitLabel={editingDish?"保存修改":isDrinkMenu?"添加饮品":"添加菜品"} busy={saving}><form id="food-dish-form" className="editor-card compact-editor" onSubmit={saveDish}><div className="form-grid"><label className="field"><span>{isDrinkMenu?"饮品名称":"菜名"}</span><input required autoFocus value={dishDraft.name} onChange={event=>setDishDraft({...dishDraft,name:event.target.value})}/></label><label className="field"><span>品类</span><input value={dishDraft.category} onChange={event=>setDishDraft({...dishDraft,category:event.target.value})}/></label><div className="field"><span>评价</span><SearchableSelect label="评价" searchable={false} value={dishDraft.rating} onValueChange={(value) =>setDishDraft({...dishDraft,rating:value as TasteRating|""})} options={[{value:"",label:"未评价"},...Object.entries(ratingLabels).map(([value,label])=>({value:value,label:label}))]}/></div><label className="field checkbox-field"><input type="checkbox" checked={dishDraft.recommended} onChange={event=>setDishDraft({...dishDraft,recommended:event.target.checked})}/><span>{isDrinkMenu?"推荐这款饮品":"推荐这道菜"}</span></label><label className="field wide"><span>备注</span><textarea rows={4} value={dishDraft.notes} onChange={event=>setDishDraft({...dishDraft,notes:event.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}{editingDish&&<FoodDeleteAction label={isDrinkMenu?"删除或归档饮品":"删除或归档菜品"} description={`确定删除「${editingDish.name}」？有关联记录时只会归档；否则永久删除。`} onDelete={()=>removeDish(editingDish)} disabled={saving}/>}</form></FormSheet>}
  </div>;
}
