import { ValidationError } from "./validation";
import type { CatFoodAmountUnit, CatFoodCategory } from "./types";

function object(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new ValidationError("请求内容格式不正确"); return value as Record<string, unknown>; }
function text(value: unknown, label: string, max = 500, required = false) { const result = typeof value === "string" ? value.trim() : ""; if (required && !result) throw new ValidationError(`请填写${label}`); if (result.length > max) throw new ValidationError(`${label}过长`); return result; }
function positive(value: unknown, label: string) { const result = Number(value); if (!Number.isFinite(result) || result <= 0) throw new ValidationError(`${label}必须大于 0`); return result; }
function whole(value: unknown, label: string, minimum = 0) { const result = Number(value); if (!Number.isSafeInteger(result) || result < minimum) throw new ValidationError(`${label}格式不正确`); return result; }
function date(value: unknown) { const result = text(value, "购买日期", 10, true); if (!/^\d{4}-\d{2}-\d{2}$/.test(result) || Number.isNaN(new Date(`${result}T00:00:00Z`).getTime())) throw new ValidationError("购买日期格式不正确"); return result; }
function category(value: unknown) { const result = value as CatFoodCategory; if (!["dry", "wet", "treat", "supplement", "other"].includes(result)) throw new ValidationError("食品分类不正确"); return result; }
function unit(value: unknown) { const result = value as CatFoodAmountUnit; if (!["g", "ml", "piece"].includes(result)) throw new ValidationError("规格单位不正确"); return result; }

export function parseCatFoodItem(value: unknown) { const body = object(value); return { name: text(body.name, "食品名称", 120, true), brand: text(body.brand, "品牌", 120), category: category(body.category), flavor: text(body.flavor, "口味", 120), notes: text(body.notes, "备注", 2000), lowStockThresholdPackages: whole(body.lowStockThresholdPackages, "低库存阈值"), restockIntervalDays: null, restockLeadDays: 0, restockReminderTime: null }; }
export function parseCatFoodItemPatch(value: unknown) { const item = parseCatFoodItem(value); return { name: item.name, brand: item.brand, category: item.category, flavor: item.flavor, notes: item.notes, lowStockThresholdPackages: item.lowStockThresholdPackages }; }
export function parseCatFoodPurchase(value: unknown, itemId: number) { const body = object(value), packageCount = whole(body.packageCount, "购买包数", 1), remainingPackageCount = body.remainingPackageCount === undefined ? packageCount : whole(body.remainingPackageCount, "剩余包数"); if (remainingPackageCount > packageCount) throw new ValidationError("剩余包数不能超过购买包数"); const paid = positive(body.paidAmount, "实付金额"); return { itemId, purchasedOn: date(body.purchasedOn), merchant: text(body.merchant, "购买渠道", 120), packageCount, remainingPackageCount, amountPerPackage: positive(body.amountPerPackage, "单包规格"), amountUnit: unit(body.amountUnit), paidAmountMinor: Math.round(paid * 100), currency: "CNY" as const, notes: text(body.notes, "备注", 2000) }; }
export function parseCatFoodPurchasePatch(value: unknown) { const body = object(value); const parsed = parseCatFoodPurchase(body, whole(body.itemId, "食品 ID", 1)); return { purchasedOn: parsed.purchasedOn, merchant: parsed.merchant, packageCount: parsed.packageCount, remainingPackageCount: parsed.remainingPackageCount, amountPerPackage: parsed.amountPerPackage, amountUnit: parsed.amountUnit, paidAmountMinor: parsed.paidAmountMinor, currency: parsed.currency, notes: parsed.notes }; }
export function parseCatFoodRestock(value: unknown) { const body = object(value), enabled = Boolean(body.enabled), intervalDays = whole(body.intervalDays, "购买周期", 1), leadDays = whole(body.leadDays, "提前天数"); if (leadDays >= intervalDays) throw new ValidationError("提前天数必须小于购买周期"); const reminderTime = body.reminderTime ? text(body.reminderTime, "提醒时间", 5) : null; if (enabled && (!reminderTime || !/^([01]\d|2[0-3]):[0-5]\d$/.test(reminderTime))) throw new ValidationError("请选择有效的提醒时间"); return { enabled, intervalDays, leadDays, reminderTime }; }
