import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { parseCatRecord,parseCatRoutine,parsePet,parseReminder } from "./cats-validation.ts";
import { catRoutineCompletionPatch,catRoutineSkipPatch,notificationSendAt,notificationShouldSend,reminderActionPatch,reminderIsDue,selectDueReminders,snoozeUntil } from "./reminder-engine.ts";
import type { Reminder } from "./types.ts";

const base:Reminder={id:1,title:"驱虫",targetType:"cat",targetId:7,sourceType:null,sourceId:null,scheduleType:"interval",startsAt:"2026-08-01T00:00:00.000Z",nextDueAt:"2026-08-27T00:00:00.000Z",intervalValue:30,intervalUnit:"day",timesOfDay:[],endsAt:null,timezone:"Asia/Shanghai",note:"",leadTimeMinutes:0,status:"scheduled",sentAt:null,cancelledAt:null,isActive:true,lastCompletedAt:null,snoozedUntil:null,lastNotifiedAt:null,createdAt:"",updatedAt:""};

test("validates pet profile and each Cats record type",()=>{assert.equal(parsePet({name:"Luna"}).name,"Luna");assert.equal(parseCatRecord({kind:"event",petId:null,eventType:"cleaning",title:"小喷泉"}).record.petId,null);assert.equal(parseCatRecord({kind:"symptom",petId:1,title:"结痂"}).kind,"symptom");assert.equal(parseCatRecord({kind:"vet_visit",petId:1,reason:"皮肤问题"}).kind,"vet_visit");assert.equal(parseCatRecord({kind:"medication",petId:1,name:"夫速宁"}).kind,"medication");assert.equal(parseCatRecord({kind:"measurement",petId:1,measurementType:"Weight",value:4.8,unit:"kg"}).kind,"measurement");});
test("validates one-time, interval and course reminders",()=>{assert.equal(parseReminder({title:"复查",targetType:"cat",targetId:1,scheduleType:"one_time",nextDueAt:"2026-09-15T09:00:00Z"}).scheduleType,"one_time");assert.equal(parseReminder({title:"驱虫",targetType:"cat",targetId:1,scheduleType:"interval",nextDueAt:"2026-09-15T09:00:00Z",intervalValue:30,intervalUnit:"day"}).intervalValue,30);assert.equal(parseReminder({title:"服药",targetType:"cat",targetId:1,scheduleType:"course",nextDueAt:"2026-09-15T09:00:00Z",intervalValue:12,intervalUnit:"hour",endsAt:"2026-09-22T09:00:00Z"}).scheduleType,"course");});
test("interval completion uses actual completion time as the next anchor",()=>{const patch=reminderActionPatch(base,"complete",new Date("2026-08-29T08:00:00.000Z"));assert.equal(patch.nextDueAt,"2026-09-28T08:00:00.000Z");assert.equal(patch.lastCompletedAt,"2026-08-29T08:00:00.000Z");});
test("skip advances an occurrence without recording completion",()=>{const patch=reminderActionPatch(base,"skip",new Date("2026-08-29T08:00:00.000Z"));assert.equal(patch.nextDueAt,"2026-09-26T00:00:00.000Z");assert.ok(!("lastCompletedAt" in patch));});
test("one-time completion and expired course deactivate",()=>{const once={...base,scheduleType:"one_time" as const,intervalValue:null,intervalUnit:null};assert.equal(reminderActionPatch(once,"complete").isActive,false);const course={...base,scheduleType:"course" as const,intervalValue:1,endsAt:"2026-08-30T00:00:00.000Z"};assert.equal(reminderActionPatch(course,"complete",new Date("2026-08-30T08:00:00.000Z")).isActive,false);});
test("course reminder advances to the next local time of day",()=>{const course={...base,scheduleType:"course" as const,intervalValue:1,intervalUnit:"day" as const,timesOfDay:["09:00","21:00"],endsAt:"2026-09-03T00:00:00.000Z"};assert.equal(reminderActionPatch(course,"complete",new Date("2026-08-27T02:00:00.000Z")).nextDueAt,"2026-08-27T13:00:00.000Z");});
test("snooze and due calculation use the temporary due time",()=>{const now=new Date("2026-08-27T08:00:00.000Z");const snoozed=snoozeUntil("later_today",now);assert.equal(snoozed,"2026-08-27T11:00:00.000Z");assert.equal(reminderIsDue({...base,snoozedUntil:snoozed},now),false);});
test("tomorrow snooze uses the reminder timezone",()=>{assert.equal(snoozeUntil("tomorrow",new Date("2026-08-27T15:30:00.000Z"),undefined,"Asia/Shanghai"),"2026-08-28T01:00:00.000Z");});
test("Home Due query returns only active due reminders",()=>{const now=new Date("2026-08-27T08:00:00.000Z");const future={...base,id:2,nextDueAt:"2026-08-28T00:00:00.000Z"};const inactive={...base,id:3,isActive:false};assert.deepEqual(selectDueReminders([future,inactive,base],now,3).map(item=>item.id),[1]);});
test("validates cat and household routines",()=>{assert.equal(parseCatRoutine({scope:"cat",petId:1,title:"Nail trim",intervalValue:30,intervalUnit:"day",firstDueAt:"2026-09-01T09:00:00Z"}).scope,"cat");assert.equal(parseCatRoutine({scope:"household",petId:null,title:"Filter",intervalValue:1,intervalUnit:"month",firstDueAt:"2026-09-01T09:00:00Z"}).petId,null);assert.throws(()=>parseCatRoutine({scope:"cat",petId:null,title:"Invalid",intervalValue:1,intervalUnit:"day",firstDueAt:"2026-09-01T09:00:00Z"}));});
test("routine completion anchors next due to actual completion while skip advances the scheduled occurrence",()=>{const routine={intervalValue:1,intervalUnit:"month" as const,nextDueAt:"2026-09-01T09:00:00.000Z"};assert.deepEqual(catRoutineCompletionPatch(routine,new Date("2026-09-03T09:00:00.000Z")),{lastCompletedAt:"2026-09-03T09:00:00.000Z",nextDueAt:"2026-10-03T09:00:00.000Z"});assert.equal(catRoutineSkipPatch(routine).nextDueAt,"2026-10-01T09:00:00.000Z");});
test("notification lead time schedules delivery without changing business due time",()=>{const reminder={...base,nextDueAt:"2026-09-10T09:00:00.000Z",leadTimeMinutes:1440};assert.equal(notificationSendAt(reminder),"2026-09-09T09:00:00.000Z");assert.equal(notificationShouldSend(reminder,new Date("2026-09-09T09:00:00.000Z")),true);assert.equal(notificationShouldSend({...reminder,lastNotifiedAt:"2026-09-09T09:00:00.000Z"},new Date("2026-09-09T10:00:00.000Z")),false);});
test("Cats migration keeps ownership and household records RLS-sensitive",()=>{const sql=readFileSync(new URL("../../supabase/migrations/202608270003_cats_and_reminders.sql",import.meta.url),"utf8");for(const table of ["pets","cat_events","cat_symptoms","vet_visits","cat_medications","cat_measurements","reminders","reminder_occurrences"])assert.match(sql,new RegExp(`['\"]${table}['\"]`));assert.match(sql,/alter table public\.%I enable row level security/);assert.match(sql,/pet_id bigint,/);assert.match(sql,/references public\.pets\(id,user_id\) on delete restrict/);assert.match(sql,/auth\.uid\(\).*user_id/s);});
test("routine migration preserves legacy Cats reminders and protects new tables with RLS",()=>{const sql=readFileSync(new URL("../../supabase/migrations/202608280001_cat_routines_notifications.sql",import.meta.url),"utf8");assert.match(sql,/create table if not exists public\.cat_routines/);assert.match(sql,/create table if not exists public\.notification_deliveries/);assert.match(sql,/insert into public\.cat_routines/);assert.match(sql,/on conflict\(reminder_id\) do nothing/);assert.match(sql,/alter table public\.cat_routines enable row level security/);assert.match(sql,/alter table public\.notification_deliveries enable row level security/);assert.doesNotMatch(sql,/grant all/i);});
