import type { CatEventType, CatRecordKind, CatRoutineScope, PetSex, ReminderIntervalUnit, ReminderScheduleType, ReminderTargetType } from "./types.ts";
import { ValidationError } from "./validation.ts";

function object(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))throw new ValidationError("请求内容必须是对象");return value as Record<string,unknown>;}
function text(value:unknown,label:string,max=5000,required=false){if(value===undefined||value===null)return required?(()=>{throw new ValidationError(`${label}不能为空`);})():"";if(typeof value!=="string")throw new ValidationError(`${label}格式不正确`);const result=value.trim();if(required&&!result)throw new ValidationError(`${label}不能为空`);if(result.length>max)throw new ValidationError(`${label}过长`);return result;}
function id(value:unknown,label="ID"){if(typeof value!=="number"||!Number.isSafeInteger(value)||value<=0)throw new ValidationError(`${label}格式不正确`);return value;}
function iso(value:unknown,label:string,nullable=false){if(nullable&&(value===null||value===""||value===undefined))return null;const result=text(value,label,80,true);const date=new Date(result);if(!Number.isFinite(date.getTime()))throw new ValidationError(`${label}格式不正确`);return date.toISOString();}
function date(value:unknown,label:string){if(value===null||value===""||value===undefined)return null;const result=text(value,label,10,true);if(!/^\d{4}-\d{2}-\d{2}$/.test(result))throw new ValidationError(`${label}格式不正确`);return result;}
function number(value:unknown,label:string,nullable=false){if(nullable&&(value===null||value===""||value===undefined))return null;if(typeof value!=="number"||!Number.isFinite(value))throw new ValidationError(`${label}格式不正确`);return value;}
function nonnegativeInteger(value:unknown,label:string,fallback=0){const result=value===undefined?fallback:value;if(typeof result!=="number"||!Number.isSafeInteger(result)||result<0)throw new ValidationError(`${label}格式不正确`);return result;}
function enumValue<T extends string>(value:unknown,label:string,values:readonly T[],fallback?:T){if(value===undefined&&fallback)return fallback;if(typeof value!=="string"||!values.includes(value as T))throw new ValidationError(`${label}格式不正确`);return value as T;}
function avatar(value:unknown){const result=text(value,"头像",1000);if(!result||result.startsWith("/")||/^https:\/\//i.test(result))return result;throw new ValidationError("头像必须是 HTTPS 地址或站内路径");}
function timezone(value:unknown){const result=text(value??"Asia/Shanghai","时区",80,true);try{new Intl.DateTimeFormat("en",{timeZone:result}).format();return result;}catch{throw new ValidationError("时区格式不正确");}}
function boolean(value:unknown,label:string,fallback=true){if(value===undefined)return fallback;if(typeof value!=="boolean")throw new ValidationError(`${label}格式不正确`);return value;}

export function parsePet(value:unknown){const b=object(value);return{name:text(b.name,"名称",80,true),avatarUrl:avatar(b.avatarUrl),sex:b.sex===null||b.sex===""||b.sex===undefined?null:enumValue(b.sex,"性别",["female","male","unknown"] as const) as PetSex,birthday:date(b.birthday,"生日"),adoptionDate:date(b.adoptionDate,"到家日期"),notes:text(b.notes,"备注"),isActive:b.isActive===undefined?true:Boolean(b.isActive)};}
export function parsePetPatch(value:unknown){const b=object(value);const full=parsePet({...b,name:b.name??"_"});const result:Record<string,unknown>={};for(const key of ["name","avatarUrl","sex","birthday","adoptionDate","notes","isActive"] as const)if(b[key]!==undefined)result[key]=full[key];if(!Object.keys(result).length)throw new ValidationError("没有可更新的字段");return result;}

export function parseCatRecord(value:unknown,forcedKind?:CatRecordKind){const b=object(value);const kind=forcedKind??enumValue(b.kind,"记录类型",["event","symptom","vet_visit","medication","measurement"] as const);const petId=b.petId===null?null:id(b.petId,"猫咪 ID");if(kind!=="event"&&petId===null)throw new ValidationError("这类记录必须选择猫咪");
  if(kind==="event")return{kind,record:{petId,eventType:enumValue(b.eventType,"护理类型",["deworming","grooming","care","note","cleaning","shared_note"] as const,"care") as CatEventType,occurredAt:iso(b.occurredAt,"发生日期")!,occurredHasExplicitTime:boolean(b.occurredHasExplicitTime,"发生时间精度"),title:text(b.title,"标题",200,true),note:text(b.note,"备注"),sourceType:null,sourceId:null}};
  if(kind==="symptom")return{kind,record:{petId:petId!,occurredAt:iso(b.occurredAt,"发生日期")!,occurredHasExplicitTime:boolean(b.occurredHasExplicitTime,"发生时间精度"),title:text(b.title,"症状",200,true),severity:text(b.severity,"程度",60),description:text(b.description,"描述"),bodyArea:text(b.bodyArea,"部位",200),note:text(b.note,"备注")}};
  if(kind==="vet_visit")return{kind,record:{petId:petId!,occurredAt:iso(b.occurredAt,"就诊日期")!,occurredHasExplicitTime:boolean(b.occurredHasExplicitTime,"就诊时间精度"),clinic:text(b.clinic,"医院",200),doctor:text(b.doctor,"医生",100),reason:text(b.reason,"就诊原因",500,true),symptoms:text(b.symptoms,"症状"),diagnosis:text(b.diagnosis,"诊断"),examinations:text(b.examinations,"检查"),treatment:text(b.treatment,"治疗"),prescriptions:text(b.prescriptions,"处方"),cost:number(b.cost,"费用",true),followUpAt:iso(b.followUpAt,"复查时间",true),notes:text(b.notes,"备注")}};
  if(kind==="medication")return{kind,record:{petId:petId!,name:text(b.name,"药物名称",200,true),dose:text(b.dose,"剂量",100),unit:text(b.unit,"单位",40),frequencyText:text(b.frequencyText,"频率",200),startedAt:iso(b.startedAt,"开始日期")!,startedHasExplicitTime:boolean(b.startedHasExplicitTime,"开始时间精度"),endedAt:iso(b.endedAt,"结束日期",true),endedHasExplicitTime:boolean(b.endedHasExplicitTime,"结束时间精度"),reason:text(b.reason,"原因",500),active:b.active===undefined?true:Boolean(b.active),notes:text(b.notes,"备注")}};
  return{kind,record:{petId:petId!,occurredAt:iso(b.occurredAt,"测量日期")!,occurredHasExplicitTime:boolean(b.occurredHasExplicitTime,"测量时间精度"),measurementType:text(b.measurementType,"测量类型",80,true),value:number(b.value,"数值")!,unit:text(b.unit,"单位",40,true),note:text(b.note,"备注")}};
}

export function parseReminder(value:unknown){const b=object(value);const scheduleType=enumValue(b.scheduleType,"提醒类型",["one_time","interval","course"] as const) as ReminderScheduleType;const targetType=enumValue(b.targetType,"目标类型",["cat","cat_household","tracker"] as const) as ReminderTargetType;const targetId=b.targetId===null||b.targetId===undefined?null:id(b.targetId,"目标 ID");if(targetType==="cat"&&targetId===null)throw new ValidationError("猫咪提醒必须选择猫咪");const startsAt=iso(b.startsAt??b.nextDueAt??new Date().toISOString(),"开始时间")!;const intervalValue=scheduleType==="one_time"?null:id(b.intervalValue,"间隔");const intervalUnit=scheduleType==="one_time"?null:enumValue(b.intervalUnit,"间隔单位",["hour","day","week","month"] as const) as ReminderIntervalUnit;const timesOfDay=Array.isArray(b.timesOfDay)&&b.timesOfDay.every(v=>typeof v==="string"&&/^([01]\d|2[0-3]):[0-5]\d$/.test(v))?b.timesOfDay.map(String):[];return{title:text(b.title,"提醒标题",200,true),targetType,targetId,sourceType:b.sourceType?text(b.sourceType,"来源类型",80):null,sourceId:b.sourceId? id(b.sourceId,"来源 ID"):null,scheduleType,startsAt,nextDueAt:iso(b.nextDueAt??startsAt,"下次时间")!,dueHasExplicitTime:boolean(b.dueHasExplicitTime,"到期时间精度"),intervalValue,intervalUnit,timesOfDay,endsAt:iso(b.endsAt,"结束时间",true),timezone:timezone(b.timezone),note:text(b.note,"备注"),leadTimeMinutes:nonnegativeInteger(b.leadTimeMinutes,"提前时间"),status:enumValue(b.status,"状态",["scheduled","sent","cancelled","failed","completed"] as const,"scheduled"),isActive:b.isActive===undefined?true:Boolean(b.isActive)};}

export function parseCatRoutine(value:unknown){const b=object(value);const scope=enumValue(b.scope,"日程范围",["cat","household"] as const) as CatRoutineScope;const petId=b.petId===null||b.petId===undefined?null:id(b.petId,"猫咪 ID");if(scope==="cat"&&petId===null)throw new ValidationError("猫咪日程必须选择猫咪");if(scope==="household"&&petId!==null)throw new ValidationError("家庭日程不能绑定单只猫咪");const firstDueAt=iso(b.firstDueAt??b.nextDueAt,"首次到期时间")!;return{scope,petId,title:text(b.title,"日程名称",200,true),intervalValue:id(b.intervalValue,"间隔"),intervalUnit:enumValue(b.intervalUnit,"间隔单位",["day","week","month"] as const) as "day"|"week"|"month",firstDueAt,nextDueAt:iso(b.nextDueAt??firstDueAt,"下次到期时间")!,reminderLeadMinutes:nonnegativeInteger(b.reminderLeadMinutes,"提前时间"),notes:text(b.notes,"备注"),enabled:b.enabled===undefined?true:Boolean(b.enabled),reminderId:null};}
