import assert from "node:assert/strict";
import test from "node:test";
import { appleReminderPayload,appleReminderSnapshot,eventKitHasNextOccurrence,eventKitImportsUnlinked,eventKitLinkScope,eventKitMissingAppleAction,eventKitNotificationOwner,eventKitReminderDomain,eventKitReminderMatches,eventKitSourceEnabled,mergeEventKitSnapshots,reminderSnapshot,taskSnapshot } from "./eventkit-sync.ts";
import type { Reminder,Task } from "./types.ts";

test("three-way reconcile merges non-overlapping fields",()=>{const base={title:"Dentist",notes:"",startAt:"2026-09-21T02:00:00Z"},eo={...base,notes:"bring card"},apple={...base,startAt:"2026-09-21T03:00:00Z"},result=mergeEventKitSnapshots(base,eo,apple);assert.deepEqual(result.conflicts,[]);assert.equal(result.merged.notes,"bring card");assert.equal(result.merged.startAt,"2026-09-21T03:00:00Z");});
test("three-way reconcile reports same-field conflicts",()=>{const base={title:"A"},result=mergeEventKitSnapshots(base,{title:"EO"},{title:"Apple"});assert.deepEqual(result.conflicts,["title"]);});
test("equal edits suppress echo conflicts",()=>{const base={completed:false},result=mergeEventKitSnapshots(base,{completed:true},{completed:true});assert.deepEqual(result.conflicts,[]);assert.equal(result.merged.completed,true);});
test("Off sources retain their links but are excluded from reconciliation",()=>{const modes={paused:"off",active:"two_way"} as const,scope=eventKitLinkScope([{id:1,entity_type:"task",calendar_identifier:"paused"},{id:2,entity_type:"task",calendar_identifier:"active"},{id:3,entity_type:"calendar_event",calendar_identifier:"active"}],"task",modes);assert.equal(eventKitSourceEnabled("unknown",modes),false);assert.deepEqual(scope.all.map(link=>link.id),[1,2]);assert.deepEqual(scope.active.map(link=>link.id),[2]);});
test("Apple owns the first notification only when the saved reminder has an alarm",()=>{assert.equal(eventKitNotificationOwner({alarms:[{relativeOffset:0}]}),"apple");assert.equal(eventKitNotificationOwner({alarms:[]}),"eo");assert.equal(eventKitNotificationOwner({}),"eo");});
test("Timed Task Due creates one standard Apple alert without mapping priority",()=>{const snapshot=taskSnapshot({title:"Vet",notes:"Bring card",dueDate:"2026-10-02",dueTime:"09:30",completed:false,completedAt:null,priority:"high",reminders:[{deliveryChannel:"pwa"}]} as Task),apple=appleReminderSnapshot({...snapshot,priority:1,alarms:[{relativeOffset:0}]});assert.deepEqual(snapshot,apple);assert.equal("priority" in snapshot,false);assert.equal("alarms" in snapshot,false);assert.deepEqual(appleReminderPayload(snapshot,"list"),{calendarItemIdentifier:undefined,calendarIdentifier:"list",title:"Vet",notes:"Bring card",dueDate:"2026-10-02",dueTime:"09:30",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,priority:0,completed:false,completionDate:null,alarms:[{relativeOffset:0}]});assert.deepEqual(appleReminderPayload({...snapshot,dueTime:null},"list").alarms,[]);});
test("Task updates preserve Apple-only alarms and priority",()=>{const payload=appleReminderPayload({title:"Vet",notes:"",dueDate:null,dueTime:null,completed:false,completionDate:null},"list","item",{timezone:"Asia/Shanghai",priority:1,alarms:[{relativeOffset:-3600}]});assert.equal(payload.priority,1);assert.deepEqual(payload.alarms,[{relativeOffset:-3600}]);});
test("EO Tasks only ignores unlinked Apple reminders and recreates a missing mirror",()=>{assert.equal(eventKitImportsUnlinked("reminder","two_way"),false);assert.equal(eventKitImportsUnlinked("reminder","import"),true);assert.equal(eventKitImportsUnlinked("event","two_way"),true);assert.equal(eventKitMissingAppleAction("reminder","two_way"),"recreate");assert.equal(eventKitMissingAppleAction("reminder","import"),"delete_eo");});
test("Reminder domains route independently and preserve date-only Due",()=>{const reminder={title:"Clean fountain",note:"",targetType:"cat_household",nextDueAt:"2026-10-02T04:00:00.000Z",snoozedUntil:null,timezone:"Asia/Shanghai",dueHasExplicitTime:false,status:"scheduled",lastCompletedAt:"2026-09-01T04:00:00.000Z"} as Reminder;assert.equal(eventKitReminderDomain(reminder),"cat_household");assert.equal(eventKitReminderDomain({...reminder,targetType:"cat"}),"cats");assert.equal(eventKitReminderDomain({...reminder,targetType:"task"}),null);assert.deepEqual(reminderSnapshot(reminder),{title:"Clean fountain",notes:"",dueDate:"2026-10-02",dueTime:null,completed:false,completionDate:null});});
test("Tracker missing boilerplate stays out of Apple notes and an orphan can be recovered",()=>{const reminder={title:"Wash socks",note:"Only remind when this Tracker has no entry in the current observation period.",sourceType:"tracker_missing",targetType:"tracker",nextDueAt:"2026-10-03T02:00:00.000Z",snoozedUntil:null,timezone:"Asia/Shanghai",dueHasExplicitTime:true,status:"scheduled",lastCompletedAt:null} as Reminder,snapshot=reminderSnapshot(reminder),legacy={...snapshot,notes:reminder.note};assert.equal(snapshot.notes,"");assert.equal(eventKitReminderMatches({title:"Wash socks",notes:reminder.note,dueDate:"2026-10-03",dueTime:"10:00",completed:false,completionDate:null},[snapshot,legacy]),true);});
test("Recurring domains create only the next active Apple occurrence",()=>{assert.equal(eventKitHasNextOccurrence({isActive:true,nextDueAt:"2026-11-01T02:00:00.000Z",status:"scheduled"}),true);assert.equal(eventKitHasNextOccurrence({isActive:false,nextDueAt:null,status:"completed"}),false);});
