import type { CalendarEvent,Reminder,Task } from "./types.ts";
import { nativeCall } from "./native-bridge.ts";

export type EventKitSyncMode="off"|"import"|"two_way";
export type EventKitNotificationOwner="eo"|"apple";
export type EventKitReminderDomain="tasks"|"cats"|"cat_household"|"trackers"|"health"|"subscriptions";
export type EventKitReminderRoutes=Partial<Record<EventKitReminderDomain,string>>;
export type EventKitSource={identifier:string;title:string;sourceIdentifier:string;sourceTitle:string;allowsContentModifications:boolean};
export type EventKitStatus={available:boolean;installationId:string;calendarPermission:string;reminderPermission:string;calendars:EventKitSource[];reminderLists:EventKitSource[]};
export type EventKitModes=Record<string,EventKitSyncMode>;
type Item=Record<string,unknown>;
type Link={id:number;entity_type:"task"|"reminder"|"calendar_event";eo_id:number;eventkit_entity_type:"reminder"|"event";calendar_item_identifier:string;external_identifier:string|null;calendar_identifier:string;source_identifier:string;last_synced_snapshot:Item};
export type EventKitSyncResult={imported:number;exported:number;merged:number;conflicts:Array<{entityType:string;eoId:number;fields:string[]}>;skippedEvents:Array<{title:string;calendarTitle:string;startAt:string;endAt:string}>;lastSync:string};
let activeEventKitSync:Promise<EventKitSyncResult>|null=null;

export function runEventKitSyncSingleFlight(run:()=>Promise<EventKitSyncResult>){
  if(activeEventKitSync)return activeEventKitSync;
  const current=run();activeEventKitSync=current;
  void current.then(()=>{if(activeEventKitSync===current)activeEventKitSync=null;},()=>{if(activeEventKitSync===current)activeEventKitSync=null;});
  return current;
}

export function mergeEventKitSnapshots(base:Item,eo:Item,apple:Item){const merged:Item={},conflicts:string[]=[];for(const key of new Set([...Object.keys(base),...Object.keys(eo),...Object.keys(apple)])){const b=JSON.stringify(base[key]??null),e=JSON.stringify(eo[key]??null),a=JSON.stringify(apple[key]??null),ec=e!==b,ac=a!==b;if(ec&&ac&&e!==a)conflicts.push(key);else merged[key]=ac?apple[key]:eo[key];}return{merged,conflicts,eoChanged:JSON.stringify(base)!==JSON.stringify(eo),appleChanged:JSON.stringify(base)!==JSON.stringify(apple)};}
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Item).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`;return JSON.stringify(value);}
async function hash(value:Item){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(stable(value)));return[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,"0")).join("");}
function dayTime(value:string,timezone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value)),part=(kind:Intl.DateTimeFormatPartTypes)=>parts.find(item=>item.type===kind)?.value??"";return{date:`${part("year")}-${part("month")}-${part("day")}`,time:`${part("hour")}:${part("minute")}`};}
export function taskSnapshot(task:Task):Item{return{title:task.title,notes:task.notes,dueDate:task.dueDate,dueTime:task.dueTime,completed:task.completed,completionDate:task.completedAt};}
export function eventKitReminderDomain(reminder:Reminder):Exclude<EventKitReminderDomain,"tasks">|null{if(reminder.targetType==="cat")return"cats";if(reminder.targetType==="cat_household")return"cat_household";if(reminder.targetType==="tracker")return"trackers";if(reminder.targetType==="health")return"health";if(reminder.targetType==="subscription")return"subscriptions";return null;}
export function reminderSnapshot(reminder:Reminder):Item{const due=reminder.snoozedUntil??reminder.nextDueAt,parts=due?dayTime(due,reminder.timezone):null,completed=reminder.status==="completed";return{title:reminder.title,notes:reminder.sourceType==="tracker_missing"?"":reminder.note,dueDate:parts?.date??null,dueTime:parts&&reminder.dueHasExplicitTime?parts.time:null,completed,completionDate:completed?reminder.lastCompletedAt:null};}
export function appleReminderSnapshot(item:Item):Item{return{title:String(item.title??""),notes:String(item.notes??""),dueDate:item.dueDate??null,dueTime:item.dueTime??null,completed:Boolean(item.completed),completionDate:item.completionDate??null};}
export function eventKitReminderMatches(item:Item,snapshots:Item[]){const normalized=stable(appleReminderSnapshot(item));return snapshots.some(snapshot=>stable(snapshot)===normalized);}
export function eventKitHasNextOccurrence(reminder:Pick<Reminder,"isActive"|"nextDueAt"|"status">){return reminder.isActive&&Boolean(reminder.nextDueAt)&&reminder.status!=="completed";}
function eventSnapshot(event:CalendarEvent|Item):Item{return{title:String(event.title??""),notes:String(event.notes??""),startAt:String("startAt" in event?event.startAt:event.start_at),endAt:String("endAt" in event?event.endAt:event.end_at),isAllDay:Boolean("isAllDay" in event?event.isAllDay:event.is_all_day),timezone:(event.timezone as string|null)??null,location:String(event.location??""),status:String(event.status??"confirmed")};}
function appleEventSnapshot(item:Item):Item{return{title:String(item.title??""),notes:String(item.notes??""),startAt:String(item.startAt),endAt:String(item.endAt),isAllDay:Boolean(item.isAllDay),timezone:item.timezone??null,location:String(item.location??""),status:String(item.status??"confirmed")};}
export function eventKitEventRangeValid(snapshot:Item){const start=String(snapshot.startAt??""),end=String(snapshot.endAt??"");if(snapshot.isAllDay)return/^\d{4}-\d{2}-\d{2}$/.test(start)&&/^\d{4}-\d{2}-\d{2}$/.test(end)&&end>start;const startTime=Date.parse(start),endTime=Date.parse(end);return Number.isFinite(startTime)&&Number.isFinite(endTime)&&endTime>startTime;}
export function appleReminderPayload(snapshot:Item,calendarIdentifier:string,identifier?:string,existing?:Item,timezone?:string){const existingAlarms=Array.isArray(existing?.alarms)?existing.alarms:[];return{calendarItemIdentifier:identifier,calendarIdentifier,title:snapshot.title,notes:snapshot.notes,dueDate:snapshot.dueDate,dueTime:snapshot.dueTime,timezone:timezone??(typeof existing?.timezone==="string"?existing.timezone:Intl.DateTimeFormat().resolvedOptions().timeZone),priority:Number(existing?.priority??0),completed:snapshot.completed,completionDate:snapshot.completionDate,alarms:existingAlarms.length?existingAlarms:snapshot.dueTime?[{relativeOffset:0}]:[]};}
async function json(url:string,init?:RequestInit){const response=await fetch(url,init);if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error??`Sync request failed (${response.status})`);return response.status===204?null:response.json();}
export function eventKitNotificationOwner(item:Item):EventKitNotificationOwner{return Array.isArray(item.alarms)&&item.alarms.length>0?"apple":"eo";}
export function eventKitSourceEnabled(calendarIdentifier:string,modes:EventKitModes){return Boolean(modes[calendarIdentifier]&&modes[calendarIdentifier]!=="off");}
export function eventKitCalendarReadModes(calendars:Pick<EventKitSource,"identifier">[],modes:EventKitModes){const next={...modes};for(const calendar of calendars)if(next[calendar.identifier]==="two_way")next[calendar.identifier]="import";return next;}
export function eventKitCalendarSyncRange(now=new Date()){const from=new Date(2026,9,1),to=new Date(now);to.setDate(to.getDate()+365);return{from,to};}
export function eventKitTaskNeedsAppleMirror(task:Pick<Task,"completed">){return !task.completed;}
export function eventKitLinkScope<T extends{entity_type:string;calendar_identifier:string}>(links:T[],entityType:string,modes:EventKitModes){const all=links.filter(link=>link.entity_type===entityType);return{all,active:all.filter(link=>eventKitSourceEnabled(link.calendar_identifier,modes))};}
export function eventKitImportsUnlinked(kind:"reminder"|"event",mode:EventKitSyncMode){return kind==="event"||mode==="import";}
export function eventKitMissingAppleAction(kind:"reminder"|"event",mode:EventKitSyncMode){return kind==="reminder"&&mode==="two_way"?"recreate":"delete_eo";}
function taskNotificationOwnerMatches(task:Task,apple:Item){const channel=eventKitNotificationOwner(apple)==="apple"?"apple_reminders":"pwa";return(task.reminders??[]).every(rule=>rule.deliveryChannel===channel);}
function reminderNeedsDueAlarm(snapshot:Item,apple:Item){return Boolean(snapshot.dueTime)&&eventKitNotificationOwner(apple)==="eo";}
async function saveLink(status:EventKitStatus,entityType:Link["entity_type"],eoId:number,kind:Link["eventkit_entity_type"],apple:Item,snapshot:Item){await json("/api/eventkit/links",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({installationId:status.installationId,entityType,eoId,eventkitEntityType:kind,calendarItemIdentifier:apple.calendarItemIdentifier,externalIdentifier:apple.externalIdentifier,calendarIdentifier:apple.calendarIdentifier,sourceIdentifier:apple.sourceIdentifier,lastSyncedHash:await hash(snapshot),lastSyncedSnapshot:snapshot,appleLastModifiedAt:apple.lastModifiedAt,...(kind==="reminder"?{notificationOwner:eventKitNotificationOwner(apple)}:{})})});}
async function createReminderLink(status:EventKitStatus,entityType:"task"|"reminder",eoId:number,snapshot:Item,calendarIdentifier:string,timezone?:string){const saved=await nativeCall<{item:Item}>("eventkit.save",{kind:"reminder",item:appleReminderPayload(snapshot,calendarIdentifier,undefined,undefined,timezone)});try{await saveLink(status,entityType,eoId,"reminder",saved.item,snapshot);}catch(error){try{await nativeCall("eventkit.delete",{kind:"reminder",calendarItemIdentifier:saved.item.calendarItemIdentifier});}catch{}throw error;}return saved.item;}
async function adoptReminderLink(status:EventKitStatus,entityType:"task"|"reminder",eoId:number,snapshot:Item,apple:Item,timezone?:string){const saved=reminderNeedsDueAlarm(snapshot,apple)||stable(appleReminderSnapshot(apple))!==stable(snapshot)?await nativeCall<{item:Item}>("eventkit.save",{kind:"reminder",item:appleReminderPayload(snapshot,String(apple.calendarIdentifier),String(apple.calendarItemIdentifier),apple,timezone)}).then(value=>value.item):apple;await saveLink(status,entityType,eoId,"reminder",saved,snapshot);return saved;}

export function synchronizeEventKit(status:EventKitStatus,modes:EventKitModes,routes:EventKitReminderRoutes={}){return runEventKitSyncSingleFlight(()=>performEventKitSync(status,modes,routes));}
async function performEventKitSync(status:EventKitStatus,modes:EventKitModes,routes:EventKitReminderRoutes={}):Promise<EventKitSyncResult>{const effectiveModes={...modes};for(const identifier of Object.values(routes))if(identifier)effectiveModes[identifier]="two_way";const calendarModes=eventKitCalendarReadModes(status.calendars,effectiveModes),links=await json(`/api/eventkit/links?installationId=${encodeURIComponent(status.installationId)}`) as Link[],claimedReminderIDs=new Set(links.filter(link=>link.eventkit_entity_type==="reminder").map(link=>link.calendar_item_identifier)),calendarIDs=status.calendars.filter(source=>eventKitSourceEnabled(source.identifier,calendarModes)).map(source=>source.identifier),linkedReminderIDs=Object.keys(routes).length?links.filter(link=>link.eventkit_entity_type==="reminder").map(link=>link.calendar_identifier):[],reminderIDs=[...new Set([...status.reminderLists.filter(source=>eventKitSourceEnabled(source.identifier,effectiveModes)).map(source=>source.identifier),...linkedReminderIDs])],calendarWindow=eventKitCalendarSyncRange(),from=calendarWindow.from,to=calendarWindow.to;const [appleEvents,appleReminders,tasks,reminders,events]=await Promise.all([calendarIDs.length?nativeCall<{items:Item[]}>("eventkit.fetch",{kind:"calendar",calendarIdentifiers:calendarIDs,from:from.toISOString(),to:to.toISOString()}).then(value=>value.items):[],reminderIDs.length?nativeCall<{items:Item[]}>("eventkit.fetch",{kind:"reminder",calendarIdentifiers:reminderIDs,completedSince:new Date(Date.now()-30*86400000).toISOString()}).then(value=>value.items):[],json("/api/tasks?status=all") as Promise<Task[]>,json("/api/reminders") as Promise<Reminder[]>,json(`/api/calendar-events?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}&limit=500`) as Promise<CalendarEvent[]>]);let imported=0,exported=0,merged=0;const conflicts:Array<{entityType:string;eoId:number;fields:string[]}>=[],skippedEvents:EventKitSyncResult["skippedEvents"]=[];
  async function reconcile(kind:"reminder"|"event",entityType:"task"|"calendar_event",appleItems:Item[],eoItems:Array<Task|CalendarEvent>){
    const syncModes=kind==="event"?calendarModes:effectiveModes,scope=eventKitLinkScope(links,entityType,syncModes),routed=kind==="reminder"?routes.tasks:null,destination=(kind==="event"?status.calendars:status.reminderLists).find(source=>source.allowsContentModifications&&(routed?source.identifier===routed:syncModes[source.identifier]==="two_way")),active=entityType==="task"&&routed?scope.all:scope.active,linkedEO=new Set(scope.all.map(link=>link.eo_id)),linkedApple=new Set<string>();
    function invalidEvent(apple:Item){if(kind!=="event")return false;const snapshot=appleEventSnapshot(apple);if(eventKitEventRangeValid(snapshot))return false;skippedEvents.push({title:String(snapshot.title||"Untitled event"),calendarTitle:status.calendars.find(source=>source.identifier===apple.calendarIdentifier)?.title??"Unknown calendar",startAt:String(snapshot.startAt),endAt:String(snapshot.endAt)});return true;}
    for(const link of active){
      const mode=entityType==="task"&&routed?"two_way":syncModes[link.calendar_identifier],eo=eoItems.find(item=>item.id===link.eo_id);
      let apple=appleItems.find(item=>item.calendarItemIdentifier===link.calendar_item_identifier)||appleItems.find(item=>item.externalIdentifier&&item.externalIdentifier===link.external_identifier&&item.calendarIdentifier===link.calendar_identifier&&item.sourceIdentifier===link.source_identifier);
      if(!apple){const recovered=appleItems.filter(item=>item.calendarIdentifier===link.calendar_identifier&&item.sourceIdentifier===link.source_identifier&&!claimedReminderIDs.has(String(item.calendarItemIdentifier))&&stable(kind==="reminder"?appleReminderSnapshot(item):appleEventSnapshot(item))===stable(link.last_synced_snapshot));if(recovered.length===1||kind==="reminder"&&recovered.length)apple=recovered[0];}
      if(apple)linkedApple.add(String(apple.calendarItemIdentifier));
      if(kind==="event"&&apple?.isRecurring)continue;
      if(apple&&invalidEvent(apple))continue;
      if(!eo&&apple&&kind==="event"){await json("/api/eventkit/links",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:link.id})});linkedApple.delete(String(apple.calendarItemIdentifier));continue;}
      if(!eo&&apple&&mode==="two_way"){await nativeCall("eventkit.delete",{kind:kind==="event"?"calendar":"reminder",calendarItemIdentifier:apple.calendarItemIdentifier});await json("/api/eventkit/links",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:link.id})});continue;}
      if(eo&&!apple){
        if(entityType==="task"&&!eventKitTaskNeedsAppleMirror(eo as Task))continue;
        if(entityType==="task"&&Boolean(link.last_synced_snapshot.completed)&&(!link.last_synced_snapshot.completionDate||Date.parse(String(link.last_synced_snapshot.completionDate))<Date.now()-30*86400000))continue;
        if(eventKitMissingAppleAction(kind,mode)==="recreate"){const snapshot=taskSnapshot(eo as Task);await createReminderLink(status,"task",eo.id,snapshot,destination?.identifier??link.calendar_identifier);exported++;continue;}
        await json(entityType==="task"?`/api/tasks/${eo.id}`:`/api/calendar-events/${eo.id}`,{method:"DELETE"});await json("/api/eventkit/links",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:link.id})});continue;
      }
      if(!eo||!apple)continue;
      const storedBase=link.last_synced_snapshot,base=entityType==="task"?appleReminderSnapshot(storedBase):storedBase,baselineChanged=stable(base)!==stable(storedBase),eoSnap=entityType==="task"?taskSnapshot(eo as Task):eventSnapshot(eo as CalendarEvent),appleSnap=kind==="reminder"?appleReminderSnapshot(apple):appleEventSnapshot(apple),result=mergeEventKitSnapshots(base,eoSnap,appleSnap);
      if(entityType==="task"&&destination&&apple.calendarIdentifier!==destination.identifier){const saved=await nativeCall<{item:Item}>("eventkit.save",{kind:"reminder",item:appleReminderPayload(eoSnap,destination.identifier,String(apple.calendarItemIdentifier),apple)});await saveLink(status,entityType,eo.id,kind,saved.item,eoSnap);exported++;continue;}
      if(result.conflicts.length){conflicts.push({entityType,eoId:eo.id,fields:result.conflicts});continue;}
      if(mode!=="two_way"&&result.eoChanged){conflicts.push({entityType,eoId:eo.id,fields:Object.keys(eoSnap).filter(key=>JSON.stringify(eoSnap[key]??null)!==JSON.stringify(base[key]??null))});continue;}
      if(!result.eoChanged&&!result.appleChanged){if(kind==="reminder"&&mode==="two_way"&&reminderNeedsDueAlarm(eoSnap,apple)){const saved=await nativeCall<{item:Item}>("eventkit.save",{kind:"reminder",item:appleReminderPayload(eoSnap,String(apple.calendarIdentifier),String(apple.calendarItemIdentifier),apple)});await saveLink(status,entityType,eo.id,kind,saved.item,eoSnap);exported++;continue;}if(baselineChanged||apple.calendarItemIdentifier!==link.calendar_item_identifier||(entityType==="task"&&!taskNotificationOwnerMatches(eo as Task,apple)))await saveLink(status,entityType,eo.id,kind,apple,base);continue;}
      if(result.appleChanged){if(entityType==="task")await json(`/api/tasks/${eo.id}/eventkit`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:{title:result.merged.title,notes:result.merged.notes,dueDate:result.merged.dueDate,dueTime:result.merged.dueTime,completed:result.merged.completed,completionDate:result.merged.completionDate}})});else await json(`/api/calendar-events/${eo.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(result.merged)});imported++;}
      if(result.eoChanged&&mode==="two_way"){const saved=kind==="reminder"?await nativeCall<{item:Item}>("eventkit.save",{kind:"reminder",item:appleReminderPayload(result.merged,String(apple.calendarIdentifier),String(apple.calendarItemIdentifier),apple)}):await nativeCall<{item:Item}>("eventkit.save",{kind:"calendar",item:{...result.merged,calendarIdentifier:apple.calendarIdentifier,calendarItemIdentifier:apple.calendarItemIdentifier}});apple=saved.item;exported++;}
      if(result.appleChanged&&result.eoChanged)merged++;
      await saveLink(status,entityType,eo.id,kind,apple,result.merged);
    }
    for(const apple of appleItems){
      if(kind==="event"&&apple.isRecurring)continue;
      if(linkedApple.has(String(apple.calendarItemIdentifier)))continue;
      if(!eventKitImportsUnlinked(kind,syncModes[String(apple.calendarIdentifier)]??"off"))continue;
      if(invalidEvent(apple))continue;
      const snapshot=kind==="reminder"?appleReminderSnapshot(apple):appleEventSnapshot(apple);let created:Task|CalendarEvent;
      if(entityType==="task"){const base=await json("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...snapshot,reminderMode:"none",tags:[]})});created=await json(`/api/tasks/${base.id}/eventkit`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:{title:snapshot.title,notes:snapshot.notes,dueDate:snapshot.dueDate,dueTime:snapshot.dueTime,completed:snapshot.completed,completionDate:snapshot.completionDate}})});}else created=await json("/api/calendar-events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(snapshot)});
      await saveLink(status,entityType,created.id,kind,apple,snapshot);imported++;
    }
    if(destination)for(const eo of eoItems){if(linkedEO.has(eo.id)||entityType==="task"&&!eventKitTaskNeedsAppleMirror(eo as Task))continue;const snapshot=entityType==="task"?taskSnapshot(eo as Task):eventSnapshot(eo as CalendarEvent);if(kind==="reminder"){const existing=appleItems.find(item=>item.calendarIdentifier===destination.identifier&&!claimedReminderIDs.has(String(item.calendarItemIdentifier))&&eventKitReminderMatches(item,[snapshot]));if(existing){await adoptReminderLink(status,"task",eo.id,snapshot,existing);claimedReminderIDs.add(String(existing.calendarItemIdentifier));continue;}await createReminderLink(status,"task",eo.id,snapshot,destination.identifier);}else{if(eoItems.some(candidate=>candidate.id!==eo.id&&linkedEO.has(candidate.id)&&stable(eventSnapshot(candidate as CalendarEvent))===stable(snapshot)))continue;const saved=await nativeCall<{item:Item}>("eventkit.save",{kind:"calendar",item:{...snapshot,calendarIdentifier:destination.identifier}});await saveLink(status,entityType,eo.id,kind,saved.item,snapshot);}exported++;}}
  async function reconcileDomainReminders(){const relevant=links.filter(link=>link.entity_type==="reminder"),linkedEO=new Set(relevant.map(link=>link.eo_id)),claimedApple=new Set(claimedReminderIDs);
    for(const link of relevant){let eo=reminders.find(item=>item.id===link.eo_id);if(!eo)continue;const domain=eventKitReminderDomain(eo),destination=domain?status.reminderLists.find(source=>source.identifier===routes[domain]&&source.allowsContentModifications):null;if(!destination)continue;let apple=appleReminders.find(item=>item.calendarItemIdentifier===link.calendar_item_identifier);
      if(eo.status!=="completed"&&(!eo.isActive||!eo.nextDueAt)){await nativeCall("eventkit.delete",{kind:"reminder",calendarItemIdentifier:link.calendar_item_identifier});await json("/api/eventkit/links",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:link.id})});continue;}
      let snapshot=eo.status==="completed"?{...link.last_synced_snapshot,completed:true,completionDate:eo.lastCompletedAt}:reminderSnapshot(eo);const legacy=eo.note===snapshot.notes?snapshot:{...snapshot,notes:eo.note};if(!apple){apple=appleReminders.find(item=>item.calendarIdentifier===destination.identifier&&!claimedApple.has(String(item.calendarItemIdentifier))&&eventKitReminderMatches(item,[snapshot,legacy,link.last_synced_snapshot]));if(apple)claimedApple.add(String(apple.calendarItemIdentifier));}if(!apple&&Boolean(snapshot.completed)&&(!snapshot.completionDate||Date.parse(String(snapshot.completionDate))<Date.now()-30*86400000))continue;if(apple&&Boolean(apple.completed)&&!Boolean(link.last_synced_snapshot.completed)&&!Boolean(snapshot.completed)){eo=await json(`/api/reminders/${eo.id}/complete`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}) as Reminder;snapshot=eo.status==="completed"?{...link.last_synced_snapshot,completed:true,completionDate:eo.lastCompletedAt}:reminderSnapshot(eo);imported++;if(eventKitHasNextOccurrence(eo)){await createReminderLink(status,"reminder",eo.id,snapshot,destination.identifier,eo.timezone);exported++;continue;}}
      if(!apple)await createReminderLink(status,"reminder",eo.id,snapshot,destination.identifier,eo.timezone);else if(link.calendar_item_identifier!==apple.calendarItemIdentifier||link.calendar_identifier!==destination.identifier||stable(snapshot)!==stable(link.last_synced_snapshot)||stable(appleReminderSnapshot(apple))!==stable(snapshot)||reminderNeedsDueAlarm(snapshot,apple)){const saved=await nativeCall<{item:Item}>("eventkit.save",{kind:"reminder",item:appleReminderPayload(snapshot,destination.identifier,String(apple.calendarItemIdentifier),apple,eo.timezone)});await saveLink(status,"reminder",eo.id,"reminder",saved.item,snapshot);}else continue;exported++;
    }
    for(const eo of reminders){if(linkedEO.has(eo.id)||!eo.isActive||!eo.nextDueAt)continue;const domain=eventKitReminderDomain(eo),destination=domain?status.reminderLists.find(source=>source.identifier===routes[domain]&&source.allowsContentModifications):null;if(!destination)continue;const snapshot=reminderSnapshot(eo),legacy=eo.note===snapshot.notes?snapshot:{...snapshot,notes:eo.note},existing=appleReminders.find(item=>item.calendarIdentifier===destination.identifier&&!claimedApple.has(String(item.calendarItemIdentifier))&&eventKitReminderMatches(item,[snapshot,legacy]));if(existing){await adoptReminderLink(status,"reminder",eo.id,snapshot,existing,eo.timezone);claimedApple.add(String(existing.calendarItemIdentifier));continue;}await createReminderLink(status,"reminder",eo.id,snapshot,destination.identifier,eo.timezone);exported++;}}
  await reconcile("reminder","task",appleReminders,tasks);await reconcileDomainReminders();await reconcile("event","calendar_event",appleEvents,events);return{imported,exported,merged,conflicts,skippedEvents,lastSync:new Date().toISOString()};}
