import type { CalendarEvent,Task } from "./types.ts";
import { nativeCall } from "./native-bridge.ts";

export type EventKitSyncMode="off"|"import"|"two_way";
export type EventKitNotificationOwner="eo"|"apple";
export type EventKitSource={identifier:string;title:string;sourceIdentifier:string;sourceTitle:string;allowsContentModifications:boolean};
export type EventKitStatus={available:boolean;installationId:string;calendarPermission:string;reminderPermission:string;calendars:EventKitSource[];reminderLists:EventKitSource[]};
export type EventKitModes=Record<string,EventKitSyncMode>;
type Item=Record<string,unknown>;
type Link={id:number;entity_type:"task"|"calendar_event";eo_id:number;eventkit_entity_type:"reminder"|"event";calendar_item_identifier:string;external_identifier:string|null;calendar_identifier:string;source_identifier:string;last_synced_snapshot:Item};

export function mergeEventKitSnapshots(base:Item,eo:Item,apple:Item){const merged:Item={},conflicts:string[]=[];for(const key of new Set([...Object.keys(base),...Object.keys(eo),...Object.keys(apple)])){const b=JSON.stringify(base[key]??null),e=JSON.stringify(eo[key]??null),a=JSON.stringify(apple[key]??null),ec=e!==b,ac=a!==b;if(ec&&ac&&e!==a)conflicts.push(key);else merged[key]=ac?apple[key]:eo[key];}return{merged,conflicts,eoChanged:JSON.stringify(base)!==JSON.stringify(eo),appleChanged:JSON.stringify(base)!==JSON.stringify(apple)};}
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Item).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`;return JSON.stringify(value);}
async function hash(value:Item){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(stable(value)));return[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,"0")).join("");}
export function taskSnapshot(task:Task):Item{return{title:task.title,notes:task.notes,dueDate:task.dueDate,dueTime:task.dueTime,completed:task.completed,completionDate:task.completedAt};}
export function appleReminderSnapshot(item:Item):Item{return{title:String(item.title??""),notes:String(item.notes??""),dueDate:item.dueDate??null,dueTime:item.dueTime??null,completed:Boolean(item.completed),completionDate:item.completionDate??null};}
function eventSnapshot(event:CalendarEvent|Item):Item{return{title:String(event.title??""),notes:String(event.notes??""),startAt:String("startAt" in event?event.startAt:event.start_at),endAt:String("endAt" in event?event.endAt:event.end_at),isAllDay:Boolean("isAllDay" in event?event.isAllDay:event.is_all_day),timezone:(event.timezone as string|null)??null,location:String(event.location??""),status:String(event.status??"confirmed")};}
function appleEventSnapshot(item:Item):Item{return{title:String(item.title??""),notes:String(item.notes??""),startAt:String(item.startAt),endAt:String(item.endAt),isAllDay:Boolean(item.isAllDay),timezone:item.timezone??null,location:String(item.location??""),status:String(item.status??"confirmed")};}
export function appleReminderPayload(snapshot:Item,calendarIdentifier:string,identifier?:string,existing?:Item){return{calendarItemIdentifier:identifier,calendarIdentifier,title:snapshot.title,notes:snapshot.notes,dueDate:snapshot.dueDate,dueTime:snapshot.dueTime,timezone:typeof existing?.timezone==="string"?existing.timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,priority:Number(existing?.priority??0),completed:snapshot.completed,completionDate:snapshot.completionDate,alarms:Array.isArray(existing?.alarms)?existing.alarms:[]};}
async function json(url:string,init?:RequestInit){const response=await fetch(url,init);if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error??`Sync request failed (${response.status})`);return response.status===204?null:response.json();}
export function eventKitNotificationOwner(item:Item):EventKitNotificationOwner{return Array.isArray(item.alarms)&&item.alarms.length>0?"apple":"eo";}
export function eventKitSourceEnabled(calendarIdentifier:string,modes:EventKitModes){return Boolean(modes[calendarIdentifier]&&modes[calendarIdentifier]!=="off");}
export function eventKitLinkScope<T extends{entity_type:string;calendar_identifier:string}>(links:T[],entityType:string,modes:EventKitModes){const all=links.filter(link=>link.entity_type===entityType);return{all,active:all.filter(link=>eventKitSourceEnabled(link.calendar_identifier,modes))};}
export function eventKitImportsUnlinked(kind:"reminder"|"event",mode:EventKitSyncMode){return kind==="event"||mode==="import";}
export function eventKitMissingAppleAction(kind:"reminder"|"event",mode:EventKitSyncMode){return kind==="reminder"&&mode==="two_way"?"recreate":"delete_eo";}
function taskNotificationOwnerMatches(task:Task,apple:Item){const channel=eventKitNotificationOwner(apple)==="apple"?"apple_reminders":"pwa";return(task.reminders??[]).every(rule=>rule.deliveryChannel===channel);}
async function saveLink(status:EventKitStatus,entityType:Link["entity_type"],eoId:number,kind:Link["eventkit_entity_type"],apple:Item,snapshot:Item){await json("/api/eventkit/links",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({installationId:status.installationId,entityType,eoId,eventkitEntityType:kind,calendarItemIdentifier:apple.calendarItemIdentifier,externalIdentifier:apple.externalIdentifier,calendarIdentifier:apple.calendarIdentifier,sourceIdentifier:apple.sourceIdentifier,lastSyncedHash:await hash(snapshot),lastSyncedSnapshot:snapshot,appleLastModifiedAt:apple.lastModifiedAt,...(kind==="reminder"?{notificationOwner:eventKitNotificationOwner(apple)}:{})})});}

export async function synchronizeEventKit(status:EventKitStatus,modes:EventKitModes){const calendarIDs=status.calendars.filter(source=>eventKitSourceEnabled(source.identifier,modes)).map(source=>source.identifier),reminderIDs=status.reminderLists.filter(source=>eventKitSourceEnabled(source.identifier,modes)).map(source=>source.identifier),now=new Date(),from=new Date(now);from.setDate(from.getDate()-90);const to=new Date(now);to.setDate(to.getDate()+365);const [appleEvents,appleReminders,tasks,events,links]=await Promise.all([calendarIDs.length?nativeCall<{items:Item[]}>("eventkit.fetch",{kind:"calendar",calendarIdentifiers:calendarIDs,from:from.toISOString(),to:to.toISOString()}).then(value=>value.items):[],reminderIDs.length?nativeCall<{items:Item[]}>("eventkit.fetch",{kind:"reminder",calendarIdentifiers:reminderIDs,completedSince:new Date(Date.now()-30*86400000).toISOString()}).then(value=>value.items):[],json("/api/tasks?status=all") as Promise<Task[]>,json(`/api/calendar-events?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}&limit=500`) as Promise<CalendarEvent[]>,json(`/api/eventkit/links?installationId=${encodeURIComponent(status.installationId)}`) as Promise<Link[]>]);let imported=0,exported=0,merged=0;const conflicts:Array<{entityType:string;eoId:number;fields:string[]}>=[];
  async function reconcile(kind:"reminder"|"event",entityType:"task"|"calendar_event",appleItems:Item[],eoItems:Array<Task|CalendarEvent>){
    const scope=eventKitLinkScope(links,entityType,modes),linkedEO=new Set(scope.all.map(link=>link.eo_id)),linkedApple=new Set<string>();
    for(const link of scope.active){
      const mode=modes[link.calendar_identifier],eo=eoItems.find(item=>item.id===link.eo_id);
      let apple=appleItems.find(item=>item.calendarItemIdentifier===link.calendar_item_identifier)||appleItems.find(item=>item.externalIdentifier&&item.externalIdentifier===link.external_identifier&&item.calendarIdentifier===link.calendar_identifier&&item.sourceIdentifier===link.source_identifier);
      if(!apple){const recovered=appleItems.filter(item=>item.calendarIdentifier===link.calendar_identifier&&item.sourceIdentifier===link.source_identifier&&stable(kind==="reminder"?appleReminderSnapshot(item):appleEventSnapshot(item))===stable(link.last_synced_snapshot));if(recovered.length===1)apple=recovered[0];}
      if(apple)linkedApple.add(String(apple.calendarItemIdentifier));
      if(kind==="event"&&apple?.isRecurring)continue;
      if(!eo&&apple&&mode==="two_way"){await nativeCall("eventkit.delete",{kind:kind==="event"?"calendar":"reminder",calendarItemIdentifier:apple.calendarItemIdentifier});await json("/api/eventkit/links",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:link.id})});continue;}
      if(eo&&!apple){
        if(entityType==="task"&&Boolean(link.last_synced_snapshot.completed)&&(!link.last_synced_snapshot.completionDate||Date.parse(String(link.last_synced_snapshot.completionDate))<Date.now()-30*86400000))continue;
        if(eventKitMissingAppleAction(kind,mode)==="recreate"){const snapshot=taskSnapshot(eo as Task),saved=await nativeCall<{item:Item}>("eventkit.save",{kind:"reminder",item:appleReminderPayload(snapshot,link.calendar_identifier)});await saveLink(status,entityType,eo.id,kind,saved.item,snapshot);exported++;continue;}
        await json(entityType==="task"?`/api/tasks/${eo.id}`:`/api/calendar-events/${eo.id}`,{method:"DELETE"});await json("/api/eventkit/links",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:link.id})});continue;
      }
      if(!eo||!apple)continue;
      const storedBase=link.last_synced_snapshot,base=entityType==="task"?appleReminderSnapshot(storedBase):storedBase,baselineChanged=stable(base)!==stable(storedBase),eoSnap=entityType==="task"?taskSnapshot(eo as Task):eventSnapshot(eo as CalendarEvent),appleSnap=kind==="reminder"?appleReminderSnapshot(apple):appleEventSnapshot(apple),result=mergeEventKitSnapshots(base,eoSnap,appleSnap);
      if(result.conflicts.length){conflicts.push({entityType,eoId:eo.id,fields:result.conflicts});continue;}
      if(mode!=="two_way"&&result.eoChanged){conflicts.push({entityType,eoId:eo.id,fields:Object.keys(eoSnap).filter(key=>JSON.stringify(eoSnap[key]??null)!==JSON.stringify(base[key]??null))});continue;}
      if(!result.eoChanged&&!result.appleChanged){if(baselineChanged||apple.calendarItemIdentifier!==link.calendar_item_identifier||(entityType==="task"&&!taskNotificationOwnerMatches(eo as Task,apple)))await saveLink(status,entityType,eo.id,kind,apple,base);continue;}
      if(result.appleChanged){if(entityType==="task")await json(`/api/tasks/${eo.id}/eventkit`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:{title:result.merged.title,notes:result.merged.notes,dueDate:result.merged.dueDate,dueTime:result.merged.dueTime,completed:result.merged.completed,completionDate:result.merged.completionDate}})});else await json(`/api/calendar-events/${eo.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(result.merged)});imported++;}
      if(result.eoChanged&&mode==="two_way"){const saved=kind==="reminder"?await nativeCall<{item:Item}>("eventkit.save",{kind:"reminder",item:appleReminderPayload(result.merged,String(apple.calendarIdentifier),String(apple.calendarItemIdentifier),apple)}):await nativeCall<{item:Item}>("eventkit.save",{kind:"calendar",item:{...result.merged,calendarIdentifier:apple.calendarIdentifier,calendarItemIdentifier:apple.calendarItemIdentifier}});apple=saved.item;exported++;}
      if(result.appleChanged&&result.eoChanged)merged++;
      await saveLink(status,entityType,eo.id,kind,apple,result.merged);
    }
    for(const apple of appleItems){
      if(kind==="event"&&apple.isRecurring)continue;
      if(linkedApple.has(String(apple.calendarItemIdentifier)))continue;
      if(!eventKitImportsUnlinked(kind,modes[String(apple.calendarIdentifier)]??"off"))continue;
      const snapshot=kind==="reminder"?appleReminderSnapshot(apple):appleEventSnapshot(apple);let created:Task|CalendarEvent;
      if(entityType==="task"){const base=await json("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...snapshot,reminderMode:"none",tags:[]})});created=await json(`/api/tasks/${base.id}/eventkit`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:{title:snapshot.title,notes:snapshot.notes,dueDate:snapshot.dueDate,dueTime:snapshot.dueTime,completed:snapshot.completed,completionDate:snapshot.completionDate}})});}else created=await json("/api/calendar-events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(snapshot)});
      await saveLink(status,entityType,created.id,kind,apple,snapshot);imported++;
    }
    const destination=(kind==="event"?status.calendars:status.reminderLists).find(source=>modes[source.identifier]==="two_way"&&source.allowsContentModifications);if(destination)for(const eo of eoItems){if(linkedEO.has(eo.id))continue;const snapshot=entityType==="task"?taskSnapshot(eo as Task):eventSnapshot(eo as CalendarEvent),saved=kind==="reminder"?await nativeCall<{item:Item}>("eventkit.save",{kind:"reminder",item:appleReminderPayload(snapshot,destination.identifier)}):await nativeCall<{item:Item}>("eventkit.save",{kind:"calendar",item:{...snapshot,calendarIdentifier:destination.identifier}});await saveLink(status,entityType,eo.id,kind,saved.item,snapshot);exported++;}}
  await reconcile("reminder","task",appleReminders,tasks);await reconcile("event","calendar_event",appleEvents,events);return{imported,exported,merged,conflicts,lastSync:new Date().toISOString()};}
