import { RelationRuleError, validateRelationEvent, type RelationEventInput } from "./relations.ts";
import type { RelationEventType, RelationFlowType } from "./types";
import { ValidationError, dateOnly } from "./validation.ts";

function object(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))throw new ValidationError("请求内容必须是对象");return value as Record<string,unknown>;}
function string(value:unknown,field:string,max:number,nullable=false){if(nullable&&(value===null||value===undefined||value===""))return null;if(typeof value!=="string"||!value.trim())throw new ValidationError(`${field}不能为空`);const v=value.trim();if(v.length>max)throw new ValidationError(`${field}不能超过 ${max} 个字符`);return v;}
function nullableString(value:unknown,field:string,max:number){return string(value,field,max,true);}
function id(value:unknown,field="ID"){if(typeof value!=="number"||!Number.isSafeInteger(value)||value<=0)throw new ValidationError(`${field}格式不正确`);return value;}
function minor(value:unknown,nullable=true){if(nullable&&(value===null||value===undefined))return null;if(typeof value!=="number"||!Number.isSafeInteger(value)||value<0)throw new ValidationError("金额必须是非负整数分");return value;}
const eventTypes:RelationEventType[]=["expense","gift","repayment","favor","interaction"],flowTypes:RelationFlowType[]=["advance","treat","gift","repayment","favor"];
function closeness(value:unknown){if(value===null||value===undefined||value==="")return null;if(typeof value!=="number"||!Number.isInteger(value)||value<1||value>5)throw new ValidationError("关系远近必须是 1 到 5");return value as 1|2|3|4|5;}
function relationshipStatus(value:unknown):"active"|"ended"{if(value!=="active"&&value!=="ended")throw new ValidationError("关系状态不正确");return value;}

export function parseRelationPerson(value:unknown){const body=object(value);return{name:string(body.name,"姓名",100)!,nickname:nullableString(body.nickname,"昵称",100),relationLabel:nullableString(body.relationLabel,"关系称谓",100),closenessRank:closeness(body.closenessRank),relationshipStatus:body.relationshipStatus===undefined?"active" as const:relationshipStatus(body.relationshipStatus),birthday:body.birthday?dateOnly(body.birthday,"生日"):null,likes:nullableString(body.likes,"喜好",2000),avoid:nullableString(body.avoid,"雷点",2000),note:nullableString(body.note,"备注",5000)};}
export function parseRelationPersonPatch(value:unknown){const body=object(value);const result={name:body.name===undefined?undefined:string(body.name,"姓名",100)!,nickname:body.nickname===undefined?undefined:nullableString(body.nickname,"昵称",100),relationLabel:body.relationLabel===undefined?undefined:nullableString(body.relationLabel,"关系称谓",100),closenessRank:body.closenessRank===undefined?undefined:closeness(body.closenessRank),relationshipStatus:body.relationshipStatus===undefined?undefined:relationshipStatus(body.relationshipStatus),birthday:body.birthday===undefined?undefined:body.birthday?dateOnly(body.birthday,"生日"):null,likes:body.likes===undefined?undefined:nullableString(body.likes,"喜好",2000),avoid:body.avoid===undefined?undefined:nullableString(body.avoid,"雷点",2000),note:body.note===undefined?undefined:nullableString(body.note,"备注",5000),archivedAt:body.archivedAt===undefined?undefined:body.archivedAt===null?null:string(body.archivedAt,"归档时间",50)};if(Object.values(result).every(v=>v===undefined))throw new ValidationError("没有可更新的人物字段");return result;}
export function parseRelationEvent(value:unknown):RelationEventInput{const body=object(value);if(!eventTypes.includes(body.eventType as RelationEventType))throw new ValidationError("事件类型不正确");if(typeof body.occurredAt!=="string"||Number.isNaN(Date.parse(body.occurredAt)))throw new ValidationError("发生日期不正确");if(typeof body.occurredHasExplicitTime!=="boolean")throw new ValidationError("时间精度不正确");if(!Array.isArray(body.parties)||!Array.isArray(body.items)||!Array.isArray(body.flows))throw new ValidationError("事件参与者、明细和流向必须是数组");const input:RelationEventInput={eventType:body.eventType as RelationEventType,title:string(body.title,"标题",200)!,note:nullableString(body.note,"备注",5000),occurredAt:body.occurredAt,occurredHasExplicitTime:body.occurredHasExplicitTime,currency:"CNY",totalAmountMinor:minor(body.totalAmountMinor),isInPerson:body.isInPerson===null||body.isInPerson===undefined?null:typeof body.isInPerson==="boolean"?body.isInPerson:(()=>{throw new ValidationError("是否见面格式不正确")})(),parties:body.parties.map(raw=>{const p=object(raw);if(p.partyType!=="self"&&p.partyType!=="person")throw new ValidationError("参与者类型不正确");return{key:string(p.key,"参与者标识",80)!,partyType:p.partyType,personId:p.partyType==="self"?null:id(p.personId,"人物 ID"),shareAmountMinor:minor(p.shareAmountMinor),paidAmountMinor:minor(p.paidAmountMinor)};}),items:body.items.map((raw,index)=>{const i=object(raw);return{label:string(i.label,"明细名称",200)!,amountMinor:minor(i.amountMinor,false)!,sortOrder:typeof i.sortOrder==="number"&&Number.isSafeInteger(i.sortOrder)?i.sortOrder:index};}),flows:body.flows.map(raw=>{const f=object(raw);if(!flowTypes.includes(f.flowType as RelationFlowType))throw new ValidationError("流向类型不正确");return{fromKey:string(f.fromKey,"付款方",80)!,toKey:string(f.toKey,"受益方",80)!,flowType:f.flowType as RelationFlowType,amountMinor:minor(f.amountMinor,false)!,settlesFlowId:f.settlesFlowId===null||f.settlesFlowId===undefined?null:id(f.settlesFlowId,"被结清流向 ID"),note:nullableString(f.note,"流向备注",1000)};})};try{return validateRelationEvent(input);}catch(error){if(error instanceof RelationRuleError)throw new ValidationError(error.message);throw error;}}
export function parseMemoryNote(value:unknown){return string(object(value).content,"记忆碎片",5000)!;}
export function parseSettleAdvance(value:unknown){const b=object(value);return{amountMinor:minor(b.amountMinor,false)!,occurredAt:typeof b.occurredAt==="string"&&!Number.isNaN(Date.parse(b.occurredAt))?b.occurredAt:(()=>{throw new ValidationError("还款日期不正确")})(),occurredHasExplicitTime:Boolean(b.occurredHasExplicitTime),note:nullableString(b.note,"备注",1000)};}
