import type { UiLanguage } from "@/lib/locale";

type CopyPair = readonly [zh: string, en: string];

const UI_COPY: CopyPair[] = [
  ["首页", "Home"], ["散落", "Inbox"], ["工坊", "Projects"], ["观测", "Trackers"], ["吃吃", "Food"], ["喝喝", "Drinks"], ["体征", "Health"], ["咪子", "Cats"], ["她们", "Relations"], ["展架", "Media"], ["碎片", "Memo"], ["纪事", "Chronicle"], ["设置", "Settings"],
  ["空间", "Space"], ["生活", "Life"], ["档案", "Archive"], ["工作", "Work"], ["当前", "Current"], ["最近", "Recent"], ["历史", "History"], ["偏好", "Preferences"], ["规则", "Rules"], ["状态", "Status"], ["选项", "Options"], ["详情", "Details"], ["摘要", "Summary"], ["记录", "Records"], ["内容", "Content"], ["标题", "Title"], ["名称", "Name"], ["类型", "Type"], ["日期", "Date"], ["时间", "Time"], ["备注", "Notes"], ["标签", "Tags"], ["分类", "Category"], ["评价", "Rating"], ["优先级", "Priority"], ["严重程度", "Severity"], ["来源", "Source"], ["数值", "Value"], ["单位", "Unit"],
  ["新增", "Add"], ["新增记录", "Add record"], ["新增内容", "Add media"], ["新增工坊", "Add project"], ["新增人物", "Add person"], ["新增提醒", "Add reminder"], ["新增店铺", "Add place"], ["新增菜品", "Add dish"], ["新增待办", "Add task"], ["新增观测", "Add Tracker"], ["新增碎片", "Add Memo"],
  ["编辑", "Edit"], ["编辑记录", "Edit record"], ["编辑任务", "Edit task"], ["编辑店铺", "Edit place"], ["编辑菜品", "Edit dish"], ["编辑记忆", "Edit memory"], ["保存", "Save"], ["保存修改", "Save changes"], ["保存记录", "Save record"], ["保存工坊", "Save project"], ["保存人物", "Save person"], ["保存往来", "Save exchange"], ["保存提醒", "Save reminder"], ["保存店铺", "Save place"], ["保存偏好", "Save preferences"], ["保存连接", "Save connection"], ["保存中…", "Saving…"], ["正在保存…", "Saving…"], ["添加", "Add"], ["更新", "Update"], ["删除", "Delete"], ["取消", "Cancel"], ["关闭", "Close"], ["完成", "Done"], ["稍后", "Snooze"], ["跳过", "Skip"], ["返回", "Back"], ["查看全部", "View all"], ["查看全部 →", "View all →"], ["查看历史", "View history"], ["管理", "Manage"], ["重命名", "Rename"], ["恢复默认", "Restore default"], ["清空搜索", "Clear search"], ["清除筛选", "Clear filters"], ["收起", "Show less"], ["展开", "Show more"], ["继续", "Continue"], ["发送", "Send"], ["复制", "Copy"], ["复制好了", "Copied"],
  ["全部", "All"], ["无", "None"], ["其他", "Other"], ["未设置", "Not set"], ["未填写", "Not entered"], ["未评价", "Not rated"], ["未命名", "Unnamed"], ["未选择", "Not selected"], ["不可用", "Unavailable"], ["可用", "Available"], ["启用", "Enabled"], ["已启用", "Enabled"], ["已停用", "Disabled"], ["已归档", "Archived"], ["已结束", "Ended"], ["当前关系", "Current relationship"], ["当前没有人物", "No people yet"], ["全部分类", "All categories"], ["全部类型", "All types"], ["全部状态", "All statuses"], ["全部标签", "All tags"],
  ["暂无记录", "No records yet"], ["暂无近期记录", "No recent records"], ["暂无待办", "No tasks yet"], ["暂无已完成待办", "No completed tasks yet"], ["暂无往来", "No exchanges yet"], ["暂无观测", "No Trackers yet"], ["没有匹配记录", "No matching records"], ["没有匹配的人物", "No matching people"], ["没有匹配的饮品记录", "No matching drink records"], ["没有找到匹配店铺", "No matching places"], ["没有匹配的内容", "No matching media"], ["暂无工坊", "No projects yet"], ["还没有关联记录", "No linked records yet"], ["正在载入…", "Loading…"], ["正在读取设置…", "Loading settings…"], ["正在读取店铺…", "Loading place…"], ["暂时翻不到这些数据", "Could not load this data"],
  ["今天", "Today"], ["昨天", "Yesterday"], ["明天", "Tomorrow"], ["全天", "All day"], ["现在", "Now"], ["本周", "This week"], ["本月", "This month"], ["今年", "This year"], ["最近 7 天", "Last 7 days"], ["最近 30 天", "Last 30 days"], ["最近 12 个月", "Last 12 months"], ["日期记录", "Date only"], ["不设时间", "No time"], ["自定义", "Custom"], ["今天稍后", "Later today"], ["截止日期", "Due date"], ["今天到期", "Due today"], ["明天到期", "Due tomorrow"], ["下次检查", "Next due"],
  ["私人收藏", "Private collection"], ["长期记忆", "Long-term memory"], ["留下来的", "Worth remembering"], ["总览", "All Spaces"], ["驻点", "Favorites"], ["应用与外观", "App & Appearance"], ["界面设置", "Interface"], ["界面语言", "Interface language"], ["中文字体", "Chinese typeface"], ["英文字体", "English typeface"], ["显示模式", "Display mode"], ["颜色主题", "Color theme"], ["浅色", "Light"], ["深色", "Dark"], ["跟随系统", "System"], ["全部设置", "All Settings"], ["对话身份", "Conversation identity"], ["对话外观", "Conversation appearance"], ["说话和反应", "Voice & response"], ["我的身份", "My identity"], ["我的称呼", "My name"], ["回复长度", "Response length"], ["主动程度", "Initiative"],
  ["快速操作", "Quick actions"], ["新增咪子", "Add cat"], ["护理", "Care"], ["新增护理", "Add care"], ["哪种护理？", "What kind of care?"], ["一次性", "One-time"], ["在指定日期做一次", "Do once on a specific date"], ["日常护理", "Routine"], ["按计划重复", "Repeat on a schedule"], ["新增日常护理", "Add routine"], ["编辑日常护理", "Edit routine"], ["保存日常护理", "Save routine"], ["家庭护理", "Household care"], ["家中的共享日常护理", "Shared routines for your home"], ["新增一次性护理", "Add one-time"], ["最近家庭记录", "Recent household records"], ["新增第一条家庭日常护理", "Add the first household routine"], ["最近记录", "Recent records"], ["未完成", "Not completed yet"], ["日常护理已完成", "Routine completed"], ["咪子已添加", "Cat added"], ["性别", "Sex"], ["生日", "Birthday"], ["领养日期", "Adoption date"], ["雌性", "Female"], ["雄性", "Male"], ["未知", "Unknown"],
  ["值得关注", "Worth keeping in view"], ["活跃", "Active"], ["当前没有需要关注的记录。", "Nothing active right now."], ["健康记录", "Health records"], ["新增健康记录", "Add health record"], ["编辑健康记录", "Edit health record"], ["健康记录已保存", "Health record saved"], ["训练", "Training"], ["记录训练", "Log training"], ["今日还没有训练记录。", "No training logged today."], ["静息热量", "Resting kcal"], ["活动热量", "Active kcal"], ["能量历史", "Energy history"], ["手动覆盖", "Manual overrides"], ["保存能量", "Save energy"],
  ["店铺库", "Places"], ["店铺详情", "Place details"], ["店铺名称", "Place name"], ["分店 / 门店", "Branch"], ["总体评价", "Overall rating"], ["菜品", "Dishes"], ["菜名", "Dish name"], ["推荐这道菜", "Recommend this dish"], ["最近关联的饮食", "Recent food records"], ["返回店铺库", "Back to places"], ["删除或归档店铺", "Delete or archive place"], ["店铺不存在", "Place not found"], ["店铺库还是空的", "No places yet"], ["先记下一家你愿意再吃的店。", "Add a place you would order from again."], ["还没有记录这家店的菜品。", "No dishes recorded for this place."], ["还没有关联的饮食记录", "No linked food records"], ["喜欢", "Love"], ["还不错", "Good"], ["一般", "Neutral"], ["避雷", "Avoid"], ["常吃", "Frequent"], ["偶尔吃", "Occasional"], ["暂时不点", "Paused"], ["已关闭", "Closed"],
  ["今日饮品", "Today's drinks"], ["记饮品", "Log drink"], ["饮品历史", "Drink History"], ["饮品类型", "Drink type"], ["常喝名称 / Brand", "Usual name / brand"], ["场景", "Context"], ["冷热 / 冰量", "Temperature / ice"], ["糖度", "Sweetness"], ["容量 ml", "Volume ml"], ["我的饮品习惯", "My drink preferences"], ["偏好饮品", "Preferred drinks"], ["限制", "Limits"], ["暂无限制", "No limits"], ["设置限制", "Set limit"], ["未估算热量", "Calories not estimated"], ["今天暂无饮品记录", "No drinks recorded today"], ["全部历史", "Full history"], ["常温", "Room temperature"], ["热", "Hot"], ["去冰", "No ice"], ["少冰", "Less ice"], ["正常冰", "Regular ice"], ["无糖", "No sugar"], ["半糖", "Half sugar"], ["全糖", "Full sugar"], ["水", "Water"], ["咖啡", "Coffee"], ["茶", "Tea"], ["奶茶", "Milk tea"], ["果汁", "Juice"], ["汽水", "Soda"], ["酒", "Alcohol"],
  ["餐次", "Meal"], ["早餐", "Breakfast"], ["午餐", "Lunch"], ["晚餐", "Dinner"], ["加餐", "Snack"], ["夜宵", "Late snack"], ["自制", "Homemade"], ["外食", "Restaurant"], ["外卖", "Delivery"], ["包装食品", "Packaged food"], ["吃了什么", "What did you eat?"], ["热量估算", "Calorie estimate"], ["当天暂无饮食记录", "No food recorded today"], ["补一条饮食", "Add food record"], ["未关联店铺", "No place linked"], ["未关联菜品", "No dish linked"],
  ["她们", "Relations"], ["按人物整理往来、支出与人情。", "Organize exchanges, expenses and favors by person."], ["记录往来", "Record exchange"], ["搜索人物", "Search people"], ["搜索人物…", "Search people…"], ["排序", "Sort"], ["关系状态", "Relationship status"], ["排序与筛选", "Sort & filter"], ["最近见面", "Last met"], ["最近往来", "Latest exchange"], ["亲近程度", "Closeness"], ["姓名", "Name"], ["当前关系", "Current relationship"], ["已结束", "Ended"], ["支出", "Expense"], ["礼物", "Gift"], ["还款", "Repayment"], ["人情", "Favor"], ["互动", "Interaction"], ["社交余额", "Social balance"], ["待收", "To collect"], ["待还", "To repay"], ["非常亲近", "Very close"], ["亲近", "Close"], ["疏远", "Distant"], ["非常疏远", "Very distant"], ["未设置亲近程度", "Closeness not set"], ["未设置关系", "Relationship not set"],
  ["即将发生", "Upcoming"], ["通知", "Notifications"], ["通知分类", "Notification categories"], ["原生通知", "Native notifications"], ["网页通知", "Web notifications"], ["测试通知", "Test notification"], ["刷新状态", "Refresh status"], ["允许", "Allow"], ["拒绝", "Deny"], ["已允许", "Allowed"], ["已拒绝", "Denied"], ["未请求", "Not requested"], ["计划", "Scheduled"], ["发送记录", "Delivery history"],
  ["模型连接", "Model connections"], ["新增 Provider", "Add Provider"], ["添加 Provider", "Add Provider"], ["Provider 名称", "Provider name"], ["协议", "Protocol"], ["测试连接 / 获取模型", "Test connection / fetch models"], ["模型", "Models"], ["显示名称", "Display name"], ["添加模型", "Add model"], ["设为默认", "Set as default"], ["全局默认", "Global default"], ["删除 Provider", "Delete Provider"], ["更换 Key", "Replace key"], ["移除 Key", "Remove key"], ["尚未保存 API Key", "API key not saved"],
  ["搜索", "Search"], ["自由输入", "Free text"], ["单选", "Single select"], ["多选", "Multiple select"], ["数字", "Number"], ["是 / 否", "Yes / No"], ["属性", "Properties"], ["新增属性", "Add property"], ["记录结构", "Record structure"], ["趋势", "Trend"], ["节奏", "Rhythm"], ["洞察", "Insights"], ["记下", "Record now"],
  ["处理过", "Processed"], ["没整理", "Unsorted"], ["放回未整理", "Move back to unsorted"], ["删除这条 Inbox", "Delete this Inbox item"], ["在翻 Inbox…", "Loading Inbox…"], ["队列已清空。", "The queue is clear."],
  ["全部案底", "All cases"], ["建立案底", "New case"], ["案底名称", "Case title"], ["错误类型", "Error type"], ["错误原话", "Original response"], ["正确行为", "Correct behavior"], ["复发", "Recurrence"], ["这是一次复发", "This is a recurrence"], ["连续正确", "Correct streak"], ["观察期", "Probation"],
  ["新建对话", "New conversation"], ["会话名称", "Conversation name"], ["当前会话模型", "Current conversation model"], ["翻以前聊过的", "Conversation history"], ["空白对话", "Empty conversation"], ["生成回复失败", "Could not generate response"], ["先接一个模型", "Connect a model first"], ["告诉 Eva 一件事…", "Tell Eva something…"],
  ["先放这里", "Capture here"], ["Inbox 为空", "Inbox is empty"], ["查看全部历史", "View full history"], ["常喝类型", "Frequent types"], ["还没有足够记录", "Not enough records yet"], ["有评价后会更准确", "Ratings will make this more accurate"], ["糖度倾向", "Sweetness preference"], ["冷热偏好", "Temperature preference"], ["近期常喝", "Recent favorites"], ["我设的数量线", "My limits"], ["需要时再加，不默认催你。", "Add limits only when useful."], ["今天喝了什么", "Today's drinks"],
  ["基本信息", "Basics"], ["补充信息", "Additional details"], ["事件内容", "Event content"], ["便签内容", "Note content"], ["当前有效", "Active"], ["已合并", "Merged"], ["历史记录", "History"],
  ["AI 与连接", "AI & Connection"], ["一套 Provider 保存一枚加密 Key，再为它添加多个模型。", "Each provider stores one encrypted key and can contain multiple models."], ["还没有 Provider。", "No providers yet."], ["API Key 只在服务端加密保存", "API key is encrypted and stored on the server only"], ["服务器暂时无法处理请求", "The server could not process the request"],
  ["数据与备份", "Data & Backup"], ["旧数据还在", "Preserved data"], ["Task 和 Memory 已从日常导航撤下，但页面、记录和历史链接仍然保留。这里是它们稳定的入口。", "Tasks and Memory no longer appear in daily navigation. Their pages, records and history remain available here."], ["旧待办", "Legacy tasks"], ["旧 Memory", "Legacy Memory"], ["健康与原生能力", "Health & Native"],
  ["随便想点什么", "A quiet conversation"], ["新对话使用默认模型", "New conversations use the default model"], ["OpenAI、DeepSeek、OpenRouter、Ollama 或兼容接口都行。没接也不影响其他生活记录。", "Connect OpenAI, DeepSeek, OpenRouter, Ollama, or another compatible provider. Other records work without it."], ["去设置里接上", "Open Settings"],
  ["“安静地观察，是为了更好地守护。”", "“Quiet observation makes better care possible.”"], ["唤醒 Eva", "Wake Eva"],
  ["创建 EvaOrbit、Refuel，或任何你想持续推进的个人项目。", "Create EvaOrbit, Refuel, or any personal project you want to keep moving."], ["饮食资料库", "Food Library"], ["历史与偏好", "History & Preferences"],
  ["今日进行中", "Today in progress"], ["摄入", "Intake"], ["未记录", "Not recorded"], ["消耗", "Expenditure"], ["平衡", "Balance"], ["静息", "Resting"], ["今天仍在变化，这不是完整的日结。", "Today is still changing. This is not a completed review."], ["还没有健康记录", "No health records yet"], ["只保留未来仍有用的内容。", "Keep the notes that will be useful to your future self."],
  ["电影", "Movies"], ["剧集", "TV Shows"], ["动画", "Anime"], ["纪录片", "Documentaries"], ["重看", "Rewatched"], ["任意状态", "Any status"], ["计划观看", "Planned"], ["观看中", "Watching"], ["已完成", "Completed"], ["已放弃", "Dropped"], ["任意评价", "Any rating"], ["你的私人收藏", "Your private shelf"], ["先添加一部想留在手边的作品。", "Add the first work you want to keep close."],
  ["没有匹配的碎片", "No matching Memo"], ["调整筛选，或新增一条长期记忆。", "Adjust the filters or keep a new long-term memory."], ["纪事还是空的", "Chronicle is empty"], ["先添加一条带日期的 Markdown 记录。", "Add a dated Markdown entry to begin."],
  ["浏览器推送", "Browser push"], ["网页推送和定时发送仍作为浏览器后备。", "Existing Web Push and scheduled delivery remain the browser fallback."], ["未订阅", "Not subscribed"], ["启用网页通知", "Enable Web Notifications"], ["暂无计划", "Nothing scheduled"], ["创建提醒后，它会立即显示在这里。", "Future reminders will appear here immediately after you create them."],
  ["生产数据", "Production data"], ["访问", "Access"], ["私人账户 · RLS", "Private account · RLS"], ["本地后备", "Local fallback"], ["能量同步", "Energy sync"], ["EvaOrbit 只同步静息与活动能量，不上传原始 HealthKit 样本。", "Resting and Active Energy only. EvaOrbit never uploads raw HealthKit samples."], ["仅网页", "Web only"], ["请在 EvaOrbit iOS App 内打开此页以连接 Apple Health。", "Open this page inside the EvaOrbit iOS app to connect Apple Health."],
  ["安静的事也值得被看见", "silent things are still worth noticing"], ["动态", "Posts"], ["日记", "Diary"], ["案底", "Case Files"], ["还没有发布内容。", "Nothing has been posted yet."], ["这里的安静是有意的。", "The quiet here is intentional."], ["只在服务端加密保存", "Encrypted and stored on the server only"],
  ["脑子里刚冒出来什么？\n随便写，不用整理", "What's on your mind?\nNo need to organize it."], ["Inbox 状态筛选", "Inbox status filter"], ["前一天", "Previous day"], ["选择日期", "Choose date"], ["后一天", "Next day"], ["找吃过的…", "Search food records…"], ["排序和筛选人物", "Sort and filter people"], ["AI Provider 列表", "AI provider list"], ["输入 API Key", "Enter API key"],
  ["摄入估算", "Intake estimate"], ["调整关系状态筛选，或新增人物。", "Adjust the relationship filter or add a person."], ["设置 · 通知", "Settings · Notifications"], ["旧数据入口", "Legacy data"], ["基础地址", "Base URL"],
  ["可信度：", "Confidence:"], ["低", "Low"], ["中", "Medium"], ["高", "High"],
  ["补一杯", "Log a drink"], ["饮品", "Drink name"], ["微糖", "Light sugar"], ["少糖", "Less sugar"], ["标准", "Regular"], ["多糖", "Extra sugar"], ["好喝", "Great"], ["还行", "Okay"], ["难喝", "Poor"],
];

const TO_ENGLISH = new Map(UI_COPY);
const TO_CHINESE = new Map(UI_COPY.map(([zh, en]) => [en, zh]));
const TO_CHINESE_LOWER = new Map(UI_COPY.map(([zh, en]) => [en.toLocaleLowerCase("en"), zh]));
const ENGLISH_ALIASES = new Map<string, string>([
  ["New record", "新增记录"], ["New entry", "新增记录"], ["New project", "新增工坊"], ["New Memo", "新增碎片"], ["New Tracker", "新增观测"],
  ["Add Item", "新增条目"], ["New conversation", "新建对话"], ["New case", "建立案底"], ["New Diary entry", "新增日记"],
  ["Wake Eva", "唤醒 Eva"], ["Care", "护理"], ["Latest", "最近"], ["No recent records", "暂无近期记录"],
  ["One-time care you only need to do once.", "只需完成一次的护理。"], ["Recent household records", "最近家庭记录"],
  ["TODAY · IN PROGRESS", "今日进行中"], ["AI PROVIDERS", "AI 服务商"], ["SELF", "自我"],
  ["0 entries", "0 条"], ["quiet", "安静"],
]);
const CHINESE_ALIASES = new Map([...ENGLISH_ALIASES].map(([en, zh]) => [zh, en]));

const DYNAMIC_COPY: Array<{ zh: RegExp; en: RegExp; toZh: (match: RegExpMatchArray) => string; toEn: (match: RegExpMatchArray) => string }> = [
  { zh: /^(\d+) 条$/, en: /^(\d+) entries?$/, toZh: m => `${m[1]} 条`, toEn: m => `${m[1]} ${m[1] === "1" ? "entry" : "entries"}` },
  { zh: /^共 (\d+) 次$/, en: /^(\d+) visits?$/, toZh: m => `共 ${m[1]} 次`, toEn: m => `${m[1]} ${m[1] === "1" ? "visit" : "visits"}` },
  { zh: /^(\d+) 个模型$/, en: /^(\d+) models?$/, toZh: m => `${m[1]} 个模型`, toEn: m => `${m[1]} ${m[1] === "1" ? "model" : "models"}` },
  { zh: /^逾期 (\d+) 天$/, en: /^(\d+) days? overdue$/, toZh: m => `逾期 ${m[1]} 天`, toEn: m => `${m[1]} ${m[1] === "1" ? "day" : "days"} overdue` },
  { zh: /^(\d+) 天前$/, en: /^(\d+)d ago$/, toZh: m => `${m[1]} 天前`, toEn: m => `${m[1]}d ago` },
  { zh: /^约 (\d+) kcal$/, en: /^About (\d+) kcal$/, toZh: m => `约 ${m[1]} kcal`, toEn: m => `About ${m[1]} kcal` },
  { zh: /^可信度：(低|中|高)$/, en: /^Confidence: (Low|Medium|High)$/, toZh: m => `可信度：${({Low:"低",Medium:"中",High:"高"} as Record<string,string>)[m[1]]}`, toEn: m => `Confidence: ${({低:"Low",中:"Medium",高:"High"} as Record<string,string>)[m[1]]}` },
  { zh: /^(传奇|很棒|一般|不行|糟糕)([+-])?$/, en: /^(goat|dope|mid|nope|shit)([+-])?$/i, toZh: m => `${({ goat: "传奇", dope: "很棒", mid: "一般", nope: "不行", shit: "糟糕" } as Record<string,string>)[m[1].toLowerCase()]}${m[2] ?? ""}`, toEn: m => `${({ 传奇: "goat", 很棒: "dope", 一般: "mid", 不行: "nope", 糟糕: "shit" } as Record<string,string>)[m[1]]}${m[2] ?? ""}` },
  { zh: /^(\d{4})年(\d{1,2})月(\d{1,2})日$/, en: /^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (\d{1,2}), (\d{4})$/, toZh: m => `${m[3]}年${({Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Oct:10,Nov:11,Dec:12} as Record<string,number>)[m[1]]}月${m[2]}日`, toEn: m => `${["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][Number(m[2])-1]} ${m[3]}, ${m[1]}` },
  { zh: /^(\d{1,2})月(\d{1,2})日$/, en: /^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (\d{1,2})$/, toZh: m => `${({Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Oct:10,Nov:11,Dec:12} as Record<string,number>)[m[1]]}月${m[2]}日`, toEn: m => `${["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][Number(m[1])-1]} ${m[2]}` },
];

export function translateUiCopy(value: string, language: UiLanguage) {
  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  const text = value.trim();
  if (!text) return value;
  const translated = language === "en"
    ? TO_ENGLISH.get(text) ?? CHINESE_ALIASES.get(text)
    : TO_CHINESE.get(text) ?? ENGLISH_ALIASES.get(text) ?? TO_CHINESE_LOWER.get(text.toLocaleLowerCase("en"));
  if (translated) return `${leading}${translated}${trailing}`;
  for (const pattern of DYNAMIC_COPY) {
    const match = text.match(language === "en" ? pattern.zh : pattern.en);
    if (match) return `${leading}${language === "en" ? pattern.toEn(match) : pattern.toZh(match)}${trailing}`;
  }
  return value;
}
