"use client";

import type { FormEvent } from "react";
import { useState } from "react";
import type { CatRecordKind,Pet } from "@/lib/types";

const now=()=>{const date=new Date();return new Date(date.getTime()-date.getTimezoneOffset()*60_000).toISOString().slice(0,16);};
const empty={petId:"",kind:"event" as CatRecordKind,eventType:"care",occurredAt:now(),title:"",note:"",severity:"",description:"",bodyArea:"",clinic:"",doctor:"",reason:"",symptoms:"",diagnosis:"",examinations:"",treatment:"",prescriptions:"",cost:"",followUpAt:"",createFollowUpReminder:false,name:"",dose:"",unit:"",frequencyText:"",startedAt:now(),endedAt:"",active:true,createMedicationReminder:false,medicationIntervalHours:"12",measurementType:"Weight",value:""};
type Draft=typeof empty;

function iso(value:string){return value?new Date(value).toISOString():null;}
export function CatRecordEditor({pets,initialPetId,onSaved,onCancel,editing}:{pets:Pet[];initialPetId?:number|null;onSaved:()=>void;onCancel:()=>void;editing?:{kind:CatRecordKind;id:number;record:Record<string,unknown>}}){
 const [draft,setDraft]=useState<Draft>(()=>{if(!editing)return{...empty,petId:initialPetId===null?"household":initialPetId?String(initialPetId):pets[0]?String(pets[0].id):"household"};const r=editing.record;return{...empty,...Object.fromEntries(Object.entries(r).map(([k,v])=>[k,v??""])),kind:editing.kind,petId:r.petId===null?"household":String(r.petId),occurredAt:r.occurredAt?new Date(String(r.occurredAt)).toISOString().slice(0,16):now(),startedAt:r.startedAt?new Date(String(r.startedAt)).toISOString().slice(0,16):now(),endedAt:r.endedAt?new Date(String(r.endedAt)).toISOString().slice(0,16):"",followUpAt:r.followUpAt?new Date(String(r.followUpAt)).toISOString().slice(0,16):"",cost:r.cost===null?"":String(r.cost??""),value:String(r.value??"")} as Draft;});const[error,setError]=useState("");
 const household=draft.petId==="household";const kind=household?"event":draft.kind;
 async function submit(event:FormEvent){event.preventDefault();setError("");const body:Record<string,unknown>={...draft,notes:draft.note,kind,petId:household?null:Number(draft.petId),occurredAt:iso(draft.occurredAt),startedAt:iso(draft.startedAt),endedAt:iso(draft.endedAt),followUpAt:iso(draft.followUpAt),cost:draft.cost?Number(draft.cost):null,value:draft.value?Number(draft.value):undefined};const response=await fetch(editing?`/api/cats/records/${editing.kind}/${editing.id}`:"/api/cats/records",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){setError((await response.json()).error??"Could not save record.");return;}const saved=await response.json() as {id:number};if(!editing&&draft.petId!=="household"){let reminder:Record<string,unknown>|null=null;if(kind==="vet_visit"&&draft.createFollowUpReminder&&draft.followUpAt){reminder={title:`Follow up: ${draft.reason}`,targetType:"cat",targetId:Number(draft.petId),sourceType:"vet_visit",sourceId:saved.id,scheduleType:"one_time",startsAt:iso(draft.followUpAt),nextDueAt:iso(draft.followUpAt)};}if(kind==="medication"&&draft.createMedicationReminder){reminder={title:`Medication: ${draft.name}`,targetType:"cat",targetId:Number(draft.petId),sourceType:"medication",sourceId:saved.id,scheduleType:"course",startsAt:iso(draft.startedAt),nextDueAt:iso(draft.startedAt),intervalValue:Number(draft.medicationIntervalHours),intervalUnit:"hour",endsAt:iso(draft.endedAt)};}if(reminder){const reminderResponse=await fetch("/api/reminders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(reminder)});if(!reminderResponse.ok){setError("Record saved, but its reminder could not be created.");return;}}}onSaved();}
 return <form className="editor-card cat-record-editor" onSubmit={submit}><div className="editor-title"><div><span className="eyebrow">{editing?"EDIT RECORD":"NEW RECORD"}</span><h2>{editing?"Edit record":"New record"}</h2></div><button type="button" className="text-button" onClick={onCancel}>Cancel</button></div><div className="cat-record-steps"><label className="field"><span>Subject</span><select disabled={Boolean(editing)} value={draft.petId} onChange={e=>setDraft({...draft,petId:e.target.value,kind:e.target.value==="household"?"event":draft.kind})}>{pets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}<option value="household">Household</option></select></label><label className="field"><span>Record type</span><select disabled={Boolean(editing)} value={kind} onChange={e=>setDraft({...draft,kind:e.target.value as CatRecordKind})}>{household?<><option value="event">Cleaning / Shared Care</option></>:<><option value="event">Grooming / Care</option><option value="symptom">Symptom</option><option value="vet_visit">Vet Visit</option><option value="medication">Medication</option><option value="measurement">Measurement</option></>}</select></label></div>
 {kind==="event"&&<div className="form-grid"><label className="field"><span>Care type</span><select value={draft.eventType} onChange={e=>setDraft({...draft,eventType:e.target.value})}>{household?<><option value="cleaning">Cleaning / Shared Care</option><option value="shared_note">Shared Note / Other</option></>:<><option value="deworming">Deworming</option><option value="grooming">Grooming</option><option value="care">Care</option><option value="note">Note / Other</option></>}</select></label><DateField label="Occurred at" value={draft.occurredAt} onChange={v=>setDraft({...draft,occurredAt:v})}/><TextField label="Title" value={draft.title} onChange={v=>setDraft({...draft,title:v})} required/><TextArea label="Note" value={draft.note} onChange={v=>setDraft({...draft,note:v})}/></div>}
 {kind==="symptom"&&<div className="form-grid"><DateField label="Occurred at" value={draft.occurredAt} onChange={v=>setDraft({...draft,occurredAt:v})}/><TextField label="Symptom" value={draft.title} onChange={v=>setDraft({...draft,title:v})} required/><TextField label="Severity" value={draft.severity} onChange={v=>setDraft({...draft,severity:v})}/><TextField label="Body area" value={draft.bodyArea} onChange={v=>setDraft({...draft,bodyArea:v})}/><TextArea label="Description" value={draft.description} onChange={v=>setDraft({...draft,description:v})}/><TextArea label="Note" value={draft.note} onChange={v=>setDraft({...draft,note:v})}/></div>}
 {kind==="vet_visit"&&<div className="form-grid"><DateField label="Visited at" value={draft.occurredAt} onChange={v=>setDraft({...draft,occurredAt:v})}/><TextField label="Reason" value={draft.reason} onChange={v=>setDraft({...draft,reason:v})} required/><TextField label="Clinic" value={draft.clinic} onChange={v=>setDraft({...draft,clinic:v})}/><TextField label="Doctor" value={draft.doctor} onChange={v=>setDraft({...draft,doctor:v})}/><TextArea label="Symptoms" value={draft.symptoms} onChange={v=>setDraft({...draft,symptoms:v})}/><TextArea label="Diagnosis" value={draft.diagnosis} onChange={v=>setDraft({...draft,diagnosis:v})}/><TextArea label="Examinations / tests" value={draft.examinations} onChange={v=>setDraft({...draft,examinations:v})}/><TextArea label="Treatment" value={draft.treatment} onChange={v=>setDraft({...draft,treatment:v})}/><TextArea label="Prescriptions" value={draft.prescriptions} onChange={v=>setDraft({...draft,prescriptions:v})}/><label className="field"><span>Cost</span><input type="number" min="0" value={draft.cost} onChange={e=>setDraft({...draft,cost:e.target.value})}/></label><DateField label="Follow-up" value={draft.followUpAt} onChange={v=>setDraft({...draft,followUpAt:v})}/>{!editing&&draft.followUpAt&&<label className="switch-row"><input type="checkbox" checked={draft.createFollowUpReminder} onChange={e=>setDraft({...draft,createFollowUpReminder:e.target.checked})}/>Create a one-time follow-up reminder</label>}<TextArea label="Notes" value={draft.note} onChange={v=>setDraft({...draft,note:v})}/></div>}
 {kind==="medication"&&<div className="form-grid"><TextField label="Medication" value={draft.name} onChange={v=>setDraft({...draft,name:v})} required/><TextField label="Dose" value={draft.dose} onChange={v=>setDraft({...draft,dose:v})}/><TextField label="Unit" value={draft.unit} onChange={v=>setDraft({...draft,unit:v})}/><TextField label="Frequency" value={draft.frequencyText} onChange={v=>setDraft({...draft,frequencyText:v})}/><DateField label="Started at" value={draft.startedAt} onChange={v=>setDraft({...draft,startedAt:v})}/><DateField label="Ended at" value={draft.endedAt} onChange={v=>setDraft({...draft,endedAt:v})}/><TextField label="Reason" value={draft.reason} onChange={v=>setDraft({...draft,reason:v})}/><label className="switch-row"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>Currently active</label>{!editing&&<><label className="switch-row"><input type="checkbox" checked={draft.createMedicationReminder} onChange={e=>setDraft({...draft,createMedicationReminder:e.target.checked})}/>Create a course reminder</label>{draft.createMedicationReminder&&<label className="field"><span>Repeat every (hours)</span><input required type="number" min="1" max="720" value={draft.medicationIntervalHours} onChange={e=>setDraft({...draft,medicationIntervalHours:e.target.value})}/></label>}</>}<TextArea label="Notes" value={draft.note} onChange={v=>setDraft({...draft,note:v})}/></div>}
 {kind==="measurement"&&<div className="form-grid"><DateField label="Measured at" value={draft.occurredAt} onChange={v=>setDraft({...draft,occurredAt:v})}/><TextField label="Measurement" value={draft.measurementType} onChange={v=>setDraft({...draft,measurementType:v})} required/><label className="field"><span>Value</span><input required type="number" step="any" value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})}/></label><TextField label="Unit" value={draft.unit} onChange={v=>setDraft({...draft,unit:v})} required/><TextArea label="Note" value={draft.note} onChange={v=>setDraft({...draft,note:v})}/></div>}
 {error&&<p className="form-error">{error}</p>}<button className="button primary">{editing?"Save changes":"Save record"}</button></form>;
}
function TextField({label,value,onChange,required=false}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label className="field"><span>{label}</span><input required={required} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="field wide"><span>{label}</span><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function DateField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><input type="datetime-local" value={value} onChange={e=>onChange(e.target.value)}/></label>}
