"use client";
import Link from "next/link";
import type { FormEvent } from "react";
import { useState } from "react";
import { DueReminders } from "@/components/due-reminders";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import type { CatTimelineEntry,DueReminder,Pet,Reminder } from "@/lib/types";
import { CatRecordEditor } from "./cat-record-editor";
import { ReminderEditor } from "./reminder-editor";
import { PushNotificationControl } from "@/components/push-notification-control";

type Card={pet:Pet;latest:CatTimelineEntry|null;nextReminder:Reminder|null};type Dashboard={pets:Card[];household:Array<{latest:CatTimelineEntry;nextReminder:Reminder|null}>;timeline:CatTimelineEntry[]};
function relative(value:string){const days=Math.floor((Date.now()-new Date(value).getTime())/86400000);if(days<=0)return"Today";if(days===1)return"Yesterday";return`${days} days ago`;}
function dueDate(value:string|null|undefined){return value?new Date(value).toLocaleDateString("en-US",{month:"short",day:"numeric"}):"No upcoming reminder";}
export function CatsView({initialDashboard,initialDue}:{initialDashboard:Dashboard;initialDue:DueReminder[]}){const[dashboard,setDashboard]=useState(initialDashboard);const[due,setDue]=useState(initialDue);const[panel,setPanel]=useState<"record"|"pet"|"reminder"|null>(null);const[editing,setEditing]=useState<{kind:CatTimelineEntry["kind"];id:number;record:Record<string,unknown>}|undefined>();const pets=dashboard.pets.map(item=>item.pet);const householdHistory=dashboard.timeline.filter(item=>item.petId===null);async function load(){const[d,r]=await Promise.all([fetch("/api/cats"),fetch("/api/reminders/due")]);if(d.ok)setDashboard(await d.json());if(r.ok)setDue(((await r.json()) as DueReminder[]).filter(item=>item.targetType==="cat"||item.targetType==="cat_household"));}async function editRecord(item:CatTimelineEntry){const response=await fetch(`/api/cats/records/${item.kind}/${item.id}`);if(!response.ok)return;setEditing({kind:item.kind,id:item.id,record:await response.json()});setPanel("record");}async function removeRecord(item:CatTimelineEntry){if(!confirm(`Delete “${item.title}”?`))return;const response=await fetch(`/api/cats/records/${item.kind}/${item.id}`,{method:"DELETE"});if(response.ok)void load();}return <div className="page cats-page"><PageHeader eyebrow="LIFE" title="Cats" action={<div className="page-actions"><button className="button secondary" onClick={()=>setPanel("reminder")}>Reminder</button><button className="button primary" onClick={()=>{setEditing(undefined);setPanel("record")}}><Icon name="plus"/>New record</button></div>}/>
{panel==="record"&&<CatRecordEditor pets={pets} editing={editing} initialPetId={editing?null:undefined} onCancel={()=>{setPanel(null);setEditing(undefined)}} onSaved={()=>{setPanel(null);setEditing(undefined);void load();}}/>}{panel==="reminder"&&<ReminderEditor pets={pets} onCancel={()=>setPanel(null)} onSaved={()=>{setPanel(null);void load();}}/>}{panel==="pet"&&<PetEditor onCancel={()=>setPanel(null)} onSaved={()=>{setPanel(null);void load();}}/>}
<DueReminders items={due} onChanged={()=>void load()}/>
<section className="cats-pets-section"><div className="section-heading"><span className="eyebrow">CATS</span><button className="text-button" onClick={()=>setPanel("pet")}><Icon name="plus"/>Add cat</button></div>{dashboard.pets.length?<div className="cat-card-grid">{dashboard.pets.map(({pet,latest,nextReminder})=><Link href={`/cats/${pet.id}`} className="cat-card" key={pet.id}><CatAvatar pet={pet}/><div><h2>{pet.name}</h2><p>{latest?<>Last: {latest.title} · {relative(latest.occurredAt)}</>:"No records"}</p><small>{nextReminder?.nextDueAt?`Next: ${nextReminder.title} · ${dueDate(nextReminder.nextDueAt)}`:"No upcoming reminder"}</small></div></Link>)}</div>:<button className="cats-inline-empty" onClick={()=>setPanel("pet")}><Icon name="plus"/>Add cat</button>}</section>
<section className="cats-household-section"><div className="section-heading"><span className="eyebrow">HOUSEHOLD CARE</span></div>{dashboard.household.length?<><div className="household-care-list">{dashboard.household.map(({latest,nextReminder})=><article key={`${latest.kind}-${latest.id}`}><div><strong>{latest.title}</strong><small>Last: {relative(latest.occurredAt)}</small></div><span>{nextReminder?.nextDueAt?`Next: ${dueDate(nextReminder.nextDueAt)}`:"No upcoming reminder"}</span></article>)}</div><details className="household-history"><summary>View history</summary>{householdHistory.map(item=><article key={`${item.kind}-${item.id}`}><div><strong>{item.title}</strong><small>{new Date(item.occurredAt).toLocaleString()}</small></div><div className="cat-record-actions"><button onClick={()=>void editRecord(item)}><Icon name="edit"/>Edit</button><button className="danger" onClick={()=>void removeRecord(item)}><Icon name="trash"/>Delete</button></div></article>)}</details></>:<button className="cats-inline-empty" onClick={()=>{setEditing(undefined);setPanel("record")}}><Icon name="plus"/>Add household care</button>}</section><PushNotificationControl /></div>}

export function CatAvatar({pet,size=54}:{pet:Pet;size?:number}){return <span className="cat-avatar" style={{width:size,height:size,...(pet.avatarUrl?{backgroundImage:`url(${JSON.stringify(pet.avatarUrl)})`,backgroundSize:"cover",backgroundPosition:"center"}:{})}}>{!pet.avatarUrl&&<Icon name="cats"/>}</span>}
function PetEditor({onSaved,onCancel}:{onSaved:()=>void;onCancel:()=>void}){const[draft,setDraft]=useState({name:"",avatarUrl:"",sex:"",birthday:"",adoptionDate:"",notes:""});const[error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();const response=await fetch("/api/cats/pets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,sex:draft.sex||null,isActive:true})});if(!response.ok){setError((await response.json()).error);return;}onSaved();}return <form className="editor-card pet-editor" onSubmit={submit}><div className="editor-title"><div><span className="eyebrow">PROFILE</span><h2>Add cat</h2></div><button type="button" className="text-button" onClick={onCancel}>Cancel</button></div><div className="form-grid"><label className="field"><span>Name</span><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field"><span>Avatar URL</span><input value={draft.avatarUrl} onChange={e=>setDraft({...draft,avatarUrl:e.target.value})} placeholder="Optional"/></label><label className="field"><span>Sex</span><select value={draft.sex} onChange={e=>setDraft({...draft,sex:e.target.value})}><option value="">Not set</option><option value="female">Female</option><option value="male">Male</option><option value="unknown">Unknown</option></select></label><label className="field"><span>Birthday</span><input type="date" value={draft.birthday} onChange={e=>setDraft({...draft,birthday:e.target.value})}/></label><label className="field"><span>Adoption date</span><input type="date" value={draft.adoptionDate} onChange={e=>setDraft({...draft,adoptionDate:e.target.value})}/></label><label className="field wide"><span>Notes</span><textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}<button className="button primary">Add cat</button></form>}
