"use client";
import{FormEvent,useCallback,useEffect,useState}from"react";import{PageHeader}from"@/components/page-header";import{Icon}from"@/components/icons";import type{ApiError,InboxItem,InboxStatus}from"@/lib/types";
export function InboxView(){const[items,setItems]=useState<InboxItem[]>([]),[status,setStatus]=useState<InboxStatus|"all">("inbox"),[content,setContent]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
const load=useCallback(async()=>{setLoading(true);const r=await fetch(`/api/inbox?status=${status}`);setItems(r.ok?await r.json():[]);setLoading(false);},[status]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
async function submit(e:FormEvent){e.preventDefault();setError("");const r=await fetch("/api/inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content,source:"manual"})});if(!r.ok){setError(((await r.json())as ApiError).error);return;}setContent("");setStatus("inbox");await load();}
async function patch(id:number,body:object){await fetch(`/api/inbox/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await load();}
async function remove(id:number){if(!confirm("删掉这条临时记录？"))return;await fetch(`/api/inbox/${id}`,{method:"DELETE"});await load();}
return <div className="page"><PageHeader eyebrow="SPACE" title="Inbox" description="随便丢进来，不用现在整理。"/><form className="capture-card" onSubmit={submit}><textarea autoFocus required rows={4} maxLength={10000} value={content} onChange={e=>setContent(e.target.value)} placeholder="脑子里刚冒出来什么？&#10;随便写，不用整理"/><div>{error&&<p className="form-error">{error}</p>}<button className="button primary" type="submit">先放这里</button></div></form>
<div className="toolbar"><div className="segmented">{([['inbox','没整理'],['processed','处理过'],['archived','归档'],['all','全部']]as const).map(([v,l])=><button className={status===v?"active":""} onClick={()=>setStatus(v)} key={v}>{l}</button>)}</div><span className="result-count">{items.length} 条</span></div>
{loading?<div className="loading-state">在翻 Inbox…</div>:items.length?<div className="inbox-list">{items.map(item=><article className="inbox-row" key={item.id}><p>{item.content}</p><small>{new Date(item.createdAt).toLocaleString("zh-CN")}{item.convertedType?` · 旧版已转为 ${item.convertedType}`:""}</small><div className="row-actions">{item.status==="inbox"&&<><button onClick={()=>patch(item.id,{status:"processed",processedAt:new Date().toISOString()})}>处理好了</button><button onClick={()=>patch(item.id,{status:"archived"})}>归档</button></>}<button className="danger" onClick={()=>remove(item.id)}><Icon name="trash"/></button></div></article>)}</div>:<div className="empty-state"><span className="empty-icon"><Icon name="check"/></span><h2>这里空着</h2><p>脑子也可以暂时空着。</p></div>}</div>}
