"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import { luciusCaseErrorTypeOptions, luciusCaseSeverityOptions, luciusCaseStatusOptions, optionLabel } from "@/lib/long-term-memory";
import type { ApiError, LuciusCase } from "@/lib/types";
import { CaseEditor, caseDraftFromItem, casePayload, type LuciusCaseDraft } from "../case-editor";

async function responseError(response: Response, fallback: string) { const result = await response.json().catch(() => null) as ApiError | null; return result?.error || fallback; }
function DetailBlock({ label, value }: { label: string; value: string | number | null }) { return <section><span>{label}</span><p>{value === null || value === "" ? "—" : value}</p></section>; }
export function CaseDetailView({ initial }: { initial: LuciusCase }) {
  const router = useRouter(); const [item, setItem] = useState(initial); const [draft, setDraft] = useState<LuciusCaseDraft>(() => caseDraftFromItem(initial)); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch(`/api/lucius/cases/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(casePayload(draft)) }); if (!response.ok) throw new Error(await responseError(response, "Could not update Case.")); const updated = await response.json() as LuciusCase; setItem(updated); setDraft(caseDraftFromItem(updated)); setEditing(false); setNotice("Case updated."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update Case."); } finally { setBusy(false); } }
  async function remove() { if (!window.confirm(`Delete case “${item.title}”? This cannot be undone.`)) return; setBusy(true); try { const response = await fetch(`/api/lucius/cases/${item.id}`, { method: "DELETE" }); if (!response.ok) throw new Error(await responseError(response, "Could not delete Case.")); router.push("/lucius/cases"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not delete Case."); } finally { setBusy(false); } }
  return <div className="page cases-page long-term-detail"><Link className="back-link" href="/lucius/cases">← Cases</Link><PageHeader eyebrow={`${optionLabel(luciusCaseErrorTypeOptions, item.errorType)} · ${optionLabel(luciusCaseSeverityOptions, item.severity)}`} title={item.title} description={`${optionLabel(luciusCaseStatusOptions, item.status)} · 最近发生 ${item.latestOccurredDate}`} />{notice && <p className="success-banner">{notice}</p>}{error && <p className="form-error">{error}</p>}
    {editing ? <form className="editor-card long-term-editor case-editor" onSubmit={submit}><CaseEditor draft={draft} setDraft={setDraft} /><div className="form-actions"><button className="button primary" disabled={busy}>Save changes</button><button type="button" className="text-button" onClick={() => { setDraft(caseDraftFromItem(item)); setEditing(false); }}>Cancel</button></div></form> : <><div className="case-detail-summary"><div><span>状态</span><strong>{optionLabel(luciusCaseStatusOptions, item.status)}</strong></div><div><span>累计次数</span><strong>{item.occurrenceCount}</strong></div><div><span>连续正确</span><strong>{item.consecutiveCorrectCount}</strong></div><div><span>复发</span><strong>{item.isRecurrence ? "是" : "否"}</strong></div></div><div className="case-detail-grid"><DetailBlock label="错误原话" value={item.errorQuote} /><DetailBlock label="原因" value={item.cause} /><DetailBlock label="正确行为" value={item.correctBehavior} /><DetailBlock label="强制规则" value={item.mandatoryRule} /><DetailBlock label="惩罚" value={item.punishment} /><DetailBlock label="触发场景" value={item.triggerScenes.join("、")} /></div><dl className="long-term-meta case-meta"><div><dt>首次发生</dt><dd>{item.firstOccurredDate}</dd></div><div><dt>最近发生</dt><dd>{item.latestOccurredDate}</dd></div><div><dt>下次检查</dt><dd>{item.nextCheck ?? "—"}</dd></div><div><dt>复发间隔</dt><dd>{item.recurrenceIntervalDays ? `${item.recurrenceIntervalDays} 天` : "—"}</dd></div><div><dt>重置阈值</dt><dd>{item.resetThreshold}</dd></div><div><dt>Updated</dt><dd>{new Date(item.updatedAt).toLocaleString()}</dd></div></dl><div className="long-term-actions"><button className="button primary" onClick={() => setEditing(true)}><Icon name="edit" />Edit</button><button className="text-button danger" disabled={busy} onClick={() => void remove()}><Icon name="trash" />Delete</button></div></>}
  </div>;
}
