"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { FormSheet } from "@/components/form-sheet";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import type { CatFoodPurchase, CatFoodSummary } from "@/lib/types";
import { CatFoodItemEditor, CatFoodPurchaseEditor } from "../cat-food-editors";

const categoryLabels = { dry: "干粮", wet: "湿粮", treat: "零食", supplement: "营养补充", other: "其他" };
const units = { kg: "kg", L: "L", piece: "个" };
const money = (value: number) => `¥${(value / 100).toFixed(2)}`;
const amount = (value: number) => Number.isInteger(value) ? String(value) : value.toFixed(1);

export function CatFoodDetailView({ initialItem }: { initialItem: CatFoodSummary }) {
  const router = useRouter(), [item, setItem] = useState(initialItem), [panel, setPanel] = useState<"item" | "purchase" | "restock" | null>(null), [editingPurchase, setEditingPurchase] = useState<CatFoodPurchase>(), [busy, setBusy] = useState(false), [notice, setNotice] = useState(""), [error, setError] = useState("");
  const suggestion = item.cadenceSuggestion, activeReminder = Boolean(item.restockReminderId);
  const [restock, setRestock] = useState({ enabled: activeReminder, intervalDays: String(item.restockIntervalDays ?? suggestion?.intervalDays ?? 30), leadDays: String(item.restockLeadDays ?? 5), reminderTime: item.restockReminderTime ?? "10:00" });
  async function load() { const response = await fetch(`/api/cats/food/${item.id}`); if (response.ok) setItem(await response.json()); }
  async function consume() { setBusy(true); setError(""); const response = await fetch(`/api/cats/food/${item.id}/consume`, { method: "POST" }); const body = await response.json(); setBusy(false); if (!response.ok) { setError(body.error); return; } setItem(body); setNotice("已用完 1 包，库存已更新"); }
  async function removePurchase(purchase: CatFoodPurchase) { if (!confirm(`删除 ${purchase.purchasedOn} 的购买记录？`)) return; const response = await fetch(`/api/cats/food/purchases/${purchase.id}`, { method: "DELETE" }); if (response.ok) { await load(); setNotice("购买记录已删除"); } }
  async function saveRestock(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); const response = await fetch(`/api/cats/food/${item.id}/restock`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(restock) }); const body = await response.json(); setBusy(false); if (!response.ok) { setError(body.error); return; } setItem(body); setPanel(null); setNotice(restock.enabled ? "补货提醒已开启" : "补货提醒已关闭"); }
  async function archive() { if (!confirm(`从食品库移除“${item.name}”？购买记录会保留。`)) return; const response = await fetch(`/api/cats/food/${item.id}`, { method: "DELETE" }); if (response.ok) router.push("/cats/food"); }
  function editPurchase(value?: CatFoodPurchase) { setEditingPurchase(value); setPanel("purchase"); }
  return <div className="page cat-food-detail-page"><Link className="back-link" href="/cats/food">← 食品库</Link><PageHeader eyebrow={`CATS · ${categoryLabels[item.category]}`} title={item.name} description={[item.brand, item.flavor].filter(Boolean).join(" · ") || "猫咪食品"} action={<span className="cat-food-header-actions"><button className="button secondary" onClick={() => setPanel("item")}><Icon name="edit"/>编辑</button><button className="button primary" onClick={() => editPurchase()}><Icon name="plus"/>记录购买</button></span>}/>
    {notice && <p className="success-banner" role="status">{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}
    <section className={`cat-food-stock-hero ${item.stockState}`}><div><span className="eyebrow">LIGHT INVENTORY</span><h2>{item.stockPackages ? `家里还有 ${item.stockPackages} 包` : "库存已经用完"}</h2><p>{item.stockPackages ? "用完一包时点一下，就足以帮助判断真实补货频率。" : "下次买到后记录购买，库存会自动补上。"}</p></div><button className="button secondary" disabled={busy || item.stockPackages === 0} onClick={() => void consume()}><Icon name="check"/>用完 1 包</button><div className="cat-food-stock-breakdown">{Object.entries(item.stockByUnit).filter(([, value]) => value).map(([unit, value]) => <span key={unit}><strong>{amount(value!)}</strong><small>{unit === "piece" ? "个" : unit} 剩余总量</small></span>)}</div></section>
    <div className="cat-food-detail-grid"><section className="cat-food-insight-card"><div className="section-heading"><div><span className="eyebrow">PRICE</span><h2>价格印象</h2></div></div>{item.latestPurchase ? <><div className="cat-food-price-focus"><span><small>最近单价</small><strong>{money(item.latestPurchase.normalizedPriceMinor)} <i>/ {units[item.latestPurchase.normalizedUnit]}</i></strong></span>{item.latestPurchase.changePercent !== null && <b className={item.latestPurchase.changePercent > 0 ? "price-up" : "price-down"}>{item.latestPurchase.changePercent > 0 ? "+" : ""}{item.latestPurchase.changePercent}%</b>}</div><p>历史好价 {money(item.bestPriceMinor!)} / {units[item.latestPurchase.normalizedUnit]}。按统一规格换算，买不同包装也能直接比较。</p></> : <p className="cat-food-muted">记录第一次购买后，这里会显示最近单价和历史好价。</p>}</section>
      <section className="cat-food-insight-card"><div className="section-heading"><div><span className="eyebrow">RHYTHM</span><h2>补货节奏</h2></div><button className="text-button" onClick={() => setPanel("restock")}>{activeReminder ? "调整" : "设置"}</button></div>{suggestion ? <><div className="cat-food-rhythm"><strong>约 {suggestion.intervalDays} 天</strong><span>购买间隔已经比较稳定</span></div><p>{activeReminder ? `已在预计补货前 ${item.restockLeadDays} 天提醒。` : "可以按这个节奏开启补货提醒，时间仍由你决定。"}</p>{!activeReminder && <button className="button secondary compact" onClick={() => setPanel("restock")}><Icon name="notifications"/>采用这个周期</button>}</> : <><div className="cat-food-rhythm pending"><strong>{Math.min(item.purchases.length, 4)} / 4</strong><span>次不同日期的购买记录</span></div><p>至少积累 4 次且间隔较稳定后，才会建议周期，避免过早猜测。</p></>}</section></div>
    <section className="cat-food-history"><div className="section-heading"><div><span className="eyebrow">PURCHASES</span><h2>购买记录</h2></div><button className="text-button" onClick={() => editPurchase()}><Icon name="plus"/>新增</button></div>{item.purchases.length ? <div className="cat-food-purchase-list">{item.purchases.map(purchase => <article key={purchase.id} className={purchase.isBestPrice ? "best" : ""}><div className="cat-food-purchase-date"><time>{purchase.purchasedOn}</time><span>{purchase.merchant || "未记录渠道"}</span></div><div className="cat-food-purchase-spec"><strong>{purchase.packageCount} 包 × {amount(purchase.amountPerPackage)} {purchase.amountUnit === "piece" ? "个" : purchase.amountUnit}</strong><small>当前剩余 {purchase.remainingPackageCount} 包</small></div><div className="cat-food-purchase-price"><strong>{money(purchase.paidAmountMinor)}</strong><small>{money(purchase.normalizedPriceMinor)} / {units[purchase.normalizedUnit]}{purchase.isBestPrice ? " · 历史好价" : ""}</small></div><div className="cat-record-actions"><button onClick={() => editPurchase(purchase)}><Icon name="edit"/>编辑</button><button className="danger" onClick={() => void removePurchase(purchase)}><Icon name="trash"/>删除</button></div></article>)}</div> : <div className="cat-food-empty compact"><h2>还没有购买记录</h2><p>记下日期、包装和实付金额，就能开始比价。</p><button className="button primary" onClick={() => editPurchase()}><Icon name="plus"/>记录第一次购买</button></div>}</section>
    <button className="danger-text cat-food-archive" onClick={() => void archive()}>从食品库移除</button>
    {panel === "item" && <FormSheet title="编辑食品" onClose={() => setPanel(null)} formId="cat-food-edit-form" submitLabel="保存修改" busy={busy}><CatFoodItemEditor item={item} formId="cat-food-edit-form" onSavingChange={setBusy} onSaved={async () => { await load(); setPanel(null); setNotice("食品资料已更新"); }}/></FormSheet>}
    {panel === "purchase" && <FormSheet title={editingPurchase ? "编辑购买" : "记录购买"} onClose={() => { setPanel(null); setEditingPurchase(undefined); }} formId="cat-food-detail-purchase-form" submitLabel={editingPurchase ? "保存修改" : "保存购买"} busy={busy}><CatFoodPurchaseEditor itemId={item.id} purchase={editingPurchase} formId="cat-food-detail-purchase-form" onSavingChange={setBusy} onSaved={async () => { await load(); setPanel(null); setEditingPurchase(undefined); setNotice(editingPurchase ? "购买记录已更新" : "购买与库存已更新"); }}/></FormSheet>}
    {panel === "restock" && <FormSheet title="补货提醒" onClose={() => setPanel(null)} formId="cat-food-restock-form" submitLabel="保存设置" busy={busy}><form id="cat-food-restock-form" className="editor-card compact-editor" onSubmit={saveRestock}><label className="field checkbox-field"><input type="checkbox" checked={restock.enabled} onChange={event => setRestock({ ...restock, enabled: event.target.checked })}/><span>开启补货提醒</span></label><div className="form-grid"><label className="field"><span>购买周期</span><span className="field-with-suffix"><input required min="1" type="number" value={restock.intervalDays} onChange={event => setRestock({ ...restock, intervalDays: event.target.value })}/><i>天</i></span></label><label className="field"><span>提前提醒</span><span className="field-with-suffix"><input required min="0" type="number" value={restock.leadDays} onChange={event => setRestock({ ...restock, leadDays: event.target.value })}/><i>天</i></span></label><label className="field"><span>提醒时间</span><input disabled={!restock.enabled} required={restock.enabled} type="time" value={restock.reminderTime} onChange={event => setRestock({ ...restock, reminderTime: event.target.value })}/></label></div><p className="field-note">每次记录新购买后，下次提醒日期会自动按这个周期顺延。</p>{error && <p className="form-error">{error}</p>}</form></FormSheet>}
  </div>;
}
