"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import { luciusCaseErrorTypeOptions, luciusCaseSeverityOptions, luciusCaseStatusOptions, optionLabel } from "@/lib/long-term-memory";
import type { ApiError, LuciusCase, LuciusCaseErrorType, LuciusCaseSeverity } from "@/lib/types";
import { CaseEditor, casePayload, emptyCaseDraft, type LuciusCaseDraft } from "./case-editor";

async function responseError(response: Response, fallback: string) { const result = await response.json().catch(() => null) as ApiError | null; return result?.error || fallback; }
export function CasesView({ initial }: { initial: LuciusCase[] }) {
  const router = useRouter(); const [items, setItems] = useState(initial); const [view, setView] = useState<"current" | "all">("current"); const [query, setQuery] = useState(""); const [errorType, setErrorType] = useState<"" | LuciusCaseErrorType>(""); const [severity, setSeverity] = useState<"" | LuciusCaseSeverity>(""); const [showForm, setShowForm] = useState(false); const [draft, setDraft] = useState<LuciusCaseDraft>(emptyCaseDraft); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const params = new URLSearchParams({ view, limit: "100" }); if (query.trim()) params.set("q", query.trim()); if (errorType) params.set("errorType", errorType); if (severity) params.set("severity", severity); try { const response = await fetch(`/api/lucius/cases?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error(await responseError(response, "Could not load Cases.")); setItems(await response.json() as LuciusCase[]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load Cases."); } finally { setLoading(false); } }, [errorType, query, severity, view]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 180); return () => window.clearTimeout(timer); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/lucius/cases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(casePayload(draft)) }); if (!response.ok) throw new Error(await responseError(response, "Could not create Case.")); const created = await response.json() as LuciusCase; router.push(`/lucius/cases/${created.id}`); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create Case."); } finally { setSaving(false); } }
  return <div className="page cases-page"><Link className="back-link" href="/lucius">← Lucius</Link><PageHeader eyebrow="LUCIUS" title="Cases" description="错误、复发与必须遵守的纠正规则。" action={<button className="button primary" onClick={() => { setDraft(emptyCaseDraft()); setShowForm(true); }}><Icon name="plus" />New case</button>} />
    {showForm && <form className="editor-card long-term-editor case-editor" onSubmit={submit}><div className="editor-title"><div><span className="eyebrow">NEW CASE</span><h2>建立案底</h2></div><button type="button" className="text-button" onClick={() => setShowForm(false)}>Cancel</button></div><CaseEditor draft={draft} setDraft={setDraft} />{error && <p className="form-error">{error}</p>}<div className="form-actions"><button className="button primary" disabled={saving}>{saving ? "Saving…" : "Save case"}</button></div></form>}
    {!showForm && error && <p className="form-error">{error}</p>}<div className="case-view-tabs"><button className={view === "current" ? "active" : ""} onClick={() => setView("current")}>当前服刑 / 观察</button><button className={view === "all" ? "active" : ""} onClick={() => setView("all")}>全部案底</button></div>
    <div className="long-term-toolbar case-toolbar" aria-busy={loading}><label className="search-box"><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cases…" /></label><select value={errorType} onChange={(event) => setErrorType(event.target.value as "" | LuciusCaseErrorType)}><option value="">All errors</option>{luciusCaseErrorTypeOptions.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select><select value={severity} onChange={(event) => setSeverity(event.target.value as "" | LuciusCaseSeverity)}><option value="">All severity</option>{luciusCaseSeverityOptions.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select><span className="result-count">{items.length}</span></div>
    {items.length ? <div className="case-list" aria-busy={loading}>{items.map((item) => <Link href={`/lucius/cases/${item.id}`} key={item.id}><span className="case-title"><strong>{item.title}</strong><small>{optionLabel(luciusCaseErrorTypeOptions, item.errorType)}</small></span><span className={`case-severity ${item.severity}`}>{optionLabel(luciusCaseSeverityOptions, item.severity)}</span><span className="case-status">{optionLabel(luciusCaseStatusOptions, item.status)}</span><span className="case-count"><strong>{item.occurrenceCount}</strong><small>累计</small></span><time dateTime={item.latestOccurredDate}>{item.latestOccurredDate}</time><Icon name="arrow" /></Link>)}</div> : <div className="empty-state"><span className="empty-icon"><Icon name="history" /></span><h2>No cases in this view</h2><p>Switch views, adjust filters, or create a case.</p></div>}
  </div>;
}
