"use client";

import { currentLocalDate } from "@/components/date-time-field";
import { luciusCaseErrorTypeOptions, luciusCaseSeverityOptions, luciusCaseStatusOptions, parseTagInput } from "@/lib/long-term-memory";
import type { LuciusCase, LuciusCaseErrorType, LuciusCaseSeverity, LuciusCaseStatus } from "@/lib/types";

export type LuciusCaseDraft = { title: string; errorType: LuciusCaseErrorType; severity: LuciusCaseSeverity; status: LuciusCaseStatus; triggerScenes: string; errorQuote: string; cause: string; correctBehavior: string; mandatoryRule: string; nextCheck: string; punishment: string; firstOccurredDate: string; latestOccurredDate: string; occurrenceCount: string; consecutiveCorrectCount: string; recurrenceIntervalDays: string; isRecurrence: boolean; resetThreshold: string };
export function emptyCaseDraft(): LuciusCaseDraft { const date = currentLocalDate(); return { title: "", errorType: "other", severity: "moderate", status: "serving", triggerScenes: "", errorQuote: "", cause: "", correctBehavior: "", mandatoryRule: "", nextCheck: "", punishment: "", firstOccurredDate: date, latestOccurredDate: date, occurrenceCount: "1", consecutiveCorrectCount: "0", recurrenceIntervalDays: "", isRecurrence: false, resetThreshold: "3" }; }
export function caseDraftFromItem(item: LuciusCase): LuciusCaseDraft { return { title: item.title, errorType: item.errorType, severity: item.severity, status: item.status, triggerScenes: item.triggerScenes.join(", "), errorQuote: item.errorQuote, cause: item.cause, correctBehavior: item.correctBehavior, mandatoryRule: item.mandatoryRule, nextCheck: item.nextCheck ?? "", punishment: item.punishment, firstOccurredDate: item.firstOccurredDate, latestOccurredDate: item.latestOccurredDate, occurrenceCount: String(item.occurrenceCount), consecutiveCorrectCount: String(item.consecutiveCorrectCount), recurrenceIntervalDays: item.recurrenceIntervalDays?.toString() ?? "", isRecurrence: item.isRecurrence, resetThreshold: String(item.resetThreshold) }; }
export function casePayload(draft: LuciusCaseDraft) { return { ...draft, triggerScenes: parseTagInput(draft.triggerScenes), nextCheck: draft.nextCheck || null, occurrenceCount: Number(draft.occurrenceCount), consecutiveCorrectCount: Number(draft.consecutiveCorrectCount), recurrenceIntervalDays: draft.recurrenceIntervalDays ? Number(draft.recurrenceIntervalDays) : null, resetThreshold: Number(draft.resetThreshold) }; }

export function CaseEditor({ draft, setDraft }: { draft: LuciusCaseDraft; setDraft: (value: LuciusCaseDraft) => void }) {
  return <div className="form-grid case-form-grid">
    <label className="field wide"><span>案底名称</span><input autoFocus required maxLength={300} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label>
    <label className="field"><span>错误类型</span><select value={draft.errorType} onChange={(event) => setDraft({ ...draft, errorType: event.target.value as LuciusCaseErrorType })}>{luciusCaseErrorTypeOptions.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label>
    <label className="field"><span>严重程度</span><select value={draft.severity} onChange={(event) => setDraft({ ...draft, severity: event.target.value as LuciusCaseSeverity })}>{luciusCaseSeverityOptions.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label>
    <label className="field"><span>状态</span><select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as LuciusCaseStatus })}>{luciusCaseStatusOptions.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label>
    <label className="field"><span>触发场景 <small>逗号分隔</small></span><input value={draft.triggerScenes} onChange={(event) => setDraft({ ...draft, triggerScenes: event.target.value })} /></label>
    <label className="field"><span>首次发生</span><input required type="date" value={draft.firstOccurredDate} onChange={(event) => setDraft({ ...draft, firstOccurredDate: event.target.value, latestOccurredDate: draft.latestOccurredDate === draft.firstOccurredDate ? event.target.value : draft.latestOccurredDate })} /></label>
    <label className="field"><span>最近发生</span><input required type="date" value={draft.latestOccurredDate} onChange={(event) => setDraft({ ...draft, latestOccurredDate: event.target.value })} /></label>
    <label className="field"><span>累计次数</span><input required type="number" min="1" value={draft.occurrenceCount} onChange={(event) => setDraft({ ...draft, occurrenceCount: event.target.value })} /></label>
    <label className="field"><span>连续正确次数</span><input required type="number" min="0" value={draft.consecutiveCorrectCount} onChange={(event) => setDraft({ ...draft, consecutiveCorrectCount: event.target.value })} /></label>
    <label className="field"><span>复发间隔天数 <small>Optional</small></span><input type="number" min="1" value={draft.recurrenceIntervalDays} onChange={(event) => setDraft({ ...draft, recurrenceIntervalDays: event.target.value })} /></label>
    <label className="field"><span>重置阈值</span><input required type="number" min="1" value={draft.resetThreshold} onChange={(event) => setDraft({ ...draft, resetThreshold: event.target.value })} /></label>
    <label className="field"><span>下次检查 <small>Optional</small></span><input type="date" value={draft.nextCheck} onChange={(event) => setDraft({ ...draft, nextCheck: event.target.value })} /></label>
    <label className="field checkbox-field"><input type="checkbox" checked={draft.isRecurrence} onChange={(event) => setDraft({ ...draft, isRecurrence: event.target.checked })} /><span>这是一次复发</span></label>
    <label className="field wide"><span>错误原话 <small>Optional</small></span><textarea rows={3} maxLength={10000} value={draft.errorQuote} onChange={(event) => setDraft({ ...draft, errorQuote: event.target.value })} /></label>
    <label className="field wide"><span>原因</span><textarea required rows={4} maxLength={20000} value={draft.cause} onChange={(event) => setDraft({ ...draft, cause: event.target.value })} /></label>
    <label className="field wide"><span>正确行为</span><textarea required rows={4} maxLength={20000} value={draft.correctBehavior} onChange={(event) => setDraft({ ...draft, correctBehavior: event.target.value })} /></label>
    <label className="field wide"><span>强制规则</span><textarea required rows={4} maxLength={20000} value={draft.mandatoryRule} onChange={(event) => setDraft({ ...draft, mandatoryRule: event.target.value })} /></label>
    <label className="field wide"><span>惩罚 <small>Optional</small></span><textarea rows={3} maxLength={10000} value={draft.punishment} onChange={(event) => setDraft({ ...draft, punishment: event.target.value })} /></label>
  </div>;
}
