"use client";
import Link from"next/link";import{FormEvent,useCallback,useEffect,useState}from"react";import{PageHeader}from"@/components/page-header";import{Icon}from"@/components/icons";import type{ApiError,DailyNutritionSummary,EstimateConfidence,FoodLog,MealType}from"@/lib/types";
const meals:{value:MealType;label:string}[]=[{value:"breakfast",label:"早餐"},{value:"lunch",label:"午餐"},{value:"dinner",label:"晚餐"},{value:"snack",label:"加餐"},{value:"late_night",label:"夜宵"}];
const empty={title:"",description:"",mealType:"lunch"as MealType,estimatedKcal:"",kcalMin:"",kcalMax:"",confidence:"medium"as EstimateConfidence,portion:"",notes:""};
export function FoodView(){const today=new Date().toLocaleDateString("en-CA");const[date,setDate]=useState(today),[mealFilter,setMealFilter]=useState(""),[query,setQuery]=useState(""),[logs,setLogs]=useState<FoodLog[]>([]),[summary,setSummary]=useState<DailyNutritionSummary|null>(null),[draft,setDraft]=useState(empty),[editing,setEditing]=useState<number|null>(null),[showForm,setShowForm]=useState(false),[error,setError]=useState("");
const load=useCallback(async()=>{const p=new URLSearchParams({date});if(mealFilter)p.set("mealType",mealFilter);if(query)p.set("q",query);const[a,b]=await Promise.all([fetch(`/api/food/logs?${p}`),fetch(`/api/nutrition/daily?date=${date}`)]);if(a.ok)setLogs(await a.json());if(b.ok)setSummary(await b.json());},[date,mealFilter,query]);useEffect(()=>{const t=setTimeout(()=>void load(),120);return()=>clearTimeout(t)},[load]);
function edit(item:FoodLog){setEditing(item.id);setDraft({title:item.title,description:item.description,mealType:item.mealType,estimatedKcal:item.estimatedKcal?.toString()||"",kcalMin:item.kcalMin?.toString()||"",kcalMax:item.kcalMax?.toString()||"",confidence:item.confidence,portion:item.portion,notes:item.notes});setShowForm(true);scrollTo({top:0,behavior:"smooth"});}
async function submit(e:FormEvent){e.preventDefault();const body={...draft,occurredAt:`${date}T12:00:00+08:00`,scene:"other",estimatedKcal:draft.estimatedKcal?Number(draft.estimatedKcal):null,kcalMin:draft.kcalMin?Number(draft.kcalMin):null,kcalMax:draft.kcalMax?Number(draft.kcalMax):null,imageUrl:null,attachmentId:null};const r=await fetch(editing?`/api/food/logs/${editing}`:"/api/food/logs",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json())as ApiError).error);return;}setDraft(empty);setEditing(null);setShowForm(false);await load();}
async function remove(id:number){if(!confirm("删掉这条饮食记录？"))return;await fetch(`/api/food/logs/${id}`,{method:"DELETE"});await load();}
return <div className="page"><PageHeader eyebrow="LIFE" title="Food" description="主要还是直接告诉 Eva；这里用来看、改和补漏。" action={<button className="button primary" onClick={()=>{setEditing(null);setDraft(empty);setShowForm(true)}}><Icon name="plus"/>补一条</button>}/>
<div className="food-summary"><div><span>摄入估算</span><strong>{summary?summary.intakeMin!==summary.intakeMax?`约 ${summary.intakeMin}–${summary.intakeMax} kcal`:`约 ${summary.estimatedIntakeKcal} kcal`:"—"}</strong><small>可信度：{summary?.confidence==="high"?"高":summary?.confidence==="medium"?"中":"低"}</small></div><div className="summary-links"><Link href="/drinks">今天喝了什么 <Icon name="arrow"/></Link><Link href="/food/library">Food Library <Icon name="arrow"/></Link></div></div>
{showForm&&<form className="editor-card compact-editor" onSubmit={submit}><div className="editor-title"><h2>{editing?"改饮食记录":"补一条饮食"}</h2><button type="button" className="text-button" onClick={()=>setShowForm(false)}>先不写</button></div><div className="form-grid"><label className="field"><span>餐次</span><select value={draft.mealType} onChange={e=>setDraft({...draft,mealType:e.target.value as MealType})}>{meals.map(m=><option value={m.value} key={m.value}>{m.label}</option>)}</select></label><label className="field"><span>吃了什么</span><input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field wide"><span>明细</span><textarea rows={3} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field"><span>热量估算</span><input type="number" value={draft.estimatedKcal} onChange={e=>setDraft({...draft,estimatedKcal:e.target.value})}/></label><label className="field"><span>范围 kcal</span><div className="range-pair"><input type="number" placeholder="最低" value={draft.kcalMin} onChange={e=>setDraft({...draft,kcalMin:e.target.value})}/><input type="number" placeholder="最高" value={draft.kcalMax} onChange={e=>setDraft({...draft,kcalMax:e.target.value})}/></div></label></div>{error&&<p className="form-error">{error}</p>}<button className="button primary">{editing?"改好了":"记下"}</button></form>}
<div className="food-toolbar"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><label className="search-box"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="找吃过的…"/></label></div><div className="chip-row"><button className={!mealFilter?"active":""} onClick={()=>setMealFilter("")}>全部</button>{meals.map(m=><button className={mealFilter===m.value?"active":""} onClick={()=>setMealFilter(m.value)} key={m.value}>{m.label}</button>)}</div>
{logs.length?<div className="food-log-list">{logs.map(log=><article className="food-log-card" key={log.id}><div><span>{meals.find(m=>m.value===log.mealType)?.label} · {new Date(log.occurredAt).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}</span><h2>{log.title}</h2>{log.description&&<p>{log.description}</p>}<small>{log.kcalMin!==null&&log.kcalMax!==null?`${log.kcalMin}–${log.kcalMax} kcal`:log.estimatedKcal!==null?`约 ${log.estimatedKcal} kcal`:"未估算热量"} · 可信度{log.confidence==="high"?"高":log.confidence==="medium"?"中":"低"}</small></div><div className="row-actions"><button onClick={()=>edit(log)}><Icon name="edit"/></button><button className="danger" onClick={()=>remove(log.id)}><Icon name="trash"/></button></div></article>)}</div>:<div className="empty-state"><h2>这天还没记</h2><p>直接去“想想”里告诉 Eva 就行。</p><Link className="button secondary" href="/ai?prompt=我刚刚吃了">告诉 Eva</Link></div>}</div>}
