"use client";

import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { FormSheet } from "@/components/form-sheet";
import { PageHeader } from "@/components/page-header";
import { Icon } from "@/components/icons";
import { TASTE_RATINGS } from "@/lib/types";
import type { ApiError,DailyNutritionSummary,EstimateConfidence,FoodLog,FoodScene,MealType,TasteRating } from "@/lib/types";

const meals:{value:MealType;label:string}[]=[{value:"breakfast",label:"早餐"},{value:"lunch",label:"午餐"},{value:"dinner",label:"晚餐"},{value:"snack",label:"加餐"},{value:"late_night",label:"夜宵"}];
const scenes:{value:FoodScene;label:string}[]=[{value:"home",label:"自制"},{value:"delivery",label:"外卖"},{value:"restaurant",label:"外食"},{value:"packaged_food",label:"包装食品"},{value:"other",label:"其他"}];
const tasteLabels:Record<TasteRating,string>={love:"好吃",good:"还行",neutral:"一般",dislike:"难吃"};
type Draft={title:string;description:string;mealType:MealType;scene:FoodScene;rating:TasteRating|"";estimatedKcal:string;kcalMin:string;kcalMax:string;confidence:EstimateConfidence;portion:string;notes:string};
const empty:Draft={title:"",description:"",mealType:"lunch",scene:"other",rating:"",estimatedKcal:"",kcalMin:"",kcalMax:"",confidence:"medium",portion:"",notes:""};
function canRate(scene:FoodScene){return scene==="delivery"||scene==="restaurant";}
function shiftDate(date:string,days:number){const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10);}

export function FoodView(){
  const today=new Date().toLocaleDateString("en-CA");const[date,setDate]=useState(today);const[mealFilter,setMealFilter]=useState("");const[query,setQuery]=useState("");const[logs,setLogs]=useState<FoodLog[]>([]);const[summary,setSummary]=useState<DailyNutritionSummary|null>(null);const[draft,setDraft]=useState(empty);const[editing,setEditing]=useState<number|null>(null);const[showForm,setShowForm]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
  const load=useCallback(async()=>{const params=new URLSearchParams({date});if(mealFilter)params.set("mealType",mealFilter);if(query)params.set("q",query);const[recordsResponse,summaryResponse]=await Promise.all([fetch(`/api/food/logs?${params}`),fetch(`/api/nutrition/daily?date=${date}`)]);if(recordsResponse.ok)setLogs(await recordsResponse.json());if(summaryResponse.ok)setSummary(await summaryResponse.json());},[date,mealFilter,query]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),120);return()=>clearTimeout(timer);},[load]);
  function edit(item:FoodLog){setEditing(item.id);setDraft({title:item.title,description:item.description,mealType:item.mealType,scene:item.scene,rating:item.rating??"",estimatedKcal:item.estimatedKcal?.toString()||"",kcalMin:item.kcalMin?.toString()||"",kcalMax:item.kcalMax?.toString()||"",confidence:item.confidence,portion:item.portion,notes:item.notes});setShowForm(true);}
  async function submit(event:FormEvent){event.preventDefault();if(saving)return;setSaving(true);setError("");try{const body={...draft,rating:canRate(draft.scene)&&draft.rating?draft.rating:null,occurredAt:`${date}T12:00:00+08:00`,estimatedKcal:draft.estimatedKcal?Number(draft.estimatedKcal):null,kcalMin:draft.kcalMin?Number(draft.kcalMin):null,kcalMax:draft.kcalMax?Number(draft.kcalMax):null,imageUrl:null,attachmentId:null};const response=await fetch(editing?`/api/food/logs/${editing}`:"/api/food/logs",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){setError(((await response.json())as ApiError).error);return;}setDraft(empty);setEditing(null);setShowForm(false);await load();}finally{setSaving(false);}}
  async function remove(id:number){if(!confirm("删掉这条饮食记录？"))return;setSaving(true);setError("");try{const response=await fetch(`/api/food/logs/${id}`,{method:"DELETE"});if(!response.ok){setError("无法删除这条饮食记录");return;}setShowForm(false);setEditing(null);setDraft(empty);await load();}finally{setSaving(false);}}
  return <div className="page food-page"><PageHeader eyebrow="LIFE" title="Food" description="记录和回看每天的饮食与场景。" action={<button className="button primary" onClick={()=>{setEditing(null);setDraft(empty);setShowForm(true);}}><Icon name="plus"/>补一条</button>}/>
    <div className="food-summary"><div><span>摄入估算</span><strong>{summary?summary.intakeMin!==summary.intakeMax?`约 ${summary.intakeMin}–${summary.intakeMax} kcal`:`约 ${summary.estimatedIntakeKcal} kcal`:"—"}</strong><small>可信度：{summary?.confidence==="high"?"高":summary?.confidence==="medium"?"中":"低"}</small></div><div className="summary-links"><Link href="/drinks">今日饮品 <Icon name="arrow"/></Link><Link href="/food/library">Food Library <Icon name="arrow"/></Link></div></div>
    {showForm&&<FormSheet title={editing?"改饮食记录":"补一条饮食"} onClose={()=>setShowForm(false)} formId="food-record-form" submitLabel={editing?"改好了":"记下"} busy={saving} busyLabel={editing?"正在修改…":"正在保存…"}><form id="food-record-form" className="editor-card compact-editor" onSubmit={submit}><div className="form-grid">
      <label className="field"><span>餐次</span><select value={draft.mealType} onChange={event=>setDraft({...draft,mealType:event.target.value as MealType})}>{meals.map(meal=><option value={meal.value} key={meal.value}>{meal.label}</option>)}</select></label>
      <label className="field"><span>场景</span><select value={draft.scene} onChange={event=>{const scene=event.target.value as FoodScene;setDraft({...draft,scene,rating:canRate(scene)?draft.rating:""});}}>{scenes.map(scene=><option value={scene.value} key={scene.value}>{scene.label}</option>)}</select></label>
      <label className="field"><span>吃了什么</span><input required value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label>
      {canRate(draft.scene)&&<label className="field"><span>评价</span><select value={draft.rating} onChange={event=>setDraft({...draft,rating:event.target.value as TasteRating|""})}><option value="">未评价</option>{TASTE_RATINGS.map(value=><option value={value} key={value}>{tasteLabels[value]}</option>)}</select></label>}
      <label className="field wide"><span>明细</span><textarea rows={3} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label>
      <label className="field"><span>热量估算</span><input type="number" value={draft.estimatedKcal} onChange={event=>setDraft({...draft,estimatedKcal:event.target.value})}/></label>
      <label className="field"><span>范围 kcal</span><div className="range-pair"><input type="number" placeholder="最低" value={draft.kcalMin} onChange={event=>setDraft({...draft,kcalMin:event.target.value})}/><input type="number" placeholder="最高" value={draft.kcalMax} onChange={event=>setDraft({...draft,kcalMax:event.target.value})}/></div></label>
    </div>{error&&<p className="form-error">{error}</p>}{editing&&<button className="danger-text food-record-delete" type="button" onClick={()=>void remove(editing)}>删除这条饮食记录</button>}</form></FormSheet>}
    <div className="food-toolbar"><div className="food-date-nav"><button type="button" aria-label="前一天" onClick={()=>setDate(shiftDate(date,-1))}>‹</button><input aria-label="选择日期" type="date" value={date} onChange={event=>setDate(event.target.value)}/><button type="button" aria-label="后一天" onClick={()=>setDate(shiftDate(date,1))}>›</button></div><label className="search-box food-search-box"><Icon name="search"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="找吃过的…"/></label></div><div className="chip-row food-meal-filters"><button className={!mealFilter?"active":""} onClick={()=>setMealFilter("")}>全部</button>{meals.map(meal=><button className={mealFilter===meal.value?"active":""} onClick={()=>setMealFilter(meal.value)} key={meal.value}>{meal.label}</button>)}</div>
    {logs.length?<div className="food-log-list">{logs.map(log=><article className="food-log-card" key={log.id}><div><span>{meals.find(meal=>meal.value===log.mealType)?.label} · {scenes.find(scene=>scene.value===log.scene)?.label} · {new Date(log.occurredAt).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}</span><h2>{log.title}</h2>{log.description&&<p>{log.description}</p>}<small>{[log.rating?tasteLabels[log.rating]:"",log.kcalMin!==null&&log.kcalMax!==null?`${log.kcalMin}–${log.kcalMax} kcal`:log.estimatedKcal!==null?`约 ${log.estimatedKcal} kcal`:"未估算热量",`可信度${log.confidence==="high"?"高":log.confidence==="medium"?"中":"低"}`].filter(Boolean).join(" · ")}</small></div><div className="row-actions"><button aria-label={`编辑 ${log.title}`} onClick={()=>edit(log)}><Icon name="edit"/></button></div></article>)}</div>:<div className="empty-state"><h2>这天还没记</h2><p>直接去“想想”里告诉 Eva 就行。</p><Link className="button secondary" href="/ai?prompt=我刚刚吃了">告诉 Eva</Link></div>}
  </div>;
}
