"use client";

import { useState,type FormEvent } from "react";
import type { RelationPerson } from "@/lib/types";

const empty={name:"",nickname:"",relationLabel:"",closenessRank:"",relationshipStatus:"active" as const,birthday:"",likes:"",avoid:"",note:""};
export function RelationPersonEditor({editing,onSaved,onBusy}:{editing?:RelationPerson;onSaved:()=>void;onBusy:(value:boolean)=>void}){
  const[data,setData]=useState(()=>editing?{name:editing.name,nickname:editing.nickname??"",relationLabel:editing.relationLabel??"",closenessRank:editing.closenessRank?String(editing.closenessRank):"",relationshipStatus:editing.relationshipStatus,birthday:editing.birthday??"",likes:editing.likes??"",avoid:editing.avoid??"",note:editing.note??""}:empty);
  const[file,setFile]=useState<File|null>(null),[error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();onBusy(true);setError("");try{const response=await fetch(editing?`/api/relations/people/${editing.id}`:"/api/relations/people",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,closenessRank:data.closenessRank?Number(data.closenessRank):null})});if(!response.ok)throw new Error((await response.json()).error);const person=await response.json() as RelationPerson;if(file){const form=new FormData();form.set("file",file);const photo=await fetch(`/api/relations/people/${person.id}/photo`,{method:"POST",body:form});if(!photo.ok)throw new Error((await photo.json()).error);}onSaved();}catch(reason){setError(reason instanceof Error?reason.message:"Could not save person");}finally{onBusy(false);}}
  return <form className="editor-card relation-editor" onSubmit={submit}><div className="form-grid"><label className="field"><span>Name</span><input required value={data.name} onChange={event=>setData({...data,name:event.target.value})}/></label><label className="field"><span>Nickname</span><input value={data.nickname} onChange={event=>setData({...data,nickname:event.target.value})}/></label><label className="field"><span>Relationship</span><input placeholder="Friend, colleague…" value={data.relationLabel} onChange={event=>setData({...data,relationLabel:event.target.value})}/></label><label className="field"><span>Relationship status</span><select value={data.relationshipStatus} onChange={event=>setData({...data,relationshipStatus:event.target.value as "active"|"ended"})}><option value="active">Current relationship</option><option value="ended">Ended</option></select></label><label className="field"><span>Closeness</span><select value={data.closenessRank} onChange={event=>setData({...data,closenessRank:event.target.value})}><option value="">Not set</option><option value="5">Very close</option><option value="4">Close</option><option value="3">Regular</option><option value="2">Distant</option><option value="1">Very distant</option></select></label><label className="field"><span>Birthday</span><input type="date" value={data.birthday} onChange={event=>setData({...data,birthday:event.target.value})}/></label><label className="field wide"><span>Likes</span><textarea rows={2} value={data.likes} onChange={event=>setData({...data,likes:event.target.value})}/></label><label className="field wide"><span>Avoid</span><textarea rows={2} value={data.avoid} onChange={event=>setData({...data,avoid:event.target.value})}/></label><label className="field wide"><span>Photo <small>Optional · JPG, PNG or WebP</small></span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><label className="field wide"><span>Notes</span><textarea rows={3} value={data.note} onChange={event=>setData({...data,note:event.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}</form>;
}
