"use client";

import Link from "next/link";
import { type FormEvent, useState } from "react";
import type { ApiError, Project, ProjectItem, ProjectItemStatus, ProjectItemType } from "@/lib/types";

const statuses:ProjectItemStatus[]=["to_solve","doing","blocked","done","verified","dropped"];
const statusLabels:Record<ProjectItemStatus,string>={to_solve:"To Solve",doing:"Doing",blocked:"Blocked",done:"Done",verified:"Verified",dropped:"Dropped"};
const types:ProjectItemType[]=["feature","bug","ui","migration","research","tech_debt","other"];
function stamp(value:string|null){return value?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";}
export function ProjectItemDetailView({project,initial}:{project:Project;initial:ProjectItem}){const [item,setItem]=useState(initial);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [draft,setDraft]=useState({title:item.title,description:item.description??"",type:item.type,status:item.status,module:item.module??"",priority:item.priority??"",nextStep:item.nextStep??"",resolution:item.resolution??""});async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch(`/api/project-items/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,description:draft.description||null,module:draft.module||null,priority:draft.priority||null,nextStep:draft.nextStep||null,resolution:draft.resolution||null})});const result=await response.json() as ProjectItem|ApiError;if(!response.ok)throw new Error((result as ApiError).error||"Could not update issue.");setItem(result as ProjectItem);setDraft({...draft,status:(result as ProjectItem).status});}catch(reason){setError(reason instanceof Error?reason.message:"Could not update issue.");}finally{setSaving(false);}}
return <div className="page project-item-page"><Link href={`/projects/${project.id}`} className="back-link">← {project.name}</Link><div className="project-item-title"><span className="eyebrow">ITEM {item.id}</span><h1>{item.title}</h1><span className="item-status" data-status={item.status}>{statusLabels[item.status]}</span></div><form className="editor-card project-item-editor" onSubmit={submit}><div className="form-grid"><label className="field wide"><span>Title</span><input required maxLength={300} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field"><span>Status</span><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as ProjectItemStatus})}>{statuses.map(status=><option value={status} key={status}>{statusLabels[status]}</option>)}</select><small className="field-note">Done is awaiting your check. Choose Verified only after you confirm the result.</small></label><label className="field"><span>Type</span><select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as ProjectItemType})}>{types.map(type=><option value={type} key={type}>{type.replace("_"," ")}</option>)}</select></label><label className="field"><span>Module <small>Optional</small></span><input maxLength={120} value={draft.module} onChange={e=>setDraft({...draft,module:e.target.value})}/></label><label className="field"><span>Priority <small>Optional</small></span><input maxLength={60} value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}/></label><label className="field wide"><span>Original request</span><textarea rows={6} maxLength={20000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field wide"><span>Next step <small>Optional</small></span><textarea rows={3} maxLength={5000} value={draft.nextStep} onChange={e=>setDraft({...draft,nextStep:e.target.value})}/></label><label className="field wide"><span>Resolution <small>Shown in Chronicle</small></span><textarea rows={5} maxLength={10000} value={draft.resolution} onChange={e=>setDraft({...draft,resolution:e.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button className="button primary" disabled={saving}>{saving?"Saving…":"Save changes"}</button></div></form><section className="lifecycle"><span className="eyebrow">LIFECYCLE</span><dl><div><dt>Created</dt><dd>{stamp(item.createdAt)}</dd></div><div><dt>Started</dt><dd>{stamp(item.startedAt)}</dd></div><div><dt>Completed</dt><dd>{stamp(item.completedAt)}</dd></div><div><dt>Verified</dt><dd>{stamp(item.verifiedAt)}</dd></div><div><dt>Updated</dt><dd>{stamp(item.updatedAt)}</dd></div></dl></section></div>;}
