"use client";

import Link from "next/link";
import { type FormEvent, useState } from "react";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import type { ApiError, Project, ProjectStatus } from "@/lib/types";

const statusLabels:Record<ProjectStatus,string>={active:"Active",paused:"Paused",archived:"Archived"};
function updated(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value));}
export function ProjectsView({initial}:{initial:Project[]}){
  const [projects,setProjects]=useState(initial);const [show,setShow]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [draft,setDraft]=useState({name:"",description:"",status:"active" as ProjectStatus});
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,description:draft.description||null})});const result=await response.json() as Project|ApiError;if(!response.ok)throw new Error((result as ApiError).error||"Could not create project.");setProjects([result as Project,...projects]);setShow(false);setDraft({name:"",description:"",status:"active"});}catch(reason){setError(reason instanceof Error?reason.message:"Could not create project.");}finally{setSaving(false);}}
  return <div className="page projects-page"><PageHeader eyebrow="工作" title="Projects" action={<button className="button primary" onClick={()=>setShow(true)}><Icon name="plus"/>新增项目</button>}/>
    {show&&<form className="editor-card project-editor" onSubmit={submit}><div className="editor-title"><div><span className="eyebrow">NEW PROJECT</span><h2>Create a project</h2></div><button type="button" className="text-button" onClick={()=>setShow(false)}>Cancel</button></div><div className="form-grid"><label className="field"><span>Name</span><input autoFocus required maxLength={200} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field"><span>Status</span><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as ProjectStatus})}>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field wide"><span>Description <small>Optional</small></span><textarea rows={3} maxLength={5000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button className="button primary" disabled={saving}>{saving?"Saving…":"Create project"}</button></div></form>}
    {projects.length?<div className="project-list">{projects.map(project=><Link href={`/projects/${project.id}`} className="project-row" key={project.id}><div className="project-row-main"><span className="project-status-dot" data-status={project.status}/><div><strong>{project.name}</strong>{project.description&&<p>{project.description}</p>}</div></div><div className="project-counts"><span><b>{project.doingCount}</b> Doing</span><span><b>{project.toSolveCount}</b> To Solve</span></div><time dateTime={project.updatedAt}>{updated(project.updatedAt)}</time><span className="project-state">{statusLabels[project.status]}</span><Icon name="arrow"/></Link>)}</div>:<div className="empty-state"><span className="empty-icon"><Icon name="tasks"/></span><h2>No projects yet</h2><p>Create EvaOrbit, Refuel, or any personal project you want to keep moving.</p><button className="button secondary" onClick={()=>setShow(true)}><Icon name="plus"/>New project</button></div>}
  </div>;
}
