"use client";
import { SearchableSelect } from "@/components/searchable-select";
import { SuggestedInput } from "@/components/suggested-input";
import { showActionToast } from "@/components/action-toast";

import { drinkRecordName } from "@/lib/drink-display";
import Link from "next/link";
import { FoodLibraryPicker } from "../food/food-library-picker";
import { FoodLinkPicker } from "../food/food-link-picker";
import { FoodDeleteAction } from "../food/food-delete-action";
import styles from "./drink-place.module.css";
import { useEffect, useState } from "react";
import { compactDateTimePayload, compactDateTimeValue, currentLocalDate, DateTimeField } from "@/components/date-time-field";
import { FormSheet } from "@/components/form-sheet";
import { Icon } from "@/components/icons";
import { invalidateCachedJson } from "@/lib/client-json-cache";
import { DRINK_TEMPERATURES, SUGAR_LEVELS, TASTE_RATINGS } from "@/lib/types";
import type { FoodDish, FoodPlace, ApiError, DrinkInputSuggestions, DrinkLog, DrinkTemperature, DrinkType, EstimateConfidence, SugarLevel, TasteRating } from "@/lib/types";

export const drinkTypes: [DrinkType, string][] = [["coffee","咖啡"],["milk_tea","奶茶"],["tea","茶"],["soda","汽水"],["juice","果汁"],["water","水"],["alcohol","酒"],["other","其他"]];
export const temperatureLabels: Record<DrinkTemperature,string> = { normal_ice:"正常冰",less_ice:"少冰",no_ice:"去冰",room_temperature:"常温",hot:"热" };
export const tasteLabels: Record<TasteRating,string> = { love:"好喝",good:"还行",neutral:"一般",dislike:"难喝" };

type Draft = { foodLibraryId:string;drinkMenuId:string;foodPlaceId:string;occurredAt:string;name:string;brand:string;drinkType:DrinkType;volumeMl:string;caffeineMg:string;sugarLevel:SugarLevel;temperature:DrinkTemperature|"";rating:TasteRating|"";estimatedKcal:string;kcalMin:string;kcalMax:string;confidence:EstimateConfidence;notes:string };
function editableSugarLevel(value:string):SugarLevel { if(value==="五分糖")return "半糖";return value===""||SUGAR_LEVELS.some(level=>level===value)?value as SugarLevel:""; }
function emptyDraft(initialDate?:string):Draft{return{foodLibraryId:"",drinkMenuId:"",foodPlaceId:"",occurredAt:initialDate??currentLocalDate(),name:"",brand:"",drinkType:"other",volumeMl:"",caffeineMg:"",sugarLevel:"",temperature:"",rating:"",estimatedKcal:"",kcalMin:"",kcalMax:"",confidence:"medium",notes:""};}
function draftFromRecord(record?:DrinkLog,initialDate?:string):Draft{return record?{foodLibraryId:record.foodLibraryId?.toString()??"",drinkMenuId:record.drinkMenuId?.toString()??"",foodPlaceId:record.foodPlaceId?.toString()??"",occurredAt:compactDateTimeValue(record.occurredAt,record.occurredHasExplicitTime),name:record.name,brand:record.brand,drinkType:record.drinkType,volumeMl:record.volumeMl?.toString()??"",caffeineMg:record.caffeineMg?.toString()??"",sugarLevel:editableSugarLevel(record.sugarLevel),temperature:record.temperature??"",rating:record.rating??"",estimatedKcal:record.estimatedKcal?.toString()??"",kcalMin:record.kcalMin?.toString()??"",kcalMax:record.kcalMax?.toString()??"",confidence:record.confidence,notes:record.notes}:emptyDraft(initialDate);}

export function DrinkRecordEditor({record,suggestions,initialDate,onClose,onSaved,onDeleted}:{record?:DrinkLog;suggestions:DrinkInputSuggestions;initialDate?:string;onClose:()=>void;onSaved:()=>Promise<void>|void;onDeleted?:()=>Promise<void>|void}){
  const[draft,setDraft]=useState<Draft>(()=>draftFromRecord(record,initialDate));const[saving,setSaving]=useState(false);const[error,setError]=useState("");
  const [places,setPlaces]=useState<FoodPlace[]>([]);const [placeQuery,setPlaceQuery]=useState("");
  const [placeLoading, setPlaceLoading] = useState(false); const [placeError, setPlaceError] = useState(""); const [placeAttempt, setPlaceAttempt] = useState(0);
  useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setPlaceLoading(true); setPlaceError(""); void fetch(`/api/food/places?purpose=drink&limit=200&q=${encodeURIComponent(placeQuery)}`,{signal:controller.signal}).then(response=>{if(!response.ok)throw new Error("店铺加载失败，请重试");return response.json() as Promise<FoodPlace[]>;}).then(items=>setPlaces(current=>[...new Map([...current,...items].map(item=>[item.id,item])).values()])).catch(reason=>{if(reason.name!=="AbortError")setPlaceError(reason.message);}).finally(()=>{if(!controller.signal.aborted)setPlaceLoading(false);});},150);return()=>{clearTimeout(timer);controller.abort();};},[placeQuery, placeAttempt]);
  const placeOptions=[...new Map([...(record?.foodPlaceId&&record.foodPlaceName?[{id:record.foodPlaceId,name:record.foodPlaceName,detail:[record.foodPlaceCity,record.foodPlaceLocation,record.foodPlaceBranch].filter(Boolean).join(" · ")}]:[]),...places.map(place=>({id:place.id,name:place.name,detail:[place.city,place.location,place.branch].filter(Boolean).join(" · ")}))].map(place=>[place.id,place])).values()];
  const [menus,setMenus]=useState<FoodDish[]>([]);const [menuQuery,setMenuQuery]=useState("");const [menuError,setMenuError]=useState("");const [menuLoading,setMenuLoading]=useState(false);const [menuAttempt,setMenuAttempt]=useState(0);
  useEffect(()=>{if(!draft.foodPlaceId)return;const controller=new AbortController();const timer=setTimeout(()=>{setMenuLoading(true);setMenuError("");void fetch(`/api/food/places/${draft.foodPlaceId}/dishes?kind=drink&q=${encodeURIComponent(menuQuery)}`,{signal:controller.signal}).then(response=>{if(!response.ok)throw new Error("饮品菜单加载失败");return response.json() as Promise<FoodDish[]>;}).then(items=>setMenus(current=>[...new Map([...current,...items].map(item=>[item.id,item])).values()])).catch(reason=>{if(reason.name!=="AbortError")setMenuError(reason.message);}).finally(()=>{if(!controller.signal.aborted)setMenuLoading(false);});},150);return()=>{clearTimeout(timer);controller.abort();};},[draft.foodPlaceId,menuQuery,menuAttempt]);
  const menuOptions=[...new Map([...(record?.drinkMenuId&&record.drinkMenuName&&record.foodPlaceId===Number(draft.foodPlaceId)?[{id:record.drinkMenuId,name:record.drinkMenuName}]:[]),...menus.map(item=>({id:item.id,name:item.name,detail:item.category}))].map(item=>[item.id,item])).values()];
  async function submit(event:React.FormEvent){event.preventDefault();if(saving)return;setSaving(true);setError("");try{const occurred=compactDateTimePayload(draft.occurredAt);const body={...draft,drinkMenuId:draft.drinkMenuId?Number(draft.drinkMenuId):null,foodPlaceId:draft.foodPlaceId?Number(draft.foodPlaceId):null,occurredAt:occurred.value,occurredHasExplicitTime:occurred.hasExplicitTime,temperature:draft.temperature||null,rating:draft.rating||null,volumeMl:draft.volumeMl?Number(draft.volumeMl):null,caffeineMg:draft.caffeineMg?Number(draft.caffeineMg):null,estimatedKcal:draft.estimatedKcal?Number(draft.estimatedKcal):null,kcalMin:draft.kcalMin?Number(draft.kcalMin):null,kcalMax:draft.kcalMax?Number(draft.kcalMax):null,foodLibraryId:draft.foodLibraryId?Number(draft.foodLibraryId):null};const response=await fetch(record?`/api/drinks/logs/${record.id}`:"/api/drinks/logs",{method:record?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){const result=await response.json().catch(()=>null) as ApiError|null;setError(result?.error||`无法保存饮品记录（${response.status}）`);return;}invalidateCachedJson("/api/drinks/suggestions");await onSaved();onClose();}catch(reason){setError(reason instanceof Error?reason.message:"无法保存饮品记录");}finally{setSaving(false);}}
  async function remove(){if(!record||!onDeleted||saving)return;setSaving(true);setError("");try{const response=await fetch(`/api/drinks/logs/${record.id}`,{method:"DELETE"});if(!response.ok)throw new Error("无法删除饮品记录，请重试");invalidateCachedJson("/api/drinks/suggestions");await onDeleted();showActionToast("饮品记录已删除","deleted");onClose();}finally{setSaving(false);}}
  return <FormSheet title={record?"改饮品记录":"补一杯"} onClose={onClose} formId="drink-record-form" submitLabel={record?"改好了":"记下"} busy={saving} busyLabel={record?"正在修改…":"正在保存…"}><form id="drink-record-form" className="editor-card compact-editor" onSubmit={submit}>
    <DateTimeField label="日期" value={{date:draft.occurredAt.slice(0,10),time:draft.occurredAt.length>10?draft.occurredAt.slice(11,16):""}} onChange={value=>setDraft({...draft,occurredAt:value.date+(value.time?`T${value.time}`:"")})}/>
    <div className="form-grid drink-record-form-grid">
      <div className="field"><span>饮品名称（可选）</span><SuggestedInput recommendationStyle="chips" suggestionLabel="饮品" suggestions={suggestions.names} placeholder="关联菜单后使用菜单品名" maxLength={200} value={draft.name} onValueChange={nextValue =>setDraft({...draft,name:nextValue,drinkMenuId:""})}/></div>
      <div className="field"><span>品牌（可选）</span><SuggestedInput recommendationStyle="search" suggestionLabel="品牌" suggestions={suggestions.brands} maxLength={120} value={draft.brand} onValueChange={nextValue =>setDraft({...draft,brand:nextValue})} placeholder="可不填"/></div>
      <FoodLinkPicker label="店铺 / 门店（可选）" options={placeOptions} selected={draft.foodPlaceId?[Number(draft.foodPlaceId)]:[]} loading={placeLoading} error={placeError} onRetry={() => setPlaceAttempt(value => value + 1)} onSearch={setPlaceQuery} onChange={ids=>{setMenus([]);setMenuQuery("");setDraft({...draft,foodPlaceId:ids[0]?.toString()??"",drinkMenuId:""});}}/>
      {draft.foodPlaceId&&<FoodLinkPicker itemType="drink" label="饮品菜单（可选）" options={menuOptions} selected={draft.drinkMenuId?[Number(draft.drinkMenuId)]:[]} loading={menuLoading} error={menuError} onRetry={()=>setMenuAttempt(value=>value+1)} onSearch={setMenuQuery} onChange={ids=>{const item=menuOptions.find(item=>item.id===ids[0]);setDraft({...draft,drinkMenuId:ids[0]?.toString()??"",...(item?{name:item.name}:{})});}}/>}
      <FoodLibraryPicker placeId={draft.foodPlaceId} value={draft.foodLibraryId} onChange={(id,item)=>setDraft({...draft,foodLibraryId:id,...(item&&!draft.name?{name:item.name}:{})})}/>
      <div className="field"><span>类型</span><SearchableSelect label="类型" searchable={false} value={draft.drinkType} onValueChange={(value) =>setDraft({...draft,drinkType:value as DrinkType})} options={[...drinkTypes.map(([value,label])=>({value:value,label:label}))]}/></div>
      <label className="field"><span>咖啡因 mg（可选）</span><input type="number" min="0" max="5000" value={draft.caffeineMg} onChange={event=>setDraft({...draft,caffeineMg:event.target.value})}/></label>
      <label className="field"><span>容量 ml</span><input type="number" min="0" max="10000" value={draft.volumeMl} onChange={event=>setDraft({...draft,volumeMl:event.target.value})}/></label>
      <div className="field"><span>糖度</span><SearchableSelect label="糖度" searchable={false} value={draft.sugarLevel} onValueChange={(value) =>setDraft({...draft,sugarLevel:value as SugarLevel})} options={[{value:"",label:"未填写"},...SUGAR_LEVELS.map(level=>({value:level,label:level}))]}/></div>
      <div className="field"><span>冷热 / 冰量</span><SearchableSelect label="冷热 / 冰量" searchable={false} value={draft.temperature} onValueChange={(value) =>setDraft({...draft,temperature:value as DrinkTemperature|""})} options={[{value:"",label:"未填写"},...DRINK_TEMPERATURES.map(value=>({value:value,label:temperatureLabels[value]}))]}/></div>
      <div className="field"><span>评价</span><SearchableSelect label="评价" searchable={false} value={draft.rating} onValueChange={(value) =>setDraft({...draft,rating:value as TasteRating|""})} options={[{value:"",label:"未评价"},...TASTE_RATINGS.map(value=>({value:value,label:tasteLabels[value]}))]}/></div>
      <label className="field"><span>热量估算</span><input type="number" min="0" value={draft.estimatedKcal} onChange={event=>setDraft({...draft,estimatedKcal:event.target.value})}/></label>
      <label className="field wide"><span>Notes</span><textarea rows={3} maxLength={2000} value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})}/></label>
    </div>

    {error&&<p className="form-error">{error}</p>}{record&&onDeleted&&<FoodDeleteAction label="删除这条饮品记录" description={`确定删除「${drinkRecordName(record)}」？删除后无法恢复。`} onDelete={remove} disabled={saving}/>}
  </form></FormSheet>;
}

function momentLabel(log:DrinkLog,showDate:boolean){const compact=compactDateTimeValue(log.occurredAt,log.occurredHasExplicitTime);const date=compact.slice(0,10);const time=compact.length>10?compact.slice(11,16):"日期记录";return showDate?`${date} · ${time}`:time;}
export function DrinkRecordCard({log,onEdit,showDate=false}:{log:DrinkLog;onEdit:(log:DrinkLog)=>void;showDate?:boolean}){const specifications=[log.volumeMl?`${log.volumeMl} ml`:"",log.sugarLevel,log.caffeineMg!==null?`咖啡因 ${log.caffeineMg} mg`:"",log.temperature?temperatureLabels[log.temperature]:""].filter(Boolean).join(" · ");const assessment=[log.rating?tasteLabels[log.rating]:"",log.kcalMin!==null&&log.kcalMax!==null?`${log.kcalMin}–${log.kcalMax} kcal`:log.estimatedKcal!==null?`约 ${log.estimatedKcal} kcal`:"未估算热量"].filter(Boolean).join(" · ");return <article className="drink-record-card"><button className="drink-record-main" onClick={()=>onEdit(log)}><div className="drink-record-copy"><span>{drinkTypes.find(([value])=>value===log.drinkType)?.[1]} · {momentLabel(log,showDate)}</span><h2>{drinkRecordName(log)}</h2>{log.brand&&log.brand!==log.foodPlaceName&&<p className="drink-record-brand">{log.brand}</p>}<small className="drink-record-specifications">{specifications}</small><small className="drink-record-assessment">{assessment}</small></div></button><button className="drink-record-edit" aria-label={`编辑 ${drinkRecordName(log)}`} onClick={()=>onEdit(log)}><Icon name="edit"/></button>{log.foodPlaceId&&log.foodPlaceName&&<Link className={styles.link} href={`/food/places/${log.foodPlaceId}`}>{[log.foodPlaceName,log.foodPlaceCity,log.foodPlaceLocation,log.foodPlaceBranch].filter(Boolean).join(" · ")}</Link>}</article>;}
