import { NextRequest,NextResponse } from "next/server";
import { apiError } from "@/lib/api";
import { createFoodPlace,listFoodPlaces } from "@/lib/services/food";
import { parseFoodPlace, ValidationError } from "@/lib/validation";
import { placeServiceLabels,placeKindLabels,placeScopeLabels } from "@/lib/place-menu";
import { TASTE_RATINGS, type FoodPlaceStatus, type TasteRating, type FoodPlace } from "@/lib/types";
export const runtime="nodejs";
export async function GET(request:NextRequest){try{const p=request.nextUrl.searchParams;const kind=p.get("kind"),scope=p.get("scope");if(kind&&!Object.hasOwn(placeKindLabels,kind))throw new ValidationError("来源类型不正确");if(scope&&!Object.hasOwn(placeScopeLabels,scope))throw new ValidationError("地点范围不正确");const purpose=p.get("purpose");if(purpose&&purpose!=="food"&&purpose!=="drink")throw new ValidationError("店铺用途不正确");const serviceType=p.get("serviceType"),rating=p.get("rating");if(serviceType&&!Object.hasOwn(placeServiceLabels,serviceType))throw new ValidationError("店铺类型不正确");if(rating&&rating!=="unrated"&&!TASTE_RATINGS.includes(rating as TasteRating))throw new ValidationError("店铺评价不正确");return NextResponse.json(await listFoodPlaces(p.get("q")??"",{kind:(kind||undefined) as FoodPlace["kind"],scope:(scope||undefined) as FoodPlace["scope"],purpose:(purpose??undefined) as "food"|"drink"|undefined,serviceType:(serviceType||undefined) as FoodPlace["serviceType"]|undefined,city:p.get("city")||undefined,rating:(rating||undefined) as TasteRating|"unrated"|undefined,status:(p.get("status")||undefined) as FoodPlaceStatus|undefined,category:p.get("category")||undefined,limit:p.get("limit")?Number(p.get("limit")):undefined}));}catch(error){return apiError(error);}}
export async function POST(request:NextRequest){try{return NextResponse.json(await createFoodPlace(parseFoodPlace(await request.json())),{status:201});}catch(error){return apiError(error);}}
