"use client";

import type { FormEvent } from "react";
import { useState } from "react";
import type { CatFoodItem, CatFoodPurchase } from "@/lib/types";

const today = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
const blankItem = { name: "", brand: "", category: "dry", flavor: "", notes: "", lowStockThresholdPackages: "1" };

export function CatFoodItemEditor({ item, formId, onSaved, onSavingChange }: { item?: CatFoodItem; formId: string; onSaved: (item: CatFoodItem) => void; onSavingChange: (value: boolean) => void }) {
  const [draft, setDraft] = useState(item ? { name: item.name, brand: item.brand, category: item.category, flavor: item.flavor, notes: item.notes, lowStockThresholdPackages: String(item.lowStockThresholdPackages) } : blankItem);
  const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); onSavingChange(true); try { const response = await fetch(item ? `/api/cats/food/${item.id}` : "/api/cats/food", { method: item ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); onSaved(body); } catch (value) { setError(value instanceof Error ? value.message : "保存失败"); } finally { onSavingChange(false); } }
  return <form id={formId} className="editor-card compact-editor" onSubmit={submit}><div className="form-grid"><label className="field"><span>食品名称</span><input autoFocus required value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} placeholder="例如：室内成猫粮"/></label><label className="field"><span>品牌</span><input value={draft.brand} onChange={event => setDraft({ ...draft, brand: event.target.value })} placeholder="可留空"/></label><label className="field"><span>分类</span><select value={draft.category} onChange={event => setDraft({ ...draft, category: event.target.value })}><option value="dry">干粮</option><option value="wet">湿粮</option><option value="treat">零食</option><option value="supplement">营养补充</option><option value="other">其他</option></select></label><label className="field"><span>口味 / 配方</span><input value={draft.flavor} onChange={event => setDraft({ ...draft, flavor: event.target.value })} placeholder="例如：鸡肉"/></label><label className="field"><span>低库存提醒线</span><span className="field-with-suffix"><input required min="0" type="number" value={draft.lowStockThresholdPackages} onChange={event => setDraft({ ...draft, lowStockThresholdPackages: event.target.value })}/><i>包</i></span></label><label className="field wide"><span>备注</span><textarea rows={3} value={draft.notes} onChange={event => setDraft({ ...draft, notes: event.target.value })} placeholder="适口性、猫咪偏好或需要记住的事"/></label></div>{error && <p className="form-error" role="alert">{error}</p>}</form>;
}

export function CatFoodPurchaseEditor({ itemId, purchase, formId, onSaved, onSavingChange }: { itemId: number; purchase?: CatFoodPurchase; formId: string; onSaved: () => void; onSavingChange: (value: boolean) => void }) {
  const [draft, setDraft] = useState({ purchasedOn: purchase?.purchasedOn ?? today(), merchant: purchase?.merchant ?? "", packageCount: String(purchase?.packageCount ?? 1), remainingPackageCount: String(purchase?.remainingPackageCount ?? 1), amountPerPackage: String(purchase?.amountPerPackage ?? ""), amountUnit: purchase?.amountUnit ?? "g", paidAmount: purchase ? (purchase.paidAmountMinor / 100).toFixed(2) : "", notes: purchase?.notes ?? "" });
  const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); onSavingChange(true); try { const response = await fetch(purchase ? `/api/cats/food/purchases/${purchase.id}` : `/api/cats/food/${itemId}/purchases`, { method: purchase ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...draft, itemId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); onSaved(); } catch (value) { setError(value instanceof Error ? value.message : "保存失败"); } finally { onSavingChange(false); } }
  return <form id={formId} className="editor-card compact-editor" onSubmit={submit}><div className="form-grid"><label className="field"><span>购买日期</span><input required type="date" value={draft.purchasedOn} onChange={event => setDraft({ ...draft, purchasedOn: event.target.value })}/></label><label className="field"><span>购买渠道</span><input value={draft.merchant} onChange={event => setDraft({ ...draft, merchant: event.target.value })} placeholder="例如：京东自营"/></label><label className="field"><span>购买数量</span><span className="field-with-suffix"><input required min="1" type="number" value={draft.packageCount} onChange={event => setDraft({ ...draft, packageCount: event.target.value, remainingPackageCount: purchase ? draft.remainingPackageCount : event.target.value })}/><i>包</i></span></label><label className="field"><span>当前剩余</span><span className="field-with-suffix"><input required min="0" max={draft.packageCount} type="number" value={draft.remainingPackageCount} onChange={event => setDraft({ ...draft, remainingPackageCount: event.target.value })}/><i>包</i></span></label><label className="field"><span>单包规格</span><span className="field-combo"><input required min="0.01" step="0.01" type="number" value={draft.amountPerPackage} onChange={event => setDraft({ ...draft, amountPerPackage: event.target.value })}/><select aria-label="规格单位" value={draft.amountUnit} onChange={event => setDraft({ ...draft, amountUnit: event.target.value as CatFoodPurchase["amountUnit"] })}><option value="g">克</option><option value="ml">毫升</option><option value="piece">个</option></select></span></label><label className="field"><span>实付总额</span><span className="field-with-suffix prefix"><i>¥</i><input required min="0.01" step="0.01" type="number" value={draft.paidAmount} onChange={event => setDraft({ ...draft, paidAmount: event.target.value })}/></span></label><label className="field wide"><span>备注</span><textarea rows={3} value={draft.notes} onChange={event => setDraft({ ...draft, notes: event.target.value })} placeholder="优惠、批次或其他信息"/></label></div>{error && <p className="form-error" role="alert">{error}</p>}</form>;
}
