"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { Icon } from "@/components/icons";
import { FormSheet } from "@/components/form-sheet";
import { PageHeader } from "@/components/page-header";
import { diarySuggestedTags, parseTagInput } from "@/lib/long-term-memory";
import type { ApiError, LuciusDiaryEntry } from "@/lib/types";

async function responseError(response: Response, fallback: string) { const result = await response.json().catch(() => null) as ApiError | null; return result?.error || fallback; }
export function DiaryDetailView({ initial }: { initial: LuciusDiaryEntry }) {
  const router = useRouter(); const [item, setItem] = useState(initial); const [date, setDate] = useState(initial.date); const [content, setContent] = useState(initial.content); const [tags, setTags] = useState(initial.tags.join(", ")); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch(`/api/lucius/diary/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date, content, tags: parseTagInput(tags) }) }); if (!response.ok) throw new Error(await responseError(response, "Could not update Diary.")); const updated = await response.json() as LuciusDiaryEntry; setItem(updated); setEditing(false); setNotice("Diary entry updated."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update Diary."); } finally { setBusy(false); } }
  async function remove() { if (!window.confirm(`Delete Diary entry from ${item.date}? This cannot be undone.`)) return; setBusy(true); try { const response = await fetch(`/api/lucius/diary/${item.id}`, { method: "DELETE" }); if (!response.ok) throw new Error(await responseError(response, "Could not delete Diary entry.")); router.push("/lucius/diary"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not delete Diary entry."); } finally { setBusy(false); } }
  return <div className="page diary-page long-term-detail"><Link className="back-link" href="/lucius/diary">← Diary</Link><PageHeader eyebrow="LUCIUS DIARY" title={item.date} description={`Updated ${new Date(item.updatedAt).toLocaleString()}`} />{notice && <p className="success-banner">{notice}</p>}{error && <p className="form-error">{error}</p>}
    {editing ? <FormSheet title="Edit Diary entry" onClose={() => { setDate(item.date); setContent(item.content); setTags(item.tags.join(", ")); setEditing(false); }} formId="diary-edit-form" submitLabel="Save changes" busy={busy}><form id="diary-edit-form" className="editor-card long-term-editor" onSubmit={submit}><div className="form-grid"><label className="field"><span>Date</span><input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="field"><span>Tags</span><input value={tags} onChange={(event) => setTags(event.target.value)} /></label><label className="field wide"><span>Content</span><textarea required rows={18} value={content} onChange={(event) => setContent(event.target.value)} /></label></div><div className="suggested-tags">{diarySuggestedTags.map((value) => <button type="button" key={value} onClick={() => setTags(parseTagInput(`${tags},${value}`).join(", "))}>{value}</button>)}</div><div className="form-actions"><button className="button primary" disabled={busy}>Save changes</button><button type="button" className="text-button" onClick={() => { setDate(item.date); setContent(item.content); setTags(item.tags.join(", ")); setEditing(false); }}>Cancel</button></div></form></FormSheet> : <><article className="long-term-prose">{item.content}</article>{item.tags.length > 0 && <div className="tag-line detail-tags">{item.tags.map((value) => <em key={value}>{value}</em>)}</div>}<div className="long-term-actions"><button className="button primary" onClick={() => setEditing(true)}><Icon name="edit" />Edit</button><button className="text-button danger" disabled={busy} onClick={() => void remove()}><Icon name="trash" />Delete</button></div></>}
  </div>;
}
