"use client";

import Link from "next/link";
import { ArrowDown5 } from "reicon-react";
import { useState } from "react";
import type { DueReminder } from "@/lib/types";
import { reconcileNativeNotifications } from "@/lib/native-bridge";
import { useLocale } from "./locale-controller";
import { playNativeHaptic } from "@/lib/native-haptics";

function dueLabel(item:DueReminder){if(item.overdueMs<60_000)return"Now";const days=Math.floor(item.overdueMs/86_400_000);if(days>0)return`${days} ${days===1?"day":"days"} overdue`;return"Today";}

export function DueReminders({items,limit,onChanged,compact=false}:{items:DueReminder[];limit?:number;onChanged?:()=>void;compact?:boolean}){
  const {english}=useLocale();
  const [busy,setBusy]=useState<number|null>(null);const [snoozing,setSnoozing]=useState<number|null>(null);const [dismissed,setDismissed]=useState<number[]>([]);const [expanded,setExpanded]=useState(false);const [promoted,setPromoted]=useState<number|null>(null);const remaining=items.filter(item=>!dismissed.includes(item.id));const visible=limit?remaining.slice(0,limit):remaining;
  if(!visible.length)return null;
  async function action(id:number,name:"complete"|"skip"|"snooze",body?:unknown){setBusy(id);const response=await fetch(`/api/reminders/${id}/${name}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body??{})});setBusy(null);if(response.ok){playNativeHaptic(name==="complete"?"success":"selection");setSnoozing(null);if(id===remaining[0]?.id)setPromoted(remaining.find(item=>item.id!==id)?.id??null);setDismissed(current=>[...current,id]);onChanged?.();try{await reconcileNativeNotifications();}catch{/* Web notification delivery remains active. */}}else playNativeHaptic("error");}
  function card(item:DueReminder,top=false){const content=<><div className="due-card-copy"><strong className="user-content">{item.subjectLabel} · {item.title}</strong><small>{english?dueLabel(item):item.overdueMs<60_000?"现在":Math.floor(item.overdueMs/86_400_000)>0?`逾期 ${Math.floor(item.overdueMs/86_400_000)} 天`:"今天"}</small></div><div className="due-actions"><button disabled={busy===item.id} onClick={()=>void action(item.id,"complete")}>{english?"Complete":"完成"}</button><button disabled={busy===item.id} onClick={()=>setSnoozing(snoozing===item.id?null:item.id)}>{english?"Snooze":"稍后"}</button><button disabled={busy===item.id} onClick={()=>void action(item.id,"skip")}>{english?"Skip":"跳过"}</button></div></>;return <article className={top?"due-stack-top":""} data-promoted={top&&promoted===item.id||undefined} key={item.id}>{top?<><div className="due-stack-card-head"><button className="due-stack-toggle" type="button" aria-expanded={expanded} aria-label={expanded?(english?"Collapse due reminders":"收起待办"):(english?"Expand due reminders":"展开待办")} onClick={()=>setExpanded(value=>!value)}><span className="eyebrow">{english?"DUE":"待办"}</span><span className="due-stack-count">{remaining.length}</span><ArrowDown5 className="due-stack-toggle-icon" size={13} weight="Outline" aria-hidden="true"/></button>{limit&&remaining.length>limit?<Link href="/cats">{english?"View all →":"查看全部 →"}</Link>:null}</div><div className="due-stack-card-body">{content}</div></>:content}{snoozing===item.id&&<div className="snooze-menu"><button onClick={()=>void action(item.id,"snooze",{choice:"later_today"})}>{english?"Later today":"今天稍后"}</button><button onClick={()=>void action(item.id,"snooze",{choice:"tomorrow"})}>{english?"Tomorrow":"明天"}</button><label>{english?"Custom":"自定义"}<input type="datetime-local" onChange={event=>event.target.value&&void action(item.id,"snooze",{choice:"custom",custom:new Date(event.target.value).toISOString()})}/></label></div>}</article>}
  if(!compact)return <section className="due-section"><div className="section-heading compact"><span className="eyebrow">{english?"DUE":"待办"}</span>{limit&&remaining.length>limit?<Link href="/cats">{english?"View all →":"查看全部 →"}</Link>:null}</div><div className="due-list">{visible.map(item=>card(item))}</div></section>;
  return <section className={`due-section compact due-stack ${expanded?"expanded":""}`}><div className="due-stack-shell"><div className="due-list">{card(visible[0],true)}<div className="due-stack-more" aria-hidden={!expanded} inert={!expanded}><div>{visible.slice(1).map(item=>card(item))}</div></div></div></div></section>;
}
