"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icons";
import { FormSheet } from "@/components/form-sheet";
import { PageHeader } from "@/components/page-header";
import { TrackerIcon } from "@/components/tracker-icon";
import type { ApiError, Tracker, TrackerEntry, TrackerField, TrackerFieldType, TrackerGoal, TrackerGoalOperator, TrackerInsights, TrackerPeriodType, TrackerReminder, TrackerReminderType, TrackerStats } from "@/lib/types";

type Detail = { tracker: Tracker; fields: TrackerField[]; entries: TrackerEntry[]; goals: TrackerGoal[]; reminders: TrackerReminder[]; stats: TrackerStats; insights: TrackerInsights };
type Tab = "insights" | "timeline" | "settings";
type TimelinePeriod = "all" | "7d" | "30d" | "year";
const fieldTypes: Array<[TrackerFieldType,string]> = [["number","Number"],["single_select","Single select"],["multi_select","Multi select"],["text","Text"],["boolean","Switch"],["rating","Rating"]];
const emptyField = { name:"", type:"text" as TrackerFieldType, options:"", required:false, showAfterQuickCapture:false, includeInStats:false, unit:"", precision:"0" };
const emptyGoal = { operator:"<=" as TrackerGoalOperator, targetValue:"", periodType:"monthly" as TrackerPeriodType, customPeriod:"" };
const emptyReminder = { reminderType:"interval" as TrackerReminderType, intervalDays:"", scheduleRule:"" };

function localDateTime() { const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16); }
function elapsed(value:string|null){if(!value)return"No records yet";const difference=Date.now()-new Date(value).getTime();const days=Math.floor(difference/86400000);if(days)return`${days}d ago`;const hours=Math.floor(difference/3600000);if(hours)return`${hours}h ago`;return`${Math.max(1,Math.floor(difference/60000))}m ago`;}
function periodLabel(value:TrackerPeriodType){return{daily:"Daily",weekly:"Weekly",monthly:"Monthly",yearly:"Yearly",custom:"Custom"}[value];}
function shownValue(value:unknown){return Array.isArray(value)?value.join(", "):typeof value==="boolean"?value?"Yes":"No":String(value??"");}
function entryMatchesPeriod(entry:TrackerEntry,period:TimelinePeriod){if(period==="all")return true;const occurred=new Date(entry.occurredAt);const now=new Date();if(period==="year")return occurred.getFullYear()===now.getFullYear();const days=period==="7d"?7:30;return occurred.getTime()>=now.getTime()-days*86400000;}
function entryMatchesField(entry:TrackerEntry,field:TrackerField|undefined,filter:string){if(!field||!filter)return true;const value=entry.values[field.key]??entry.values[String(field.id)];if(Array.isArray(value))return value.some((item)=>String(item)===filter);if(field.type==="text")return String(value??"").toLocaleLowerCase().includes(filter.toLocaleLowerCase());return String(value??"")===filter;}

export function TrackerDetailView({ trackerId, openDetailedRecord = false }: { trackerId: number; openDetailedRecord?: boolean }) {
  const router=useRouter();
  const [detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[appliedQuery,setAppliedQuery]=useState(""),[tab,setTab]=useState<Tab>(openDetailedRecord?"timeline":"insights");
  const [showEntry,setShowEntry]=useState(openDetailedRecord),[showField,setShowField]=useState(false),[showRules,setShowRules]=useState(false);
  const [periodFilter,setPeriodFilter]=useState<TimelinePeriod>("all"),[fieldFilter,setFieldFilter]=useState(""),[fieldValueFilter,setFieldValueFilter]=useState("");
  const [occurredAt,setOccurredAt]=useState(localDateTime),[note,setNote]=useState(""),[values,setValues]=useState<Record<string,unknown>>({});
  const [fieldDraft,setFieldDraft]=useState(emptyField),[goalDraft,setGoalDraft]=useState(emptyGoal),[reminderDraft,setReminderDraft]=useState(emptyReminder);
  const load=useCallback(async(search="")=>{setLoading(true);const response=await fetch(`/api/trackers/${trackerId}${search?`?query=${encodeURIComponent(search)}`:""}`,{cache:"no-store"});if(response.ok)setDetail(await response.json());else setError(((await response.json())as ApiError).error);setLoading(false);},[trackerId]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  async function request(url:string,options:RequestInit){setWorking(true);setError("");const response=await fetch(url,options);if(!response.ok){setError(((await response.json())as ApiError).error);setWorking(false);return false;}await load(appliedQuery);setWorking(false);return true;}
  async function quick(){if(await request(`/api/trackers/${trackerId}/entries`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({occurredAt:new Date().toISOString(),values:{},note:""})}))setShowEntry(false);}
  function openEntryForm(){setTab("timeline");setShowEntry(true);}
  async function addEntry(event:FormEvent){event.preventDefault();const ok=await request(`/api/trackers/${trackerId}/entries`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({occurredAt:new Date(occurredAt).toISOString(),values,note})});if(ok){setOccurredAt(localDateTime());setNote("");setValues({});setShowEntry(false);}}
  async function addField(event:FormEvent){event.preventDefault();const activeCount=detail?.fields.filter((field)=>!field.archivedAt).length??0;const ok=await request(`/api/trackers/${trackerId}/fields`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...fieldDraft,precision:Number(fieldDraft.precision),options:fieldDraft.options.split(/[，,]/).map(item=>item.trim()).filter(Boolean),defaultValue:null,sortOrder:activeCount})});if(ok){setFieldDraft(emptyField);setShowField(false);}}
  async function addGoal(event:FormEvent){event.preventDefault();const ok=await request(`/api/trackers/${trackerId}/goals`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...goalDraft,targetValue:Number(goalDraft.targetValue),enabled:true})});if(ok)setGoalDraft(emptyGoal);}
  async function addReminder(event:FormEvent){event.preventDefault();const ok=await request(`/api/trackers/${trackerId}/reminders`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...reminderDraft,intervalDays:reminderDraft.intervalDays?Number(reminderDraft.intervalDays):null,enabled:true})});if(ok)setReminderDraft(emptyReminder);}
  async function uploadIcon(file:File|undefined){if(!file)return;if(file.size>4*1024*1024){setError("The image must be smaller than 4 MB.");return;}if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError("Use a JPG, PNG or WebP image.");return;}setWorking(true);const body=new FormData();body.set("file",file);const response=await fetch(`/api/trackers/${trackerId}/icon`,{method:"POST",body});if(!response.ok)setError(((await response.json())as ApiError).error);else await load(appliedQuery);setWorking(false);}
  async function removeTracker(){if(!confirm(`Delete “${detail?.tracker.name}” and every record inside it?`))return;const response=await fetch(`/api/trackers/${trackerId}`,{method:"DELETE"});if(response.ok){router.push("/trackers");router.refresh();}else setError(((await response.json())as ApiError).error);}
  function setFieldValue(field:TrackerField,value:unknown){setValues(current=>({...current,[field.key]:value}));}
  if(loading&&!detail)return <div className="page"><div className="loading-state">Opening Tracker…</div></div>;
  if(!detail)return <div className="page"><PageHeader eyebrow="TRACKER" title="Tracker not found" description={error}/><Link className="button secondary" href="/trackers">Back to Trackers</Link></div>;
  const {tracker,stats,insights}=detail;
  const activeFields=detail.fields.filter((field)=>!field.archivedAt);
  const selectedFilterField=activeFields.find((field)=>field.key===fieldFilter);
  const timelineEntries=detail.entries.filter((entry)=>entryMatchesPeriod(entry,periodFilter)&&entryMatchesField(entry,selectedFilterField,fieldValueFilter));
  const filtersActive=Boolean(appliedQuery||periodFilter!=="all"||fieldValueFilter);
  return <div className="page tracker-detail-page">
    <Link className="back-link" href="/trackers">← All Trackers</Link>
    <PageHeader eyebrow={`${tracker.groupName} · ${tracker.dataSourceType==="linked_source"?"LINKED":"MOMENT"}`} title={<span className="tracker-title"><TrackerIcon tracker={tracker} size={58}/><span>{tracker.name}</span></span>} action={tracker.dataSourceType==="native_tracker"?(tracker.quickCaptureEnabled?<button className="button primary" disabled={working} onClick={()=>void quick()}><Icon name="plus"/>Record now</button>:<button className="button primary" onClick={openEntryForm}><Icon name="plus"/>Add record</button>):undefined}/>
    <nav className="tracker-tabs" aria-label="Tracker views">{(["insights","timeline","settings"] as Tab[]).map((value)=><button className={tab===value?"active":""} onClick={()=>setTab(value)} key={value}>{value[0].toUpperCase()+value.slice(1)}</button>)}</nav>
    {error&&<p className="form-error">{error}</p>}

    {tab==="insights"&&<>
      <div className="tracker-stat-grid"><article><span>Today</span><strong>{stats.today}</strong></article><article><span>This week</span><strong>{stats.week}</strong></article><article><span>This month</span><strong>{stats.month}</strong></article><article><span>This year</span><strong>{stats.year}</strong></article><article className="wide"><span>Last recorded</span><strong>{elapsed(stats.lastOccurredAt)}</strong></article></div>
      {stats.reminderDue&&<div className="tracker-reminder-alert"><Icon name="history"/><span><strong>An interval reminder is due</strong><small>The reminder is based on the last recorded moment.</small></span></div>}
      <section className="tracker-insight-card"><div className="section-heading"><div><span className="eyebrow">ACTIVITY</span><h2>A year at a glance</h2></div><span>{insights.activeDays} active days</span></div><TrackerHeatmap insights={insights}/></section>
      <div className="tracker-insight-grid">
        <section className="tracker-insight-card"><div className="section-heading"><div><span className="eyebrow">TREND</span><h2>Last 12 months</h2></div></div><BarChart items={insights.monthly}/></section>
        <section className="tracker-insight-card"><div className="section-heading"><div><span className="eyebrow">RHYTHM</span><h2>Day of week</h2></div></div><BarChart items={insights.weekdays}/></section>
        <section className="tracker-insight-card"><div className="section-heading"><div><span className="eyebrow">RHYTHM</span><h2>Time of day</h2></div></div><BarChart items={insights.dayParts}/></section>
      </div>
      {(insights.numericFields.length>0||insights.choiceFields.length>0)&&<section className="tracker-detail-section"><div className="section-heading"><div><span className="eyebrow">PROPERTIES</span><h2>What the details reveal</h2></div></div><div className="tracker-property-insights">
        {insights.numericFields.map((field)=><article key={field.fieldKey}><span>{field.name}</span><strong>{field.average}{field.unit&&` ${field.unit}`}</strong><small>Average · {field.minimum}–{field.maximum} · latest {field.latest}</small></article>)}
        {insights.choiceFields.map((field)=><article className="choice" key={field.fieldKey}><span>{field.name}</span><div>{field.values.map((value)=><p key={value.key}><span>{value.label}</span><strong>{value.count}</strong><i style={{width:`${value.percentage}%`}}/></p>)}</div></article>)}
      </div></section>}
      {stats.total===0&&<div className="empty-state compact-empty"><h2>Patterns will appear here</h2><p>Record a few moments and the heatmap, rhythm and property summaries will grow naturally.</p></div>}
    </>}

    {tab==="timeline"&&<>
      {tracker.dataSourceType==="native_tracker"&&<section className="tracker-detail-section"><div className="section-heading"><div><span className="eyebrow">CAPTURE</span><h2>Add details</h2></div><button className="text-button" onClick={()=>setShowEntry(value=>!value)}>{showEntry?"Close":"New record"}</button></div>
        {showEntry&&<FormSheet title="Add details" onClose={()=>setShowEntry(false)} formId="tracker-entry-form" submitLabel="Save record" busy={working}><form id="tracker-entry-form" className="editor-card tracker-entry-form" onSubmit={addEntry}><label className="field"><span>When</span><input required type="datetime-local" value={occurredAt} onChange={event=>setOccurredAt(event.target.value)}/></label>
        {activeFields.length>0&&<div className="tracker-values-grid">{activeFields.map(field=><FieldInput field={field} value={values[field.key]} onChange={value=>setFieldValue(field,value)} key={field.id}/>)}</div>}
        <label className="field"><span>Note</span><textarea rows={3} maxLength={5000} value={note} onChange={event=>setNote(event.target.value)} placeholder="Optional"/></label><button className="button primary" disabled={working}>Save record</button></form></FormSheet>}
      </section>}
      <section className="tracker-detail-section"><div className="section-heading"><div><span className="eyebrow">TIMELINE</span><h2>Every record</h2></div><span>{filtersActive?`${timelineEntries.length} / ${stats.total}`:stats.total}</span></div><form className="tracker-search" onSubmit={event=>{event.preventDefault();setAppliedQuery(query);void load(query);}}><Icon name="search"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search notes or properties"/><button>Search</button></form>
        <div className="tracker-filters"><label><span>Time</span><select value={periodFilter} onChange={event=>setPeriodFilter(event.target.value as TimelinePeriod)}><option value="all">Any time</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="year">This year</option></select></label>{activeFields.length>0&&<label><span>Property</span><select value={fieldFilter} onChange={event=>{setFieldFilter(event.target.value);setFieldValueFilter("");}}><option value="">Any property</option>{activeFields.map(field=><option value={field.key} key={field.key}>{field.name}</option>)}</select></label>}{selectedFilterField&&<FieldFilter field={selectedFilterField} value={fieldValueFilter} onChange={setFieldValueFilter}/>} {filtersActive&&<button type="button" onClick={()=>{setQuery("");setAppliedQuery("");setPeriodFilter("all");setFieldFilter("");setFieldValueFilter("");void load("");}}>Clear</button>}</div>
        {timelineEntries.length?<div className="tracker-entry-list">{timelineEntries.map(entry=><article key={`${entry.sourceType}-${entry.id}`}><div className="tracker-entry-time"><strong>{new Date(entry.occurredAt).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</strong><span>{new Date(entry.occurredAt).toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit"})}</span></div><div><div className="tracker-entry-values">{Object.entries(entry.values).map(([key,value])=><span key={key}>{detail.fields.find(field=>field.key===key||String(field.id)===key)?.name??"Archived property"}: {shownValue(value)}</span>)}</div>{entry.note&&<p>{entry.note}</p>}{entry.sourceType==="drink"&&<small>From Drinks</small>}</div>{entry.sourceType==="native_tracker"&&<button className="danger-icon" aria-label="Delete record" onClick={()=>confirm("Delete this record?")&&void request(`/api/trackers/${trackerId}/entries?entryId=${entry.id}`,{method:"DELETE"})}><Icon name="trash"/></button>}</article>)}</div>:<div className="empty-state compact-empty"><h2>{filtersActive?"No matching records":"No records yet"}</h2><p>{filtersActive?"Try a wider time range or clear one of the filters.":tracker.dataSourceType==="linked_source"?"Matching Drink records will appear here.":"Use Record now when this happens."}</p></div>}
      </section>
    </>}

    {tab==="settings"&&<>
      <section className="tracker-detail-section"><div className="section-heading"><div><span className="eyebrow">APPEARANCE</span><h2>Tracker image</h2></div></div><div className="tracker-icon-settings"><TrackerIcon tracker={tracker} size={82}/><div><strong>{tracker.iconType==="image"?"Custom image":"Default icon"}</strong><small>Images are cropped to a square and kept private.</small><div><label className="button secondary">{working?"Uploading…":"Choose image"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={working} onChange={(event)=>{void uploadIcon(event.target.files?.[0]);event.target.value="";}}/></label>{tracker.iconType==="image"&&<button className="text-button" onClick={()=>void request(`/api/trackers/${trackerId}/icon`,{method:"DELETE"})}>Restore default</button>}</div></div></div></section>
      {tracker.dataSourceType==="native_tracker"&&<section className="tracker-detail-section"><div className="section-heading"><div><span className="eyebrow">PROPERTIES</span><h2>Record structure</h2></div><button className="text-button" onClick={()=>setShowField(value=>!value)}>{showField?"Close":"Add property"}</button></div>
        {activeFields.length>0&&<div className="tracker-rule-list">{activeFields.map(field=><article key={field.id}><span><strong>{field.name}</strong><small>{fieldTypes.find(([type])=>type===field.type)?.[1]}{field.unit?` · ${field.unit}`:""}{field.required?" · Required":""}{field.includeInStats?" · In Insights":""}</small></span><button aria-label={`Archive ${field.name}`} onClick={()=>confirm("Archive this property? Historical records will keep its meaning.")&&void request(`/api/trackers/${trackerId}/fields?fieldId=${field.id}`,{method:"DELETE"})}><Icon name="trash"/></button></article>)}</div>}
        {showField&&<form className="editor-card tracker-rule-form" onSubmit={addField}><div className="form-grid"><label className="field"><span>Property name</span><input required value={fieldDraft.name} onChange={event=>setFieldDraft({...fieldDraft,name:event.target.value})}/></label><label className="field"><span>Type</span><select value={fieldDraft.type} onChange={event=>setFieldDraft({...fieldDraft,type:event.target.value as TrackerFieldType})}>{fieldTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{["single_select","multi_select"].includes(fieldDraft.type)&&<label className="field wide"><span>Options, separated by commas</span><input required value={fieldDraft.options} onChange={event=>setFieldDraft({...fieldDraft,options:event.target.value})}/></label>}{fieldDraft.type==="number"&&<><label className="field"><span>Unit</span><input maxLength={20} value={fieldDraft.unit} onChange={event=>setFieldDraft({...fieldDraft,unit:event.target.value})} placeholder="ml, kg, ¥…"/></label><label className="field"><span>Decimal places</span><input type="number" min="0" max="6" value={fieldDraft.precision} onChange={event=>setFieldDraft({...fieldDraft,precision:event.target.value})}/></label></>}</div><div className="tracker-inline-checks"><label><input type="checkbox" checked={fieldDraft.required} onChange={event=>setFieldDraft({...fieldDraft,required:event.target.checked})}/>Required</label><label><input type="checkbox" checked={fieldDraft.showAfterQuickCapture} onChange={event=>setFieldDraft({...fieldDraft,showAfterQuickCapture:event.target.checked})}/>Useful after quick capture</label><label><input type="checkbox" checked={fieldDraft.includeInStats} onChange={event=>setFieldDraft({...fieldDraft,includeInStats:event.target.checked})}/>Include in Insights</label></div><button className="button primary">Add property</button></form>}
      </section>}
      <section className="tracker-detail-section"><div className="section-heading"><div><span className="eyebrow">RULES</span><h2>Goals and reminders</h2></div><button className="text-button" onClick={()=>setShowRules(value=>!value)}>{showRules?"Close":"Manage"}</button></div>
        <div className="tracker-rule-list">{detail.goals.map(goal=><article key={`goal-${goal.id}`}><span><strong>{goal.operator==="<="?"Limit":"Goal"} · {periodLabel(goal.periodType)} {goal.operator} {goal.targetValue}</strong><small>A statistical rule, separate from reminders</small></span><button aria-label="Delete goal" onClick={()=>void request(`/api/trackers/${trackerId}/goals?goalId=${goal.id}`,{method:"DELETE"})}><Icon name="trash"/></button></article>)}{detail.reminders.map(reminder=><article key={`reminder-${reminder.id}`}><span><strong>{reminder.reminderType==="interval"?`${reminder.intervalDays} days since last record`:`Scheduled · ${reminder.scheduleRule}`}</strong><small>Reminder rule saved</small></span><button aria-label="Delete reminder" onClick={()=>void request(`/api/trackers/${trackerId}/reminders?reminderId=${reminder.id}`,{method:"DELETE"})}><Icon name="trash"/></button></article>)}</div>
        {showRules&&<div className="tracker-rules-editor"><form className="editor-card tracker-rule-form" onSubmit={addGoal}><h3>Goal / Limit</h3><div className="form-grid"><label className="field"><span>Rule</span><select value={goalDraft.operator} onChange={event=>setGoalDraft({...goalDraft,operator:event.target.value as TrackerGoalOperator})}><option value="<=">At most</option><option value=">=">At least</option><option value="=">Exactly</option></select></label><label className="field"><span>Records</span><input required type="number" min="1" value={goalDraft.targetValue} onChange={event=>setGoalDraft({...goalDraft,targetValue:event.target.value})}/></label><label className="field"><span>Period</span><select value={goalDraft.periodType} onChange={event=>setGoalDraft({...goalDraft,periodType:event.target.value as TrackerPeriodType})}>{(["daily","weekly","monthly","yearly","custom"]as TrackerPeriodType[]).map(period=><option key={period} value={period}>{periodLabel(period)}</option>)}</select></label>{goalDraft.periodType==="custom"&&<label className="field"><span>Custom period</span><input value={goalDraft.customPeriod} onChange={event=>setGoalDraft({...goalDraft,customPeriod:event.target.value})}/></label>}</div><button className="button secondary">Save rule</button></form>
        <form className="editor-card tracker-rule-form" onSubmit={addReminder}><h3>Reminder</h3><label className="field"><span>Type</span><select value={reminderDraft.reminderType} onChange={event=>setReminderDraft({...reminderDraft,reminderType:event.target.value as TrackerReminderType})}><option value="interval">Time since last record</option><option value="scheduled">Scheduled</option></select></label>{reminderDraft.reminderType==="interval"?<label className="field"><span>Days</span><input required type="number" min="1" value={reminderDraft.intervalDays} onChange={event=>setReminderDraft({...reminderDraft,intervalDays:event.target.value})}/></label>:<label className="field"><span>Schedule</span><input required value={reminderDraft.scheduleRule} onChange={event=>setReminderDraft({...reminderDraft,scheduleRule:event.target.value})} placeholder="Every Sunday"/></label>}<button className="button secondary">Save reminder</button></form></div>}
      </section>
      <div className="tracker-danger-zone"><button className="danger-text" onClick={()=>void removeTracker()}>Delete this Tracker</button></div>
    </>}
  </div>;
}

function TrackerHeatmap({insights}:{insights:TrackerInsights}) {
  const maximum=Math.max(1,...insights.heatmap.map((day)=>day.count));
  const firstDay=insights.heatmap[0]?.date;
  const blanks=firstDay?(new Date(`${firstDay}T12:00:00Z`).getUTCDay()+6)%7:0;
  return <div className="tracker-heatmap-scroll"><div className="tracker-heatmap" role="img" aria-label="365 day activity heatmap">{Array.from({length:blanks},(_,index)=><i className="blank" key={`blank-${index}`}/>)}{insights.heatmap.map((day)=>{const level=day.count===0?0:Math.max(1,Math.ceil(day.count/maximum*4));return <i className={`level-${level}`} title={`${day.date}: ${day.count}`} aria-label={`${day.date}, ${day.count} records`} key={day.date}/>;})}</div><div className="tracker-heatmap-legend"><span>Less</span>{[0,1,2,3,4].map(level=><i className={`level-${level}`} key={level}/>)}<span>More</span></div></div>;
}

function BarChart({items}:{items:TrackerInsights["monthly"]}) {
  const maximum=Math.max(1,...items.map((item)=>item.count));
  return <div className="tracker-bars">{items.map((item)=><div key={item.key}><span title={`${item.label}: ${item.count}`} style={{height:`${Math.max(item.count?8:2,item.count/maximum*100)}%`}}/><small>{item.label}</small></div>)}</div>;
}

function FieldInput({field,value,onChange}:{field:TrackerField;value:unknown;onChange:(value:unknown)=>void}){
  if(field.type==="boolean")return <label className="tracker-check field-check"><input type="checkbox" checked={Boolean(value)} onChange={event=>onChange(event.target.checked)}/>{field.name}</label>;
  if(field.type==="single_select")return <label className="field"><span>{field.name}</span><select required={field.required} value={typeof value==="string"?value:""} onChange={event=>onChange(event.target.value)}><option value="">Not selected</option>{field.options.map(option=><option key={option}>{option}</option>)}</select></label>;
  if(field.type==="multi_select")return <fieldset className="tracker-multi-field"><legend>{field.name}</legend>{field.options.map(option=><label key={option}><input type="checkbox" checked={Array.isArray(value)&&value.includes(option)} onChange={event=>{const current=Array.isArray(value)?value as string[]:[];onChange(event.target.checked?[...current,option]:current.filter(item=>item!==option));}}/>{option}</label>)}</fieldset>;
  if(field.type==="rating")return <label className="field"><span>{field.name}</span><select required={field.required} value={typeof value==="number"?value:""} onChange={event=>onChange(event.target.value?Number(event.target.value):null)}><option value="">Not rated</option>{[1,2,3,4,5].map(score=><option key={score} value={score}>{"★".repeat(score)}</option>)}</select></label>;
  return <label className="field"><span>{field.name}{field.unit&&` (${field.unit})`}</span><input required={field.required} type={field.type==="number"?"number":"text"} step={field.type==="number"?10**-field.precision:undefined} value={typeof value==="string"||typeof value==="number"?String(value):""} onChange={event=>onChange(field.type==="number"?(event.target.value?Number(event.target.value):null):event.target.value)}/></label>;
}

function FieldFilter({field,value,onChange}:{field:TrackerField;value:string;onChange:(value:string)=>void}){
  if(field.type==="single_select"||field.type==="multi_select")return <label><span>Value</span><select value={value} onChange={event=>onChange(event.target.value)}><option value="">Any value</option>{field.options.map(option=><option key={option}>{option}</option>)}</select></label>;
  if(field.type==="boolean")return <label><span>Value</span><select value={value} onChange={event=>onChange(event.target.value)}><option value="">Any value</option><option value="true">Yes</option><option value="false">No</option></select></label>;
  if(field.type==="rating")return <label><span>Rating</span><select value={value} onChange={event=>onChange(event.target.value)}><option value="">Any rating</option>{[1,2,3,4,5].map(score=><option value={score} key={score}>{score} stars</option>)}</select></label>;
  return <label><span>{field.type==="number"?"Exact value":"Contains"}</span><input type={field.type==="number"?"number":"search"} value={value} onChange={event=>onChange(event.target.value)} placeholder={field.type==="number"?field.unit||"Value":"Text"}/></label>;
}
