"use client";
import { groupTrackerTimeline, matchesTrackerSearch } from "@/lib/tracker-timeline";
import { SuggestedInput } from "@/components/suggested-input";
import { formatTrackerTimeRange, trackerDurationMinutes } from "@/lib/tracker-time-range";
import { ToastNotice, showActionToast } from "@/components/action-toast";

import Link from "next/link";
import { FormEvent, useCallback, useState, type CSSProperties } from "react";
import { useRouter } from "next/navigation";
import { ArchiveBox, ArrowLeft2, ArrowRight2, More, Trash } from "reicon-react";
import { Icon } from "@/components/icons";
import { FormSheet } from "@/components/form-sheet";
import { useLocale } from "@/components/locale-controller";
import { PageHeader } from "@/components/page-header";
import { TrackerIcon } from "@/components/tracker-icon";
import { invalidateCachedJson } from "@/lib/client-json-cache";
import { reconcileNativeNotifications } from "@/lib/native-bridge";
import { playNativeHaptic } from "@/lib/native-haptics";
import { shiftTrackerMonth, trackerCalendarMonth, trackerHeatLevel } from "@/lib/tracker-insights";
import { translateUiCopy } from "@/lib/ui-copy";
import { TrackerEntryEditor } from "../tracker-entry-editor";
import type { ApiError, Tracker, TrackerEntry, TrackerField, TrackerFieldType, TrackerGoal, TrackerGoalOperator, TrackerInsights, TrackerPeriodType, TrackerReminder, TrackerReminderMode, TrackerStats } from "@/lib/types";

type Detail = { groupNames?: string[]; tracker: Tracker; fields: TrackerField[]; entries: TrackerEntry[]; goals: TrackerGoal[]; reminders: TrackerReminder[]; stats: TrackerStats; insights: TrackerInsights };
type Tab = "insights" | "timeline" | "settings";
type TimelinePeriod = "all" | "7d" | "30d" | "year";
const fieldTypes: Array<[TrackerFieldType,string]> = [["time_range","Time range"],["number","Number"],["single_select","Single select"],["multi_select","Multi select"],["text","Text"],["boolean","Switch"],["rating","Rating"]];
const emptyField = { name:"", type:"text" as TrackerFieldType, options:"", required:false, showAfterQuickCapture:false, includeInStats:false, unit:"", precision:"0" };
const emptyGoal = { operator:"<=" as TrackerGoalOperator, targetValue:"", periodType:"monthly" as TrackerPeriodType, customPeriod:"" };
type SettingsConfirmation = { title: string; message: string; label: string; destructive: boolean; action: () => Promise<unknown> };
const emptyReminder = { reminderMode:"missing" as TrackerReminderMode, periodDays:"1", configuredTime:"20:00", anchorDate:new Date().toLocaleDateString("en-CA") };

function elapsed(value:string|null){if(!value)return"No records yet";const difference=Date.now()-new Date(value).getTime();const days=Math.floor(difference/86400000);if(days)return`${days}d ago`;const hours=Math.floor(difference/3600000);if(hours)return`${hours}h ago`;return`${Math.max(1,Math.floor(difference/60000))}m ago`;}
function periodLabel(value:TrackerPeriodType,english=true){return english?{daily:"Daily",weekly:"Weekly",monthly:"Monthly",yearly:"Yearly",custom:"Custom"}[value]:{daily:"每天",weekly:"每周",monthly:"每月",yearly:"每年",custom:"自定义周期"}[value];}
function fieldTypeLabel(type:TrackerFieldType,english:boolean){return english?fieldTypes.find(([value])=>value===type)?.[1]??type:{time_range:"时间段",number:"数字",single_select:"单选",multi_select:"多选",text:"文本",boolean:"是 / 否",rating:"评价"}[type];}
function shownValue(value:unknown){return Array.isArray(value)?value.join(", "):typeof value==="boolean"?value?"Yes":"No":String(value??"");}
function entryMatchesPeriod(entry:TrackerEntry,period:TimelinePeriod){if(period==="all")return true;const occurred=new Date(entry.occurredAt);const now=new Date();if(period==="year")return occurred.getFullYear()===now.getFullYear();const days=period==="7d"?7:30;return occurred.getTime()>=now.getTime()-days*86400000;}
function entryMatchesField(entry:TrackerEntry,field:TrackerField|undefined,filter:string){if(!field||!filter)return true;const value=entry.values[field.key]??entry.values[String(field.id)];if(Array.isArray(value))return value.some((item)=>String(item)===filter);if(field.type==="time_range")return trackerDurationMinutes(value)===Number(filter);if(field.type==="text")return String(value??"").toLocaleLowerCase().includes(filter.toLocaleLowerCase());return String(value??"")===filter;}

export function TrackerDetailView({ initial, trackerId, openDetailedRecord = false }: { initial: Detail; trackerId: number; openDetailedRecord?: boolean }) {
  const router=useRouter();
  const {english,language}=useLocale();
  const copy=(value:string)=>translateUiCopy(value,language);
  const [detail,setDetail]=useState<Detail|null>(initial),[loading,setLoading]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[tab,setTab]=useState<Tab>("timeline");
  const [showEntry,setShowEntry]=useState(openDetailedRecord),[showField,setShowField]=useState(false),[rulePanel,setRulePanel]=useState<"goal"|"reminder"|null>(null);
  const [showRename,setShowRename]=useState(false),[trackerName,setTrackerName]=useState("");
  const [trackerGroup,setTrackerGroup]=useState(""),[trackerQuick,setTrackerQuick]=useState(true),[editingFieldId,setEditingFieldId]=useState<number|null>(null);
  const [periodFilter,setPeriodFilter]=useState<TimelinePeriod>("all"),[fieldFilter,setFieldFilter]=useState(""),[fieldValueFilter,setFieldValueFilter]=useState("");
  const [fieldDraft,setFieldDraft]=useState(emptyField),[goalDraft,setGoalDraft]=useState(emptyGoal),[reminderDraft,setReminderDraft]=useState(emptyReminder);
  const [editingReminderId,setEditingReminderId]=useState<number|null>(null);
  const [confirmation,setConfirmation]=useState<SettingsConfirmation|null>(null);
  const load=useCallback(async(search="")=>{setLoading(true);const response=await fetch(`/api/trackers/${trackerId}${search?`?query=${encodeURIComponent(search)}`:""}`,{cache:"no-store"});if(response.ok)setDetail(await response.json());else setError(((await response.json())as ApiError).error);setLoading(false);},[trackerId]);
  async function request(url:string,options:RequestInit,success?:string){if(working)return false;setWorking(true);setError("");setMessage("");try{const response=await fetch(url,options);if(!response.ok){setError(((await response.json())as ApiError).error);return false;}invalidateCachedJson("/api/trackers/quick-log");await load();try{await reconcileNativeNotifications();}catch{/* Web Push remains the fallback. */}if(success)setMessage(success);return true;}catch(reason){setError(reason instanceof Error?reason.message:"Could not save this change.");return false;}finally{setWorking(false);}}
  async function quick(){if(await request(`/api/trackers/${trackerId}/entries`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({occurredAt:new Date().toISOString(),values:{},note:""})})){playNativeHaptic("light");setShowEntry(false);}}
  function openEntryForm(){setTab("timeline");setShowEntry(true);}
  async function addField(event:FormEvent){event.preventDefault();if(working)return;const activeCount=detail?.fields.filter((field)=>!field.archivedAt).length??0;const editing=editingFieldId!==null;const ok=await request(`/api/trackers/${trackerId}/fields${editing?`?fieldId=${editingFieldId}`:""}`,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{name:fieldDraft.name,required:fieldDraft.required,includeInStats:fieldDraft.includeInStats}:{...fieldDraft,showAfterQuickCapture:false,precision:Number(fieldDraft.precision),options:fieldDraft.options.split(/[，,]/).map(item=>item.trim()).filter(Boolean),defaultValue:null,sortOrder:activeCount})});if(ok){setFieldDraft(emptyField);setEditingFieldId(null);setShowField(false);setMessage(english?"Property saved.":"属性已保存。");}}
  async function addGoal(event:FormEvent){event.preventDefault();const ok=await request(`/api/trackers/${trackerId}/goals`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...goalDraft,targetValue:Number(goalDraft.targetValue),enabled:true})});if(ok){setGoalDraft(emptyGoal);setRulePanel(null);setMessage("Goal saved.");}}
  function trackerReminderPayload(reminder:typeof reminderDraft,enabled=true){return{...reminder,periodDays:Number(reminder.periodDays),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,enabled};}
  async function addReminder(event:FormEvent){event.preventDefault();const editing=editingReminderId!==null;const ok=await request(`/api/trackers/${trackerId}/reminders${editingReminderId?`?reminderId=${editingReminderId}`:""}`,{method:editingReminderId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(trackerReminderPayload(reminderDraft))});if(ok){setReminderDraft({...emptyReminder,anchorDate:new Date().toLocaleDateString("en-CA")});setEditingReminderId(null);setRulePanel(null);setMessage(editing?"Reminder updated.":"Reminder added.");}}
  async function toggleTrackerReminder(reminder:TrackerReminder){await request(`/api/trackers/${trackerId}/reminders?reminderId=${reminder.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({reminderMode:reminder.reminderMode,periodDays:reminder.periodDays,configuredTime:reminder.configuredTime,anchorDate:reminder.anchorDate,timezone:reminder.timezone,enabled:!reminder.enabled})});}
  async function renameTracker(event:FormEvent){event.preventDefault();if(await request(`/api/trackers/${trackerId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:trackerName,groupName:trackerGroup,quickCaptureEnabled:trackerQuick})})){setShowRename(false);setMessage(english?"Tracker updated.":"基本信息已保存。");}}
  function editTrackerReminder(reminder:TrackerReminder){setReminderDraft({reminderMode:reminder.reminderMode,periodDays:String(reminder.periodDays),configuredTime:reminder.configuredTime,anchorDate:reminder.anchorDate});setEditingReminderId(reminder.id);setRulePanel("reminder");}
  function closeReminderSheet(){setRulePanel(null);setEditingReminderId(null);setReminderDraft({...emptyReminder,anchorDate:new Date().toLocaleDateString("en-CA")});}
  async function uploadIcon(file:File|undefined){
    if(!file||working)return;
    if(file.size>4*1024*1024){setError(english?"The image must be smaller than 4 MB.":"图片不能超过 4 MB。");return;}
    if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError(english?"Use a JPG, PNG or WebP image.":"请选择 JPG、PNG 或 WebP 图片。");return;}
    const body=new FormData();body.set("file",file);
    await request(`/api/trackers/${trackerId}/icon`,{method:"POST",body},english?"Image updated.":"图片已更新。");
  }
  async function removeTracker(){
    if(working)return false;
    setWorking(true);setError("");
    try{const response=await fetch(`/api/trackers/${trackerId}`,{method:"DELETE"});if(!response.ok){setError(((await response.json())as ApiError ).error);return false;}
      invalidateCachedJson("/api/trackers/quick-log");try{await reconcileNativeNotifications();}catch{/* Web Push remains the fallback. */}
      showActionToast(english?"Tracker deleted":"Tracker 已删除","deleted");router.push("/trackers");router.refresh();return true;
    }catch{setError(english?"Could not delete the Tracker. Please try again.":"删除失败，请重试。");return false;}finally{setWorking(false);}
  }
  function openField(field?:TrackerField){setError("");setEditingFieldId(field?.id??null);setFieldDraft(field?{name:field.name,type:field.type,options:field.options.join(", "),required:field.required,showAfterQuickCapture:false,includeInStats:field.includeInStats,unit:field.unit,precision:String(field.precision)}:emptyField);setShowField(true);}
  async function setFieldArchived(field:TrackerField,archived:boolean){await request(`/api/trackers/${trackerId}/fields?fieldId=${field.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({archived})},english?(archived?"Property archived; historical values are kept.":"Property restored."):(archived?"属性已归档，历史值已保留。":"属性已恢复。"));}
  function removeField(field:TrackerField){
    setError("");setConfirmation({title:english?"Permanently delete property":"永久删除属性",message:english?`Delete “${field.name}” and its values in ALL historical records? Other properties, dates and notes stay. This cannot be undone.`:`删除属性「${field.name}」及全部历史记录中该属性的值？其他属性、时间和备注会保留。删除后无法恢复。`,label:english?"Delete permanently":"确认永久删除",destructive:true,action:()=>request(`/api/trackers/${trackerId}/fields?fieldId=${field.id}&permanent=true`,{method:"DELETE"},english?"Property and historical values deleted.":"属性及其历史值已删除。")});
  }
  async function setTrackerArchived(archived:boolean){
    const save=()=>request(`/api/trackers/${trackerId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({archived})},english?(archived?"Tracker archived.":"Tracker restored; enable reminders separately."):(archived?"Tracker 已归档。":"Tracker 已恢复，请按需重新开启提醒。"));
    if(archived){setError("");setConfirmation({title:english?"Archive Tracker":"归档 Tracker",message:english?"History is kept. New recording and all reminders stop. You can restore this Tracker later; reminders must be enabled separately.":"历史数据会保留，暂停新增记录并关闭所有提醒。之后可以恢复 Tracker，提醒需按需重新开启。",label:english?"Archive":"确认归档",destructive:false,action:save});}
    else await save();
  }
  if(loading&&!detail)return <div className="page"><div className="loading-state">Opening Tracker…</div></div>;
  if(!detail)return <div className="page"><PageHeader eyebrow="TRACKER" title="Tracker not found" description={error}/><Link className="button secondary" href="/trackers">Back to Trackers</Link></div>;
  const {tracker,stats,insights}=detail;
  const activeFields=detail.fields.filter((field)=>!field.archivedAt);
  const selectedFilterField=detail.fields.find((field)=>field.key===fieldFilter);
  const timelineEntries=detail.entries.filter((entry)=>matchesTrackerSearch(entry,query)&&entryMatchesPeriod(entry,periodFilter)&&entryMatchesField(entry,selectedFilterField,fieldValueFilter));
  const filtersActive=Boolean(query.trim()||periodFilter!=="all"||fieldFilter);
  const timelineGroups=groupTrackerTimeline(timelineEntries);
  return <div className="page tracker-detail-page">
    <Link className="back-link" href="/trackers">← All Trackers</Link>
    <PageHeader eyebrow={`${tracker.groupName} · MOMENT`} title={<span className="tracker-title"><TrackerIcon tracker={tracker} size={58}/><span>{tracker.name}</span></span>} action={tracker.archivedAt?<span className="tracker-archived-label">{english?"Archived":"已归档"}</span>:tracker.quickCaptureEnabled?<button className="button primary" disabled={working} onClick={()=>void quick()}><Icon name="plus"/>Record now</button>:<button className="button primary" disabled={working} onClick={openEntryForm}><Icon name="plus"/>Add record</button>}/>
    <nav className="tracker-tabs" aria-label="Tracker views">{(["timeline","insights","settings"] as Tab[]).map((value)=><button aria-current={tab===value?"page":undefined} className={tab===value?"active":""} onClick={()=>setTab(value)} key={value}>{value[0].toUpperCase()+value.slice(1)}</button>)}</nav>
    {error&&<p className="form-error">{error}</p>}
    {tracker.archivedAt&&<p className="tracker-archive-note">{english?"History is preserved. Restore this Tracker in Settings to record again; reminders remain off until you enable them.":"历史数据已保留。可在设置中恢复 Tracker，恢复后请按需重新开启提醒。"}</p>}
    {message&&<ToastNotice message={message} onShown={() => setMessage("")} />}

    {tab==="insights"&&<>
      <div className="tracker-stat-grid"><article><span>Today</span><strong>{stats.today}</strong></article><article><span>This week</span><strong>{stats.week}</strong></article><article><span>This month</span><strong>{stats.month}</strong></article><article><span>This year</span><strong>{stats.year}</strong></article><article className="wide"><span>Last recorded</span><strong>{elapsed(stats.lastOccurredAt)}</strong></article></div>
      {stats.reminderDue&&<div className="tracker-reminder-alert"><Icon name="history"/><span><strong>A Tracker reminder is due</strong><small>Missing reminders only consider entries from this Tracker and this observation period.</small></span></div>}
      <section className="tracker-insight-card"><div className="section-heading"><div><span className="eyebrow">{english?"ACTIVITY":"活跃记录"}</span><h2>{english?"Monthly activity":"月度热力图"}</h2></div></div><TrackerHeatmap insights={insights}/></section>
      <div className="tracker-insight-grid">
        <section className="tracker-insight-card"><div className="section-heading"><div><span className="eyebrow">TREND</span><h2>Last 12 months</h2></div></div><BarChart items={insights.monthly}/></section>
        <section className="tracker-insight-card"><div className="section-heading"><div><span className="eyebrow">RHYTHM</span><h2>Day of week</h2></div></div><BarChart items={insights.weekdays}/></section>
        <section className="tracker-insight-card"><div className="section-heading"><div><span className="eyebrow">RHYTHM</span><h2>Time of day</h2></div></div><BarChart items={insights.dayParts}/></section>
      </div>
      {(insights.numericFields.length>0||insights.choiceFields.length>0)&&<section className="tracker-detail-section"><div className="section-heading"><div><span className="eyebrow">PROPERTIES</span><h2>{english?"What the details reveal":"属性分布"}</h2></div></div><div className="tracker-property-insights">
        {insights.numericFields.map((field)=><article className="metric" key={field.fieldKey}><span>{copy(field.name)}</span><strong>{field.average}{field.unit&&` ${field.unit}`}</strong><small>{english?`Average · ${field.minimum}-${field.maximum} · latest ${field.latest}`:`平均值 · ${field.minimum}-${field.maximum} · 最近 ${field.latest}`}</small></article>)}
        {insights.choiceFields.map((field)=>{const total=field.values.reduce((sum,value)=>sum+value.count,0);return <article className="choice" key={field.fieldKey}><header><strong>{copy(field.name)}</strong><span>{english?`${total} record${total===1?"":"s"}`:`${total} 条记录`}</span></header><div role="list">{field.values.map((value)=>{const label=copy(value.label);return <p role="listitem" aria-label={english?`${label}: ${value.count} records`:`${label}：${value.count} 条记录`} data-zero={value.count===0} key={value.key}><span>{label}</span><i aria-hidden="true"><b style={{width:`${value.percentage}%`}}/></i><strong>{value.count}</strong></p>;})}</div></article>;})}
      </div></section>}
      {stats.total===0&&<div className="empty-state compact-empty"><h2>Patterns will appear here</h2><p>Record a few moments and the heatmap, rhythm and property summaries will grow naturally.</p></div>}
    </>}

    {tab==="timeline"&&<>
      {showEntry&&<TrackerEntryEditor trackerId={trackerId} fields={activeFields} onClose={()=>setShowEntry(false)} onSaved={()=>load()}/>}
      <section className="tracker-detail-section tracker-timeline-section"><div className="section-heading tracker-timeline-heading"><div><h2>{english?"Every record":"全部记录"}</h2><p>{filtersActive?(english?`${timelineEntries.length} of ${stats.total} records`:`显示 ${timelineEntries.length} / ${stats.total} 条记录`):(english?`${stats.total} record${stats.total===1?"":"s"}`:`${stats.total} 条记录`)}</p></div></div>
        <div className="tracker-timeline-toolbar"><div className="tracker-search"><Icon name="search"/><input type="search" aria-label={english?"Search records":"搜索记录"} value={query} onChange={event=>setQuery(event.target.value)} placeholder={english?"Search notes or property values":"搜索备注或属性值"}/></div>
          <div className="tracker-filters"><label><span>{english?"Time":"时间"}</span><select value={periodFilter} onChange={event=>setPeriodFilter(event.target.value as TimelinePeriod)}><option value="all">{english?"Any time":"全部时间"}</option><option value="7d">{english?"Last 7 days":"最近 7 天"}</option><option value="30d">{english?"Last 30 days":"最近 30 天"}</option><option value="year">{english?"This year":"今年"}</option></select></label>{detail.fields.length>0&&<label><span>{english?"Property":"属性"}</span><select value={fieldFilter} onChange={event=>{setFieldFilter(event.target.value);setFieldValueFilter("");}}><option value="">{english?"Any property":"全部属性"}</option>{detail.fields.map(field=><option value={field.key} key={field.key}>{field.name}{field.archivedAt?(english?" · Archived":" · 已归档"):""}</option>)}</select></label>}{selectedFilterField&&<FieldFilter field={selectedFilterField} value={fieldValueFilter} onChange={setFieldValueFilter}/>} {filtersActive&&<button type="button" onClick={()=>{setQuery("");setPeriodFilter("all");setFieldFilter("");setFieldValueFilter("");}}>{english?"Clear":"清除"}</button>}</div>
        </div>
        {timelineEntries.length?<div className="tracker-timeline-groups">{timelineGroups.map(group=><section className="tracker-timeline-day" key={group.date} aria-label={group.date}>
          <header><h3><time dateTime={group.date}>{new Date(group.date+'T12:00:00+08:00').toLocaleDateString(english?'en-US':'zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'short',day:'numeric',weekday:'short'})}</time></h3><span>{english?`${group.entries.length} record${group.entries.length===1?"":"s"}`:`${group.entries.length} 条记录`}</span></header>
          <div className="tracker-entry-list">{group.entries.map(entry=>{const values=Object.entries(entry.values).filter(([,value])=>value!==null&&value!==undefined&&value!==''&&(!Array.isArray(value)||value.length>0));return <article key={entry.id}>
            <div className="tracker-entry-time"><time dateTime={entry.occurredAt}>{new Date(entry.occurredAt).toLocaleTimeString(english?'en-US':'zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hourCycle:'h23'})}</time></div>
            <div className="tracker-entry-content">{values.length>0&&<div className="tracker-entry-values">{values.map(([key,value])=>{const field=detail.fields.find(item=>item.key===key||String(item.id)===key);return <span key={key}><small className="user-content">{field?.name??(english?"Archived property":"已归档属性")}{field?.archivedAt?(english?" · Archived":" · 已归档"):""}</small><strong className="user-content">{field?.type==="time_range"?formatTrackerTimeRange(value,english):typeof value==='boolean'?(value?(english?'Yes':'是'):(english?'No':'否')):shownValue(value)}{field?.type==='number'&&field.unit?` ${field.unit}`:''}</strong></span>;})}</div>}{entry.note&&<p className="user-content">{entry.note}</p>}{!values.length&&!entry.note&&<p className="tracker-quick-record">{english?'Moment recorded':'已记录此刻'}</p>}</div>
            <details className="tracker-entry-actions"><summary aria-label={english?'Record actions':'记录操作'}><More className="icon" weight="Outline" aria-hidden="true"/></summary><div><button type="button" disabled={working} onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');setError('');setConfirmation({title:english?'Delete record':'删除记录',message:english?'Permanently delete this record and its property values and note? This cannot be undone.':'永久删除这条记录及其属性值和备注？删除后无法恢复。',label:english?'Delete permanently':'确认永久删除',destructive:true,action:()=>request(`/api/trackers/${trackerId}/entries?entryId=${entry.id}`,{method:'DELETE'},english?'Record deleted.':'记录已删除。')});}}><Trash className="icon" weight="Outline" aria-hidden="true"/>{english?'Delete':'删除'}</button></div></details>
          </article>;})}</div></section>)}</div>:<div className="empty-state compact-empty"><h2>{filtersActive?(english?"No matching records":"没有匹配的记录"):(english?"No records yet":"暂无记录")}</h2><p>{filtersActive?(english?"Try a wider time range or clear one of the filters.":"尝试扩大时间范围或清除部分筛选条件。"):(english?"Use Record now when this happens.":"发生时立即记录即可。")}</p></div>}
      </section>
    </>}

    {tab==="settings"&&<div className="tracker-settings" onClickCapture={event=>{const target=event.target as HTMLElement;if(target.closest("button")){const menu=target.closest("details.tracker-setting-actions");if(menu instanceof HTMLDetailsElement)menu.open=false;}}} onKeyDown={event=>{if(event.key==="Escape"){const menu=(event.target as HTMLElement).closest("details.tracker-setting-actions");if(menu instanceof HTMLDetailsElement){event.preventDefault();event.stopPropagation();menu.open=false;menu.querySelector("summary")?.focus();}}}}>
      <section className="tracker-settings-section">
        <div className="section-heading"><h2>{english?"Basic information":"基本信息"}</h2><button className="text-button" disabled={working} onClick={()=>{setError("");setTrackerName(tracker.name);setTrackerGroup(tracker.groupName);setTrackerQuick(tracker.quickCaptureEnabled);setShowRename(true);}}>{english?"Edit":"编辑"}</button></div>
        <dl className="tracker-settings-summary"><div><dt>{english?"Name":"名称"}</dt><dd className="user-content">{tracker.name}</dd></div><div><dt>{english?"Group":"分组"}</dt><dd className="user-content">{tracker.groupName}</dd></div><div><dt>{english?"List + button":"首页 + 按钮"}</dt><dd>{tracker.quickCaptureEnabled?(english?"Quick record":"立即记录"):(english?"Open detailed form":"打开详细表单")}</dd></div></dl>
        <div className="tracker-icon-settings"><TrackerIcon tracker={tracker} size={64}/><div><strong>{english?"Tracker icon":"Tracker 图标"}</strong><small>{english?"JPG, PNG or WebP · up to 4 MB · cropped to a square":"JPG、PNG 或 WebP · 最大 4 MB · 裁剪为正方形"}</small><div><label className="button secondary">{english?"Choose image":"更换图片"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={working} onChange={event=>{void uploadIcon(event.target.files?.[0]);event.target.value="";}}/></label>{tracker.iconType==="image"&&<button className="text-button" disabled={working} onClick={()=>void request(`/api/trackers/${trackerId}/icon`,{method:"DELETE"},english?"Default icon restored.":"已恢复默认图标。")}>{english?"Restore default":"恢复默认图标"}</button>}</div></div></div>
        {showRename&&<FormSheet title={english?"Edit Tracker":"编辑 Tracker"} onClose={()=>setShowRename(false)} formId="tracker-basics-form" submitLabel={english?"Save changes":"保存修改"} busy={working}><form id="tracker-basics-form" className="editor-card compact-editor" onSubmit={renameTracker}>
          <label className="field"><span>{english?"Name":"名称"}</span><input required maxLength={80} value={trackerName} onChange={event=>setTrackerName(event.target.value)}/></label>
          <div className="field"><span>{english?"Group":"分组"}</span><SuggestedInput recommendationStyle="search" suggestionLabel={english?"Group":"分组"} suggestions={detail.groupNames??[tracker.groupName]} maxLength={60} value={trackerGroup} onValueChange={setTrackerGroup}/></div>
          <fieldset className="tracker-capture-mode"><legend>{english?"List + button":"首页 + 按钮"}</legend><label className={trackerQuick?"selected":""}><input type="radio" name="settings-capture" checked={trackerQuick} onChange={()=>setTrackerQuick(true)}/><span><strong>{english?"Quick record":"立即记录"}</strong><small>{english?"Save the current moment with one tap":"点击后直接保存当前时刻"}</small></span></label><label className={!trackerQuick?"selected":""}><input type="radio" name="settings-capture" checked={!trackerQuick} onChange={()=>setTrackerQuick(false)}/><span><strong>{english?"Detailed record":"详细记录"}</strong><small>{english?"Fill in time, properties and note":"填写时间、属性和备注后保存"}</small></span></label></fieldset>
          {error&&<p className="form-error">{error}</p>}
        </form></FormSheet>}
      </section>
      <section className="tracker-settings-section">
        <div className="section-heading"><h2>{english?"Record properties":"记录属性"}</h2><button className="text-button" disabled={working} onClick={()=>openField()}>{english?"Add property":"新增属性"}</button></div>
        <p className="tracker-settings-help">{english?"Archive keeps old values. Delete permanently removes this property and its historical values.":"归档会保留旧值；删除会永久移除该属性及其历史值。"}</p>
        {activeFields.length? <div className="tracker-setting-list">{activeFields.map(field=><article key={field.id}><div><strong className="user-content">{field.name}</strong><small>{fieldTypeLabel(field.type,english)}{field.unit?` · ${!english&&field.type==="time_range"?"分钟":field.unit}`:""}{field.required?(english?" · Required":" · 必填"):""}{field.includeInStats?(english?" · In Insights":" · 参与统计"):""}</small></div><details className="tracker-setting-actions"><summary aria-label={english?`Actions for ${field.name}`:`${field.name}的操作`}><More className="icon" weight="Outline" aria-hidden="true"/></summary><div><button disabled={working} onClick={()=>openField(field)}><Icon name="edit"/>{english?"Edit":"编辑"}</button><button disabled={working} onClick={()=>void setFieldArchived(field,true)}><ArchiveBox className="icon" weight="Outline" aria-hidden="true"/>{english?"Archive":"归档"}</button><button className="danger-text" disabled={working} onClick={()=>void removeField(field)}><Trash className="icon" weight="Outline" aria-hidden="true"/>{english?"Delete permanently":"永久删除"}</button></div></details></article>)}</div>:<p className="tracker-settings-empty">{english?"No active properties. Every record still includes its time and optional note.":"暂无使用中的属性。每条记录仍包含时间和可选备注。"}</p>}
        {detail.fields.some(field=>field.archivedAt)&&<details className="tracker-archived-properties"><summary>{english?"Archived properties":"已归档属性"} · {detail.fields.filter(field=>field.archivedAt).length}</summary><div className="tracker-setting-list">{detail.fields.filter(field=>field.archivedAt).map(field=><article key={field.id}><div><strong className="user-content">{field.name}</strong><small>{english?"Historical values preserved":"历史值已保留"}</small></div><div className="tracker-setting-row-actions"><button className="text-button" disabled={working} onClick={()=>void setFieldArchived(field,false)}>{english?"Restore":"恢复"}</button><button className="tracker-delete-button danger-text" disabled={working} onClick={()=>void removeField(field)}><Trash className="icon" weight="Outline" aria-hidden="true"/>{english?"Delete":"删除"}</button></div></article>)}</div></details>}
        {showField&&<FormSheet title={editingFieldId?(english?"Edit property":"编辑属性"):(english?"Add property":"新增属性")} onClose={()=>{setShowField(false);setEditingFieldId(null);setFieldDraft(emptyField);}} formId="tracker-field-form" submitLabel={english?"Save property":"保存属性"} busy={working}><form id="tracker-field-form" className="editor-card tracker-rule-form" onSubmit={addField}>
          <div className="form-grid"><label className="field"><span>{english?"Property name":"属性名称"}</span><input required maxLength={60} value={fieldDraft.name} onChange={event=>setFieldDraft({...fieldDraft,name:event.target.value})}/></label><label className="field"><span>{english?"Type":"类型"}</span><select disabled={editingFieldId!==null} value={fieldDraft.type} onChange={event=>{const type=event.target.value as TrackerFieldType;setFieldDraft({...fieldDraft,type,includeInStats:type!=="text"});}}>{fieldTypes.map(([value])=><option key={value} value={value}>{fieldTypeLabel(value,english)}</option>)}</select></label>
          {!editingFieldId&&["single_select","multi_select"].includes(fieldDraft.type)&&<label className="field wide"><span>{english?"Options, separated by commas":"选项，用逗号分隔"}</span><input required value={fieldDraft.options} onChange={event=>setFieldDraft({...fieldDraft,options:event.target.value})}/></label>}
          {!editingFieldId&&fieldDraft.type==="number"&&<><label className="field"><span>{english?"Unit":"单位"}</span><input maxLength={20} value={fieldDraft.unit} onChange={event=>setFieldDraft({...fieldDraft,unit:event.target.value})} placeholder="ml, kg, ¥…"/></label><label className="field"><span>{english?"Decimal places":"小数位数"}</span><input type="number" min="0" max="6" value={fieldDraft.precision} onChange={event=>setFieldDraft({...fieldDraft,precision:event.target.value})}/></label></>}</div>
          {editingFieldId&&<p className="tracker-settings-help">{english?"The type stays unchanged to preserve the meaning of historical values.":"为保留历史值的含义，已有属性的类型不可更改。"}</p>}
          <div className="tracker-inline-checks"><label><input type="checkbox" checked={fieldDraft.required} onChange={event=>setFieldDraft({...fieldDraft,required:event.target.checked})}/>{english?"Required in detailed records":"详细记录时必填"}</label>{fieldDraft.type!=="text"&&<label><input type="checkbox" checked={fieldDraft.includeInStats} onChange={event=>setFieldDraft({...fieldDraft,includeInStats:event.target.checked})}/>{english?"Include in Insights":"参与统计"}</label>}</div>
          {fieldDraft.type==="time_range"&&<p className="tracker-settings-help">{english?"Enter start and end dates and times; duration is calculated in minutes.":"填写开始与结束日期时间，自动计算分钟数，支持跨午夜。"}</p>}
          {error&&<p className="form-error">{error}</p>}
        </form></FormSheet>}
      </section>
      <section className="tracker-settings-section">
        <div className="section-heading"><h2>{english?"Record goals":"记录目标"}</h2><button className="text-button" disabled={working||Boolean(tracker.archivedAt)} onClick={()=>{setError("");setGoalDraft(emptyGoal);setRulePanel("goal");}}>{english?"Add goal":"新增目标"}</button></div>
        <p className="tracker-settings-help">{english?"Goals describe record counts; they do not send reminders.":"目标约定记录数量，不会发送提醒。"}</p>
        {detail.goals.length?<div className="tracker-setting-list">{detail.goals.map(goal=><article key={goal.id}><div><strong>{periodLabel(goal.periodType,english)} · {goal.operator==="<="?(english?"At most":"最多"):goal.operator===">="?(english?"At least":"至少"):(english?"Exactly":"恰好")} {goal.targetValue} {english?"records":"条记录"}</strong>{goal.periodType==="custom"&&<small className="user-content">{goal.customPeriod}</small>}</div><details className="tracker-setting-actions"><summary aria-label={english?"Goal actions":"目标操作"}><Icon name="more"/></summary><div><button className="danger-text" disabled={working} onClick={()=>{setError("");setConfirmation({title:english?"Delete goal":"删除目标",message:english?"Delete this goal? All records are kept.":"删除此目标？全部记录会保留。",label:english?"Delete":"确认删除",destructive:true,action:()=>request(`/api/trackers/${trackerId}/goals?goalId=${goal.id}`,{method:"DELETE"},english?"Goal deleted.":"目标已删除。")});}}>{english?"Delete":"删除"}</button></div></details></article>)}</div>:<p className="tracker-settings-empty">{english?"No goals set.":"暂未设置目标。"}</p>}
        {rulePanel==="goal"&&<FormSheet title={english?"Add goal":"新增目标"} onClose={()=>setRulePanel(null)} formId="tracker-goal-form" submitLabel={english?"Save goal":"保存目标"} busy={working}><form id="tracker-goal-form" className="editor-card tracker-rule-form" onSubmit={addGoal}><div className="form-grid"><label className="field"><span>{english?"Rule":"数量要求"}</span><select value={goalDraft.operator} onChange={event=>setGoalDraft({...goalDraft,operator:event.target.value as TrackerGoalOperator})}><option value="<=">{english?"At most":"最多"}</option><option value=">=">{english?"At least":"至少"}</option><option value="=">{english?"Exactly":"恰好"}</option></select></label><label className="field"><span>{english?"Records":"记录条数"}</span><input required type="number" min="1" step="1" value={goalDraft.targetValue} onChange={event=>setGoalDraft({...goalDraft,targetValue:event.target.value})}/></label><label className="field"><span>{english?"Period":"周期"}</span><select value={goalDraft.periodType} onChange={event=>setGoalDraft({...goalDraft,periodType:event.target.value as TrackerPeriodType})}>{(["daily","weekly","monthly","yearly","custom"]as TrackerPeriodType[]).map(period=><option key={period} value={period}>{periodLabel(period,english)}</option>)}</select></label>{goalDraft.periodType==="custom"&&<label className="field"><span>{english?"Custom period description":"自定义周期说明"}</span><input maxLength={200} value={goalDraft.customPeriod} onChange={event=>setGoalDraft({...goalDraft,customPeriod:event.target.value})}/></label>}</div>{error&&<p className="form-error">{error}</p>}</form></FormSheet>}
      </section>
      <section className="tracker-settings-section">
        <div className="section-heading"><h2>{english?"Reminders":"提醒"}</h2><button className="text-button" disabled={working||Boolean(tracker.archivedAt)} onClick={()=>{setError("");closeReminderSheet();setRulePanel("reminder");}}>{english?"Add reminder":"新增提醒"}</button></div>
        {detail.reminders.length?<div className="tracker-setting-list">{detail.reminders.map(reminder=><article key={reminder.id}><div><strong>{reminder.reminderMode==="missing"?(english?`No record in ${reminder.periodDays} days`:`${reminder.periodDays} 天内未记录时提醒`):(english?`Every ${reminder.periodDays} days`:`每 ${reminder.periodDays} 天提醒`)} · {reminder.configuredTime}</strong><small>{reminder.enabled?(english?`Next check: ${new Date(reminder.nextDueAt).toLocaleString('en-US',{timeZone:reminder.timezone,year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}`:`下次检查：${new Date(reminder.nextDueAt).toLocaleString('zh-CN',{timeZone:reminder.timezone,year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}`):(english?"Off":"已关闭")} · {reminder.timezone}</small><small>{reminder.reminderMode==="missing"?(english?"Skipped if this period has a record":"本周期已有记录时跳过提醒"):(english?"Sent even if already recorded":"本周期已有记录时仍会提醒")}</small></div><div className="tracker-setting-row-actions"><button className="tracker-reminder-toggle" role="switch" aria-checked={reminder.enabled} aria-label={english?`Reminder at ${reminder.configuredTime}`:`${reminder.configuredTime}的提醒`} disabled={working||Boolean(tracker.archivedAt)} onClick={()=>void toggleTrackerReminder(reminder)}>{reminder.enabled?(english?"On":"开启"):(english?"Off":"关闭")}</button><details className="tracker-setting-actions"><summary aria-label={english?"Reminder actions":"提醒操作"}><Icon name="more"/></summary><div><button disabled={working||Boolean(tracker.archivedAt)} onClick={()=>{setError("");editTrackerReminder(reminder);}}>{english?"Edit":"编辑"}</button><button className="danger-text" disabled={working} onClick={()=>{setError("");setConfirmation({title:english?"Delete reminder":"删除提醒",message:english?"Delete this reminder? All records are kept.":"删除此提醒？全部记录会保留。",label:english?"Delete":"确认删除",destructive:true,action:()=>request(`/api/trackers/${trackerId}/reminders?reminderId=${reminder.id}`,{method:"DELETE"},english?"Reminder deleted.":"提醒已删除。")});}}>{english?"Delete":"删除"}</button></div></details></div></article>)}</div>:<p className="tracker-settings-empty">{english?"No reminders set. Recording works without them.":"暂未设置提醒，不影响正常记录。"}</p>}
        {rulePanel==="reminder"&&<FormSheet title={editingReminderId?(english?"Edit reminder":"编辑提醒"):(english?"Add reminder":"新增提醒")} onClose={closeReminderSheet} formId="tracker-reminder-form" submitLabel={english?"Save reminder":"保存提醒"} busy={working}><form id="tracker-reminder-form" className="editor-card tracker-rule-form" onSubmit={addReminder}><label className="field"><span>{english?"Type":"提醒方式"}</span><select value={reminderDraft.reminderMode} onChange={event=>setReminderDraft({...reminderDraft,reminderMode:event.target.value as TrackerReminderMode})}><option value="standard">{english?"Regular reminder":"固定周期提醒"}</option><option value="missing">{english?"Remind only if missing":"未记录时提醒"}</option></select></label><div className="form-grid"><label className="field"><span>{reminderDraft.reminderMode==="missing"?(english?"Observation period (days)":"观察周期（天）"):(english?"Repeat every (days)":"间隔天数")}</span><input required type="number" min="1" max="999" step="1" value={reminderDraft.periodDays} onChange={event=>setReminderDraft({...reminderDraft,periodDays:event.target.value})}/></label><label className="field"><span>{english?"Reminder time":"提醒时间"}</span><input required type="time" value={reminderDraft.configuredTime} onChange={event=>setReminderDraft({...reminderDraft,configuredTime:event.target.value})}/></label><label className="field"><span>{english?"Period starts":"周期起点"}</span><input required type="date" value={reminderDraft.anchorDate} onChange={event=>setReminderDraft({...reminderDraft,anchorDate:event.target.value})}/></label></div><p className="tracker-settings-help">{reminderDraft.reminderMode==="missing"?(english?"A record in the observation period suppresses this reminder.":"观察周期内已有记录时，不发送提醒。"):(english?"This reminder is sent regardless of existing records.":"无论是否已有记录，都按周期发送提醒。")}</p>{error&&<p className="form-error">{error}</p>}</form></FormSheet>}
      </section>
      <section className="tracker-settings-section tracker-settings-lifecycle"><h2>{english?"Archive and delete":"归档与删除"}</h2><p className="tracker-settings-help">{english?"Archive preserves all history and disables reminders. Permanent deletion removes this Tracker and all its data.":"归档保留全部历史并关闭提醒；永久删除会移除此 Tracker 及其全部数据。"}</p><div className="tracker-setting-row-actions"><button className="button secondary" disabled={working} onClick={()=>void setTrackerArchived(!tracker.archivedAt)}>{tracker.archivedAt?(english?"Restore Tracker":"恢复 Tracker"):(english?"Archive Tracker":"归档 Tracker")}</button><button className="tracker-delete-button danger-text" disabled={working} onClick={()=>{setError("");setConfirmation({title:english?"Permanently delete Tracker":"永久删除 Tracker",message:english?`Delete “${tracker.name}” and all ${stats.total} records, properties, goals and reminders? This cannot be undone.`:`删除「${tracker.name}」及全部 ${stats.total} 条记录、属性、目标和提醒？删除后无法恢复。`,label:english?"Delete permanently":"确认永久删除",destructive:true,action:removeTracker});}}><Trash className="icon" weight="Outline" aria-hidden="true"/>{english?"Delete permanently":"永久删除 Tracker"}</button></div></section>
    </div>}

    {confirmation&&<FormSheet title={confirmation.title} onClose={()=>setConfirmation(null)} formId="tracker-confirmation-form" submitLabel={confirmation.label} busy={working} dirty={false}><form id="tracker-confirmation-form" className={confirmation.destructive?"tracker-settings-confirm destructive":"tracker-settings-confirm"} onSubmit={async event=>{event.preventDefault();if(working)return;const result=await confirmation.action();if(result!==false)setConfirmation(null);}}><p>{confirmation.message}</p>{error&&<p className="form-error">{error}</p>}</form></FormSheet>}
  </div>;
}

function TrackerHeatmap({insights}:{insights:TrackerInsights}) {
  const {english}=useLocale();
  const latestDate=insights.heatmap.at(-1)?.date??new Date().toISOString().slice(0,10);
  const latestMonth=latestDate.slice(0,7),earliestMonth=(insights.heatmap[0]?.date??latestDate).slice(0,7);
  const [month,setMonth]=useState(latestMonth);
  const calendar=trackerCalendarMonth(insights.heatmap,month,latestDate);
  const locale=english?"en-US":"zh-CN";
  const monthLabel=new Intl.DateTimeFormat(locale,{year:"numeric",month:"long",timeZone:"UTC"}).format(new Date(`${month}-15T12:00:00Z`));
  const weekdays=english?["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]:["一","二","三","四","五","六","日"];
  const summary=english?`${calendar.activeDays} active days · ${calendar.totalRecords} records`:`${calendar.activeDays} 个活跃日 · ${calendar.totalRecords} 条记录`;
  return <div className="tracker-heatmap-calendar">
    <header className="tracker-heatmap-toolbar"><div><strong>{monthLabel}</strong><span>{summary}</span></div><div>{month!==latestMonth&&<button type="button" onClick={()=>setMonth(latestMonth)}>{english?"This month":"本月"}</button>}<button type="button" aria-label={english?"Previous month":"上个月"} disabled={month<=earliestMonth} onClick={()=>setMonth(value=>shiftTrackerMonth(value,-1))}><ArrowLeft2 size={16} weight="Outline" aria-hidden="true"/></button><button type="button" aria-label={english?"Next month":"下个月"} disabled={month>=latestMonth} onClick={()=>setMonth(value=>shiftTrackerMonth(value,1))}><ArrowRight2 size={16} weight="Outline" aria-hidden="true"/></button></div></header>
    <div className="tracker-heatmap-weekdays" aria-hidden="true">{weekdays.map(day=><span key={day}>{day}</span>)}</div>
    <div className="tracker-heatmap" aria-label={english?`${monthLabel} activity calendar`:`${monthLabel}活动日历`}>{Array.from({length:calendar.leadingDays},(_,index)=><i className="blank" key={`blank-${index}`} aria-hidden="true"/>)}{calendar.days.map(day=>{const label=!day.available?(day.date>latestDate?(english?`${day.date}, future date`:`${day.date}，未来日期`):(english?`${day.date}, outside available history`:`${day.date}，超出可用历史范围`)):(english?`${day.date}, ${day.count} record${day.count===1?"":"s"}`:`${day.date}，${day.count} 条记录`);return <span className={`tracker-heatmap-cell level-${trackerHeatLevel(day.count)}`} data-today={day.date===latestDate} data-unavailable={!day.available} title={label} aria-label={label} key={day.date}><strong>{Number(day.date.slice(-2))}</strong>{day.available&&day.count>1&&<small>{english?`${day.count}×`:`${day.count}次`}</small>}</span>;})}</div>
    <div className="tracker-heatmap-legend" aria-label={english?"Records per day":"每日记录次数"}><span>{english?"Records":"次数"}</span>{[0,1,2,3,4].map(level=><span key={level}><i className={`level-${level}`}/><small>{level===4?"4+":level}</small></span>)}</div>
  </div>;
}

function BarChart({items}:{items:TrackerInsights["monthly"]}) {
  const {english}=useLocale();
  const maximum=Math.max(1,...items.map((item)=>item.count));
  return <div className="tracker-bars" role="list">{items.map((item)=>{const height=item.count?Math.max(8,item.count/maximum*82):0;return <div role="listitem" aria-label={english?`${item.label}: ${item.count} records`:`${item.label}：${item.count} 条记录`} key={item.key}><div className="tracker-bar-plot" style={{"--bar-height":`${height}%`} as CSSProperties}>{item.count>0&&<strong>{item.count}</strong>}<span aria-hidden="true"/></div><small>{item.label}</small></div>;})}</div>;
}

function FieldFilter({field,value,onChange}:{field:TrackerField;value:string;onChange:(value:string)=>void}){
  const {english,language}=useLocale();
  if(field.type==="time_range")return <label><span>{english?"Duration (min)":"时长（分钟）"}</span><input type="number" min="0" step="any" value={value} onChange={event=>onChange(event.target.value)} /></label>;
  if(field.type==="single_select"||field.type==="multi_select")return <label><span>{english?"Value":"值"}</span><select value={value} onChange={event=>onChange(event.target.value)}><option value="">{english?"Any value":"全部值"}</option>{field.options.map(option=><option className="user-content" value={option} key={option}>{translateUiCopy(option,language)}</option>)}</select></label>;
  if(field.type==="boolean")return <label><span>{english?"Value":"值"}</span><select value={value} onChange={event=>onChange(event.target.value)}><option value="">{english?"Any value":"全部值"}</option><option value="true">{english?"Yes":"是"}</option><option value="false">{english?"No":"否"}</option></select></label>;
  if(field.type==="rating")return <label><span>{english?"Rating":"评分"}</span><select value={value} onChange={event=>onChange(event.target.value)}><option value="">{english?"Any rating":"全部评分"}</option>{[1,2,3,4,5].map(score=><option value={score} key={score}>{english?`${score} stars`:`${score} 星`}</option>)}</select></label>;
  return <label><span>{field.type==="number"?(english?"Exact value":"精确值"):(english?"Contains":"包含")}</span><input type={field.type==="number"?"number":"search"} value={value} onChange={event=>onChange(event.target.value)} placeholder={field.type==="number"?field.unit||(english?"Value":"数值"):(english?"Text":"文本")}/></label>;
}
