"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState,type FormEvent } from "react";
import { currentLocalDate,dateTimePayload,DateTimeField } from "@/components/date-time-field";
import { FormSheet } from "@/components/form-sheet";
import { Icon } from "@/components/icons";
import { minorFromDecimal } from "@/lib/relations";
import type { PersonMemoryNote,RelationBalance,RelationEvent,RelationEventFlow,RelationPerson,RelationPersonSummary } from "@/lib/types";
import { RelationEventEditor } from "../relation-event-editor";
import { RelationPersonEditor } from "../relation-person-editor";

type Detail={person:RelationPerson;balance:RelationBalance;latestEvent:RelationEvent|null;lastMetAt:string|null;lastMetHasExplicitTime:boolean|null;events:RelationEvent[];memoryNotes:PersonMemoryNote[]};
const money=(value:number)=>`${value>=0?"+":"−"}¥${(Math.abs(value)/100).toFixed(2)}`;
const moneyPlain=(value:number)=>`¥${(value/100).toFixed(2)}`;
const labels:Record<string,string>={expense:"Expense",gift:"Gift",repayment:"Repayment",favor:"Favor",interaction:"Interaction",advance:"advanced for",treat:"treated",repayment_flow:"repaid",favor_flow:"helped",gift_flow:"gave"};
const closenessLabels:Record<number,string>={5:"Very close",4:"Close",3:"Regular",2:"Distant",1:"Very distant"};
function dateLabel(event:RelationEvent){const date=new Date(event.occurredAt);return event.occurredHasExplicitTime?date.toLocaleString():date.toLocaleDateString();}

function SettleEditor({flow,outstanding,onBusy,onSaved}:{flow:RelationEventFlow;outstanding:number;onBusy:(value:boolean)=>void;onSaved:()=>void}){
  const[amount,setAmount]=useState((outstanding/100).toFixed(2)),[date,setDate]=useState({date:currentLocalDate(),time:""}),[note,setNote]=useState(""),[error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();onBusy(true);setError("");try{const when=dateTimePayload(date),response=await fetch(`/api/relations/flows/${flow.id}/settle`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amountMinor:minorFromDecimal(amount),occurredAt:when.value,occurredHasExplicitTime:when.hasExplicitTime,note:note||null})});if(!response.ok)throw new Error((await response.json()).error);onSaved();}catch(reason){setError(reason instanceof Error?reason.message:"Could not record repayment");}finally{onBusy(false);}}
  return <form onSubmit={submit}><div className="form-grid"><label className="field"><span>Amount · CNY</span><input required inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></label><div className="wide"><DateTimeField label="Date" value={date} onChange={setDate}/></div><label className="field wide"><span>Note</span><textarea rows={3} value={note} onChange={event=>setNote(event.target.value)}/></label></div>{error&&<p className="form-error">{error}</p>}</form>;
}

export function RelationPersonView({initial,people}:{initial:Detail;people:RelationPersonSummary[]}){
  const router=useRouter();
  const[data,setData]=useState(initial),[panel,setPanel]=useState<"profile"|"event"|"note"|"settle"|null>(null),[editing,setEditing]=useState<RelationEvent>(),[settling,setSettling]=useState<{flow:RelationEventFlow;outstanding:number}>(),[busy,setBusy]=useState(false),[note,setNote]=useState("");
  async function load(){const response=await fetch(`/api/relations/people/${data.person.id}`);if(response.ok)setData(await response.json());}
  function openEvent(event?:RelationEvent){setEditing(event);setPanel("event");}
  async function removeEvent(id:number){if(!confirm("Delete this exchange?"))return;const response=await fetch(`/api/relations/events/${id}`,{method:"DELETE"});if(response.ok)void load();}
  async function addNote(){setBusy(true);const response=await fetch(`/api/relations/people/${data.person.id}/notes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:note})});setBusy(false);if(response.ok){setNote("");setPanel(null);void load();}}
  async function archive(){if(!confirm(`Archive ${data.person.name}?`))return;const response=await fetch(`/api/relations/people/${data.person.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({archivedAt:new Date().toISOString()})});if(response.ok)router.push("/relations");}
  const allFlows=data.events.flatMap(event=>event.flows);
  const openAdvances=allFlows.filter(flow=>flow.flowType==="advance").map(flow=>({flow,outstanding:flow.amountMinor-allFlows.filter(item=>item.flowType==="repayment"&&item.settlesFlowId===flow.id).reduce((sum,item)=>sum+item.amountMinor,0)})).filter(item=>item.outstanding>0);

  return <div className="page relation-detail-page"><Link href="/relations" className="back-link">← Relations</Link><header className="relation-profile-head"><div className="relation-profile-title"><span className="relation-avatar large">{data.person.photoPath?<span style={{backgroundImage:`url(${data.person.photoPath})`}}/>:<strong>{data.person.name.slice(0,1)}</strong>}</span><div><span className="eyebrow">{data.person.relationLabel??"RELATION"}</span><h1>{data.person.name}</h1>{data.person.nickname&&<p>{data.person.nickname}</p>}<div className="relation-profile-tags"><span>{data.person.relationshipStatus==="active"?"Current relationship":"Ended"}</span><span>{data.person.closenessRank?closenessLabels[data.person.closenessRank]:"Closeness not set"}</span></div></div></div><div className="page-actions"><button className="button secondary" onClick={()=>setPanel("profile")}><Icon name="edit"/>Profile</button><button className="button primary" onClick={()=>openEvent()}><Icon name="plus"/>Exchange</button></div></header>
  <section className="relation-summary" data-settlement={data.balance.settlementMinor!==0}><article><span>Social balance</span><strong>{money(data.balance.socialMinor)}</strong><p>Treats, gifts and valued favors. Kept separate from debt.</p></article>{data.balance.settlementMinor!==0&&<article className="relation-settlement-alert"><span>{data.balance.settlementMinor>0?"To collect":"To repay"}</span><strong>{money(data.balance.settlementMinor)}</strong><p>Outstanding advances and repayments that still need attention.</p></article>}</section>
  {openAdvances.length>0&&<section className="relation-open-advances"><span className="eyebrow">OPEN ADVANCES</span>{openAdvances.map(({flow,outstanding})=><article key={flow.id}><span>Outstanding {moneyPlain(outstanding)}</span><button className="button secondary compact" onClick={()=>{setSettling({flow,outstanding});setPanel("settle")}}>Record repayment</button></article>)}</section>}
  <section className="relation-profile-facts">{data.person.birthday&&<div><span>Birthday</span><p>{data.person.birthday}</p></div>}{data.person.likes&&<div><span>Likes</span><p>{data.person.likes}</p></div>}{data.person.avoid&&<div><span>Avoid</span><p>{data.person.avoid}</p></div>}{data.person.note&&<div><span>Notes</span><p>{data.person.note}</p></div>}</section>
  <section className="relation-section"><div className="section-heading"><div><span className="eyebrow">TIMELINE</span><p>Each group activity appears once.</p></div></div>{data.events.length?<div className="relation-timeline">{data.events.map(event=>{const self=event.parties.find(party=>party.partyType==="self"),person=event.parties.find(party=>party.personId===data.person.id),relevant=event.flows.filter(flow=>self&&person&&((flow.fromPartyId===self.id&&flow.toPartyId===person.id)||(flow.fromPartyId===person.id&&flow.toPartyId===self.id)));return <article key={event.id}><div className="relation-time"><time>{dateLabel(event)}</time><span>{labels[event.eventType]}</span></div><div className="relation-event-card"><div><h3>{event.title}</h3>{event.totalAmountMinor!==null&&<b>{moneyPlain(event.totalAmountMinor)}</b>}</div>{event.note&&<p>{event.note}</p>}<details><summary>Amounts and flows</summary>{event.eventType==="expense"&&<dl>{event.parties.map(party=><div key={party.id}><dt>{party.partyType==="self"?"Me":people.find(item=>item.id===party.personId)?.name??`#${party.personId}`}</dt><dd>Share {moneyPlain(party.shareAmountMinor!)} · Paid {moneyPlain(party.paidAmountMinor!)}</dd></div>)}</dl>}{event.items.length>0&&<ul>{event.items.map(item=><li key={item.id}>{item.label}<b>{moneyPlain(item.amountMinor)}</b></li>)}</ul>}<ul>{relevant.map(flow=><li key={flow.id}>{flow.fromPartyId===self?.id?"Me":data.person.name} {labels[flow.flowType]??flow.flowType} {flow.toPartyId===self?.id?"me":data.person.name}<b>{moneyPlain(flow.amountMinor)}</b></li>)}</ul></details><div className="relation-event-actions"><button onClick={()=>openEvent(event)}><Icon name="edit"/>Edit</button><button className="danger" onClick={()=>void removeEvent(event.id)}><Icon name="trash"/>Delete</button></div></div></article>})}</div>:<p className="project-empty-line">No exchanges yet.</p>}</section>
  <section className="relation-section"><div className="section-heading"><div><span className="eyebrow">MEMORY NOTES</span><p>Small details worth remembering.</p></div><button className="text-button" onClick={()=>setPanel("note")}><Icon name="plus"/>Add note</button></div><div className="relation-note-list">{data.memoryNotes.map(item=><article key={item.id}><p>{item.content}</p><time>{new Date(item.createdAt).toLocaleDateString()}</time></article>)}</div></section>
  <button className="text-button danger relation-archive" onClick={()=>void archive()}>Archive person</button>
  {panel==="profile"&&<FormSheet title="Edit profile" onClose={()=>setPanel(null)} submitLabel="Save profile" busy={busy}><RelationPersonEditor editing={data.person} onBusy={setBusy} onSaved={()=>{setPanel(null);void load();}}/></FormSheet>}
  {panel==="event"&&<FormSheet title={editing?"Edit exchange":"Record an exchange"} onClose={()=>{setPanel(null);setEditing(undefined)}} submitLabel={editing?"Save changes":"Save exchange"} busy={busy}><RelationEventEditor people={people} editing={editing} initialPersonId={data.person.id} onBusy={setBusy} onSaved={()=>{setPanel(null);setEditing(undefined);void load();}}/></FormSheet>}
  {panel==="note"&&<FormSheet title="Memory note" onClose={()=>setPanel(null)} submitLabel="Save note" busy={busy}><form onSubmit={event=>{event.preventDefault();void addNote()}}><label className="field"><span>What should you remember?</span><textarea required rows={6} value={note} onChange={event=>setNote(event.target.value)}/></label></form></FormSheet>}
  {panel==="settle"&&settling&&<FormSheet title="Record repayment" onClose={()=>setPanel(null)} submitLabel="Save repayment" busy={busy}><SettleEditor {...settling} onBusy={setBusy} onSaved={()=>{setPanel(null);setSettling(undefined);void load();}}/></FormSheet>}</div>;
}
