"use client";
import Link from "next/link";
import type { FormEvent } from "react";
import { useState } from "react";
import { Icon } from "@/components/icons";
import type { CatMeasurement,CatMedication,CatRecordKind,CatTimelineEntry,Pet,Reminder } from "@/lib/types";
import { CatRecordEditor } from "../cat-record-editor";
import { CatAvatar } from "../cats-view";
import { ReminderEditor } from "../reminder-editor";
type Detail={pet:Pet;timeline:CatTimelineEntry[];reminders:Reminder[];medications:CatMedication[];measurements:CatMeasurement[]};type Tab="timeline"|"health"|"routine"|"profile";
const health=new Set(["symptom","vet_visit","medication","measurement"]);
export function PetDetailView({initial}:{initial:Detail}){const[detail,setDetail]=useState(initial);const[tab,setTab]=useState<Tab>("timeline");const[editor,setEditor]=useState<"record"|"reminder"|null>(null);const[editing,setEditing]=useState<{kind:CatRecordKind;id:number;record:Record<string,unknown>}|undefined>();const[expanded,setExpanded]=useState<string|null>(null);const[recordDetails,setRecordDetails]=useState<Record<string,Record<string,unknown>>>({});const[error,setError]=useState("");async function load(){const response=await fetch(`/api/cats/pets/${detail.pet.id}`);if(response.ok)setDetail(await response.json());}async function edit(item:CatTimelineEntry){const response=await fetch(`/api/cats/records/${item.kind}/${item.id}`);if(!response.ok)return;setEditing({kind:item.kind,id:item.id,record:await response.json()});setEditor("record");}async function toggle(item:CatTimelineEntry){const key=`${item.kind}-${item.id}`;if(expanded===key){setExpanded(null);return;}setExpanded(key);if(recordDetails[key])return;const response=await fetch(`/api/cats/records/${item.kind}/${item.id}`);if(response.ok){const record=await response.json() as Record<string,unknown>;setRecordDetails(current=>({...current,[key]:record}));}}async function remove(item:CatTimelineEntry){if(!confirm(`Delete “${item.title}”?`))return;const response=await fetch(`/api/cats/records/${item.kind}/${item.id}`,{method:"DELETE"});if(response.ok)void load();else setError((await response.json()).error);}const visible=tab==="timeline"?detail.timeline:tab==="health"?detail.timeline.filter(i=>health.has(i.kind)):detail.timeline.filter(i=>i.kind==="event");return <div className="page pet-detail-page"><Link className="back-link" href="/cats">← Cats</Link><header className="pet-profile-head"><CatAvatar pet={detail.pet} size={66}/><div><span className="eyebrow">CAT</span><h1>{detail.pet.name}</h1>{!detail.pet.isActive&&<small>Archived</small>}</div><div className="page-actions">{detail.pet.isActive&&<button className="button secondary" onClick={()=>setEditor("reminder")}>Reminder</button>}{detail.pet.isActive&&<button className="button primary" onClick={()=>{setEditing(undefined);setEditor("record")}}><Icon name="plus"/>New record</button>}</div></header><nav className="cat-tabs" aria-label="Cat sections">{(["timeline","health","routine","profile"] as Tab[]).map(value=><button key={value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</nav>
{editor==="record"&&<CatRecordEditor pets={[detail.pet]} initialPetId={detail.pet.id} editing={editing} onCancel={()=>{setEditor(null);setEditing(undefined)}} onSaved={()=>{setEditor(null);setEditing(undefined);void load();}}/>}{editor==="reminder"&&<ReminderEditor pets={[detail.pet]} initialPetId={detail.pet.id} onCancel={()=>setEditor(null)} onSaved={()=>{setEditor(null);void load();}}/>}
{tab!=="profile"?<section className="cat-timeline">{visible.length?visible.map(item=>{const key=`${item.kind}-${item.id}`;return <article key={key} className={expanded===key?"expanded":""}><button className="cat-timeline-main" onClick={()=>void toggle(item)}><time><strong>{new Date(item.occurredAt).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</strong><span>{new Date(item.occurredAt).toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit"})}</span></time><span><small>{item.eventType.replaceAll("_"," ")}</small><strong>{item.title}</strong>{item.summary&&<p>{item.summary}</p>}</span></button>{expanded===key&&<><RecordDetails record={recordDetails[key]}/><div className="cat-record-actions"><button onClick={()=>void edit(item)}><Icon name="edit"/>Edit</button><button className="danger" onClick={()=>void remove(item)}><Icon name="trash"/>Delete</button></div></>}</article>}):<div className="cats-inline-empty">No records</div>}</section>:<ProfileEditor detail={detail} onChanged={updated=>setDetail({...detail,pet:updated})}/>} {tab==="routine"&&<ReminderList reminders={detail.reminders} onChanged={()=>void load()}/>} {error&&<p className="form-error">{error}</p>}</div>}

function RecordDetails({record}:{record?:Record<string,unknown>}){if(!record)return <p className="cat-record-loading">Loading…</p>;const hidden=new Set(["id","petId","createdAt","updatedAt"]);const rows=Object.entries(record).filter(([key,value])=>!hidden.has(key)&&value!==null&&value!==""&&value!==undefined);return <dl className="cat-record-details">{rows.map(([key,value])=><div key={key}><dt>{key.replace(/([A-Z])/g," $1").replaceAll("_"," ")}</dt><dd>{typeof value==="boolean"?(value?"Yes":"No"):Array.isArray(value)?value.join(", "):String(value)}</dd></div>)}</dl>}

function ReminderList({reminders,onChanged}:{reminders:Reminder[];onChanged:()=>void}){async function remove(id:number){if(!confirm("Delete this reminder?"))return;const response=await fetch(`/api/reminders/${id}`,{method:"DELETE"});if(response.ok)onChanged();}if(!reminders.length)return null;return <section className="pet-reminders"><div className="section-heading compact"><span className="eyebrow">REMINDERS</span></div>{reminders.map(item=><article key={item.id}><div><strong>{item.title}</strong><small>{item.scheduleType.replace("_"," ")} · {item.nextDueAt?new Date(item.nextDueAt).toLocaleString():"Inactive"}</small></div><button className="danger-icon" onClick={()=>void remove(item.id)}><Icon name="trash"/></button></article>)}</section>}
function ProfileEditor({detail,onChanged}:{detail:Detail;onChanged:(pet:Pet)=>void}){const[draft,setDraft]=useState(detail.pet);const[error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();const response=await fetch(`/api/cats/pets/${detail.pet.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});if(response.ok)onChanged(await response.json());else setError((await response.json()).error);}async function archive(){if(!confirm(`Archive ${detail.pet.name}? Historical records will remain.`))return;const response=await fetch(`/api/cats/pets/${detail.pet.id}`,{method:"DELETE"});if(response.ok)onChanged({...draft,isActive:false});}return <form className="editor-card pet-profile-form" onSubmit={submit}><div className="form-grid"><label className="field"><span>Name</span><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field"><span>Avatar URL</span><input value={draft.avatarUrl} onChange={e=>setDraft({...draft,avatarUrl:e.target.value})}/></label><label className="field"><span>Sex</span><select value={draft.sex??""} onChange={e=>setDraft({...draft,sex:e.target.value as Pet["sex"]||null})}><option value="">Not set</option><option value="female">Female</option><option value="male">Male</option><option value="unknown">Unknown</option></select></label><label className="field"><span>Birthday</span><input type="date" value={draft.birthday??""} onChange={e=>setDraft({...draft,birthday:e.target.value||null})}/></label><label className="field"><span>Adoption date</span><input type="date" value={draft.adoptionDate??""} onChange={e=>setDraft({...draft,adoptionDate:e.target.value||null})}/></label><label className="field wide"><span>Notes</span><textarea rows={4} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="page-actions"><button className="button primary">Save profile</button>{draft.isActive&&<button type="button" className="button danger" onClick={()=>void archive()}>Archive cat</button>}</div></form>}
