"use client";

import Link from "next/link";
import type { FormEvent } from "react";
import { useState } from "react";
import { Icon } from "@/components/icons";
import { FormSheet } from "@/components/form-sheet";
import type { CatMeasurement, CatMedication, CatRecordKind, CatRoutine, CatTimelineEntry, Pet, Reminder } from "@/lib/types";
import { CatRecordEditor } from "../cat-record-editor";
import { CatAvatar, routineCadence, routineDueLabel, routineDueState, routineLastDoneLabel } from "../cats-view";
import { ReminderEditor } from "../reminder-editor";
import { RoutineEditor } from "../routine-editor";

type Detail = { pet: Pet; timeline: CatTimelineEntry[]; reminders: Reminder[]; routines: CatRoutine[]; medications: CatMedication[]; measurements: CatMeasurement[] };
type Tab = "timeline" | "health" | "routine" | "profile";
const health = new Set(["symptom", "vet_visit", "medication", "measurement"]);

function timelineType(item: CatTimelineEntry) { return item.eventType.replaceAll("_", " ").replace(/\b\w/g, value => value.toUpperCase()); }

export function PetDetailView({ initial }: { initial: Detail }) {
  const [detail, setDetail] = useState(initial); const [tab, setTab] = useState<Tab>("timeline"); const [editor, setEditor] = useState<"record" | "care" | "reminder" | "routine" | null>(null); const [editing, setEditing] = useState<{ kind: CatRecordKind; id: number; record: Record<string, unknown> }>(); const [editingRoutine, setEditingRoutine] = useState<CatRoutine>(); const [editingReminder, setEditingReminder] = useState<Reminder>(); const [expanded, setExpanded] = useState<string | null>(null); const [recordDetails, setRecordDetails] = useState<Record<string, Record<string, unknown>>>({}); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [sheetBusy, setSheetBusy] = useState(false);
  async function load() { const response = await fetch(`/api/cats/pets/${detail.pet.id}`); if (response.ok) setDetail(await response.json()); }
  async function edit(item: CatTimelineEntry) { const response = await fetch(`/api/cats/records/${item.kind}/${item.id}`); if (!response.ok) return; setEditing({ kind: item.kind, id: item.id, record: await response.json() }); setEditor("record"); }
  async function toggle(item: CatTimelineEntry) { const key = `${item.kind}-${item.id}`; if (expanded === key) { setExpanded(null); return; } setExpanded(key); if (recordDetails[key]) return; const response = await fetch(`/api/cats/records/${item.kind}/${item.id}`); if (response.ok) { const record = await response.json(); setRecordDetails(current => ({ ...current, [key]: record })); } }
  async function remove(item: CatTimelineEntry) { if (!confirm(`Delete “${item.title}”?`)) return; const response = await fetch(`/api/cats/records/${item.kind}/${item.id}`, { method: "DELETE" }); if (response.ok) void load(); else setError((await response.json()).error); }
  async function routineAction(routine: CatRoutine, action: "complete" | "delete") { if (action === "delete" && !confirm(`Delete routine “${routine.title}”? Records will remain.`)) return; const response = await fetch(`/api/cats/routines/${routine.id}${action === "complete" ? "/complete" : ""}`, { method: action === "complete" ? "POST" : "DELETE" }); if (response.ok) { setMessage(action === "complete" ? "Routine completed" : "Routine deleted"); await load(); } else setError((await response.json()).error); }
  async function reminderAction(reminder:Reminder,action:"complete"|"cancel"){if(action==="cancel"&&!confirm(`Cancel “${reminder.title}”?`))return;const response=await fetch(`/api/reminders/${reminder.id}${action==="complete"?"/complete":""}`,{method:action==="complete"?"POST":"DELETE"});if(response.ok){setMessage(action==="complete"?"One-time task completed":"One-time task cancelled");await load();}else setError((await response.json()).error);}
  const visible = tab === "timeline" ? detail.timeline : detail.timeline.filter(item => health.has(item.kind));
  return <div className="page pet-detail-page"><Link className="back-link" href="/cats">← Cats</Link><header className="pet-profile-head"><CatAvatar pet={detail.pet} size={66}/><div><span className="eyebrow">CAT</span><h1>{detail.pet.name}</h1>{!detail.pet.isActive && <small>Archived</small>}</div><div className="page-actions">{detail.pet.isActive && <button className="button secondary" onClick={() => setEditor("care")}><Icon name="plus"/>Add care</button>}{detail.pet.isActive && <button className="button primary" onClick={() => { setEditing(undefined); setEditor("record"); }}><Icon name="plus"/>New record</button>}</div></header><nav className="cat-tabs" aria-label="Cat sections">{(["timeline", "health", "routine", "profile"] as Tab[]).map(value => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{value[0].toUpperCase() + value.slice(1)}</button>)}</nav>
    {message && <p className="success-banner" role="status">{message}</p>}
    {editor === "record" && <FormSheet title={editing ? "Edit record" : "New record"} onClose={() => { setEditor(null); setEditing(undefined); }} submitLabel={editing ? "Save changes" : "Save record"} busy={sheetBusy}><CatRecordEditor pets={[detail.pet]} initialPetId={detail.pet.id} editing={editing} onSavingChange={setSheetBusy} onCancel={() => { setEditor(null); setEditing(undefined); }} onSaved={async saved => { if (editing) { const key = `${editing.kind}-${editing.id}`; setRecordDetails(current => ({ ...current, [key]: saved })); } await load(); setEditor(null); setEditing(undefined); setMessage(editing ? "Record updated" : "Record saved"); }}/></FormSheet>}
    {editor === "routine" && <FormSheet title={editingRoutine ? "Edit routine" : "Add routine"} onClose={() => { setEditor(null); setEditingRoutine(undefined); }} submitLabel="Save routine" busy={sheetBusy}><RoutineEditor pets={[detail.pet]} initialPetId={detail.pet.id} initialScope="cat" editing={editingRoutine} onSavingChange={setSheetBusy} onCancel={() => { setEditor(null); setEditingRoutine(undefined); }} onSaved={value => { setEditor(null); setEditingRoutine(undefined); setMessage(value); void load(); }}/></FormSheet>}
    {editor === "care" && <FormSheet title="What kind of care?" onClose={() => setEditor(null)}><section className="editor-card care-choice"><div className="editor-title"><div><span className="eyebrow">ADD CARE</span><h2>What kind of care?</h2></div><button type="button" className="text-button" onClick={() => setEditor(null)}>Cancel</button></div><div className="care-choice-grid"><button type="button" onClick={() => { setEditingReminder(undefined); setEditor("reminder"); }}><strong>One-time</strong><span>Do once on a specific date</span></button><button type="button" onClick={() => { setEditingRoutine(undefined); setEditor("routine"); }}><strong>Routine</strong><span>Repeat on a schedule</span></button></div></section></FormSheet>}
    {editor === "reminder" && <FormSheet title={editingReminder ? "Edit one-time task" : "Do once"} onClose={() => { setEditor(null); setEditingReminder(undefined); }} submitLabel={editingReminder ? "Save changes" : "Save one-time task"} busy={sheetBusy}><ReminderEditor pets={[detail.pet]} initialPetId={detail.pet.id} editing={editingReminder} onSavingChange={setSheetBusy} onCancel={() => { setEditor(null); setEditingReminder(undefined); }} onSaved={() => { setEditor(null); setEditingReminder(undefined); setMessage(editingReminder ? "One-time task updated" : "One-time task created"); void load(); }}/></FormSheet>}
    {(tab === "timeline" || tab === "health") && (
      <Timeline items={visible} expanded={expanded} recordDetails={recordDetails} onToggle={toggle} onEdit={edit} onRemove={remove}/>
    )}
    {tab === "routine" && (
      <><OneTimeTasks items={detail.reminders.filter(item=>item.scheduleType==="one_time"&&item.sourceType!=="cat_routine"&&item.isActive&&item.nextDueAt)} onEdit={item=>{setEditingReminder(item);setEditor("reminder");}} onComplete={item=>void reminderAction(item,"complete")} onCancel={item=>void reminderAction(item,"cancel")}/><RoutineTab routines={detail.routines} records={detail.timeline.filter(item => item.kind === "event" && item.metadata.sourceType === "cat_routine")} onComplete={routine => void routineAction(routine, "complete")} onEdit={routine => { setEditingRoutine(routine); setEditor("routine"); }} onDelete={routine => void routineAction(routine, "delete")}/></>
    )}
    {tab === "profile" && <ProfileSection detail={detail} onChanged={pet => setDetail({ ...detail, pet })}/>} {error && <p className="form-error">{error}</p>}
  </div>;
}

function OneTimeTasks({items,onEdit,onComplete,onCancel}:{items:Reminder[];onEdit:(item:Reminder)=>void;onComplete:(item:Reminder)=>void;onCancel:(item:Reminder)=>void}){if(!items.length)return null;return <section className="pet-one-time"><div className="section-heading compact"><span className="eyebrow">ONE-TIME</span></div><div className="cats-one-time-list">{items.map(item=><article key={item.id}><div><strong>{item.title}</strong><small>{new Date(item.nextDueAt!).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}{item.dueHasExplicitTime?` · ${new Date(item.nextDueAt!).toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit"})}`:" · Date only"}</small></div><div className="routine-card-actions"><button className="text-button" onClick={()=>onEdit(item)}>Edit</button><button className="text-button danger" onClick={()=>onCancel(item)}>Cancel</button><button className="button primary compact" onClick={()=>onComplete(item)}>Done</button></div></article>)}</div></section>}

function Timeline({ items, expanded, recordDetails, onToggle, onEdit, onRemove }: { items: CatTimelineEntry[]; expanded: string | null; recordDetails: Record<string, Record<string, unknown>>; onToggle: (item: CatTimelineEntry) => void; onEdit: (item: CatTimelineEntry) => void; onRemove: (item: CatTimelineEntry) => void }) { return <section className="cat-timeline">{items.length ? items.map(item => { const key = `${item.kind}-${item.id}`; const type = timelineType(item); const showType = type.localeCompare(item.title.trim(), undefined, { sensitivity: "accent" }) !== 0; return <article key={key} className={expanded === key ? "expanded" : ""}><button className="cat-timeline-main" onClick={() => void onToggle(item)}><time><strong>{new Date(item.occurredAt).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</strong>{item.occurredHasExplicitTime && <span>{new Date(item.occurredAt).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</span>}</time><span>{showType && <small>{type}</small>}<strong>{item.title}</strong>{item.summary && <p>{item.summary}</p>}</span></button>{expanded === key && <><RecordDetails record={recordDetails[key]}/><div className="cat-record-actions"><button onClick={() => void onEdit(item)}><Icon name="edit"/>Edit</button><button className="danger" onClick={() => void onRemove(item)}><Icon name="trash"/>Delete</button></div></>}</article>; }) : <div className="cats-inline-empty">No records</div>}</section>; }

function RoutineTab({ routines, records, onComplete, onEdit, onDelete }: { routines: CatRoutine[]; records: CatTimelineEntry[]; onComplete: (routine: CatRoutine) => void; onEdit: (routine: CatRoutine) => void; onDelete: (routine: CatRoutine) => void }) {
  return <div className="routine-tab"><section className="pet-routine-list">{routines.length ? routines.map(routine => {
    const state = routineDueState(routine.nextDueAt);
    const lastDone = routine.lastCompletedAt ?? records.find(item => String(item.metadata.sourceId) === String(routine.id))?.occurredAt;
    return <article key={routine.id} className={`routine-status-card ${state} ${!routine.enabled ? "disabled" : ""}`}>
      <div className="routine-card-copy"><div className="routine-card-heading"><strong>{routine.title}</strong><span className={`routine-due ${state}`}>{routineDueLabel(routine.nextDueAt)}</span></div><small className="routine-meta">{routineCadence(routine)} · {routineLastDoneLabel(lastDone)}</small></div>
      <div className="routine-card-actions"><button className="text-button" onClick={() => onEdit(routine)}>Edit</button><button className="danger-icon" title="Delete routine" onClick={() => onDelete(routine)}><Icon name="trash"/></button>{routine.enabled && <button className="button primary compact" onClick={() => onComplete(routine)}>Done</button>}</div>
    </article>;
  }) : <div className="cats-inline-empty">No routines yet</div>}</section><section className="routine-records"><div className="section-heading compact"><span className="eyebrow">RECENT RECORDS</span></div>{records.length ? records.slice(0, 10).map(item => <article key={item.id}><div><strong>{item.title}</strong><small>{new Date(item.occurredAt).toLocaleString()}</small></div></article>) : <p className="empty-copy">Completed routines will appear here.</p>}</section></div>;
}

function RecordDetails({ record }: { record?: Record<string, unknown> }) { if (!record) return <p className="cat-record-loading">Loading…</p>; const hidden = new Set(["id", "petId", "createdAt", "updatedAt", "sourceType", "sourceId"]); const rows = Object.entries(record).filter(([key, value]) => !hidden.has(key) && value !== null && value !== "" && value !== undefined); return <dl className="cat-record-details">{rows.map(([key, value]) => <div key={key}><dt>{key.replace(/([A-Z])/g, " $1").replaceAll("_", " ")}</dt><dd>{typeof value === "boolean" ? (value ? "Yes" : "No") : Array.isArray(value) ? value.join(", ") : String(value)}</dd></div>)}</dl>; }

function age(birthday: string | null) { if (!birthday) return "Not set"; const born = new Date(`${birthday}T00:00:00`); const now = new Date(); let years = now.getFullYear() - born.getFullYear(); if (now < new Date(now.getFullYear(), born.getMonth(), born.getDate())) years--; return `${years} year${years === 1 ? "" : "s"}`; }
function ProfileSection({ detail, onChanged }: { detail: Detail; onChanged: (pet: Pet) => void }) { const [editing, setEditing] = useState(false); const [uploading, setUploading] = useState(false); async function upload(file?: File) { if (!file) return; setUploading(true); const form = new FormData(); form.set("file", file); const response = await fetch(`/api/cats/pets/${detail.pet.id}/avatar`, { method: "POST", body: form }); setUploading(false); if (response.ok) onChanged(await response.json()); } async function reset() { const response = await fetch(`/api/cats/pets/${detail.pet.id}/avatar`, { method: "DELETE" }); if (response.ok) onChanged(await response.json()); } if (editing) return <ProfileEditor detail={detail} onChanged={pet => { onChanged(pet); setEditing(false); }} onCancel={() => setEditing(false)}/>; const pet = detail.pet; return <section className="pet-profile-view"><div className="pet-profile-identity"><div className="pet-photo-control"><CatAvatar pet={pet} size={88}/><label aria-label="Change photo">{uploading ? "…" : <Icon name="edit"/>}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={event => { void upload(event.target.files?.[0]); event.target.value = ""; }}/></label></div><div><h2>{pet.name}</h2><p>{pet.sex ? pet.sex[0].toUpperCase() + pet.sex.slice(1) : "Sex not set"}</p>{pet.avatarUrl && <button className="text-button" onClick={() => void reset()}>Remove photo</button>}</div></div><dl><div><dt>Birthday</dt><dd>{pet.birthday ? new Date(`${pet.birthday}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "Not set"}</dd></div><div><dt>Adoption date</dt><dd>{pet.adoptionDate ? new Date(`${pet.adoptionDate}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "Not set"}</dd></div><div><dt>Age</dt><dd>{age(pet.birthday)}</dd></div></dl><div className="profile-notes"><span className="eyebrow">NOTES</span><p>{pet.notes || "No notes yet."}</p></div><button className="button primary" onClick={() => setEditing(true)}>Edit profile</button>{pet.isActive && <div className="danger-zone"><span className="eyebrow">DANGER ZONE</span><p>Archive this cat while keeping all historical records.</p><ArchiveButton detail={detail} onChanged={onChanged}/></div>}</section>; }

function ArchiveButton({ detail, onChanged }: { detail: Detail; onChanged: (pet: Pet) => void }) { async function archive() { if (!confirm(`Archive ${detail.pet.name}? Historical records will remain.`)) return; const response = await fetch(`/api/cats/pets/${detail.pet.id}`, { method: "DELETE" }); if (response.ok) onChanged({ ...detail.pet, isActive: false }); } return <button type="button" className="text-button danger" onClick={() => void archive()}>Archive cat</button>; }
function ProfileEditor({ detail, onChanged, onCancel }: { detail: Detail; onChanged: (pet: Pet) => void; onCancel: () => void }) { const [draft, setDraft] = useState(detail.pet); const [error, setError] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/cats/pets/${detail.pet.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); if (response.ok) onChanged(await response.json()); else setError((await response.json()).error); } return <form className="editor-card pet-profile-form" onSubmit={submit}><div className="editor-title"><div><span className="eyebrow">PROFILE</span><h2>Edit profile</h2></div><button type="button" className="text-button" onClick={onCancel}>Cancel</button></div><div className="form-grid"><label className="field"><span>Name</span><input required value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })}/></label><label className="field"><span>Sex</span><select value={draft.sex ?? ""} onChange={e => setDraft({ ...draft, sex: e.target.value as Pet["sex"] || null })}><option value="">Not set</option><option value="female">Female</option><option value="male">Male</option><option value="unknown">Unknown</option></select></label><label className="field"><span>Birthday</span><input type="date" value={draft.birthday ?? ""} onChange={e => setDraft({ ...draft, birthday: e.target.value || null })}/></label><label className="field"><span>Adoption date</span><input type="date" value={draft.adoptionDate ?? ""} onChange={e => setDraft({ ...draft, adoptionDate: e.target.value || null })}/></label><label className="field wide"><span>Notes</span><textarea rows={4} value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })}/></label></div>{error && <p className="form-error">{error}</p>}<button className="button primary">Save profile</button></form>; }
