import "server-only";

import * as sqlite from "../db";
import type { EvaOrbitRepository } from "./types";

/**
 * Local development and migration fallback. Production selects the Supabase
 * repository and never writes durable data to Vercel's filesystem.
 */
export const sqliteRepository: EvaOrbitRepository = {
  async listTasks(filter) { return sqlite.listTasks(filter); },
  async getTask(id) { return sqlite.getTask(id); },
  async createTask(input) { return sqlite.createTask(input); },
  async updateTask(id, input) { return sqlite.updateTask(id, input); },
  async deleteTask(id) { return sqlite.deleteTask(id); },
  async listMemories(query, category) { return sqlite.listMemories(query, category); },
  async getMemory(id) { return sqlite.getMemory(id); },
  async createMemory(input) { return sqlite.createMemory(input); },
  async updateMemory(id, input) { return sqlite.updateMemory(id, input); },
  async deleteMemory(id) { return sqlite.deleteMemory(id); },
  async getDashboardSummary() { return sqlite.getDashboardSummary(); },
  async getUiPreferences() { return sqlite.getUiPreferences(); },
  async updateHomeModuleOrder(order) { return sqlite.updateHomeModuleOrder(order); },
  async getAiSettings() { return sqlite.getAiSettings(); },
  async updateAiSettings(input) { return sqlite.updateAiSettings(input); },
  async updateChatPreferences(input) { return sqlite.updateChatPreferences(input); },
  async getAiRuntimeSettings(modelConfigId) { return sqlite.getAiRuntimeSettings(modelConfigId); },
  async listAiProviders() { return sqlite.listAiProviders(); },
  async getAiProvider(id) { return sqlite.getAiProvider(id); },
  async createAiProvider(input) { return sqlite.createAiProvider(input); },
  async updateAiProvider(id, input) { return sqlite.updateAiProvider(id, input); },
  async deleteAiProvider(id) { return sqlite.deleteAiProvider(id); },
  async createAiModelConfig(providerId, input) { return sqlite.createAiModelConfig(providerId, input); },
  async updateAiModelConfig(id, input) { return sqlite.updateAiModelConfig(id, input); },
  async deleteAiModelConfig(id) { return sqlite.deleteAiModelConfig(id); },
  async listChatSessions() { return sqlite.listChatSessions(); },
  async getChatSession(id) { return sqlite.getChatSession(id); },
  async createChatSession(title, modelConfigId) { return sqlite.createChatSession(title, modelConfigId); },
  async updateChatSession(id, input) { return sqlite.updateChatSession(id, input); },
  async deleteChatSession(id) { return sqlite.deleteChatSession(id); },
  async listChatMessages(sessionId) { return sqlite.listChatMessages(sessionId); },
  async addChatMessage(sessionId, role, content, model, providerId, modelConfigId) { return sqlite.addChatMessage(sessionId, role, content, model, providerId, modelConfigId); },
  async autoTitleChatSession(id, content) { sqlite.autoTitleChatSession(id, content); },
  async listInbox(status) { return sqlite.listInbox(status); },
  async getInboxItem(id) { return sqlite.getInboxItem(id); },
  async createInboxItem(input) { return sqlite.createInboxItem(input); },
  async updateInboxItem(id, input) { return sqlite.updateInboxItem(id, input); },
  async deleteInboxItem(id) { return sqlite.deleteInboxItem(id); },
  async listFoodLogs(input) { return sqlite.listFoodLogs(input); },
  async getFoodLog(id) { return sqlite.getFoodLog(id); },
  async createFoodLog(input) { return sqlite.createFoodLog(input); },
  async updateFoodLog(id, input) { return sqlite.updateFoodLog(id, input); },
  async deleteFoodLog(id) { return sqlite.deleteFoodLog(id); },
  async searchFoodLibrary(query, brand) { return sqlite.searchFoodLibrary(query, brand); },
  async getFoodLibraryItem(id) { return sqlite.getFoodLibraryItem(id); },
  async upsertFoodLibraryItem(input) { return sqlite.upsertFoodLibraryItem(input); },
  async updateFoodLibraryItem(id, input) { return sqlite.updateFoodLibraryItem(id, input); },
  async removeFoodLibraryItem(id) { return sqlite.removeFoodLibraryItem(id); },
  async listDrinkLogs(input) { return sqlite.listDrinkLogs(input); },
  async getDrinkLog(id) { return sqlite.getDrinkLog(id); },
  async createDrinkLog(input) { return sqlite.createDrinkLog(input); },
  async updateDrinkLog(id, input) { return sqlite.updateDrinkLog(id, input); },
  async deleteDrinkLog(id) { return sqlite.deleteDrinkLog(id); },
  async listDrinkLimits() { return sqlite.listDrinkLimits(); },
  async createDrinkLimit(input) { return sqlite.createDrinkLimit(input); },
  async updateDrinkLimit(id, input) { return sqlite.updateDrinkLimit(id, input); },
  async deleteDrinkLimit(id) { return sqlite.deleteDrinkLimit(id); },
  async listTrackers() { return sqlite.listTrackers(); },
  async getTracker(id) { return sqlite.getTracker(id); },
  async createTracker(input) { return sqlite.createTracker(input); },
  async updateTracker(id, input) { return sqlite.updateTracker(id, input); },
  async deleteTracker(id) { return sqlite.deleteTracker(id); },
  async listTrackerFields(trackerId) { return sqlite.listTrackerFields(trackerId); },
  async createTrackerField(input) { return sqlite.createTrackerField(input); },
  async deleteTrackerField(id) { return sqlite.deleteTrackerField(id); },
  async listTrackerEntries(trackerId, input) { return sqlite.listTrackerEntries(trackerId, input); },
  async getTrackerEntry(id) { return sqlite.getTrackerEntry(id); },
  async createTrackerEntry(input) { return sqlite.createTrackerEntry(input); },
  async updateTrackerEntry(id, input) { return sqlite.updateTrackerEntry(id, input); },
  async deleteTrackerEntry(id) { return sqlite.deleteTrackerEntry(id); },
  async listTrackerGoals(trackerId) { return sqlite.listTrackerGoals(trackerId); },
  async createTrackerGoal(input) { return sqlite.createTrackerGoal(input); },
  async deleteTrackerGoal(id) { return sqlite.deleteTrackerGoal(id); },
  async listTrackerReminders(trackerId) { return sqlite.listTrackerReminders(trackerId); },
  async createTrackerReminder(input) { return sqlite.createTrackerReminder(input); },
  async deleteTrackerReminder(id) { return sqlite.deleteTrackerReminder(id); },
  async listPets(includeInactive) { return sqlite.listPets(includeInactive); },
  async getPet(id) { return sqlite.getPet(id); }, async createPet(input) { return sqlite.createPet(input); }, async updatePet(id,input) { return sqlite.updatePet(id,input); }, async archivePet(id) { return sqlite.archivePet(id); },
  async listCatEvents(petId) { return sqlite.listCatEvents(petId); }, async getCatEvent(id) { return sqlite.getCatEvent(id); }, async createCatEvent(input) { return sqlite.createCatEvent(input); }, async updateCatEvent(id,input) { return sqlite.updateCatEvent(id,input); }, async deleteCatEvent(id) { return sqlite.deleteCatEvent(id); },
  async listCatSymptoms(petId) { return sqlite.listCatSymptoms(petId); }, async getCatSymptom(id) { return sqlite.getCatSymptom(id); }, async createCatSymptom(input) { return sqlite.createCatSymptom(input); }, async updateCatSymptom(id,input) { return sqlite.updateCatSymptom(id,input); }, async deleteCatSymptom(id) { return sqlite.deleteCatSymptom(id); },
  async listCatVetVisits(petId) { return sqlite.listCatVetVisits(petId); }, async getCatVetVisit(id) { return sqlite.getCatVetVisit(id); }, async createCatVetVisit(input) { return sqlite.createCatVetVisit(input); }, async updateCatVetVisit(id,input) { return sqlite.updateCatVetVisit(id,input); }, async deleteCatVetVisit(id) { return sqlite.deleteCatVetVisit(id); },
  async listCatMedications(petId) { return sqlite.listCatMedications(petId); }, async getCatMedication(id) { return sqlite.getCatMedication(id); }, async createCatMedication(input) { return sqlite.createCatMedication(input); }, async updateCatMedication(id,input) { return sqlite.updateCatMedication(id,input); }, async deleteCatMedication(id) { return sqlite.deleteCatMedication(id); },
  async listCatMeasurements(petId) { return sqlite.listCatMeasurements(petId); }, async getCatMeasurement(id) { return sqlite.getCatMeasurement(id); }, async createCatMeasurement(input) { return sqlite.createCatMeasurement(input); }, async updateCatMeasurement(id,input) { return sqlite.updateCatMeasurement(id,input); }, async deleteCatMeasurement(id) { return sqlite.deleteCatMeasurement(id); },
  async listReminders(input) { return sqlite.listReminders(input); }, async getReminder(id) { return sqlite.getReminder(id); }, async createReminder(input) { return sqlite.createReminder(input); }, async updateReminder(id,input) { return sqlite.updateReminder(id,input); }, async deleteReminder(id) { return sqlite.deleteReminder(id); }, async createReminderOccurrence(input) { return sqlite.createReminderOccurrence(input); },
  async listPushSubscriptions() { return sqlite.listPushSubscriptions(); }, async upsertPushSubscription(input) { return sqlite.upsertPushSubscription(input); }, async deletePushSubscription(endpoint) { return sqlite.deletePushSubscription(endpoint); },
  async getNutritionSettings(date) { return sqlite.getNutritionSettings(date); },
  async updateNutritionSettings(date, input) { sqlite.updateNutritionSettings(date, input); },
};
