import "server-only";

import * as sqlite from "../db";
import type { EvaOrbitRepository } from "./types";

/**
 * Local development and migration fallback. Production selects the Supabase
 * repository and never writes durable data to Vercel's filesystem.
 */
export const sqliteRepository: EvaOrbitRepository = {
  async listRelationPeople(input){return sqlite.listRelationPeople(input);},async getRelationPerson(id){return sqlite.getRelationPerson(id);},async createRelationPerson(input){return sqlite.createRelationPerson(input);},async updateRelationPerson(id,input){return sqlite.updateRelationPerson(id,input);},
  async listRelationEvents(input){return sqlite.listRelationEvents(input);},async getRelationEvent(id){return sqlite.getRelationEvent(id);},async createRelationEvent(input){return sqlite.createRelationEvent(input);},async updateRelationEvent(id,input){return sqlite.updateRelationEvent(id,input);},async deleteRelationEvent(id){return sqlite.deleteRelationEvent(id);},
  async listPersonMemoryNotes(personId){return sqlite.listPersonMemoryNotes(personId);},async getPersonMemoryNote(id){return sqlite.getPersonMemoryNote(id);},async createPersonMemoryNote(personId,content){return sqlite.createPersonMemoryNote(personId,content);},async updatePersonMemoryNote(id,content){return sqlite.updatePersonMemoryNote(id,content);},async deletePersonMemoryNote(id){return sqlite.deletePersonMemoryNote(id);},
  async listTasks(filter) { return sqlite.listTasks(filter); },
  async getTask(id) { return sqlite.getTask(id); },
  async createTask(input) { return sqlite.createTask(input); },
  async updateTask(id, input) { return sqlite.updateTask(id, input); },
  async deleteTask(id) { return sqlite.deleteTask(id); },
  async listMemories(query, category) { return sqlite.listMemories(query, category); },
  async getMemory(id) { return sqlite.getMemory(id); },
  async createMemory(input) { return sqlite.createMemory(input); },
  async updateMemory(id, input) { return sqlite.updateMemory(id, input); },
  async deleteMemory(id) { return sqlite.deleteMemory(id); },
  async getDashboardSummary() { return sqlite.getDashboardSummary(); },
  async getUiPreferences() { return sqlite.getUiPreferences(); },
  async updateHomeModuleOrder(order) { return sqlite.updateHomeModuleOrder(order); },
  async updateAppearancePreferences(input) { return sqlite.updateAppearancePreferences(input); },
  async getAiSettings() { return sqlite.getAiSettings(); },
  async updateAiSettings(input) { return sqlite.updateAiSettings(input); },
  async updateChatPreferences(input) { return sqlite.updateChatPreferences(input); },
  async getAiRuntimeSettings(modelConfigId) { return sqlite.getAiRuntimeSettings(modelConfigId); },
  async listAiProviders() { return sqlite.listAiProviders(); },
  async getAiProvider(id) { return sqlite.getAiProvider(id); },
  async createAiProvider(input) { return sqlite.createAiProvider(input); },
  async updateAiProvider(id, input) { return sqlite.updateAiProvider(id, input); },
  async deleteAiProvider(id) { return sqlite.deleteAiProvider(id); },
  async createAiModelConfig(providerId, input) { return sqlite.createAiModelConfig(providerId, input); },
  async updateAiModelConfig(id, input) { return sqlite.updateAiModelConfig(id, input); },
  async deleteAiModelConfig(id) { return sqlite.deleteAiModelConfig(id); },
  async listChatSessions() { return sqlite.listChatSessions(); },
  async getChatSession(id) { return sqlite.getChatSession(id); },
  async createChatSession(title, modelConfigId) { return sqlite.createChatSession(title, modelConfigId); },
  async updateChatSession(id, input) { return sqlite.updateChatSession(id, input); },
  async deleteChatSession(id) { return sqlite.deleteChatSession(id); },
  async listChatMessages(sessionId) { return sqlite.listChatMessages(sessionId); },
  async addChatMessage(sessionId, role, content, model, providerId, modelConfigId) { return sqlite.addChatMessage(sessionId, role, content, model, providerId, modelConfigId); },
  async autoTitleChatSession(id, content) { sqlite.autoTitleChatSession(id, content); },
  async listInbox(status) { return sqlite.listInbox(status); },
  async getInboxItem(id) { return sqlite.getInboxItem(id); },
  async createInboxItem(input) { return sqlite.createInboxItem(input); },
  async updateInboxItem(id, input) { return sqlite.updateInboxItem(id, input); },
  async deleteInboxItem(id) { return sqlite.deleteInboxItem(id); },
  async listFoodLogs(input) { return sqlite.listFoodLogs(input); },
  async getFoodLog(id) { return sqlite.getFoodLog(id); },
  async createFoodLog(input) { return sqlite.createFoodLog(input); },
  async updateFoodLog(id, input) { return sqlite.updateFoodLog(id, input); },
  async deleteFoodLog(id) { return sqlite.deleteFoodLog(id); },
  async searchFoodLibrary(query, brand, options) { return sqlite.searchFoodLibrary(query, brand, options); },
  async getFoodLibraryItem(id) { return sqlite.getFoodLibraryItem(id); },
  async upsertFoodLibraryItem(input) { return sqlite.upsertFoodLibraryItem(input); },
  async updateFoodLibraryItem(id, input) { return sqlite.updateFoodLibraryItem(id, input); },
  async removeFoodLibraryItem(id) { return sqlite.removeFoodLibraryItem(id); },
  async listHealthRecords(input) { return sqlite.listHealthRecords(input); },
  async getHealthRecord(id) { return sqlite.getHealthRecord(id); },
  async createHealthRecord(input) { return sqlite.createHealthRecord(input); },
  async updateHealthRecord(id, input) { return sqlite.updateHealthRecord(id, input); },
  async deleteHealthRecord(id) { return sqlite.deleteHealthRecord(id); },
  async listTrainingLogs(input) { return sqlite.listTrainingLogs(input); },
  async getTrainingLog(id) { return sqlite.getTrainingLog(id); },
  async createTrainingLog(input) { return sqlite.createTrainingLog(input); },
  async updateTrainingLog(id, input) { return sqlite.updateTrainingLog(id, input); },
  async deleteTrainingLog(id) { return sqlite.deleteTrainingLog(id); },
  async listMediaItems(input) { return sqlite.listMediaItems(input); },
  async listMediaSeries() { return sqlite.listMediaSeries(); },
  async getMediaSeries(id) { return sqlite.getMediaSeries(id); },
  async createMediaSeries(name) { return sqlite.createMediaSeries(name); },
  async getMediaItem(id) { return sqlite.getMediaItem(id); },
  async createMediaItem(input) { return sqlite.createMediaItem(input); },
  async updateMediaItem(id, input) { return sqlite.updateMediaItem(id, input); },
  async deleteMediaItem(id) { return sqlite.deleteMediaItem(id); },
  async listMediaViewings(mediaId) { return sqlite.listMediaViewings(mediaId); },
  async getMediaViewing(id) { return sqlite.getMediaViewing(id); },
  async createMediaViewing(input) { return sqlite.createMediaViewing(input); },
  async updateMediaViewing(id, watchedDate) { return sqlite.updateMediaViewing(id, watchedDate); },
  async deleteMediaViewing(id) { return sqlite.deleteMediaViewing(id); },
  async listChronicleEntries(input) { return sqlite.listChronicleEntries(input); },
  async getChronicleEntry(id) { return sqlite.getChronicleEntry(id); },
  async createChronicleEntry(input) { return sqlite.createChronicleEntry(input); },
  async updateChronicleEntry(id, input) { return sqlite.updateChronicleEntry(id, input); },
  async deleteChronicleEntry(id) { return sqlite.deleteChronicleEntry(id); },
  async listProjects(input) { return sqlite.listProjects(input); },
  async getProject(id) { return sqlite.getProject(id); },
  async createProject(input) { return sqlite.createProject(input); },
  async updateProject(id, input) { return sqlite.updateProject(id, input); },
  async listProjectItems(input) { return sqlite.listProjectItems(input); },
  async getProjectItem(id) { return sqlite.getProjectItem(id); },
  async createProjectItem(input) { return sqlite.createProjectItem(input); },
  async updateProjectItem(id, input) { return sqlite.updateProjectItem(id, input); },
  async listMemos(input) { return sqlite.listMemos(input); },
  async getMemo(id) { return sqlite.getMemo(id); },
  async createMemo(input) { return sqlite.createMemo(input); },
  async updateMemo(id, input) { return sqlite.updateMemo(id, input); },
  async deleteMemo(id) { return sqlite.deleteMemo(id); },
  async listLuciusDiaryEntries(input) { return sqlite.listLuciusDiaryEntries(input); },
  async getLuciusDiaryEntry(id) { return sqlite.getLuciusDiaryEntry(id); },
  async createLuciusDiaryEntry(input) { return sqlite.createLuciusDiaryEntry(input); },
  async updateLuciusDiaryEntry(id, input) { return sqlite.updateLuciusDiaryEntry(id, input); },
  async deleteLuciusDiaryEntry(id) { return sqlite.deleteLuciusDiaryEntry(id); },
  async listLuciusCases(input) { return sqlite.listLuciusCases(input); },
  async getLuciusCase(id) { return sqlite.getLuciusCase(id); },
  async createLuciusCase(input) { return sqlite.createLuciusCase(input); },
  async updateLuciusCase(id, input) { return sqlite.updateLuciusCase(id, input); },
  async deleteLuciusCase(id) { return sqlite.deleteLuciusCase(id); },
  async recordLuciusCaseRecurrence(id, occurredDate) { return sqlite.recordLuciusCaseRecurrence(id, occurredDate); },
  async getLuciusState() { return sqlite.getLuciusState(); },
  async updateLuciusState(input) { return sqlite.updateLuciusState(input); },
  async listLuciusPosts(input) { return sqlite.listLuciusPosts(input); },
  async getLuciusPost(id) { return sqlite.getLuciusPost(id); },
  async createLuciusPost(input) { return sqlite.createLuciusPost(input); },
  async updateLuciusPost(id, input) { return sqlite.updateLuciusPost(id, input); },
  async deleteLuciusPost(id) { return sqlite.deleteLuciusPost(id); },
  async listDrinkLogs(input) { return sqlite.listDrinkLogs(input); },
  async getDrinkLog(id) { return sqlite.getDrinkLog(id); },
  async createDrinkLog(input) { return sqlite.createDrinkLog(input); },
  async updateDrinkLog(id, input) { return sqlite.updateDrinkLog(id, input); },
  async deleteDrinkLog(id) { return sqlite.deleteDrinkLog(id); },
  async listDrinkLimits() { return sqlite.listDrinkLimits(); },
  async createDrinkLimit(input) { return sqlite.createDrinkLimit(input); },
  async updateDrinkLimit(id, input) { return sqlite.updateDrinkLimit(id, input); },
  async deleteDrinkLimit(id) { return sqlite.deleteDrinkLimit(id); },
  async listTrackers() { return sqlite.listTrackers(); },
  async getTracker(id) { return sqlite.getTracker(id); },
  async createTracker(input) { return sqlite.createTracker(input); },
  async updateTracker(id, input) { return sqlite.updateTracker(id, input); },
  async deleteTracker(id) { return sqlite.deleteTracker(id); },
  async listTrackerFields(trackerId) { return sqlite.listTrackerFields(trackerId); },
  async createTrackerField(input) { return sqlite.createTrackerField(input); },
  async deleteTrackerField(id) { return sqlite.deleteTrackerField(id); },
  async listTrackerEntries(trackerId, input) { return sqlite.listTrackerEntries(trackerId, input); },
  async getTrackerEntry(id) { return sqlite.getTrackerEntry(id); },
  async createTrackerEntry(input) { return sqlite.createTrackerEntry(input); },
  async updateTrackerEntry(id, input) { return sqlite.updateTrackerEntry(id, input); },
  async deleteTrackerEntry(id) { return sqlite.deleteTrackerEntry(id); },
  async listTrackerGoals(trackerId) { return sqlite.listTrackerGoals(trackerId); },
  async createTrackerGoal(input) { return sqlite.createTrackerGoal(input); },
  async deleteTrackerGoal(id) { return sqlite.deleteTrackerGoal(id); },
  async listTrackerReminders(trackerId) { return sqlite.listTrackerReminders(trackerId); },
  async createTrackerReminder(input) { return sqlite.createTrackerReminder(input); },
  async deleteTrackerReminder(id) { return sqlite.deleteTrackerReminder(id); },
  async listPets(includeInactive) { return sqlite.listPets(includeInactive); },
  async getPet(id) { return sqlite.getPet(id); }, async createPet(input) { return sqlite.createPet(input); }, async updatePet(id,input) { return sqlite.updatePet(id,input); }, async archivePet(id) { return sqlite.archivePet(id); },
  async listCatEvents(petId) { return sqlite.listCatEvents(petId); }, async getCatEvent(id) { return sqlite.getCatEvent(id); }, async createCatEvent(input) { return sqlite.createCatEvent(input); }, async updateCatEvent(id,input) { return sqlite.updateCatEvent(id,input); }, async deleteCatEvent(id) { return sqlite.deleteCatEvent(id); },
  async listCatSymptoms(petId) { return sqlite.listCatSymptoms(petId); }, async getCatSymptom(id) { return sqlite.getCatSymptom(id); }, async createCatSymptom(input) { return sqlite.createCatSymptom(input); }, async updateCatSymptom(id,input) { return sqlite.updateCatSymptom(id,input); }, async deleteCatSymptom(id) { return sqlite.deleteCatSymptom(id); },
  async listCatVetVisits(petId) { return sqlite.listCatVetVisits(petId); }, async getCatVetVisit(id) { return sqlite.getCatVetVisit(id); }, async createCatVetVisit(input) { return sqlite.createCatVetVisit(input); }, async updateCatVetVisit(id,input) { return sqlite.updateCatVetVisit(id,input); }, async deleteCatVetVisit(id) { return sqlite.deleteCatVetVisit(id); },
  async listCatMedications(petId) { return sqlite.listCatMedications(petId); }, async getCatMedication(id) { return sqlite.getCatMedication(id); }, async createCatMedication(input) { return sqlite.createCatMedication(input); }, async updateCatMedication(id,input) { return sqlite.updateCatMedication(id,input); }, async deleteCatMedication(id) { return sqlite.deleteCatMedication(id); },
  async listCatMeasurements(petId) { return sqlite.listCatMeasurements(petId); }, async getCatMeasurement(id) { return sqlite.getCatMeasurement(id); }, async createCatMeasurement(input) { return sqlite.createCatMeasurement(input); }, async updateCatMeasurement(id,input) { return sqlite.updateCatMeasurement(id,input); }, async deleteCatMeasurement(id) { return sqlite.deleteCatMeasurement(id); },
  async listCatRoutines(input) { return sqlite.listCatRoutines(input); }, async getCatRoutine(id) { return sqlite.getCatRoutine(id); }, async createCatRoutine(input) { return sqlite.createCatRoutine(input); }, async updateCatRoutine(id,input) { return sqlite.updateCatRoutine(id,input); }, async archiveCatRoutine(id) { return sqlite.archiveCatRoutine(id); },
  async listReminders(input) { return sqlite.listReminders(input); }, async getReminder(id) { return sqlite.getReminder(id); }, async createReminder(input) { return sqlite.createReminder(input); }, async updateReminder(id,input) { return sqlite.updateReminder(id,input); }, async deleteReminder(id) { return sqlite.deleteReminder(id); }, async createReminderOccurrence(input) { return sqlite.createReminderOccurrence(input); },
  async listNotificationDeliveries(limit) { return sqlite.listNotificationDeliveries(limit); }, async createNotificationDelivery(input) { return sqlite.createNotificationDelivery(input); },
  async listPushSubscriptions() { return sqlite.listPushSubscriptions(); }, async upsertPushSubscription(input) { return sqlite.upsertPushSubscription(input); }, async deletePushSubscription(endpoint) { return sqlite.deletePushSubscription(endpoint); },
  async getNutritionSettings(date) { return sqlite.getNutritionSettings(date); },
  async listNutritionSettings(limit) { return sqlite.listNutritionSettings(limit); },
  async updateNutritionSettings(date, input) { sqlite.updateNutritionSettings(date, input); },
};
