import type { AiModelConfig, AiProvider, AiSettings, CatEvent, CatMeasurement, CatMedication, CatRoutine, CatSymptom, CatVetVisit, ChatMessage, ChatPreferences, ChatRole, ChatSession, ChronicleEntry, ChronicleSource, DashboardSummary, DailyNutritionSummary, DrinkLimit, DrinkLog, FoodLibraryItem, FoodLog, HealthRecord, HealthRecordStatus, HealthRecordType, InboxItem, InboxStatus, LuciusCase, LuciusCaseErrorType, LuciusCaseSeverity, LuciusCaseStatus, LuciusDiaryEntry, MediaItem, MediaRating, MediaSeries, MediaStatus, MediaType, MediaViewing, Memo, MemoStatus, MemoType, Memory, NotificationDelivery, PersonMemoryNote, Pet, Project, ProjectItem, ProjectItemStatus, ProjectItemType, ProjectStatus, PushSubscriptionRecord, RelationEvent, RelationPerson, Reminder, ReminderOccurrence, Task, Tracker, TrackerEntry, TrackerField, TrackerGoal, TrackerReminder, TrainingLog, UiPreferences } from "../types";
import type { RelationEventInput } from "../relations";
import type { HomeModuleId } from "../home-modules";

export type TaskFilter = "all" | "open" | "done";

export type NewTask = {
  title: string;
  notes: string;
  dueDate: string | null;
  priority: string;
  tags: string[];
};

export type AiSettingsInput = ChatPreferences & {
  providerPreset: string;
  providerName: string;
  baseUrl: string;
  apiKey?: string;
  clearApiKey: boolean;
  model: string;
  enabled: boolean;
  temperature: number;
  systemPrompt: string;
  responseLength: "brief" | "balanced" | "detailed";
  initiative: "quiet" | "balanced" | "active";
  allowSuggestions: boolean;
  allowTeasing: boolean;
  includeTasks: boolean;
  includeMemories: boolean;
  allowWriteActions: boolean;
};

export type InternalAiSettings = AiSettings & { apiKey: string; providerId: number | null; modelConfigId: number | null };
export type InternalAiProvider = Omit<AiProvider, "models" | "hasApiKey" | "maskedApiKey"> & { apiKey: string };
export type AiProviderInput = { name: string; providerType: string; baseUrl: string; enabled: boolean; apiKey?: string; clearApiKey: boolean };
export type AiModelConfigInput = { modelId: string; displayName: string; enabled: boolean; isDefault: boolean; capabilities: Record<string, unknown> };

export type NewInboxItem = Pick<InboxItem, "content" | "source">;
export type NewFoodLog = Omit<FoodLog, "id" | "createdAt" | "updatedAt">;
export type NewFoodLibraryItem = Omit<FoodLibraryItem, "id" | "archivedAt" | "updatedAt">;
export type FoodLibrarySearchOptions = { name?: string; category?: FoodLibraryItem["category"]; limit?: number };
export type FoodLibraryRemoval = { id: number; action: "deleted" | "archived" };
export type NewHealthRecord = Omit<HealthRecord, "id" | "createdAt" | "updatedAt">;
export type HealthRecordListInput = { status?: HealthRecordStatus; type?: HealthRecordType; from?: string; to?: string; limit?: number };
export type NewTrainingLog = Omit<TrainingLog, "id" | "createdAt" | "updatedAt">;
export type TrainingLogPatch = Partial<NewTrainingLog>;
export type TrainingLogListInput = { from?: string; to?: string; limit?: number };
export type NewMediaItem = Pick<MediaItem, "title" | "originalTitle" | "translatedTitle" | "mediaType" | "status" | "rating" | "isFavorite" | "note" | "coverUrl" | "seriesId" | "seasonNumber" | "seasonTitle">;
export type NewMediaDraft = Omit<NewMediaItem,"title">;
export type MediaListInput = { query?: string; mediaType?: MediaType; status?: MediaStatus; rating?: MediaRating; seriesId?: number; favorite?: boolean; rewatched?: boolean; limit?: number };
export type MediaItemPatch = { title?: string; originalTitle?: string | null; translatedTitle?: string | null; mediaType?: MediaType; status?: MediaStatus; rating?: MediaRating | null; isFavorite?: boolean; note?: string | null; coverUrl?: string | null; seriesId?: number | null; seasonNumber?: number | null; seasonTitle?: string | null };
export type MediaDraftPatch = Omit<MediaItemPatch,"title">;
export type NewChronicleEntry = Pick<ChronicleEntry, "date" | "title" | "contentMd" | "source">;
export type ChronicleListInput = { query?: string; limit?: number };
export type ChronicleEntryPatch = { date?: string; title?: string; contentMd?: string; source?: ChronicleSource };
export type NewMemo = Omit<Memo, "id" | "createdAt" | "updatedAt">;
export type MemoPatch = Partial<NewMemo>;
export type MemoListInput = { query?: string; tag?: string; type?: MemoType; status?: MemoStatus; limit?: number };
export type NewProject = Pick<Project, "name" | "description" | "status">;
export type ProjectPatch = Partial<NewProject>;
export type ProjectListInput = { query?: string; status?: ProjectStatus; limit?: number };
export type NewProjectItem = Omit<ProjectItem, "id" | "projectName" | "createdAt" | "startedAt" | "completedAt" | "verifiedAt" | "updatedAt">;
export type ProjectItemPatch = Partial<Omit<NewProjectItem, "projectId">> & { projectId?: number };
export type ProjectItemListInput = { query?: string; projectId?: number; project?: string; status?: ProjectItemStatus; type?: ProjectItemType; module?: string; limit?: number };
export type NewLuciusDiaryEntry = Omit<LuciusDiaryEntry, "id" | "createdAt" | "updatedAt">;
export type LuciusDiaryPatch = Partial<NewLuciusDiaryEntry>;
export type LuciusDiaryListInput = { query?: string; tag?: string; limit?: number };
export type NewLuciusCase = Omit<LuciusCase, "id" | "createdAt" | "updatedAt">;
export type LuciusCasePatch = Partial<NewLuciusCase>;
export type LuciusCaseListInput = { query?: string; errorType?: LuciusCaseErrorType; severity?: LuciusCaseSeverity; status?: LuciusCaseStatus; currentOnly?: boolean; limit?: number };
export type NutritionSettings = Pick<DailyNutritionSummary, "date" | "restingEnergyKcal" | "activeEnergyKcal" | "notes">;
export type NewDrinkLog = Omit<DrinkLog, "id" | "createdAt" | "updatedAt">;
export type NewDrinkLimit = Omit<DrinkLimit, "id" | "createdAt" | "updatedAt">;
export type NewTracker = Omit<Tracker, "id" | "createdAt" | "updatedAt">;
export type NewTrackerField = Omit<TrackerField, "id" | "createdAt" | "updatedAt">;
export type NewTrackerEntry = Omit<TrackerEntry, "id" | "createdAt" | "updatedAt">;
export type NewTrackerGoal = Omit<TrackerGoal, "id" | "createdAt" | "updatedAt">;
export type NewTrackerReminder = Omit<TrackerReminder, "id" | "createdAt" | "updatedAt">;
export type NewPet = Omit<Pet, "id" | "createdAt" | "updatedAt">;
export type NewCatEvent = Omit<CatEvent, "id" | "createdAt" | "updatedAt">;
export type NewCatSymptom = Omit<CatSymptom, "id" | "createdAt" | "updatedAt">;
export type NewCatVetVisit = Omit<CatVetVisit, "id" | "createdAt" | "updatedAt">;
export type NewCatMedication = Omit<CatMedication, "id" | "createdAt" | "updatedAt">;
export type NewCatMeasurement = Omit<CatMeasurement, "id" | "createdAt" | "updatedAt">;
export type NewReminder = Omit<Reminder, "id" | "lastCompletedAt" | "snoozedUntil" | "lastNotifiedAt" | "sentAt" | "cancelledAt" | "createdAt" | "updatedAt">;
export type NewCatRoutine = Omit<CatRoutine, "id" | "lastCompletedAt" | "createdAt" | "updatedAt">;
export type NewRelationPerson = Omit<RelationPerson, "id" | "photoPath" | "archivedAt" | "createdAt" | "updatedAt">;
export type RelationPersonPatch = Partial<NewRelationPerson> & { photoPath?: string | null; archivedAt?: string | null };

export interface EvaOrbitRepository {
  listRelationPeople(input?: { query?: string; includeArchived?: boolean }): Promise<RelationPerson[]>;
  getRelationPerson(id: number): Promise<RelationPerson | null>;
  createRelationPerson(input: NewRelationPerson): Promise<RelationPerson>;
  updateRelationPerson(id: number, input: RelationPersonPatch): Promise<RelationPerson | null>;
  listRelationEvents(input?: { personId?: number; from?: string; to?: string; limit?: number }): Promise<RelationEvent[]>;
  getRelationEvent(id: number): Promise<RelationEvent | null>;
  createRelationEvent(input: RelationEventInput): Promise<RelationEvent>;
  updateRelationEvent(id: number, input: RelationEventInput): Promise<RelationEvent | null>;
  deleteRelationEvent(id: number): Promise<boolean>;
  listPersonMemoryNotes(personId: number): Promise<PersonMemoryNote[]>;
  getPersonMemoryNote(id: number): Promise<PersonMemoryNote | null>;
  createPersonMemoryNote(personId: number, content: string): Promise<PersonMemoryNote>;
  updatePersonMemoryNote(id: number, content: string): Promise<PersonMemoryNote | null>;
  deletePersonMemoryNote(id: number): Promise<boolean>;
  listTasks(filter?: TaskFilter): Promise<Task[]>;
  getTask(id: number): Promise<Task | null>;
  createTask(input: NewTask): Promise<Task>;
  updateTask(id: number, input: Record<string, unknown>): Promise<Task | null>;
  deleteTask(id: number): Promise<boolean>;

  listMemories(query?: string, category?: string): Promise<Memory[]>;
  getMemory(id: number): Promise<Memory | null>;
  createMemory(input: { title: string; content: string; category: string }): Promise<Memory>;
  updateMemory(id: number, input: Record<string, unknown>): Promise<Memory | null>;
  deleteMemory(id: number): Promise<boolean>;

  getDashboardSummary(): Promise<DashboardSummary>;
  getUiPreferences(): Promise<UiPreferences>;
  updateHomeModuleOrder(order: HomeModuleId[]): Promise<UiPreferences>;
  getAiSettings(): Promise<InternalAiSettings>;
  updateAiSettings(input: AiSettingsInput): Promise<InternalAiSettings>;
  updateChatPreferences(input: ChatPreferences): Promise<InternalAiSettings>;
  getAiRuntimeSettings(modelConfigId?: number | null): Promise<InternalAiSettings>;
  listAiProviders(): Promise<AiProvider[]>;
  getAiProvider(id: number): Promise<InternalAiProvider | null>;
  createAiProvider(input: AiProviderInput): Promise<AiProvider>;
  updateAiProvider(id: number, input: AiProviderInput): Promise<AiProvider | null>;
  deleteAiProvider(id: number): Promise<boolean>;
  createAiModelConfig(providerId: number, input: AiModelConfigInput): Promise<AiModelConfig>;
  updateAiModelConfig(id: number, input: AiModelConfigInput): Promise<AiModelConfig | null>;
  deleteAiModelConfig(id: number): Promise<boolean>;

  listChatSessions(): Promise<ChatSession[]>;
  getChatSession(id: number): Promise<ChatSession | null>;
  createChatSession(title?: string, modelConfigId?: number | null): Promise<ChatSession>;
  updateChatSession(id: number, input: { title?: string; modelConfigId?: number | null }): Promise<ChatSession | null>;
  deleteChatSession(id: number): Promise<boolean>;
  listChatMessages(sessionId: number): Promise<ChatMessage[]>;
  addChatMessage(sessionId: number, role: ChatRole, content: string, model?: string | null, providerId?: number | null, modelConfigId?: number | null): Promise<ChatMessage>;
  autoTitleChatSession(id: number, content: string): Promise<void>;

  listInbox(status?: InboxStatus | "all"): Promise<InboxItem[]>;
  getInboxItem(id: number): Promise<InboxItem | null>;
  createInboxItem(input: NewInboxItem): Promise<InboxItem>;
  updateInboxItem(id: number, input: Record<string, unknown>): Promise<InboxItem | null>;
  deleteInboxItem(id: number): Promise<boolean>;

  listFoodLogs(input?: { date?: string; query?: string; mealType?: string; from?: string; to?: string }): Promise<FoodLog[]>;
  getFoodLog(id: number): Promise<FoodLog | null>;
  createFoodLog(input: NewFoodLog): Promise<FoodLog>;
  updateFoodLog(id: number, input: Record<string, unknown>): Promise<FoodLog | null>;
  deleteFoodLog(id: number): Promise<boolean>;
  searchFoodLibrary(query?: string, brand?: string, options?: FoodLibrarySearchOptions): Promise<FoodLibraryItem[]>;
  getFoodLibraryItem(id: number): Promise<FoodLibraryItem | null>;
  upsertFoodLibraryItem(input: NewFoodLibraryItem): Promise<FoodLibraryItem>;
  updateFoodLibraryItem(id: number, input: NewFoodLibraryItem): Promise<FoodLibraryItem | null>;
  removeFoodLibraryItem(id: number): Promise<FoodLibraryRemoval | null>;

  listHealthRecords(input?: HealthRecordListInput): Promise<HealthRecord[]>;
  getHealthRecord(id: number): Promise<HealthRecord | null>;
  createHealthRecord(input: NewHealthRecord): Promise<HealthRecord>;
  updateHealthRecord(id: number, input: Record<string, unknown>): Promise<HealthRecord | null>;
  deleteHealthRecord(id: number): Promise<boolean>;

  listTrainingLogs(input?: TrainingLogListInput): Promise<TrainingLog[]>;
  getTrainingLog(id: number): Promise<TrainingLog | null>;
  createTrainingLog(input: NewTrainingLog): Promise<TrainingLog>;
  updateTrainingLog(id: number, input: TrainingLogPatch): Promise<TrainingLog | null>;
  deleteTrainingLog(id: number): Promise<boolean>;

  listMediaItems(input?: MediaListInput): Promise<MediaItem[]>;
  listMediaSeries(): Promise<MediaSeries[]>;
  getMediaSeries(id: number): Promise<MediaSeries | null>;
  createMediaSeries(name: string): Promise<MediaSeries>;
  getMediaItem(id: number): Promise<MediaItem | null>;
  createMediaItem(input: NewMediaItem): Promise<MediaItem>;
  updateMediaItem(id: number, input: MediaItemPatch): Promise<MediaItem | null>;
  deleteMediaItem(id: number): Promise<boolean>;
  listMediaViewings(mediaId?: number): Promise<MediaViewing[]>;
  getMediaViewing(id: number): Promise<MediaViewing | null>;
  createMediaViewing(input: { mediaId: number; watchedDate: string }): Promise<MediaViewing>;
  updateMediaViewing(id: number, watchedDate: string): Promise<MediaViewing | null>;
  deleteMediaViewing(id: number): Promise<boolean>;

  listChronicleEntries(input?: ChronicleListInput): Promise<ChronicleEntry[]>;
  getChronicleEntry(id: number): Promise<ChronicleEntry | null>;
  createChronicleEntry(input: NewChronicleEntry): Promise<ChronicleEntry>;
  updateChronicleEntry(id: number, input: ChronicleEntryPatch): Promise<ChronicleEntry | null>;
  deleteChronicleEntry(id: number): Promise<boolean>;

  listProjects(input?: ProjectListInput): Promise<Project[]>;
  getProject(id: number): Promise<Project | null>;
  createProject(input: NewProject): Promise<Project>;
  updateProject(id: number, input: ProjectPatch): Promise<Project | null>;
  listProjectItems(input?: ProjectItemListInput): Promise<ProjectItem[]>;
  getProjectItem(id: number): Promise<ProjectItem | null>;
  createProjectItem(input: NewProjectItem): Promise<ProjectItem>;
  updateProjectItem(id: number, input: ProjectItemPatch): Promise<ProjectItem | null>;

  listMemos(input?: MemoListInput): Promise<Memo[]>;
  getMemo(id: number): Promise<Memo | null>;
  createMemo(input: NewMemo): Promise<Memo>;
  updateMemo(id: number, input: MemoPatch): Promise<Memo | null>;
  deleteMemo(id: number): Promise<boolean>;

  listLuciusDiaryEntries(input?: LuciusDiaryListInput): Promise<LuciusDiaryEntry[]>;
  getLuciusDiaryEntry(id: number): Promise<LuciusDiaryEntry | null>;
  createLuciusDiaryEntry(input: NewLuciusDiaryEntry): Promise<LuciusDiaryEntry>;
  updateLuciusDiaryEntry(id: number, input: LuciusDiaryPatch): Promise<LuciusDiaryEntry | null>;
  deleteLuciusDiaryEntry(id: number): Promise<boolean>;

  listLuciusCases(input?: LuciusCaseListInput): Promise<LuciusCase[]>;
  getLuciusCase(id: number): Promise<LuciusCase | null>;
  createLuciusCase(input: NewLuciusCase): Promise<LuciusCase>;
  updateLuciusCase(id: number, input: LuciusCasePatch): Promise<LuciusCase | null>;
  deleteLuciusCase(id: number): Promise<boolean>;
  recordLuciusCaseRecurrence(id: number, occurredDate: string): Promise<LuciusCase | null>;

  listDrinkLogs(input?: { date?: string; from?: string; to?: string; drinkType?: string }): Promise<DrinkLog[]>;
  getDrinkLog(id: number): Promise<DrinkLog | null>;
  createDrinkLog(input: NewDrinkLog): Promise<DrinkLog>;
  updateDrinkLog(id: number, input: Record<string, unknown>): Promise<DrinkLog | null>;
  deleteDrinkLog(id: number): Promise<boolean>;
  listDrinkLimits(): Promise<DrinkLimit[]>;
  createDrinkLimit(input: NewDrinkLimit): Promise<DrinkLimit>;
  updateDrinkLimit(id: number, input: Record<string, unknown>): Promise<DrinkLimit | null>;
  deleteDrinkLimit(id: number): Promise<boolean>;

  listTrackers(): Promise<Tracker[]>;
  getTracker(id: number): Promise<Tracker | null>;
  createTracker(input: NewTracker): Promise<Tracker>;
  updateTracker(id: number, input: Record<string, unknown>): Promise<Tracker | null>;
  deleteTracker(id: number): Promise<boolean>;
  listTrackerFields(trackerId: number): Promise<TrackerField[]>;
  createTrackerField(input: NewTrackerField): Promise<TrackerField>;
  deleteTrackerField(id: number): Promise<boolean>;
  listTrackerEntries(trackerId?: number, input?: { from?: string; to?: string; query?: string }): Promise<TrackerEntry[]>;
  getTrackerEntry(id: number): Promise<TrackerEntry | null>;
  createTrackerEntry(input: NewTrackerEntry): Promise<TrackerEntry>;
  updateTrackerEntry(id: number, input: Record<string, unknown>): Promise<TrackerEntry | null>;
  deleteTrackerEntry(id: number): Promise<boolean>;
  listTrackerGoals(trackerId: number): Promise<TrackerGoal[]>;
  createTrackerGoal(input: NewTrackerGoal): Promise<TrackerGoal>;
  deleteTrackerGoal(id: number): Promise<boolean>;
  listTrackerReminders(trackerId: number): Promise<TrackerReminder[]>;
  createTrackerReminder(input: NewTrackerReminder): Promise<TrackerReminder>;
  deleteTrackerReminder(id: number): Promise<boolean>;

  listPets(includeInactive?: boolean): Promise<Pet[]>;
  getPet(id: number): Promise<Pet | null>;
  createPet(input: NewPet): Promise<Pet>;
  updatePet(id: number, input: Record<string, unknown>): Promise<Pet | null>;
  archivePet(id: number): Promise<boolean>;
  listCatEvents(petId?: number | null): Promise<CatEvent[]>;
  getCatEvent(id: number): Promise<CatEvent | null>;
  createCatEvent(input: NewCatEvent): Promise<CatEvent>;
  updateCatEvent(id: number, input: Record<string, unknown>): Promise<CatEvent | null>;
  deleteCatEvent(id: number): Promise<boolean>;
  listCatSymptoms(petId?: number): Promise<CatSymptom[]>;
  getCatSymptom(id: number): Promise<CatSymptom | null>;
  createCatSymptom(input: NewCatSymptom): Promise<CatSymptom>;
  updateCatSymptom(id: number, input: Record<string, unknown>): Promise<CatSymptom | null>;
  deleteCatSymptom(id: number): Promise<boolean>;
  listCatVetVisits(petId?: number): Promise<CatVetVisit[]>;
  getCatVetVisit(id: number): Promise<CatVetVisit | null>;
  createCatVetVisit(input: NewCatVetVisit): Promise<CatVetVisit>;
  updateCatVetVisit(id: number, input: Record<string, unknown>): Promise<CatVetVisit | null>;
  deleteCatVetVisit(id: number): Promise<boolean>;
  listCatMedications(petId?: number): Promise<CatMedication[]>;
  getCatMedication(id: number): Promise<CatMedication | null>;
  createCatMedication(input: NewCatMedication): Promise<CatMedication>;
  updateCatMedication(id: number, input: Record<string, unknown>): Promise<CatMedication | null>;
  deleteCatMedication(id: number): Promise<boolean>;
  listCatMeasurements(petId?: number): Promise<CatMeasurement[]>;
  getCatMeasurement(id: number): Promise<CatMeasurement | null>;
  createCatMeasurement(input: NewCatMeasurement): Promise<CatMeasurement>;
  updateCatMeasurement(id: number, input: Record<string, unknown>): Promise<CatMeasurement | null>;
  deleteCatMeasurement(id: number): Promise<boolean>;

  listCatRoutines(input?: { scope?: string; petId?: number | null; enabledOnly?: boolean }): Promise<CatRoutine[]>;
  getCatRoutine(id: number): Promise<CatRoutine | null>;
  createCatRoutine(input: NewCatRoutine): Promise<CatRoutine>;
  updateCatRoutine(id: number, input: Record<string, unknown>): Promise<CatRoutine | null>;
  archiveCatRoutine(id: number): Promise<boolean>;

  listReminders(input?: { targetType?: string; targetId?: number | null; activeOnly?: boolean; dueBefore?: string }): Promise<Reminder[]>;
  getReminder(id: number): Promise<Reminder | null>;
  createReminder(input: NewReminder): Promise<Reminder>;
  updateReminder(id: number, input: Record<string, unknown>): Promise<Reminder | null>;
  deleteReminder(id: number): Promise<boolean>;
  createReminderOccurrence(input: Omit<ReminderOccurrence, "id" | "createdAt">): Promise<ReminderOccurrence>;
  listNotificationDeliveries(limit?: number): Promise<NotificationDelivery[]>;
  createNotificationDelivery(input: Omit<NotificationDelivery, "id" | "createdAt">): Promise<NotificationDelivery>;
  listPushSubscriptions(): Promise<PushSubscriptionRecord[]>;
  upsertPushSubscription(input: Pick<PushSubscriptionRecord, "endpoint" | "p256dh" | "auth">): Promise<PushSubscriptionRecord>;
  deletePushSubscription(endpoint: string): Promise<boolean>;

  getNutritionSettings(date: string): Promise<Pick<DailyNutritionSummary, "restingEnergyKcal" | "activeEnergyKcal" | "notes">>;
  listNutritionSettings(limit?: number): Promise<NutritionSettings[]>;
  updateNutritionSettings(date: string, input: { restingEnergyKcal: number | null; activeEnergyKcal: number | null; notes: string }): Promise<void>;
}
