"use client";

import Link from "next/link";
import { type FormEvent, useMemo, useState } from "react";
import { Icon } from "@/components/icons";
import type { ApiError, Project, ProjectItem, ProjectItemStatus, ProjectItemType } from "@/lib/types";

const types:ProjectItemType[]=["feature","bug","ui","migration","research","tech_debt","other"];
const typeLabels:Record<ProjectItemType,string>={feature:"Feature",bug:"Bug",ui:"UI / UX",migration:"Migration",research:"Research",tech_debt:"Tech debt",other:"Other"};
const statusLabels:Record<ProjectItemStatus,string>={to_solve:"To Solve",doing:"Doing",blocked:"Blocked",done:"Done",verified:"Verified",dropped:"Dropped"};
function date(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(value));}
function monthDay(value:string){const valueDate=new Date(value);return {month:new Intl.DateTimeFormat("en-US",{month:"short"}).format(valueDate).toUpperCase(),day:String(valueDate.getDate()).padStart(2,"0")};}
function ItemRow({item}:{item:ProjectItem}){return <Link className="project-item-row" href={`/projects/${item.projectId}/items/${item.id}`}><span className="item-status" data-status={item.status}>{statusLabels[item.status]}</span><span className="item-copy"><strong>{item.title}</strong><small>{[item.module,typeLabels[item.type],item.priority].filter(Boolean).join(" · ")}</small>{item.nextStep&&["doing","blocked"].includes(item.status)&&<em>{item.nextStep}</em>}</span><time>{date(item.updatedAt)}</time><Icon name="arrow"/></Link>;}
export function ProjectDetailView({initialProject,initialItems}:{initialProject:Project;initialItems:ProjectItem[]}){
  const [items,setItems]=useState(initialItems);const [show,setShow]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [draft,setDraft]=useState({title:"",description:"",type:"feature" as ProjectItemType,module:"",priority:"",nextStep:""});
  const groups=useMemo(()=>({focus:items.filter(i=>i.status==="doing"||i.status==="blocked"),open:items.filter(i=>i.status==="to_solve"),solved:items.filter(i=>i.status==="done"||i.status==="verified").slice(0,8),chronicle:items.filter(i=>i.status==="done"||i.status==="verified").filter(i=>i.completedAt||i.verifiedAt).sort((a,b)=>(b.verifiedAt??b.completedAt??"").localeCompare(a.verifiedAt??a.completedAt??""))}),[items]);
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/project-items",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId:initialProject.id,title:draft.title,description:draft.description||null,type:draft.type,status:"to_solve",module:draft.module||null,priority:draft.priority||null,nextStep:draft.nextStep||null,resolution:null})});const result=await response.json() as ProjectItem|ApiError;if(!response.ok)throw new Error((result as ApiError).error||"Could not record issue.");setItems([result as ProjectItem,...items]);setShow(false);setDraft({title:"",description:"",type:"feature",module:"",priority:"",nextStep:""});}catch(reason){setError(reason instanceof Error?reason.message:"Could not record issue.");}finally{setSaving(false);}}
  return <div className="page project-detail-page"><div className="project-detail-header"><div><Link href="/projects" className="back-link">← Projects</Link><span className="eyebrow">{initialProject.status.toUpperCase()}</span><h1>{initialProject.name}</h1>{initialProject.description&&<p>{initialProject.description}</p>}</div><button className="button primary" onClick={()=>setShow(true)}><Icon name="plus"/>Issue</button></div>
    {show&&<form className="editor-card project-editor" onSubmit={submit}><div className="editor-title"><div><span className="eyebrow">CAPTURE</span><h2>Record an issue</h2></div><button type="button" className="text-button" onClick={()=>setShow(false)}>Cancel</button></div><div className="form-grid"><label className="field wide"><span>Title</span><input autoFocus required maxLength={300} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field"><span>Type</span><select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as ProjectItemType})}>{types.map(type=><option value={type} key={type}>{typeLabels[type]}</option>)}</select></label><label className="field"><span>Module <small>Optional</small></span><input maxLength={120} value={draft.module} onChange={e=>setDraft({...draft,module:e.target.value})}/></label><label className="field wide"><span>Original request</span><textarea rows={4} maxLength={20000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field"><span>Priority <small>Optional</small></span><input maxLength={60} placeholder="High, P1…" value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}/></label><label className="field"><span>Next step <small>Optional</small></span><input maxLength={5000} value={draft.nextStep} onChange={e=>setDraft({...draft,nextStep:e.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button className="button primary" disabled={saving}>{saving?"Recording…":"Record issue"}</button></div></form>}
    <section className="project-section"><div className="section-heading"><div><span className="eyebrow">NOW</span><h2>Current Focus</h2></div><small>{groups.focus.length}</small></div>{groups.focus.length?<div className="project-item-list focus">{groups.focus.map(i=><ItemRow item={i} key={i.id}/>)}</div>:<p className="project-empty-line">Nothing is actively moving or blocked.</p>}</section>
    <div className="project-columns"><section className="project-section"><div className="section-heading"><div><span className="eyebrow">QUEUE</span><h2>To Solve</h2></div><small>{groups.open.length}</small></div>{groups.open.length?<div className="project-item-list">{groups.open.map(i=><ItemRow item={i} key={i.id}/>)}</div>:<p className="project-empty-line">The queue is clear.</p>}</section><section className="project-section"><div className="section-heading"><div><span className="eyebrow">RECENT</span><h2>Recently Solved</h2></div><small>{groups.solved.length}</small></div>{groups.solved.length?<div className="project-item-list">{groups.solved.map(i=><ItemRow item={i} key={i.id}/>)}</div>:<p className="project-empty-line">No completed work yet.</p>}</section></div>
    <section className="project-section project-chronicle"><div className="section-heading"><div><span className="eyebrow">GROWTH</span><h2>Project Chronicle</h2></div></div>{groups.chronicle.length?<div className="project-timeline">{groups.chronicle.map(item=>{const stamp=monthDay(item.verifiedAt??item.completedAt!);return <Link href={`/projects/${item.projectId}/items/${item.id}`} className="project-timeline-entry" key={item.id}><time><b>{stamp.month}</b><strong>{stamp.day}</strong></time><div><h3>{item.title}</h3><small>{[item.module,typeLabels[item.type],item.status==="verified"?"Verified":"Done"].filter(Boolean).join(" · ")}</small><p>{item.resolution||"Implementation completed; resolution notes have not been added yet."}</p></div></Link>;})}</div>:<p className="project-empty-line">Completed work will grow into a quiet project history here.</p>}</section>
  </div>;
}
