import { NextRequest,NextResponse } from "next/server";
import { apiError } from "@/lib/api";
import { HttpError } from "@/lib/errors";
import { currentNativeAccount } from "@/lib/native-account";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { ValidationError } from "@/lib/validation";

export const runtime="nodejs";export const dynamic="force-dynamic";
async function account(){const value=await currentNativeAccount();if(!value)throw new HttpError("登录已失效",401);return value;}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function installation(value:unknown){if(typeof value!=="string"||!uuid.test(value))throw new ValidationError("installationId 格式不正确");return value;}
function identifier(value:unknown,label:string,optional=false){if(optional&&(value===null||value===undefined))return null;if(typeof value!=="string"||!value||value.length>500)throw new ValidationError(`${label}格式不正确`);return value;}
export async function GET(request:NextRequest){try{await account();const installationId=installation(request.nextUrl.searchParams.get("installationId"));const client=await createSupabaseServerClient(),{data,error}=await client.from("eventkit_links").select("*").eq("installation_id",installationId);if(error)throw error;return NextResponse.json(data);}catch(error){return apiError(error);}}
export async function PUT(request:NextRequest){try{const user=await account(),body=await request.json() as Record<string,unknown>,required=["installationId","entityType","eoId","eventkitEntityType","calendarItemIdentifier","calendarIdentifier","sourceIdentifier","lastSyncedHash","lastSyncedSnapshot"];if(required.some(key=>body[key]===undefined))throw new ValidationError("EventKit mapping 不完整");if(!["task","calendar_event"].includes(String(body.entityType))||!["reminder","event"].includes(String(body.eventkitEntityType))||!Number.isSafeInteger(body.eoId)||Number(body.eoId)<1)throw new ValidationError("EventKit mapping 格式不正确");if(typeof body.lastSyncedHash!=="string"||!/^[0-9a-f]{64}$/.test(body.lastSyncedHash)||!body.lastSyncedSnapshot||typeof body.lastSyncedSnapshot!=="object"||Array.isArray(body.lastSyncedSnapshot))throw new ValidationError("EventKit snapshot 格式不正确");const row={user_id:user.id,installation_id:installation(body.installationId),entity_type:body.entityType,eo_id:body.eoId,eventkit_entity_type:body.eventkitEntityType,calendar_item_identifier:identifier(body.calendarItemIdentifier,"calendarItemIdentifier"),external_identifier:identifier(body.externalIdentifier,"externalIdentifier",true),calendar_identifier:identifier(body.calendarIdentifier,"calendarIdentifier"),source_identifier:identifier(body.sourceIdentifier,"sourceIdentifier"),last_synced_hash:body.lastSyncedHash,last_synced_snapshot:body.lastSyncedSnapshot,apple_last_modified_at:body.appleLastModifiedAt??null,last_synced_at:new Date().toISOString()};const client=await createSupabaseServerClient(),{data,error}=await client.from("eventkit_links").upsert(row,{onConflict:"user_id,installation_id,entity_type,eo_id"}).select().single();if(error)throw error;if(body.entityType==="task"){const ownership=await client.from("task_reminders").update({delivery_channel:"apple_reminders"}).eq("task_id",body.eoId);if(ownership.error)throw ownership.error;}return NextResponse.json(data);}catch(error){return apiError(error);}}
export async function DELETE(request:NextRequest){try{await account();const body=await request.json() as Record<string,unknown>,id=Number(body.id);if(!Number.isSafeInteger(id)||id<1)throw new ValidationError("mapping id 格式不正确");const client=await createSupabaseServerClient(),existing=await client.from("eventkit_links").select("entity_type,eo_id").eq("id",id).maybeSingle();if(existing.error)throw existing.error;const result=await client.from("eventkit_links").delete().eq("id",id);if(result.error)throw result.error;if(existing.data?.entity_type==="task"){const ownership=await client.from("task_reminders").update({delivery_channel:"pwa"}).eq("task_id",existing.data.eo_id);if(ownership.error)throw ownership.error;}return new NextResponse(null,{status:204});}catch(error){return apiError(error);}}
