import "server-only";

import fs from "node:fs/promises";
import path from "node:path";
import { detectAvatarImage, MAX_AVATAR_BYTES } from "../avatar";
import { allowedEmail, usesSupabase } from "../config";
import { getRepository } from "../repositories";
import { createSupabaseServerClient } from "../supabase/server";
import { ValidationError } from "../validation";

const validExtensions = ["jpg", "png", "webp"];
function storedExtension(value: string) { try { const result = new URL(value, "http://evaorbit.local").searchParams.get("type") ?? ""; return validExtensions.includes(result) ? result : ""; } catch { return ""; } }
function localDirectory() { return path.resolve(/* turbopackIgnore: true */ process.env.EVAORBIT_CAT_AVATAR_DIR || path.join(process.cwd(), "data", "cat-avatars")); }
function localPath(petId: number, extension: string) { const directory = localDirectory(); const target = path.resolve(directory, `${petId}.${extension}`); if (path.dirname(target) !== directory) throw new Error("Cat avatar path is unsafe"); return { directory, target }; }
async function cloudIdentity() { const client = await createSupabaseServerClient(); const { data, error } = await client.auth.getClaims(); if (error) throw new Error("Could not verify cat avatar access"); const userId = typeof data?.claims?.sub === "string" ? data.claims.sub : ""; const email = typeof data?.claims?.email === "string" ? data.claims.email.toLocaleLowerCase() : ""; if (!userId || !allowedEmail() || email !== allowedEmail()) throw new Error("Cat avatar access denied"); return { client, userId }; }

export async function saveCatAvatar(petId: number, file: File) { if (file.size <= 0 || file.size > MAX_AVATAR_BYTES) throw new ValidationError("Cat photo must be smaller than 4 MB"); const bytes = new Uint8Array(await file.arrayBuffer()); const kind = detectAvatarImage(bytes); if (!kind) throw new ValidationError("Cat photos only accept real JPG, PNG, or WebP images"); const repository = await getRepository(); const pet = await repository.getPet(petId); if (!pet) throw new ValidationError("Cat not found"); const previous = storedExtension(pet.avatarUrl); if (usesSupabase()) { const { client, userId } = await cloudIdentity(); const objectPath = `${userId}/cats/${petId}.${kind.extension}`; const { error } = await client.storage.from("avatars").upload(objectPath, bytes, { contentType: kind.mime, upsert: true, cacheControl: "300" }); if (error) throw new Error("Could not upload cat photo"); if (previous && previous !== kind.extension) await client.storage.from("avatars").remove([`${userId}/cats/${petId}.${previous}`]); } else { const { directory, target } = localPath(petId, kind.extension); await fs.mkdir(directory, { recursive: true }); const temporary = `${target}.uploading`; await fs.writeFile(temporary, bytes, { flag: "w" }); await fs.rm(target, { force: true }); await fs.rename(temporary, target); if (previous && previous !== kind.extension) await fs.rm(localPath(petId, previous).target, { force: true }); } return repository.updatePet(petId, { avatarUrl: `/api/cats/pets/${petId}/avatar?type=${kind.extension}&v=${Date.now()}` }); }
export async function readCatAvatar(petId: number) { const pet = await (await getRepository()).getPet(petId); if (!pet) return null; const extension = storedExtension(pet.avatarUrl); if (!extension) return null; const mime = extension === "jpg" ? "image/jpeg" : `image/${extension}`; if (usesSupabase()) { const { client, userId } = await cloudIdentity(); const { data, error } = await client.storage.from("avatars").download(`${userId}/cats/${petId}.${extension}`); if (error || !data) return null; return { bytes: new Uint8Array(await data.arrayBuffer()), mime }; } try { return { bytes: new Uint8Array(await fs.readFile(/* turbopackIgnore: true */ localPath(petId, extension).target)), mime }; } catch { return null; } }
export async function resetCatAvatar(petId: number) { const repository = await getRepository(); const pet = await repository.getPet(petId); if (!pet) return null; const extension = storedExtension(pet.avatarUrl); if (extension) { if (usesSupabase()) { const { client, userId } = await cloudIdentity(); await client.storage.from("avatars").remove([`${userId}/cats/${petId}.${extension}`]); } else await fs.rm(localPath(petId, extension).target, { force: true }); } return repository.updatePet(petId, { avatarUrl: "" }); }
