import "server-only";

import { ConflictError } from "../errors";
import { getRepository } from "../repositories";
import type { NewCatEvent, NewCatMeasurement, NewCatMedication, NewCatSymptom, NewCatVetVisit, NewPet } from "../repositories/types";
import type { CatRecordKind, CatTimelineEntry } from "../types";

async function ensurePet(id:number, allowInactive=false){const pet=await(await getRepository()).getPet(id);if(!pet||!allowInactive&&!pet.isActive)throw new ConflictError("Cat not found or inactive.");return pet;}

export async function listPets(includeInactive=false){return(await getRepository()).listPets(includeInactive);}
export async function createPet(input:NewPet){return(await getRepository()).createPet(input);}
export async function updatePet(id:number,input:Record<string,unknown>){await ensurePet(id,true);return(await getRepository()).updatePet(id,input);}
export async function archivePet(id:number){await ensurePet(id,true);const repository=await getRepository();const archived=await repository.archivePet(id);if(!archived)return false;const [reminders,routines]=await Promise.all([repository.listReminders({targetType:"cat",targetId:id,activeOnly:true}),repository.listCatRoutines({scope:"cat",petId:id,enabledOnly:true})]);await Promise.all([...reminders.map(reminder=>repository.updateReminder(reminder.id,{isActive:false,status:"cancelled",cancelledAt:new Date().toISOString(),snoozedUntil:null})),...routines.map(routine=>repository.updateCatRoutine(routine.id,{enabled:false}))]);return true;}

export async function createCatRecord(kind:CatRecordKind,input:NewCatEvent|NewCatSymptom|NewCatVetVisit|NewCatMedication|NewCatMeasurement){const repository=await getRepository();const petId=(input as {petId:number|null}).petId;if(petId!==null)await ensurePet(petId);if(kind==="event")return repository.createCatEvent(input as NewCatEvent);if(kind==="symptom")return repository.createCatSymptom(input as NewCatSymptom);if(kind==="vet_visit")return repository.createCatVetVisit(input as NewCatVetVisit);if(kind==="medication")return repository.createCatMedication(input as NewCatMedication);return repository.createCatMeasurement(input as NewCatMeasurement);}
export async function updateCatRecord(kind:CatRecordKind,id:number,input:Record<string,unknown>){const repository=await getRepository();if(typeof input.petId==="number")await ensurePet(input.petId,true);if(kind==="event")return repository.updateCatEvent(id,input);if(kind==="symptom")return repository.updateCatSymptom(id,input);if(kind==="vet_visit")return repository.updateCatVetVisit(id,input);if(kind==="medication")return repository.updateCatMedication(id,input);return repository.updateCatMeasurement(id,input);}
export async function deleteCatRecord(kind:CatRecordKind,id:number){const repository=await getRepository();if(kind==="event")return repository.deleteCatEvent(id);if(kind==="symptom")return repository.deleteCatSymptom(id);if(kind==="vet_visit")return repository.deleteCatVetVisit(id);if(kind==="medication")return repository.deleteCatMedication(id);return repository.deleteCatMeasurement(id);}

export async function getCatRecord(kind:CatRecordKind,id:number){const repository=await getRepository();if(kind==="event")return repository.getCatEvent(id);if(kind==="symptom")return repository.getCatSymptom(id);if(kind==="vet_visit")return repository.getCatVetVisit(id);if(kind==="medication")return repository.getCatMedication(id);return repository.getCatMeasurement(id);}

export async function catTimeline(petId?:number|null):Promise<CatTimelineEntry[]>{const repository=await getRepository();const [events,symptoms,visits,medications,measurements]=await Promise.all([repository.listCatEvents(petId),petId===null?Promise.resolve([]):repository.listCatSymptoms(petId),petId===null?Promise.resolve([]):repository.listCatVetVisits(petId),petId===null?Promise.resolve([]):repository.listCatMedications(petId),petId===null?Promise.resolve([]):repository.listCatMeasurements(petId)]);return[
  ...events.map(item=>({id:item.id,kind:"event" as const,petId:item.petId,occurredAt:item.occurredAt,eventType:item.eventType,title:item.title,summary:item.note,metadata:{sourceType:item.sourceType,sourceId:item.sourceId}})),
  ...symptoms.map(item=>({id:item.id,kind:"symptom" as const,petId:item.petId,occurredAt:item.occurredAt,eventType:"symptom",title:item.title,summary:[item.severity,item.bodyArea,item.description].filter(Boolean).join(" · "),metadata:{severity:item.severity,bodyArea:item.bodyArea}})),
  ...visits.map(item=>({id:item.id,kind:"vet_visit" as const,petId:item.petId,occurredAt:item.occurredAt,eventType:"vet_visit",title:"Vet Visit",summary:[item.reason,item.clinic,item.diagnosis].filter(Boolean).join(" · "),metadata:{followUpAt:item.followUpAt,cost:item.cost}})),
  ...medications.map(item=>({id:item.id,kind:"medication" as const,petId:item.petId,occurredAt:item.startedAt,eventType:"medication",title:item.name,summary:[item.dose,item.unit,item.frequencyText,item.active?"Active":"Completed"].filter(Boolean).join(" · "),metadata:{active:item.active,endedAt:item.endedAt}})),
  ...measurements.map(item=>({id:item.id,kind:"measurement" as const,petId:item.petId,occurredAt:item.occurredAt,eventType:"measurement",title:item.measurementType,summary:`${item.value} ${item.unit}${item.note?` · ${item.note}`:""}`,metadata:{value:item.value,unit:item.unit}})),
].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));}

export async function getPetDetail(id:number){const pet=await ensurePet(id,true);const repository=await getRepository();const [timeline,reminders,routines,medications,measurements]=await Promise.all([catTimeline(id),repository.listReminders({targetType:"cat",targetId:id}),repository.listCatRoutines({scope:"cat",petId:id}),repository.listCatMedications(id),repository.listCatMeasurements(id)]);return{pet,timeline,reminders,routines,medications,measurements};}

export async function getCatsDashboard(){const repository=await getRepository();const [pets,householdTimeline,routines]=await Promise.all([repository.listPets(),catTimeline(null),repository.listCatRoutines({enabledOnly:true})]);const petCards=await Promise.all(pets.map(async pet=>{const timeline=await catTimeline(pet.id);const nextRoutine=routines.filter(r=>r.scope==="cat"&&r.petId===pet.id).sort((a,b)=>a.nextDueAt.localeCompare(b.nextDueAt))[0]??null;return{pet,latest:timeline[0]??null,nextRoutine};}));const household=routines.filter(r=>r.scope==="household").map(routine=>({routine,latest:(householdTimeline.find(item=>item.metadata.sourceType==="cat_routine"&&item.metadata.sourceId===routine.id)||householdTimeline.find(item=>item.title===routine.title))??null}));return{pets:petCards,household,timeline:[...(await Promise.all(pets.map(p=>catTimeline(p.id)))).flat(),...householdTimeline].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt))};}
