import "server-only";
import { ConflictError } from "../errors";
import { derivePersonBalance, validateRelationEvent, type RelationEventInput } from "../relations";
import { getRepository } from "../repositories";

export async function listRelationPeople(input:{query?:string;includeArchived?:boolean}={}){const repo=await getRepository();const [people,events]=await Promise.all([repo.listRelationPeople(input),repo.listRelationEvents({limit:500})]);return people.map(person=>{const related=events.filter(event=>event.parties.some(p=>p.personId===person.id));return{...person,balance:derivePersonBalance(related,person.id),latestEvent:related[0]??null};});}
export async function getRelationPersonDetail(id:number){const repo=await getRepository();const person=await repo.getRelationPerson(id);if(!person)return null;const [events,memoryNotes]=await Promise.all([repo.listRelationEvents({personId:id,limit:500}),repo.listPersonMemoryNotes(id)]);return{person,balance:derivePersonBalance(events,id),events,memoryNotes};}
export async function createRelationPerson(input:Parameters<Awaited<ReturnType<typeof getRepository>>["createRelationPerson"]>[0]){return(await getRepository()).createRelationPerson(input);}
export async function updateRelationPerson(id:number,input:Parameters<Awaited<ReturnType<typeof getRepository>>["updateRelationPerson"]>[1]){return(await getRepository()).updateRelationPerson(id,input);}
async function ensurePeople(input:RelationEventInput){const repo=await getRepository();for(const personId of input.parties.flatMap(p=>p.personId?[p.personId]:[]))if(!await repo.getRelationPerson(personId))throw new ConflictError(`人物 ${personId} 不存在`);}
async function validateSettlementLinks(input:RelationEventInput,editingId?:number){const repo=await getRepository();const linked=input.flows.filter(f=>f.settlesFlowId!==null);if(!linked.length)return;const events=await repo.listRelationEvents({limit:500});for(const flow of linked){const sourceEvent=events.find(e=>e.flows.some(f=>f.id===flow.settlesFlowId)),source=sourceEvent?.flows.find(f=>f.id===flow.settlesFlowId);if(!sourceEvent||!source||source.flowType!=="advance")throw new ConflictError("还款只能结清已有代付");const sourceFrom=sourceEvent.parties.find(p=>p.id===source.fromPartyId),sourceTo=sourceEvent.parties.find(p=>p.id===source.toPartyId),repayFrom=input.parties.find(p=>p.key===flow.fromKey),repayTo=input.parties.find(p=>p.key===flow.toKey);const sameParty=(left:typeof sourceFrom,right:typeof repayFrom)=>Boolean(left&&right&&left.partyType===right.partyType&&left.personId===right.personId);if(!sameParty(sourceTo,repayFrom)||!sameParty(sourceFrom,repayTo))throw new ConflictError("还款流向必须与原代付方向相反");const used=events.filter(e=>e.id!==editingId).flatMap(e=>e.flows).filter(f=>f.flowType==="repayment"&&f.settlesFlowId===source.id).reduce((s,f)=>s+f.amountMinor,0);if(used+flow.amountMinor>source.amountMinor)throw new ConflictError("累计还款不能超过原代付金额");}}
export async function listRelationEvents(input:{personId?:number;from?:string;to?:string;limit?:number}={}){return(await getRepository()).listRelationEvents(input);}
export async function getRelationEvent(id:number){return(await getRepository()).getRelationEvent(id);}
export async function createRelationEvent(input:RelationEventInput){validateRelationEvent(input);await ensurePeople(input);await validateSettlementLinks(input);return(await getRepository()).createRelationEvent(input);}
export async function updateRelationEvent(id:number,input:RelationEventInput){validateRelationEvent(input);await ensurePeople(input);await validateSettlementLinks(input,id);return(await getRepository()).updateRelationEvent(id,input);}
export async function deleteRelationEvent(id:number){return(await getRepository()).deleteRelationEvent(id);}
export async function createMemoryNote(personId:number,content:string){const repo=await getRepository();if(!await repo.getRelationPerson(personId))throw new ConflictError("人物不存在");return repo.createPersonMemoryNote(personId,content);}
export async function getMemoryNote(id:number){return(await getRepository()).getPersonMemoryNote(id);}
export async function listMemoryNotes(personId:number){return(await getRepository()).listPersonMemoryNotes(personId);}
export async function updateMemoryNote(id:number,content:string){return(await getRepository()).updatePersonMemoryNote(id,content);}
export async function deleteMemoryNote(id:number){return(await getRepository()).deletePersonMemoryNote(id);}
export async function settleAdvance(flowId:number,input:{amountMinor:number;occurredAt:string;occurredHasExplicitTime:boolean;note:string|null}){const repo=await getRepository();const events=await repo.listRelationEvents({limit:500});const sourceEvent=events.find(e=>e.flows.some(f=>f.id===flowId));const source=sourceEvent?.flows.find(f=>f.id===flowId);if(!sourceEvent||!source||source.flowType!=="advance")throw new ConflictError("代付记录不存在");const from=sourceEvent.parties.find(p=>p.id===source.fromPartyId),to=sourceEvent.parties.find(p=>p.id===source.toPartyId);if(!from||!to)throw new ConflictError("代付参与者不完整");const used=events.flatMap(e=>e.flows).filter(f=>f.flowType==="repayment"&&f.settlesFlowId===flowId).reduce((s,f)=>s+f.amountMinor,0);if(used+input.amountMinor>source.amountMinor)throw new ConflictError("还款金额超过尚未结清金额");const parties=[{key:"self",partyType:"self" as const,personId:null,shareAmountMinor:null,paidAmountMinor:null},...sourceEvent.parties.filter(p=>p.partyType==="person"&&(p.id===from.id||p.id===to.id)).map(p=>({key:`p:${p.personId}`,partyType:"person" as const,personId:p.personId!,shareAmountMinor:null,paidAmountMinor:null}))];const key=(p:typeof from)=>p!.partyType==="self"?"self":`p:${p!.personId}`;return createRelationEvent({eventType:"repayment",title:"还款",note:input.note,occurredAt:input.occurredAt,occurredHasExplicitTime:input.occurredHasExplicitTime,currency:"CNY",totalAmountMinor:null,isInPerson:null,parties,items:[],flows:[{fromKey:key(to),toKey:key(from),flowType:"repayment",amountMinor:input.amountMinor,settlesFlowId:flowId,note:input.note}]});}
