import "server-only";

import { ConflictError } from "../errors";
import { effectiveDueAt, reminderActionPatch, selectDueReminders, snoozeUntil } from "../reminder-engine";
import { getRepository } from "../repositories";
import type { NewReminder } from "../repositories/types";
import type { DueReminder, Reminder } from "../types";

async function subjectLabel(reminder:Reminder){if(reminder.targetType==="cat_household")return"Household";if(reminder.targetType==="cat"&&reminder.targetId){const pet=await(await getRepository()).getPet(reminder.targetId);return pet?.name??"Cat";}if(reminder.targetType==="tracker"&&reminder.targetId){const tracker=await(await getRepository()).getTracker(reminder.targetId);return tracker?.name??"Tracker";}return reminder.targetType;}
async function validateTarget(input:NewReminder){const repository=await getRepository();if(input.targetType==="cat"&&(!input.targetId||!await repository.getPet(input.targetId)))throw new ConflictError("Cat not found.");if(input.targetType==="tracker"&&(!input.targetId||!await repository.getTracker(input.targetId)))throw new ConflictError("Tracker not found.");}
export async function listReminders(input:{targetType?:string;targetId?:number|null;activeOnly?:boolean}={}){return(await getRepository()).listReminders(input);}
export async function createReminder(input:NewReminder){await validateTarget(input);return(await getRepository()).createReminder(input);}
export async function updateReminder(id:number,input:Record<string,unknown>){const repository=await getRepository();if(!await repository.getReminder(id))return null;return repository.updateReminder(id,input);}
export async function deleteReminder(id:number){return(await getRepository()).deleteReminder(id);}
export async function getDueReminders(limit=50,now=new Date()):Promise<DueReminder[]>{const repository=await getRepository();const reminders=selectDueReminders(await repository.listReminders({activeOnly:true}),now,limit);const due=reminders.map(reminder=>{const dueAt=effectiveDueAt(reminder)!;return{...reminder,dueAt,overdueMs:now.getTime()-new Date(dueAt).getTime()};});return Promise.all(due.map(async reminder=>({...reminder,subjectLabel:await subjectLabel(reminder)})));}
export async function completeReminder(id:number,actedAt=new Date()){const repository=await getRepository();const reminder=await repository.getReminder(id);if(!reminder||!reminder.isActive)throw new ConflictError("Reminder not found or inactive.");let createdEventId:number|null=null;if(reminder.scheduleType==="interval"&&(reminder.targetType==="cat"||reminder.targetType==="cat_household")){const event=await repository.createCatEvent({petId:reminder.targetType==="cat"?reminder.targetId:null,eventType:reminder.targetType==="cat"?"care":"cleaning",occurredAt:actedAt.toISOString(),title:reminder.title,note:"",sourceType:"reminder",sourceId:reminder.id});createdEventId=event.id;}const scheduledFor=effectiveDueAt(reminder)??reminder.startsAt;await repository.createReminderOccurrence({reminderId:id,action:"completed",scheduledFor,actedAt:actedAt.toISOString(),createdEventId});return repository.updateReminder(id,reminderActionPatch(reminder,"complete",actedAt));}
export async function skipReminder(id:number,actedAt=new Date()){const repository=await getRepository();const reminder=await repository.getReminder(id);if(!reminder||!reminder.isActive)throw new ConflictError("Reminder not found or inactive.");const scheduledFor=effectiveDueAt(reminder)??reminder.startsAt;await repository.createReminderOccurrence({reminderId:id,action:"skipped",scheduledFor,actedAt:actedAt.toISOString(),createdEventId:null});return repository.updateReminder(id,reminderActionPatch(reminder,"skip",actedAt));}
export async function snoozeReminder(id:number,choice:"later_today"|"tomorrow"|"custom",custom?:string,now=new Date()){const repository=await getRepository();const reminder=await repository.getReminder(id);if(!reminder||!reminder.isActive)throw new ConflictError("Reminder not found or inactive.");return repository.updateReminder(id,{snoozedUntil:snoozeUntil(choice,now,custom,reminder.timezone)});}
