"use client";

import { useMemo, useState } from "react";
import { compactDateTimePayload, compactDateTimeValue, currentLocalDate, DateTimeField } from "@/components/date-time-field";
import { FormSheet } from "@/components/form-sheet";
import { Icon } from "@/components/icons";
import { useLocale } from "@/components/locale-controller";
import { flushPendingMenstrualFlowToHealthKit, syncMenstrualFlowToHealthKit } from "@/lib/healthkit-menstrual-flow";
import { PERIOD_MEDICATION_REMINDER_SOURCE } from "@/lib/reminder-source-registry";
import { EVAORBIT_TIME_ZONE } from "@/lib/time";
import type { MedicationDoseEvent, MedicationPreset, MenstrualFlowRecord, MenstrualPeriod, ScheduledNotification } from "@/lib/types";

type Saved = () => void | Promise<void>;
const flowLabels = { none: "无", unspecified: "未指定", light: "少量", medium: "中等", heavy: "大量" } as const;
function apiMessage(value: unknown, fallback: string) { return value && typeof value === "object" && "error" in value && typeof value.error === "string" ? value.error : fallback; }
async function jsonRequest<T>(url: string, init?: RequestInit) { const response = await fetch(url, init), body = await response.json().catch(() => null); if (!response.ok) throw new Error(apiMessage(body, "Could not save this record")); return body as T; }
function formatWhen(value: string, hasTime = true) { return new Date(value).toLocaleString("zh-CN", { month: "short", day: "numeric", hour: hasTime ? "2-digit" : undefined, minute: hasTime ? "2-digit" : undefined, timeZone: EVAORBIT_TIME_ZONE }); }
function periodLabel(item: MenstrualPeriod) { return `${item.startedOn}${item.endedOn ? ` – ${item.endedOn}` : " · 进行中"}`; }

export function PeriodMedicationSection({ initialPeriods, initialFlows, initialPresets, initialDoses, initialReminders }: { initialPeriods: MenstrualPeriod[]; initialFlows: MenstrualFlowRecord[]; initialPresets: MedicationPreset[]; initialDoses: MedicationDoseEvent[]; initialReminders: ScheduledNotification[] }) {
  const { english } = useLocale();
  const [periods, setPeriods] = useState(initialPeriods), [flows, setFlows] = useState(initialFlows), [presets, setPresets] = useState(initialPresets), [doses, setDoses] = useState(initialDoses), [reminders, setReminders] = useState(initialReminders);
  const [open, setOpen] = useState<"start" | "flow" | "dose" | "preset" | null>(null), [editingFlow, setEditingFlow] = useState<MenstrualFlowRecord>(), [editingDose, setEditingDose] = useState<MedicationDoseEvent>(), [editingPreset, setEditingPreset] = useState<MedicationPreset>();
  const [message, setMessage] = useState(""), [error, setError] = useState("");
  const current = useMemo(() => periods.find((item) => !item.endedOn) ?? null, [periods]);
  const currentFlows = current ? flows.filter((item) => item.periodId === current.id) : [];
  const currentDoses = current ? doses.filter((item) => item.periodId === current.id) : [];

  async function reload() {
    const [p, f, m, d, n] = await Promise.all([fetch("/api/health/periods?limit=30", { cache: "no-store" }), fetch("/api/health/menstrual-flow?limit=30", { cache: "no-store" }), fetch("/api/health/medications?limit=100", { cache: "no-store" }), fetch("/api/health/medication-doses?limit=30", { cache: "no-store" }), fetch("/api/notifications", { cache: "no-store" })]);
    if (p.ok) setPeriods(await p.json()); if (f.ok) setFlows(await f.json()); if (m.ok) setPresets(await m.json()); if (d.ok) setDoses(await d.json());
    if (n.ok) { const body = await n.json(); setReminders((body.upcoming ?? []).filter((item: ScheduledNotification) => item.sourceType === PERIOD_MEDICATION_REMINDER_SOURCE)); }
  }
  async function saved(text: string) { setOpen(null); setEditingFlow(undefined); setEditingDose(undefined); setEditingPreset(undefined); setMessage(text); setError(""); await reload(); }
  async function finishPeriod() { if (!current) return; setError(""); try { await jsonRequest(`/api/health/periods/${current.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ endedOn: currentLocalDate() }) }); await saved(english ? "Period end date saved" : "经期结束日期已保存"); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }
  async function remove(kind: "flow" | "dose" | "preset", id: number) {
    if (!confirm(english ? kind === "preset" ? "Archive this medication preset?" : "Delete this record?" : kind === "preset" ? "归档这个药物配置？" : "删除这条记录？")) return;
    setError("");
    try { const base = kind === "flow" ? "menstrual-flow" : kind === "dose" ? "medication-doses" : "medications"; const response = await fetch(`/api/health/${base}/${id}`, { method: "DELETE" }); if (!response.ok) throw new Error(apiMessage(await response.json().catch(() => null), "Could not remove this record")); if (kind === "flow") void flushPendingMenstrualFlowToHealthKit(); await saved(english ? kind === "preset" ? "Medication archived" : "Record deleted" : kind === "preset" ? "药物配置已归档" : "记录已删除"); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); }
  }

  return <section className="health-section" aria-labelledby="period-medication-title">
    {open === "start" && <StartPeriodEditor initialDate={currentLocalDate()} onClose={() => setOpen(null)} onSaved={() => saved(english ? "Period started" : "经期已开始")} />}
    {open === "flow" && <PeriodFlowEditor initialDate={currentLocalDate()} periods={periods} record={editingFlow} onClose={() => setOpen(null)} onSaved={() => saved(english ? "Menstrual flow saved" : "经量记录已保存")} />}
    {open === "dose" && <MedicationDoseEditor initialDate={currentLocalDate()} periods={periods} presets={presets} record={editingDose} onClose={() => setOpen(null)} onSaved={() => saved(english ? "Dose saved" : "服药记录已保存")} />}
    {open === "preset" && <MedicationPresetEditor record={editingPreset} onClose={() => setOpen(null)} onSaved={() => saved(english ? "Medication settings saved" : "药物配置已保存")} />}
    <div className="section-heading"><div><span className="eyebrow">CYCLE & MEDICATION</span><h2 id="period-medication-title">{english ? "Period and medication" : "经期与用药"}</h2></div><div className="weight-actions">
      {current ? <button className="text-button training-add" onClick={() => { setEditingFlow(undefined); setOpen("flow"); }}><Icon name="plus" />{english ? "Log flow" : "记录经量"}</button> : <button className="text-button training-add" onClick={() => setOpen("start")}><Icon name="plus" />{english ? "Start period" : "开始经期"}</button>}
      <button className="text-button training-add" disabled={!presets.length} onClick={() => { setEditingDose(undefined); setOpen("dose"); }}><Icon name="plus" />{english ? "Log dose" : "记录服药"}</button>
    </div></div>
    {message && <p className="form-success" role="status">{message}</p>}{error && <p className="form-error" role="alert">{error}</p>}
    {!current ? <div className="health-inline-empty"><p>{english ? "No active period. Start one when bleeding begins; earlier events stay in Home Timeline." : "当前没有进行中的经期。开始后可记录经量；历史记录继续在首页 Timeline 查看。"}</p><button className="button primary" onClick={() => setOpen("start")}>{english ? "Start period" : "开始经期"}</button><button className="text-button" onClick={() => { setEditingFlow(undefined); setOpen("flow"); }}>{english ? "Log an earlier flow record" : "补录历史经量"}</button></div> : <>
      <div className="weight-overview"><div className="weight-current"><span>{english ? "CURRENT PERIOD" : "当前周期"}</span><strong>{current.startedOn}</strong><small>{english ? "Ongoing" : "进行中"}</small></div><dl><div><dt>{english ? "Recent flow" : "最近经量"}</dt><dd>{currentFlows[0] ? flowLabels[currentFlows[0].flow] : "—"}</dd></div><div><dt>{english ? "Recent dose" : "最近服药"}</dt><dd>{currentDoses[0]?.medicationNameSnapshot ?? "—"}</dd></div><div><dt>{english ? "Next reminder" : "下一次提醒"}</dt><dd>{reminders[0] ? formatWhen(reminders[0].scheduledAt) : presets.some((item) => item.reminderEnabled && item.periodLinkEnabled) ? (english ? "Waiting for a dose" : "等待服药记录") : (english ? "Off" : "关闭")}</dd></div></dl></div>
      <div className="weight-actions"><button className="button secondary" onClick={() => void finishPeriod()}>{english ? "End period today" : "今天结束经期"}</button></div>
      <details className="training-history" open><summary><span><small>{english ? "CURRENT PERIOD" : "当前周期"}</small><strong>{english ? "Menstrual flow" : "经量记录"}</strong></span><span>{currentFlows.length}</span></summary>{currentFlows.length ? <RecordList items={currentFlows.slice(0, 8).map((item) => ({ id: item.id, time: formatWhen(item.occurredAt, item.occurredHasExplicitTime), title: flowLabels[item.flow], detail: `${item.isCycleStart ? (english ? "Period start" : "经期开始") : item.notes || (english ? "Menstrual flow" : "经量记录")}${item.source === "apple_health" ? " · Apple Health" : ""}`, edit: item.source === "apple_health" ? undefined : () => { setEditingFlow(item); setOpen("flow"); }, remove: item.source === "apple_health" ? undefined : () => void remove("flow", item.id), english }))} /> : <p className="health-inline-empty">{english ? "No flow recorded in this period." : "当前周期还没有经量记录。"}</p>}</details>
      <details className="training-history"><summary><span><small>{english ? "CURRENT PERIOD" : "当前周期"}</small><strong>{english ? "Medication doses" : "服药记录"}</strong></span><span>{currentDoses.length}</span></summary>{currentDoses.length ? <RecordList items={currentDoses.slice(0, 8).map((item) => ({ id: item.id, time: formatWhen(item.takenAt), title: item.medicationNameSnapshot, detail: item.doseText || item.notes || (english ? "Dose recorded" : "已记录服用"), edit: () => { setEditingDose(item); setOpen("dose"); }, remove: () => void remove("dose", item.id), english }))} /> : <p className="health-inline-empty">{english ? "No dose recorded in this period." : "当前周期还没有服药记录。"}</p>}</details>
    </>}
    <div className="weight-actions"><button className="button secondary" onClick={() => { setEditingPreset(undefined); setOpen("preset"); }}>{english ? "Add medication" : "新增药物配置"}</button></div>
    <MedicationPresets presets={presets} reminders={reminders} english={english} edit={(item) => { setEditingPreset(item); setOpen("preset"); }} remove={(id) => void remove("preset", id)} />
  </section>;
}

function MedicationPresets({ presets, reminders, english, edit, remove }: { presets: MedicationPreset[]; reminders: ScheduledNotification[]; english: boolean; edit: (item: MedicationPreset) => void; remove: (id: number) => void }) { return <details className="training-history"><summary><span><small>{english ? "SETTINGS" : "设置"}</small><strong>{english ? "Medication presets" : "药物配置"}</strong></span><span>{presets.length}</span></summary>{presets.length ? <div className="weight-record-list">{presets.map((item) => { const next = reminders.find((reminder) => reminder.sourceId === item.id); return <article key={item.id}><button onClick={() => edit(item)}><strong>{item.name}</strong><span>{item.defaultDoseText || `${item.minReminderIntervalMinutes} min`}</span><span>{next ? (english ? `Next reminder ${formatWhen(next.scheduledAt)}` : `下次提醒 ${formatWhen(next.scheduledAt)}`) : item.reminderEnabled && item.periodLinkEnabled ? (english ? "Enabled · waits for a dose" : "已开启 · 等待服药记录") : (english ? "Reminder off" : "提醒关闭")}</span><Icon name="edit" /></button><button className="text-button" onClick={() => remove(item.id)}>{english ? "Archive" : "归档"}</button></article>; })}</div> : <p className="health-inline-empty">{english ? "Add a medication before logging a dose." : "先新增药物配置，再记录服用。"}</p>}</details>; }
function RecordList({ items }: { items: Array<{ id: number; time: string; title: string; detail: string; edit?: () => void; remove?: () => void; english: boolean }> }) { return <div className="weight-record-list">{items.map((item) => <article key={item.id}><button onClick={item.edit} disabled={!item.edit} title={!item.edit ? (item.english ? "Edit this imported record in Apple Health" : "请在 Apple Health 中修改这条导入记录") : undefined}><time>{item.time}</time><strong>{item.title}</strong><span>{item.detail}</span>{item.edit && <Icon name="edit" />}</button>{item.remove && <button className="text-button" onClick={item.remove}>{item.english ? "Delete" : "删除"}</button>}</article>)}</div>; }

export function StartPeriodEditor({ initialDate, onClose, onSaved }: { initialDate: string; onClose: () => void; onSaved: Saved }) {
  const { english } = useLocale(); const [occurred, setOccurred] = useState(initialDate), [flow, setFlow] = useState<MenstrualFlowRecord["flow"]>("medium"), [notes, setNotes] = useState(""), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); let periodId: number | undefined; try { const when = compactDateTimePayload(occurred); const period = await jsonRequest<MenstrualPeriod>("/api/health/periods", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startedOn: occurred.slice(0, 10), endedOn: null, notes: "" }) }); periodId = period.id; const record = await jsonRequest<MenstrualFlowRecord>("/api/health/menstrual-flow", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ periodId, occurredAt: when.value, occurredHasExplicitTime: when.hasExplicitTime, flow, isCycleStart: true, notes }) }); try { await syncMenstrualFlowToHealthKit(record); } catch { /* remains pending for Sync Now */ } await onSaved(); } catch (reason) { if (periodId) await fetch(`/api/health/periods/${periodId}`, { method: "DELETE" }).catch(() => undefined); setError(reason instanceof Error ? reason.message : String(reason)); } finally { setSaving(false); } }
  return <FormSheet title={english ? "Start period" : "开始经期"} onClose={onClose} formId="start-period-form" submitLabel={english ? "Start period" : "开始经期"} busy={saving}><form id="start-period-form" className="weight-settings-form" onSubmit={submit}><DateTimeField label={english ? "Start date and optional time" : "开始日期（时间可选）"} value={{ date: occurred.slice(0, 10), time: occurred.length > 10 ? occurred.slice(11, 16) : "" }} onChange={(value) => setOccurred(value.date + (value.time ? `T${value.time}` : ""))} /><FlowField value={flow} onChange={setFlow} english={english} /><label className="field"><span>{english ? "Notes" : "备注"}</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}</form></FormSheet>;
}

export function PeriodFlowEditor({ initialDate, periods, record, onClose, onSaved }: { initialDate: string; periods: MenstrualPeriod[]; record?: MenstrualFlowRecord; onClose: () => void; onSaved: Saved }) {
  const { english } = useLocale(), active = periods.find((item) => !item.endedOn) ?? null;
  const [occurred, setOccurred] = useState(record ? compactDateTimeValue(record.occurredAt, record.occurredHasExplicitTime) : initialDate), [flow, setFlow] = useState<MenstrualFlowRecord["flow"]>(record?.flow ?? "medium"), [periodId, setPeriodId] = useState(record?.periodId ? String(record.periodId) : ""), [choosePeriod, setChoosePeriod] = useState(Boolean(record && record.periodId !== active?.id) || !active), [notes, setNotes] = useState(record?.notes ?? ""), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const when = compactDateTimePayload(occurred); const body = { periodId: choosePeriod ? (periodId ? Number(periodId) : null) : record?.periodId ?? null, occurredAt: when.value, occurredHasExplicitTime: when.hasExplicitTime, flow, isCycleStart: record?.isCycleStart ?? false, notes }; const saved = await jsonRequest<MenstrualFlowRecord>(record ? `/api/health/menstrual-flow/${record.id}` : "/api/health/menstrual-flow", { method: record ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); try { await syncMenstrualFlowToHealthKit(saved); } catch { /* remains pending for Sync Now */ } await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setSaving(false); } }
  return <FormSheet title={record ? (english ? "Edit menstrual flow" : "编辑经量记录") : (english ? "Log menstrual flow" : "记录经量")} onClose={onClose} formId="menstrual-flow-form" submitLabel={english ? "Save" : "保存"} busy={saving}><form id="menstrual-flow-form" className="weight-settings-form" onSubmit={submit}><DateTimeField label={english ? "Date and optional time" : "日期（时间可选）"} value={{ date: occurred.slice(0, 10), time: occurred.length > 10 ? occurred.slice(11, 16) : "" }} onChange={(value) => setOccurred(value.date + (value.time ? `T${value.time}` : ""))} /><FlowField value={flow} onChange={setFlow} english={english} />{!record?.isCycleStart && <label className="weight-reminder-toggle"><span><strong>{english ? "Backfill or choose another period" : "补录或选择其他经期"}</strong><small>{active ? (english ? "Normally linked to the active period automatically." : "日常记录会自动关联当前经期。") : (english ? "Choose only when this belongs to an earlier period." : "仅在补录历史时选择。")}</small></span><input type="checkbox" checked={choosePeriod} onChange={(event) => setChoosePeriod(event.target.checked)} /></label>}{choosePeriod && !record?.isCycleStart && <PeriodField periods={periods} value={periodId} onChange={setPeriodId} english={english} />}<label className="field"><span>{english ? "Notes" : "备注"}</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}</form></FormSheet>;
}

function FlowField({ value, onChange, english }: { value: MenstrualFlowRecord["flow"]; onChange: (value: MenstrualFlowRecord["flow"]) => void; english: boolean }) { return <label className="field"><span>{english ? "Menstrual flow" : "经量"}</span><select value={value} onChange={(event) => onChange(event.target.value as MenstrualFlowRecord["flow"])}>{Object.entries(flowLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label>; }
function PeriodField({ periods, value, onChange, english }: { periods: MenstrualPeriod[]; value: string; onChange: (value: string) => void; english: boolean }) { return <label className="field"><span>{english ? "Related period (optional)" : "关联经期（可选）"}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">—</option>{periods.map((item) => <option key={item.id} value={item.id}>{periodLabel(item)}</option>)}</select></label>; }

export function MedicationDoseEditor({ initialDate, periods, presets, record, onClose, onSaved }: { initialDate: string; periods: MenstrualPeriod[]; presets: MedicationPreset[]; record?: MedicationDoseEvent; onClose: () => void; onSaved: Saved }) {
  const { english } = useLocale(), active = periods.find((item) => !item.endedOn) ?? null, now = new Date().toTimeString().slice(0, 5); const initial = record ? compactDateTimeValue(record.takenAt, true) : `${initialDate}T${now}`;
  const [presetId, setPresetId] = useState(String(record?.medicationPresetId ?? presets[0]?.id ?? "")), [date, setDate] = useState(initial.slice(0, 10)), [time, setTime] = useState(initial.slice(11, 16)), [doseText, setDoseText] = useState(record?.doseText ?? ""), [periodId, setPeriodId] = useState(record?.periodId ? String(record.periodId) : ""), [choosePeriod, setChoosePeriod] = useState(Boolean(record && record.periodId !== active?.id)), [notes, setNotes] = useState(record?.notes ?? ""), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { if (!date || !time) throw new Error(english ? "Taken date and time are required" : "实际服药日期和时间均为必填"); const taken = compactDateTimePayload(`${date}T${time}`); await jsonRequest(record ? `/api/health/medication-doses/${record.id}` : "/api/health/medication-doses", { method: record ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ medicationPresetId: Number(presetId), periodId: choosePeriod ? (periodId ? Number(periodId) : null) : record?.periodId ?? null, takenAt: taken.value, doseText, notes }) }); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setSaving(false); } }
  return <FormSheet title={record ? (english ? "Edit dose" : "编辑服药记录") : (english ? "Log dose" : "记录服药")} onClose={onClose} formId="medication-dose-form" submitLabel={english ? "Save" : "保存"} busy={saving}><form id="medication-dose-form" className="weight-settings-form" onSubmit={submit}><label className="field"><span>{english ? "Medication" : "药物"}</span><select required value={presetId} onChange={(event) => setPresetId(event.target.value)}>{presets.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="date-time-field"><label className="field"><span>{english ? "Taken date" : "实际服药日期"}</span><input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="field date-time-clock"><span>{english ? "Taken time" : "实际服药时间"}</span><input required type="time" value={time} onChange={(event) => setTime(event.target.value)} /></label></div><label className="field"><span>{english ? "Amount taken (optional)" : "本次实际用量（可选）"}</span><input maxLength={200} value={doseText} onChange={(event) => setDoseText(event.target.value)} placeholder={english ? "For example: 2 tablets" : "例如：2片"} /></label><label className="weight-reminder-toggle"><span><strong>{english ? "Backfill or choose another period" : "补录或选择其他经期"}</strong><small>{active ? (english ? "Normally linked to the active period automatically." : "日常记录会自动关联当前经期。") : (english ? "Leave off when this dose is unrelated to a period." : "与经期无关时无需选择。")}</small></span><input type="checkbox" checked={choosePeriod} onChange={(event) => setChoosePeriod(event.target.checked)} /></label>{choosePeriod && <PeriodField periods={periods} value={periodId} onChange={setPeriodId} english={english} />}<label className="field"><span>{english ? "Notes" : "备注"}</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}</form></FormSheet>;
}

function MedicationPresetEditor({ record, onClose, onSaved }: { record?: MedicationPreset; onClose: () => void; onSaved: Saved }) {
  const { english } = useLocale(); const [name, setName] = useState(record?.name ?? ""), [dose, setDose] = useState(record?.defaultDoseText ?? ""), [interval, setInterval] = useState(String(record?.minReminderIntervalMinutes ?? 360)), [reminder, setReminder] = useState(record?.reminderEnabled ?? false), [linked, setLinked] = useState(record?.periodLinkEnabled ?? false), [notes, setNotes] = useState(record?.notes ?? ""), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await jsonRequest(record ? `/api/health/medications/${record.id}` : "/api/health/medications", { method: record ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, defaultDoseText: dose, minReminderIntervalMinutes: Number(interval), reminderEnabled: reminder, periodLinkEnabled: linked, notes }) }); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setSaving(false); } }
  return <FormSheet title={record ? (english ? "Edit medication preset" : "编辑药物配置") : (english ? "Add medication preset" : "新增药物配置")} onClose={onClose} formId="medication-preset-form" submitLabel={english ? "Save" : "保存"} busy={saving}><form id="medication-preset-form" className="weight-settings-form" onSubmit={submit}><label className="field"><span>{english ? "Medication name" : "药物名称"}</span><input required maxLength={200} value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>{english ? "Long-term usage note (optional)" : "长期用量说明（可选）"}</span><input maxLength={200} value={dose} onChange={(event) => setDose(event.target.value)} placeholder={english ? "Use the medicine instructions" : "例如：按药品说明记录"} /></label><label className="field"><span>{english ? "Minimum reminder interval (minutes)" : "最小提醒间隔（分钟）"}</span><input required type="number" min={1} max={43200} step={1} value={interval} onChange={(event) => setInterval(event.target.value)} /></label><label className="weight-reminder-toggle"><span><strong>{english ? "Enable reminders" : "开启提醒"}</strong><small>{english ? "After a linked dose, calculate the next optional reminder from this interval." : "记录关联经期的实际服用后，按此间隔计算下一次可选提示。"}</small></span><input type="checkbox" checked={reminder} onChange={(event) => setReminder(event.target.checked)} /></label><label className="weight-reminder-toggle"><span><strong>{english ? "Link during the first three period days" : "经期前三天联动"}</strong><small>{english ? "No dose or interval is inferred from the medication name." : "不会根据药名推断剂量或间隔。"}</small></span><input type="checkbox" checked={linked} onChange={(event) => setLinked(event.target.checked)} /></label><label className="field"><span>{english ? "Notes" : "备注"}</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}</form></FormSheet>;
}
