"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { DateTimeField, compactDateTimePayload, compactDateTimeValue, currentLocalDate } from "@/components/date-time-field";
import { FormSheet } from "@/components/form-sheet";
import { Icon } from "@/components/icons";
import { useLocale } from "@/components/locale-controller";
import { getNativeHostInfo, hostSupports, nativeCall, reconcileNativeNotifications } from "@/lib/native-bridge";
import { playNativeHaptic } from "@/lib/native-haptics";
import { EVAORBIT_TIME_ZONE } from "@/lib/time";
import type { WeightRecord, WeightSettings } from "@/lib/types";
import { formatWeightKg, normalizeWeightKg, type WeightRange, WEIGHT_STEP_KG, weightRecordsInRange, weightTrend } from "@/lib/weight";

const ranges: Array<{ value: WeightRange; label: string }> = [{ value:"7d",label:"7D" },{ value:"30d",label:"30D" },{ value:"90d",label:"90D" },{ value:"1y",label:"1Y" },{ value:"all",label:"ALL" }];
const MIN_WEIGHT=20,MAX_WEIGHT=300,TICK_STEP_KG=.1,TICK_PX=10,SNAP_PX=TICK_PX*WEIGHT_STEP_KG/TICK_STEP_KG;
function errorText(value:unknown,fallback:string){return value&&typeof value==="object"&&"error" in value&&typeof value.error==="string"?value.error:fallback;}

export function WeightSection({ initialRecords, initialSettings, initialFocused }: { initialRecords:WeightRecord[];initialSettings:WeightSettings;initialFocused?:WeightRecord }) {
  const { english }=useLocale();
  const [records,setRecords]=useState(initialRecords),[settings,setSettings]=useState(initialSettings),[range,setRange]=useState<WeightRange>("30d");
  const editableFocus=initialFocused?.source==="manual"?initialFocused:undefined;
  const [editing,setEditing]=useState<WeightRecord|undefined>(editableFocus),[editorOpen,setEditorOpen]=useState(Boolean(editableFocus)),[settingsOpen,setSettingsOpen]=useState(false);
  const [message,setMessage]=useState(""),[error,setError]=useState("");
  const visible=useMemo(()=>weightRecordsInRange(records,range),[records,range]);
  const recent=useMemo(()=>weightRecordsInRange(records,"7d"),[records]);
  const trend=useMemo(()=>weightTrend(visible),[visible]);
  const latest=records[0],previous=records[1],change=latest&&previous?normalizeWeightKg(latest.weightKg-previous.weightKg):null;
  function close(){setEditorOpen(false);setEditing(undefined);const url=new URL(window.location.href);if(url.searchParams.has("weight")){url.searchParams.delete("weight");window.history.replaceState(window.history.state,"",`${url.pathname}${url.search}${url.hash}`);}}
  async function reload(){const response=await fetch("/api/health/weight?limit=1000",{cache:"no-store"});if(response.ok)setRecords(await response.json());}
  return <section className="weight-section health-section" aria-labelledby="weight-title">
    {editorOpen&&<WeightEditor record={editing} initialWeight={latest?.weightKg??65} onClose={close} onSaved={async(syncMessage)=>{await reload();close();setMessage(syncMessage);}}/>}
    {settingsOpen&&<WeightSettingsSheet settings={settings} onClose={()=>setSettingsOpen(false)} onSaved={(next)=>{setSettings(next);setSettingsOpen(false);setMessage(english?"Weight settings saved":"体重设置已保存");}}/>}
    <div className="section-heading"><div><span className="eyebrow">WEIGHT</span><h2 id="weight-title">{english?"Body weight":"体重"}</h2></div><div className="weight-actions"><button className="icon-button subtle" aria-label={english?"Weight settings":"体重设置"} onClick={()=>setSettingsOpen(true)}><Icon name="settings"/></button><button className="text-button training-add" onClick={()=>{setEditing(undefined);setEditorOpen(true);setError("");setMessage("");}}><Icon name="plus"/>{english?"Log weight":"记录体重"}</button></div></div>
    {message&&<p className="form-success" role="status">{message}</p>}{error&&<p className="form-error">{error}</p>}
    <div className="weight-overview"><div className="weight-current"><span>{english?"LATEST":"最近"}</span><strong>{latest?formatWeightKg(latest.weightKg):"—"}</strong><small>{latest?"kg":english?"No records":"暂无记录"}</small></div><dl><div><dt>{english?"Change":"相比上次"}</dt><dd className={change===null?"":change>0?"up":change<0?"down":""}>{change===null?"—":`${change>0?"+":""}${formatWeightKg(change)} kg`}</dd></div><div><dt>{english?"Goal":"目标"}</dt><dd>{settings.targetWeightKg===null?"—":`${formatWeightKg(settings.targetWeightKg)} kg`}</dd></div><div><dt>{english?"Reminder":"提醒"}</dt><dd>{settings.reminderEnabled?settings.reminderTime:english?"Off":"关闭"}</dd></div></dl></div>
    <div className="weight-chart-card"><div className="weight-range-tabs" aria-label={english?"Trend range":"趋势时间范围"}>{ranges.map(item=><button key={item.value} className={range===item.value?"active":""} aria-pressed={range===item.value} onClick={()=>setRange(item.value)}>{item.label}</button>)}</div>{trend.length?<WeightChart points={trend} english={english}/>:<div className="weight-chart-empty">{english?"Add a weight record to see your trend.":"记录体重后即可查看趋势。"}</div>}<div className="weight-chart-legend"><span><i/>{english?"Weight":"体重"}</span><span><i/>{english?"7-day average":"7 日移动平均"}</span></div></div>
    <details className="training-history weight-history"><summary><span><small>{english?"LAST 7 DAYS":"最近 7 天"}</small><strong>{english?"Recent records":"近期记录"}</strong></span><span>{recent.length}</span></summary>
      {recent.length?<div className="weight-record-list">{recent.map(record=><article key={record.id}><button disabled={record.source==="apple_health"} title={record.source==="apple_health"?(english?"Manage imported records in Apple Health":"导入记录请在 Apple 健康中管理"):undefined} onClick={()=>{setEditing(record);setEditorOpen(true);}}><time>{new Date(record.occurredAt).toLocaleString(english?"en":"zh-CN",{month:"short",day:"numeric",hour:record.occurredHasExplicitTime?"2-digit":undefined,minute:record.occurredHasExplicitTime?"2-digit":undefined,timeZone:EVAORBIT_TIME_ZONE})}</time><strong>{formatWeightKg(record.weightKg)} <small>kg</small></strong><span>{record.healthKitSourceName||record.healthKitSourceBundle||(record.source==="apple_health"?"Apple Health":"EvaOrbit")}</span>{record.source==="manual"&&<Icon name="edit"/>}</button></article>)}</div>:<p className="health-inline-empty">{english?"No weight records in the last 7 days.":"最近 7 天没有体重记录。"}</p>}
      <p className="training-history-note">{english?"Earlier records stay available in Home Calendar + Timeline.":"更早记录请通过首页 Calendar + Timeline 查看。"}</p>
    </details>
  </section>;
}

function WeightChart({points,english}:{points:Array<{date:string;weightKg:number;movingAverageKg:number}>;english:boolean}){
  const [selected,setSelected]=useState<number|null>(null);
  const width=640,height=190,left=50,right=18,padY=22;const values=points.flatMap(point=>[point.weightKg,point.movingAverageKg]);const dataMin=Math.min(...values),dataMax=Math.max(...values),min=Math.floor(dataMin),max=Math.max(min+1,Math.ceil(dataMax)),span=max-min;
  const tickStep=Math.max(1,Math.ceil(span/4)),ticks=Array.from({length:Math.floor(span/tickStep)+1},(_,index)=>min+index*tickStep).filter(value=>value<=max);if(ticks.at(-1)!==max)ticks.push(max);
  const x=(index:number)=>points.length===1?(left+width-right)/2:left+index*(width-left-right)/(points.length-1),y=(value:number)=>padY+(max-value)*(height-padY*2)/span;
  const path=(key:"weightKg"|"movingAverageKg")=>points.map((point,index)=>`${index?"L":"M"}${x(index).toFixed(1)} ${y(point[key]).toFixed(1)}`).join(" ");
  function selectAt(event:React.PointerEvent<SVGSVGElement>){const bounds=event.currentTarget.getBoundingClientRect(),chartX=(event.clientX-bounds.left)*width/bounds.width,index=points.length===1?0:Math.round((chartX-left)/(width-left-right)*(points.length-1));setSelected(Math.max(0,Math.min(points.length-1,index)));}
  const point=selected===null?null:points[selected],pointX=selected===null?0:x(selected),pointY=point?y(point.weightKg):0,tipWidth=english?154:142,tipX=Math.min(width-tipWidth-4,Math.max(4,pointX-tipWidth/2)),tipY=Math.max(4,pointY-43);
  return <svg className="weight-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={english?`Weight trend from ${points[0].date} to ${points.at(-1)!.date}`:`${points[0].date} 至 ${points.at(-1)!.date} 的体重趋势`} onPointerDown={selectAt} onPointerMove={selectAt}>
    {ticks.map(tick=><g className="weight-axis" key={tick}><line x1={left} x2={width-right} y1={y(tick)} y2={y(tick)}/><text x={left-9} y={y(tick)+3} textAnchor="end">{tick.toFixed(1)}</text></g>)}
    <path className="weight-average-line" d={path("movingAverageKg")}/><path className="weight-raw-line" d={path("weightKg")}/>
    {points.map((item,index)=><g className="weight-point" key={item.date}><circle className="weight-point-dot" cx={x(index)} cy={y(item.weightKg)} r="3"/><circle className="weight-point-hit" cx={x(index)} cy={y(item.weightKg)} r="10" tabIndex={0} role="button" aria-label={`${item.date}, ${formatWeightKg(item.weightKg)} kg`} onPointerDown={()=>setSelected(index)} onPointerEnter={()=>setSelected(index)} onFocus={()=>setSelected(index)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setSelected(index);}}}/></g>)}
    {point&&<g className="weight-chart-tooltip" aria-hidden="true"><rect x={tipX} y={tipY} width={tipWidth} height="34" rx="9"/><text x={tipX+10} y={tipY+21}>{point.date} · {formatWeightKg(point.weightKg)} kg</text></g>}
  </svg>;
}

function WeightEditor({record,initialWeight,onClose,onSaved}:{record?:WeightRecord;initialWeight:number;onClose:()=>void;onSaved:(message:string)=>void|Promise<void>}){
  const {english}=useLocale();const [weight,setWeight]=useState(normalizeWeightKg(record?.weightKg??initialWeight)),[occurredAt,setOccurredAt]=useState(record?compactDateTimeValue(record.occurredAt,record.occurredHasExplicitTime):`${currentLocalDate()}T${new Date().toTimeString().slice(0,5)}`),[saving,setSaving]=useState(false),[error,setError]=useState("");
  async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");try{const occurred=compactDateTimePayload(occurredAt);const response=await fetch(record?`/api/health/weight/${record.id}`:"/api/health/weight",{method:record?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({occurredAt:occurred.value,occurredHasExplicitTime:occurred.hasExplicitTime,weightKg:weight})});const result=await response.json().catch(()=>null) as WeightRecord|{error?:string}|null;if(!response.ok)throw new Error(errorText(result,english?"Could not save weight":"保存体重失败"));const saved=result as WeightRecord;let note=english?"Weight saved":"体重已保存";const info=await getNativeHostInfo();if(saved.healthKitSyncIdentifier&&hostSupports(info,"healthkit.saveBodyMass")){try{await nativeCall("healthkit.saveBodyMass",{weightKg:saved.weightKg,occurredAt:saved.occurredAt,syncIdentifier:saved.healthKitSyncIdentifier,syncVersion:saved.healthKitSyncVersion});note=english?"Weight saved and queued for Apple Health":"体重已保存并写入 Apple Health";}catch{note=english?"Weight saved; Apple Health write needs retry":"体重已保存，Apple Health 写入需重试";}}try{await reconcileNativeNotifications();}catch{/* Web Push still checks the saved record at delivery time. */}playNativeHaptic("success");await onSaved(note);}catch(reason){playNativeHaptic("error");setError(reason instanceof Error?reason.message:String(reason));}finally{setSaving(false);}}
  return <FormSheet title={record?(english?"Edit weight":"编辑体重"):(english?"Log weight":"记录体重")} onClose={onClose} formId="weight-entry-form" submitLabel={record?(english?"Save changes":"保存修改"):(english?"Save weight":"保存体重")} busy={saving}><form id="weight-entry-form" className="weight-entry-form" onSubmit={submit}><div className="weight-entry-value"><strong>{formatWeightKg(weight)}</strong><span>kg</span></div><WeightRuler value={weight} onChange={setWeight}/><DateTimeField label={english?"Date and time":"日期与时间"} value={{date:occurredAt.slice(0,10),time:occurredAt.length>10?occurredAt.slice(11,16):""}} onChange={value=>setOccurredAt(value.date+(value.time?`T${value.time}`:""))}/>{error&&<p className="form-error">{error}</p>}</form></FormSheet>;
}

function WeightRuler({value,onChange}:{value:number;onChange:(value:number)=>void}){
  const ref=useRef<HTMLDivElement>(null),timer=useRef<number|undefined>(undefined),last=useRef(value);
  const initialValue=useRef(value);
  useEffect(()=>{const element=ref.current;if(element)element.scrollLeft=(initialValue.current-MIN_WEIGHT)/TICK_STEP_KG*TICK_PX;},[]);
  function scroll(){const element=ref.current;if(!element)return;const next=normalizeWeightKg(Math.min(MAX_WEIGHT,Math.max(MIN_WEIGHT,MIN_WEIGHT+element.scrollLeft/TICK_PX*TICK_STEP_KG)));if(next!==last.current){last.current=next;onChange(next);}window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>{const target=Math.round(element.scrollLeft/SNAP_PX)*SNAP_PX;element.scrollTo({left:target,behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});},120);}
  function keyDown(event:React.KeyboardEvent<HTMLDivElement>){const delta=event.key==="ArrowRight"||event.key==="ArrowUp"?WEIGHT_STEP_KG:event.key==="ArrowLeft"||event.key==="ArrowDown"?-WEIGHT_STEP_KG:0;const target=event.key==="Home"?MIN_WEIGHT:event.key==="End"?MAX_WEIGHT:delta?normalizeWeightKg(value+delta):null;if(target===null)return;event.preventDefault();ref.current?.scrollTo({left:(Math.min(MAX_WEIGHT,Math.max(MIN_WEIGHT,target))-MIN_WEIGHT)/TICK_STEP_KG*TICK_PX,behavior:"auto"});}
  const labels=Array.from({length:(MAX_WEIGHT-MIN_WEIGHT)/1+1},(_,index)=>MIN_WEIGHT+index);
  return <div className="weight-ruler-wrap"><span className="weight-ruler-pointer" aria-hidden="true"/><div ref={ref} className="weight-ruler" onScroll={scroll} onKeyDown={keyDown} role="slider" tabIndex={0} aria-valuemin={MIN_WEIGHT} aria-valuemax={MAX_WEIGHT} aria-valuenow={value} aria-valuetext={`${formatWeightKg(value)} kilograms`} aria-label="Weight in kilograms"><div className="weight-ruler-spacer"/><div className="weight-ruler-track">{labels.map(label=><span key={label} style={{left:`${(label-MIN_WEIGHT)/TICK_STEP_KG*TICK_PX}px`}}>{label}</span>)}</div><div className="weight-ruler-spacer"/></div></div>;
}

function WeightSettingsSheet({settings,onClose,onSaved}:{settings:WeightSettings;onClose:()=>void;onSaved:(value:WeightSettings)=>void}){
  const {english}=useLocale();const [target,setTarget]=useState(settings.targetWeightKg===null?"":String(settings.targetWeightKg)),[enabled,setEnabled]=useState(settings.reminderEnabled),[time,setTime]=useState(settings.reminderTime),[saving,setSaving]=useState(false),[error,setError]=useState("");
  async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/preferences/weight",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetWeightKg:target?Number(target):null,reminderEnabled:enabled,reminderTime:time})});const result=await response.json() as WeightSettings&{error?:string};if(!response.ok)throw new Error(result.error);onSaved(result);try{await reconcileNativeNotifications();}catch{/* Browser delivery remains available. */}}catch(reason){setError(reason instanceof Error?reason.message:"Could not save settings");}finally{setSaving(false);}}
  return <FormSheet title={english?"Weight settings":"体重设置"} onClose={onClose} formId="weight-settings-form" submitLabel={english?"Save settings":"保存设置"} busy={saving}><form id="weight-settings-form" className="weight-settings-form" onSubmit={submit}><label className="field"><span>{english?"Goal weight (kg)":"目标体重（kg）"}</span><input type="number" min="20" max="500" step="0.05" value={target} onChange={event=>setTarget(event.target.value)}/></label><label className="weight-reminder-toggle"><span><strong>{english?"Daily reminder":"每日记录提醒"}</strong><small>{english?"Skipped automatically after a weight is logged that day.":"当天已有体重记录时自动跳过。"}</small></span><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/></label>{enabled&&<label className="field"><span>{english?"Reminder time":"提醒时间"}</span><input required type="time" value={time} onChange={event=>setTime(event.target.value)}/></label>}{error&&<p className="form-error">{error}</p>}</form></FormSheet>;
}
