begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 300),
  notes text not null default '',
  completed boolean not null default false,
  due_date date,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  tags text[] not null default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 300),
  content text not null,
  category text not null default '其他',
  search_text text generated always as (title || ' ' || content) stored,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.ai_settings (
  user_id uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  provider_preset text not null default 'openai',
  provider_name text not null default 'OpenAI',
  base_url text not null default 'https://api.openai.com/v1',
  model text not null default 'gpt-4o-mini',
  enabled boolean not null default false,
  temperature double precision not null default 0.6 check (temperature between 0 and 2),
  system_prompt text not null default '',
  response_length text not null default 'balanced' check (response_length in ('brief', 'balanced', 'detailed')),
  initiative text not null default 'quiet' check (initiative in ('quiet', 'balanced', 'active')),
  allow_suggestions boolean not null default true,
  allow_teasing boolean not null default true,
  include_tasks boolean not null default true,
  include_memories boolean not null default true,
  allow_write_actions boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chat_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null default '新对话',
  model text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  session_id bigint not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  model text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint chat_messages_owned_session_fk foreign key (session_id, user_id)
    references public.chat_sessions(id, user_id) on delete cascade
);

create index if not exists idx_tasks_user_completed_due on public.tasks(user_id, completed, due_date);
create index if not exists idx_memories_user_category on public.memories(user_id, category);
create index if not exists idx_memories_search_text on public.memories using gin (to_tsvector('simple', search_text));
create index if not exists idx_chat_sessions_user_updated on public.chat_sessions(user_id, updated_at desc);
create index if not exists idx_chat_messages_user_session on public.chat_messages(user_id, session_id, id);

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks for each row execute function public.set_updated_at();
drop trigger if exists memories_set_updated_at on public.memories;
create trigger memories_set_updated_at before update on public.memories for each row execute function public.set_updated_at();
drop trigger if exists ai_settings_set_updated_at on public.ai_settings;
create trigger ai_settings_set_updated_at before update on public.ai_settings for each row execute function public.set_updated_at();
drop trigger if exists chat_sessions_set_updated_at on public.chat_sessions;
create trigger chat_sessions_set_updated_at before update on public.chat_sessions for each row execute function public.set_updated_at();

alter table public.tasks enable row level security;
alter table public.memories enable row level security;
alter table public.ai_settings enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;

do $$
declare
  table_name text;
  operation text;
begin
  foreach table_name in array array['tasks', 'memories', 'ai_settings', 'chat_sessions', 'chat_messages'] loop
    foreach operation in array array['select', 'insert', 'update', 'delete'] loop
      execute format('drop policy if exists %I on public.%I', table_name || '_owner_' || operation, table_name);
      if operation = 'insert' then
        execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_owner_' || operation, table_name);
      elsif operation = 'update' then
        execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id) with check ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_owner_' || operation, table_name);
      else
        execute format('create policy %I on public.%I for %s to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_owner_' || operation, table_name, operation);
      end if;
    end loop;
  end loop;
end;
$$;

revoke all on public.tasks, public.memories, public.ai_settings, public.chat_sessions, public.chat_messages from anon;
grant select, insert, update, delete on public.tasks, public.memories, public.ai_settings, public.chat_sessions, public.chat_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
