begin;

create table if not exists public.media_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 300),
  media_type text not null check (media_type in ('movie','tv','anime','documentary','other')),
  rating text check (rating is null or rating ~ '^(goat|dope|mid|nope|shit)[+-]?$'),
  note text,
  cover_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id)
);

create table if not exists public.media_viewings (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  media_id bigint not null,
  watched_date date not null,
  viewing_number integer not null check (viewing_number > 0),
  created_at timestamptz not null default timezone('utc', now()),
  constraint media_viewings_item_owner_fk foreign key (media_id, user_id)
    references public.media_items(id, user_id) on delete cascade,
  constraint media_viewings_number_unique unique (media_id, viewing_number)
    deferrable initially deferred
);

create index if not exists idx_media_items_user_type_title
  on public.media_items(user_id, media_type, title);
create index if not exists idx_media_viewings_user_media_date
  on public.media_viewings(user_id, media_id, watched_date desc);

drop trigger if exists media_items_set_updated_at on public.media_items;
create trigger media_items_set_updated_at
before update on public.media_items
for each row execute function public.set_updated_at();

create or replace function public.assign_media_viewing_number()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  perform 1
    from public.media_items
    where id = new.media_id and user_id = new.user_id
    for update;
  new.viewing_number := coalesce((
    select max(viewing_number)
    from public.media_viewings
    where media_id = new.media_id and user_id = new.user_id
  ), 0) + 1;
  return new;
end;
$$;

drop trigger if exists media_viewings_assign_number on public.media_viewings;
create trigger media_viewings_assign_number
before insert on public.media_viewings
for each row execute function public.assign_media_viewing_number();

create or replace function public.renumber_media_viewings_after_delete()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.media_viewings as viewing
  set viewing_number = numbered.next_number
  from (
    select id, row_number() over (order by viewing_number, id)::integer as next_number
    from public.media_viewings
    where media_id = old.media_id and user_id = old.user_id
  ) as numbered
  where viewing.id = numbered.id
    and viewing.viewing_number <> numbered.next_number;
  return old;
end;
$$;

drop trigger if exists media_viewings_renumber_after_delete on public.media_viewings;
create trigger media_viewings_renumber_after_delete
after delete on public.media_viewings
for each row execute function public.renumber_media_viewings_after_delete();

revoke all on function public.assign_media_viewing_number() from public;
revoke all on function public.renumber_media_viewings_after_delete() from public;

alter table public.media_items enable row level security;
alter table public.media_viewings enable row level security;

drop policy if exists media_items_owner_select on public.media_items;
create policy media_items_owner_select on public.media_items for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists media_items_owner_insert on public.media_items;
create policy media_items_owner_insert on public.media_items for insert to authenticated
  with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);
drop policy if exists media_items_owner_update on public.media_items;
create policy media_items_owner_update on public.media_items for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists media_items_owner_delete on public.media_items;
create policy media_items_owner_delete on public.media_items for delete to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists media_viewings_owner_select on public.media_viewings;
create policy media_viewings_owner_select on public.media_viewings for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists media_viewings_owner_insert on public.media_viewings;
create policy media_viewings_owner_insert on public.media_viewings for insert to authenticated
  with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);
drop policy if exists media_viewings_owner_update on public.media_viewings;
create policy media_viewings_owner_update on public.media_viewings for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists media_viewings_owner_delete on public.media_viewings;
create policy media_viewings_owner_delete on public.media_viewings for delete to authenticated
  using ((select auth.uid()) = user_id and viewing_number > 1);

revoke all on table public.media_items, public.media_viewings from public, anon;
grant select, insert, update, delete on table public.media_items to authenticated;
grant select, insert, delete on table public.media_viewings to authenticated;
grant update (watched_date) on table public.media_viewings to authenticated;
revoke all on sequence public.media_items_id_seq, public.media_viewings_id_seq from public, anon;
grant usage, select on sequence public.media_items_id_seq, public.media_viewings_id_seq to authenticated;

commit;
