create table if not exists public.chronicle_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  date date not null,
  title text not null check (char_length(btrim(title)) between 1 and 300),
  content_md text not null check (char_length(content_md) between 1 and 100000),
  source text not null default 'manual' check (source in ('manual', 'chatgpt')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id)
);

create index if not exists idx_chronicle_entries_user_date
  on public.chronicle_entries(user_id, date desc, id desc);

drop trigger if exists chronicle_entries_set_updated_at on public.chronicle_entries;
create trigger chronicle_entries_set_updated_at
before update on public.chronicle_entries
for each row execute function public.set_updated_at();

alter table public.chronicle_entries enable row level security;

drop policy if exists chronicle_entries_owner_select on public.chronicle_entries;
create policy chronicle_entries_owner_select on public.chronicle_entries for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists chronicle_entries_owner_insert on public.chronicle_entries;
create policy chronicle_entries_owner_insert on public.chronicle_entries for insert to authenticated
  with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);
drop policy if exists chronicle_entries_owner_update on public.chronicle_entries;
create policy chronicle_entries_owner_update on public.chronicle_entries for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists chronicle_entries_owner_delete on public.chronicle_entries;
create policy chronicle_entries_owner_delete on public.chronicle_entries for delete to authenticated
  using ((select auth.uid()) = user_id);

grant select, insert, delete on table public.chronicle_entries to authenticated;
grant update (date, title, content_md, source) on table public.chronicle_entries to authenticated;
grant usage, select on sequence public.chronicle_entries_id_seq to authenticated;
