begin;

create table if not exists public.training_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  occurred_at timestamptz not null,
  occurred_has_explicit_time boolean not null default false,
  training_type text not null check (training_type in ('cardio','strength','mixed')),
  body_parts jsonb not null default '[]'::jsonb check (jsonb_typeof(body_parts) = 'array'),
  teacher text not null default '',
  course text not null default '',
  duration_minutes integer check (duration_minutes is null or duration_minutes > 0),
  notes text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_training_logs_user_occurred on public.training_logs(user_id, occurred_at desc);

drop trigger if exists training_logs_set_updated_at on public.training_logs;
create trigger training_logs_set_updated_at before update on public.training_logs
for each row execute function public.set_updated_at();

alter table public.training_logs enable row level security;
drop policy if exists training_logs_owner_select on public.training_logs;
create policy training_logs_owner_select on public.training_logs for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists training_logs_owner_insert on public.training_logs;
create policy training_logs_owner_insert on public.training_logs for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);
drop policy if exists training_logs_owner_update on public.training_logs;
create policy training_logs_owner_update on public.training_logs for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists training_logs_owner_delete on public.training_logs;
create policy training_logs_owner_delete on public.training_logs for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on table public.training_logs from public, anon;
grant select, insert, update, delete on table public.training_logs to authenticated;
revoke all on sequence public.training_logs_id_seq from public, anon;
grant usage, select on sequence public.training_logs_id_seq to authenticated;

commit;
