create table if not exists public.migration_import_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_system text not null,
  source_id text not null,
  resource text not null check (resource in ('memo', 'chronicle', 'lucius_diary', 'lucius_case')),
  target_id bigint not null check (target_id > 0),
  source_url text,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  imported_at timestamptz not null default timezone('utc', now()),
  payload_hash text not null check (char_length(payload_hash) = 64),
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, source_system, source_id)
);

create index if not exists idx_migration_import_ledger_target
  on public.migration_import_ledger(user_id, resource, target_id);

alter table public.migration_import_ledger enable row level security;
revoke all on table public.migration_import_ledger from anon, authenticated;
revoke all on sequence public.migration_import_ledger_id_seq from anon, authenticated;
