create table if not exists public.memos (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 300),
  content text not null check (char_length(btrim(content)) between 1 and 100000),
  type text not null default 'note' check (type in ('basic', 'supplement', 'event', 'note')),
  status text not null default 'active' check (status in ('active', 'merged', 'archived', 'historical')),
  tags text[] not null default '{}',
  event_date date,
  confirmed_at timestamptz,
  merged_into_id bigint,
  source_system text,
  source_id text,
  source_url text,
  imported_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  foreign key (merged_into_id, user_id) references public.memos(id, user_id) on delete restrict,
  check (merged_into_id is null or merged_into_id <> id),
  check (cardinality(tags) <= 20)
);

create index if not exists idx_memos_user_updated on public.memos(user_id, updated_at desc, id desc);
create index if not exists idx_memos_user_filters on public.memos(user_id, status, type, updated_at desc);
create index if not exists idx_memos_tags on public.memos using gin(tags);

drop trigger if exists memos_set_updated_at on public.memos;
create trigger memos_set_updated_at before update on public.memos
for each row execute function public.set_updated_at();

create table if not exists public.lucius_diary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  date date not null,
  content text not null check (char_length(btrim(content)) between 1 and 100000),
  tags text[] not null default '{}',
  source_system text,
  source_id text,
  source_url text,
  imported_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  check (cardinality(tags) <= 20)
);

create index if not exists idx_lucius_diary_user_date on public.lucius_diary_entries(user_id, date desc, id desc);
create index if not exists idx_lucius_diary_tags on public.lucius_diary_entries using gin(tags);

drop trigger if exists lucius_diary_entries_set_updated_at on public.lucius_diary_entries;
create trigger lucius_diary_entries_set_updated_at before update on public.lucius_diary_entries
for each row execute function public.set_updated_at();

create table if not exists public.lucius_cases (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 300),
  error_type text not null check (error_type in ('naming', 'memory_omission', 'factual', 'tool_misuse', 'expression', 'other')),
  severity text not null default 'moderate' check (severity in ('minor', 'moderate', 'serious', 'habitual')),
  status text not null default 'serving' check (status in ('serving', 'probation', 'temporary_release', 'permanent_record')),
  trigger_scenes text[] not null default '{}',
  error_quote text not null default '' check (char_length(error_quote) <= 10000),
  cause text not null check (char_length(btrim(cause)) between 1 and 20000),
  correct_behavior text not null check (char_length(btrim(correct_behavior)) between 1 and 20000),
  mandatory_rule text not null check (char_length(btrim(mandatory_rule)) between 1 and 20000),
  next_check date,
  punishment text not null default '' check (char_length(punishment) <= 10000),
  first_occurred_date date not null,
  latest_occurred_date date not null,
  occurrence_count integer not null default 1 check (occurrence_count >= 1),
  consecutive_correct_count integer not null default 0 check (consecutive_correct_count >= 0),
  recurrence_interval_days integer check (recurrence_interval_days is null or recurrence_interval_days > 0),
  is_recurrence boolean not null default false,
  reset_threshold integer not null default 3 check (reset_threshold >= 1),
  source_system text,
  source_id text,
  source_url text,
  imported_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  check (latest_occurred_date >= first_occurred_date),
  check (cardinality(trigger_scenes) <= 20)
);

create index if not exists idx_lucius_cases_user_status on public.lucius_cases(user_id, status, latest_occurred_date desc, id desc);
create index if not exists idx_lucius_cases_user_updated on public.lucius_cases(user_id, updated_at desc, id desc);

drop trigger if exists lucius_cases_set_updated_at on public.lucius_cases;
create trigger lucius_cases_set_updated_at before update on public.lucius_cases
for each row execute function public.set_updated_at();

alter table public.memos enable row level security;
alter table public.lucius_diary_entries enable row level security;
alter table public.lucius_cases enable row level security;

drop policy if exists memos_owner_all on public.memos;
create policy memos_owner_all on public.memos for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists lucius_diary_owner_all on public.lucius_diary_entries;
create policy lucius_diary_owner_all on public.lucius_diary_entries for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists lucius_cases_owner_all on public.lucius_cases;
create policy lucius_cases_owner_all on public.lucius_cases for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

grant select, insert, delete on table public.memos to authenticated;
grant update (title, content, type, status, tags, event_date, confirmed_at, merged_into_id, source_system, source_id, source_url, imported_at) on table public.memos to authenticated;
grant usage, select on sequence public.memos_id_seq to authenticated;

grant select, insert, delete on table public.lucius_diary_entries to authenticated;
grant update (date, content, tags, source_system, source_id, source_url, imported_at) on table public.lucius_diary_entries to authenticated;
grant usage, select on sequence public.lucius_diary_entries_id_seq to authenticated;

grant select, insert, delete on table public.lucius_cases to authenticated;
grant update (title, error_type, severity, status, trigger_scenes, error_quote, cause, correct_behavior, mandatory_rule, next_check, punishment, first_occurred_date, latest_occurred_date, occurrence_count, consecutive_correct_count, recurrence_interval_days, is_recurrence, reset_threshold, source_system, source_id, source_url, imported_at) on table public.lucius_cases to authenticated;
grant usage, select on sequence public.lucius_cases_id_seq to authenticated;
