begin;

create table if not exists public.inbox_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  content text not null, status text not null default 'inbox' check (status in ('inbox','processed','archived')),
  source text not null default 'manual', processed_at timestamptz, converted_type text, converted_id bigint,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.food_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  occurred_at timestamptz not null, meal_type text not null check (meal_type in ('breakfast','lunch','dinner','snack','late_night')),
  title text not null, description text not null default '', search_text text generated always as (title || ' ' || description) stored, portion text not null default '',
  scene text not null default 'other' check (scene in ('home','delivery','restaurant','packaged_food','other')),
  estimated_kcal double precision, kcal_min double precision, kcal_max double precision,
  confidence text not null default 'low' check (confidence in ('high','medium','low')), notes text not null default '',
  image_url text, attachment_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check (kcal_min is null or kcal_max is null or kcal_min <= kcal_max)
);

create table if not exists public.food_library (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null, brand text not null default '', category text not null default 'other' check (category in ('staple','dish','snack','drink','other')),
  default_portion text not null default '', reference_type text not null default 'per_serving' check (reference_type in ('per_100g','per_100ml','per_serving')),
  reference_energy_kj double precision, reference_kcal double precision, serving_weight double precision, serving_kcal double precision,
  data_source text not null default 'manual' check (data_source in ('package_label','official','estimated','manual')),
  notes text not null default '', updated_at timestamptz not null default now(), unique(user_id,name,brand), unique(id,user_id)
);

create table if not exists public.drink_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  occurred_at timestamptz not null, name text not null, brand text not null default '',
  drink_type text not null default 'other' check (drink_type in ('coffee','milk_tea','tea','soda','juice','water','alcohol','other')),
  volume_ml double precision, sugar_level text not null default '', caffeine_mg double precision,
  estimated_kcal double precision, kcal_min double precision, kcal_max double precision,
  confidence text not null default 'low' check (confidence in ('high','medium','low')),
  food_library_id bigint, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  foreign key(food_library_id,user_id) references public.food_library(id,user_id) on delete set null,
  check (kcal_min is null or kcal_max is null or kcal_min <= kcal_max)
);

create table if not exists public.drink_limits (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null, target_type text not null, period text not null check (period in ('daily','weekly')),
  limit_value integer not null check (limit_value > 0), enabled boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.daily_nutrition_summaries (
  date date not null, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  resting_energy_kcal double precision, active_energy_kcal double precision, notes text not null default '', updated_at timestamptz not null default now(),
  primary key(date,user_id)
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  endpoint text not null, p256dh text not null, auth text not null,
  created_at timestamptz not null default now(), last_used_at timestamptz not null default now(), unique(user_id,endpoint)
);

create index if not exists idx_inbox_user_status on public.inbox_items(user_id,status,created_at desc);
create index if not exists idx_food_logs_user_occurred on public.food_logs(user_id,occurred_at desc);
create index if not exists idx_food_logs_search on public.food_logs using gin(to_tsvector('simple',search_text));
create index if not exists idx_food_library_user_name_brand on public.food_library(user_id,name,brand);
create index if not exists idx_drink_logs_user_occurred on public.drink_logs(user_id,occurred_at desc);

do $$
declare table_name text;
begin
  foreach table_name in array array['inbox_items','food_logs','food_library','drink_logs','drink_limits','daily_nutrition_summaries','push_subscriptions'] loop
    execute format('drop trigger if exists %I on public.%I', table_name || '_set_updated_at', table_name);
    if table_name <> 'push_subscriptions' then
      execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', table_name || '_set_updated_at', table_name);
    end if;
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end;
$$;

do $$
declare table_name text; operation text;
begin
  foreach table_name in array array['inbox_items','food_logs','food_library','drink_logs','drink_limits','daily_nutrition_summaries','push_subscriptions'] loop
    foreach operation in array array['select','insert','update','delete'] loop
      execute format('drop policy if exists %I on public.%I', table_name || '_owner_' || operation, table_name);
      if operation = 'insert' then
        execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_owner_' || operation, table_name);
      elsif operation = 'update' then
        execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id) with check ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_owner_' || operation, table_name);
      else
        execute format('create policy %I on public.%I for %s to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_owner_' || operation, table_name, operation);
      end if;
    end loop;
  end loop;
end;
$$;

revoke all on public.inbox_items,public.food_logs,public.food_library,public.drink_logs,public.drink_limits,public.daily_nutrition_summaries,public.push_subscriptions from anon;
grant select,insert,update,delete on public.inbox_items,public.food_logs,public.food_library,public.drink_logs,public.drink_limits,public.daily_nutrition_summaries,public.push_subscriptions to authenticated;
grant usage,select on all sequences in schema public to authenticated;

commit;
