begin;

create table if not exists public.health_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  occurred_at timestamptz not null,
  type text not null check (type in ('symptom','medication','visit','test','condition','treatment','measurement','note')),
  title text not null,
  summary text not null default '',
  status text not null default 'active' check (status in ('active','resolved')),
  started_at timestamptz,
  ended_at timestamptz,
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (started_at is null or ended_at is null or ended_at >= started_at)
);

create index if not exists idx_health_records_user_occurred
  on public.health_records(user_id, occurred_at desc);
create index if not exists idx_health_records_active
  on public.health_records(user_id, occurred_at desc)
  where status = 'active';

drop trigger if exists health_records_set_updated_at on public.health_records;
create trigger health_records_set_updated_at
before update on public.health_records
for each row execute function public.set_updated_at();

alter table public.health_records enable row level security;

drop policy if exists health_records_owner_select on public.health_records;
create policy health_records_owner_select
  on public.health_records for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists health_records_owner_insert on public.health_records;
create policy health_records_owner_insert
  on public.health_records for insert to authenticated
  with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists health_records_owner_update on public.health_records;
create policy health_records_owner_update
  on public.health_records for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists health_records_owner_delete on public.health_records;
create policy health_records_owner_delete
  on public.health_records for delete to authenticated
  using ((select auth.uid()) = user_id);

revoke all on table public.health_records from public, anon;
grant select, insert, update, delete on table public.health_records to authenticated;
revoke all on sequence public.health_records_id_seq from public, anon;
grant usage, select on sequence public.health_records_id_seq to authenticated;

commit;
