create table if not exists public.lucius_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  content text not null check (char_length(btrim(content)) between 1 and 1000),
  published_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_lucius_posts_user_published
  on public.lucius_posts(user_id, published_at desc, id desc);

drop trigger if exists lucius_posts_set_updated_at on public.lucius_posts;
create trigger lucius_posts_set_updated_at before update on public.lucius_posts
for each row execute function public.set_updated_at();

alter table public.lucius_posts enable row level security;

drop policy if exists lucius_posts_owner_all on public.lucius_posts;
create policy lucius_posts_owner_all on public.lucius_posts for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

grant select, insert, delete on table public.lucius_posts to authenticated;
grant update (content, published_at) on table public.lucius_posts to authenticated;
grant usage, select on sequence public.lucius_posts_id_seq to authenticated;
