begin;

create table if not exists public.task_reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  task_id bigint not null references public.tasks(id) on delete cascade,
  reminder_id bigint unique references public.reminders(id) on delete set null,
  trigger_type text not null check (trigger_type in ('absolute', 'relative')),
  absolute_date date,
  absolute_time time,
  relative_to text check (relative_to in ('due')),
  offset_minutes integer,
  timezone text not null default 'Asia/Shanghai',
  repeat_while_overdue boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint task_reminders_trigger_shape check (
    (trigger_type = 'absolute' and absolute_date is not null and absolute_time is not null and relative_to is null and offset_minutes is null)
    or
    (trigger_type = 'relative' and absolute_date is null and absolute_time is null and relative_to = 'due' and offset_minutes is not null)
  ),
  unique (id, user_id)
);

create index if not exists idx_task_reminders_task on public.task_reminders(user_id, task_id, id);
create unique index if not exists idx_task_reminder_projection on public.reminders(user_id, source_type, source_id) where source_type = 'task_reminder';

alter table public.reminders add column if not exists overdue_after timestamptz;

drop trigger if exists set_task_reminders_updated_at on public.task_reminders;
create trigger set_task_reminders_updated_at before update on public.task_reminders
for each row execute function public.set_updated_at();

alter table public.task_reminders enable row level security;
drop policy if exists task_reminders_owner_all on public.task_reminders;
create policy task_reminders_owner_all on public.task_reminders
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant select, insert, update, delete on public.task_reminders to authenticated;
grant usage, select on sequence public.task_reminders_id_seq to authenticated;

insert into public.task_reminders (user_id, task_id, reminder_id, trigger_type, relative_to, offset_minutes, timezone, repeat_while_overdue)
select t.user_id, t.id, t.reminder_id, 'relative', 'due', 0, coalesce(r.timezone, 'Asia/Shanghai'), coalesce(r.repeat_while_overdue, false)
from public.tasks t
join public.reminders r on r.id = t.reminder_id
where not exists (select 1 from public.task_reminders tr where tr.user_id = t.user_id and tr.task_id = t.id);

update public.reminders r
set source_type = 'task_reminder', source_id = tr.id,
    overdue_after = case when t.due_date is not null and t.due_time is not null
      then ((t.due_date + t.due_time) at time zone tr.timezone)
      else null end
from public.task_reminders tr
join public.tasks t on t.id = tr.task_id and t.user_id = tr.user_id
where r.id = tr.reminder_id;

commit;
