begin;

create table if not exists public.trackers (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  icon text not null default '◉' check (char_length(icon) between 1 and 16),
  group_name text not null default '日常' check (char_length(group_name) <= 60),
  time_type text not null default 'point' check (time_type in ('point','range')),
  quick_capture_enabled boolean not null default true,
  data_source_type text not null default 'native_tracker' check (data_source_type in ('native_tracker','linked_source')),
  source_config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id)
);

create table if not exists public.tracker_fields (
  id bigint generated by default as identity primary key,
  tracker_id bigint not null,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 60),
  type text not null check (type in ('number','single_select','multi_select','text','boolean','rating')),
  required boolean not null default false,
  default_value jsonb,
  options_json jsonb not null default '[]'::jsonb,
  show_after_quick_capture boolean not null default false,
  include_in_stats boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key (tracker_id, user_id) references public.trackers(id, user_id) on delete cascade
);

create table if not exists public.tracker_entries (
  id bigint generated by default as identity primary key,
  tracker_id bigint not null,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  occurred_at timestamptz not null,
  end_at timestamptz,
  values_json jsonb not null default '{}'::jsonb,
  note text not null default '' check (char_length(note) <= 5000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key (tracker_id, user_id) references public.trackers(id, user_id) on delete cascade,
  check (end_at is null or end_at >= occurred_at)
);

create table if not exists public.tracker_goals (
  id bigint generated by default as identity primary key,
  tracker_id bigint not null,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  operator text not null check (operator in ('<=','>=','=')),
  target_value double precision not null check (target_value > 0),
  period_type text not null check (period_type in ('daily','weekly','monthly','yearly','custom')),
  custom_period text not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key (tracker_id, user_id) references public.trackers(id, user_id) on delete cascade
);

create table if not exists public.tracker_reminders (
  id bigint generated by default as identity primary key,
  tracker_id bigint not null,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  reminder_type text not null check (reminder_type in ('scheduled','interval')),
  schedule_rule text not null default '',
  interval_days integer check (interval_days is null or interval_days > 0),
  enabled boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key (tracker_id, user_id) references public.trackers(id, user_id) on delete cascade,
  check ((reminder_type='scheduled' and char_length(schedule_rule)>0) or (reminder_type='interval' and interval_days is not null))
);

create index if not exists idx_trackers_user_group on public.trackers(user_id, group_name, updated_at desc);
create index if not exists idx_tracker_fields_tracker on public.tracker_fields(user_id, tracker_id, sort_order, id);
create index if not exists idx_tracker_entries_tracker_time on public.tracker_entries(user_id, tracker_id, occurred_at desc);
create index if not exists idx_tracker_entries_time on public.tracker_entries(user_id, occurred_at desc);
create index if not exists idx_tracker_goals_tracker on public.tracker_goals(user_id, tracker_id, enabled);
create index if not exists idx_tracker_reminders_tracker on public.tracker_reminders(user_id, tracker_id, enabled);

drop trigger if exists trackers_set_updated_at on public.trackers;
create trigger trackers_set_updated_at before update on public.trackers for each row execute function public.set_updated_at();
drop trigger if exists tracker_fields_set_updated_at on public.tracker_fields;
create trigger tracker_fields_set_updated_at before update on public.tracker_fields for each row execute function public.set_updated_at();
drop trigger if exists tracker_entries_set_updated_at on public.tracker_entries;
create trigger tracker_entries_set_updated_at before update on public.tracker_entries for each row execute function public.set_updated_at();
drop trigger if exists tracker_goals_set_updated_at on public.tracker_goals;
create trigger tracker_goals_set_updated_at before update on public.tracker_goals for each row execute function public.set_updated_at();
drop trigger if exists tracker_reminders_set_updated_at on public.tracker_reminders;
create trigger tracker_reminders_set_updated_at before update on public.tracker_reminders for each row execute function public.set_updated_at();

alter table public.trackers enable row level security;
alter table public.tracker_fields enable row level security;
alter table public.tracker_entries enable row level security;
alter table public.tracker_goals enable row level security;
alter table public.tracker_reminders enable row level security;

do $$
declare table_name text; operation text;
begin
  foreach table_name in array array['trackers','tracker_fields','tracker_entries','tracker_goals','tracker_reminders'] loop
    foreach operation in array array['select','insert','update','delete'] loop
      execute format('drop policy if exists %I on public.%I', table_name || '_owner_' || operation, table_name);
      if operation='insert' then
        execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid())=user_id)', table_name || '_owner_' || operation, table_name);
      elsif operation='update' then
        execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id) with check ((select auth.uid()) is not null and (select auth.uid())=user_id)', table_name || '_owner_' || operation, table_name);
      else
        execute format('create policy %I on public.%I for %s to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id)', table_name || '_owner_' || operation, table_name, operation);
      end if;
    end loop;
  end loop;
end;
$$;

revoke all on public.trackers, public.tracker_fields, public.tracker_entries, public.tracker_goals, public.tracker_reminders from anon;
grant select, insert, update, delete on public.trackers, public.tracker_fields, public.tracker_entries, public.tracker_goals, public.tracker_reminders to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
