begin;

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 200),
  current_amount_minor bigint not null check (current_amount_minor >= 0),
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  billing_interval_value integer not null check (billing_interval_value > 0),
  billing_interval_unit text not null check (billing_interval_unit in ('day','week','month','year')),
  started_on date not null,
  next_renewal_on date not null,
  status text not null default 'active' check (status in ('active','paused','ended')),
  auto_renew boolean not null default true,
  reminder_enabled boolean not null default false,
  reminder_days_before integer not null default 3 check (reminder_days_before between 0 and 3650),
  reminder_time time,
  reminder_id bigint unique references public.reminders(id) on delete set null,
  notes text not null default '' check (char_length(notes) <= 5000),
  paused_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now()),
  unique(id,user_id)
);

create table if not exists public.subscription_payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  subscription_id bigint not null,
  scheduled_for date not null,
  paid_on date not null,
  amount_minor bigint not null check (amount_minor >= 0),
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  note text not null default '' check (char_length(note) <= 5000),
  created_at timestamptz not null default timezone('utc',now()),
  foreign key(subscription_id,user_id) references public.subscriptions(id,user_id) on delete cascade,
  unique(user_id,subscription_id,scheduled_for)
);

create table if not exists public.subscription_price_changes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  subscription_id bigint not null,
  effective_on date not null,
  old_amount_minor bigint not null check (old_amount_minor >= 0),
  new_amount_minor bigint not null check (new_amount_minor >= 0),
  old_currency text not null check (old_currency ~ '^[A-Z]{3}$'),
  new_currency text not null check (new_currency ~ '^[A-Z]{3}$'),
  created_at timestamptz not null default timezone('utc',now()),
  foreign key(subscription_id,user_id) references public.subscriptions(id,user_id) on delete cascade
);

create index if not exists idx_subscriptions_user_status_due on public.subscriptions(user_id,status,next_renewal_on);
create index if not exists idx_subscription_payments_user_subscription on public.subscription_payments(user_id,subscription_id,paid_on desc);
create index if not exists idx_subscription_price_changes_user_subscription on public.subscription_price_changes(user_id,subscription_id,effective_on desc,id desc);
create unique index if not exists idx_subscription_owned_reminder on public.reminders(user_id,source_type,source_id) where source_type='subscription_renewal';

drop trigger if exists subscriptions_set_updated_at on public.subscriptions;
create trigger subscriptions_set_updated_at before update on public.subscriptions for each row execute function public.set_updated_at();

do $$ declare table_name text; operation text; begin
  foreach table_name in array array['subscriptions','subscription_payments','subscription_price_changes'] loop
    execute format('alter table public.%I enable row level security',table_name);
    foreach operation in array array['select','insert','update','delete'] loop
      execute format('drop policy if exists %I on public.%I',table_name||'_owner_'||operation,table_name);
      if operation='insert' then
        execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid())=user_id)',table_name||'_owner_'||operation,table_name);
      elsif operation='update' then
        execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id)',table_name||'_owner_'||operation,table_name);
      else
        execute format('create policy %I on public.%I for %s to authenticated using ((select auth.uid())=user_id)',table_name||'_owner_'||operation,table_name,operation);
      end if;
    end loop;
  end loop;
end $$;

alter table public.reminders drop constraint if exists reminders_target_type_check;
alter table public.reminders add constraint reminders_target_type_check check (target_type in ('cat','cat_household','tracker','health','subscription'));
alter table public.notification_deliveries drop constraint if exists notification_deliveries_target_type_check;
alter table public.notification_deliveries add constraint notification_deliveries_target_type_check check (target_type in ('cat','cat_household','tracker','food','health','subscription'));

create or replace function public.record_subscription_payment(
  p_subscription_id bigint, p_scheduled_for date, p_paid_on date, p_amount_minor bigint,
  p_currency text, p_note text, p_next_renewal_on date, p_update_current_price boolean
) returns public.subscription_payments language plpgsql security invoker set search_path=public as $$
declare current_row public.subscriptions; payment public.subscription_payments;
begin
  select * into current_row from public.subscriptions where id=p_subscription_id and user_id=auth.uid() for update;
  if not found or current_row.status<>'active' then raise exception 'Subscription not found or inactive'; end if;
  if p_update_current_price and (current_row.current_amount_minor<>p_amount_minor or current_row.currency<>p_currency) then
    insert into public.subscription_price_changes(user_id,subscription_id,effective_on,old_amount_minor,new_amount_minor,old_currency,new_currency)
    values(auth.uid(),p_subscription_id,p_paid_on,current_row.current_amount_minor,p_amount_minor,current_row.currency,p_currency);
  end if;
  insert into public.subscription_payments(user_id,subscription_id,scheduled_for,paid_on,amount_minor,currency,note)
  values(auth.uid(),p_subscription_id,p_scheduled_for,p_paid_on,p_amount_minor,p_currency,coalesce(p_note,'')) returning * into payment;
  update public.subscriptions set next_renewal_on=p_next_renewal_on,
    current_amount_minor=case when p_update_current_price then p_amount_minor else current_amount_minor end,
    currency=case when p_update_current_price then p_currency else currency end
  where id=p_subscription_id and user_id=auth.uid();
  return payment;
end $$;

create or replace function public.change_subscription_price(p_subscription_id bigint,p_amount_minor bigint,p_currency text,p_effective_on date)
returns public.subscriptions language plpgsql security invoker set search_path=public as $$
declare current_row public.subscriptions;
begin
  select * into current_row from public.subscriptions where id=p_subscription_id and user_id=auth.uid() for update;
  if not found then raise exception 'Subscription not found'; end if;
  if current_row.current_amount_minor<>p_amount_minor or current_row.currency<>p_currency then
    insert into public.subscription_price_changes(user_id,subscription_id,effective_on,old_amount_minor,new_amount_minor,old_currency,new_currency)
    values(auth.uid(),p_subscription_id,p_effective_on,current_row.current_amount_minor,p_amount_minor,current_row.currency,p_currency);
    update public.subscriptions set current_amount_minor=p_amount_minor,currency=p_currency where id=p_subscription_id and user_id=auth.uid() returning * into current_row;
  end if;
  return current_row;
end $$;

revoke all on public.subscriptions,public.subscription_payments,public.subscription_price_changes from anon;
grant select,insert,update,delete on public.subscriptions,public.subscription_payments,public.subscription_price_changes to authenticated;
grant usage,select on sequence public.subscriptions_id_seq,public.subscription_payments_id_seq,public.subscription_price_changes_id_seq to authenticated;
grant execute on function public.record_subscription_payment(bigint,date,date,bigint,text,text,date,boolean) to authenticated;
grant execute on function public.change_subscription_price(bigint,bigint,text,date) to authenticated;

commit;
