create table public.relation_people (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid(), name text not null,
  nickname text, relation_label text, photo_path text, birthday date, likes text, avoid text, note text, archived_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id)
);
create table public.relation_events (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid(),
  event_type text not null check(event_type in('expense','gift','repayment','favor','interaction')), title text not null, note text,
  occurred_at timestamptz not null, occurred_has_explicit_time boolean not null default false,
  currency text not null default 'CNY' check(currency='CNY'), total_amount_minor bigint check(total_amount_minor is null or total_amount_minor>=0),
  is_in_person boolean, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id)
);
create table public.relation_event_parties (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid(), event_id bigint not null, party_type text not null check(party_type in('self','person')),
  person_id bigint, share_amount_minor bigint check(share_amount_minor is null or share_amount_minor>=0), paid_amount_minor bigint check(paid_amount_minor is null or paid_amount_minor>=0), created_at timestamptz not null default now(),
  foreign key(event_id,user_id) references public.relation_events(id,user_id) on delete cascade,
  foreign key(person_id,user_id) references public.relation_people(id,user_id) on delete restrict,
  check((party_type='self' and person_id is null) or (party_type='person' and person_id is not null)), unique(event_id,person_id)
);
create unique index relation_event_one_self on public.relation_event_parties(event_id) where party_type='self';
create table public.relation_event_items (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid(), event_id bigint not null, label text not null,
  amount_minor bigint not null check(amount_minor>=0), sort_order integer not null default 0,
  foreign key(event_id,user_id) references public.relation_events(id,user_id) on delete cascade
);
create table public.relation_event_flows (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid(), event_id bigint not null,
  from_party_id bigint not null references public.relation_event_parties(id) on delete cascade, to_party_id bigint not null references public.relation_event_parties(id) on delete cascade,
  flow_type text not null check(flow_type in('advance','treat','gift','repayment','favor')), amount_minor bigint not null check(amount_minor>0),
  settles_flow_id bigint references public.relation_event_flows(id) on delete restrict, note text, created_at timestamptz not null default now(),
  foreign key(event_id,user_id) references public.relation_events(id,user_id) on delete cascade, check(from_party_id<>to_party_id)
);
create table public.person_memory_notes (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid(), person_id bigint not null,
  content text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  foreign key(person_id,user_id) references public.relation_people(id,user_id) on delete cascade
);
create index relation_people_active on public.relation_people(user_id,archived_at,name);
create index relation_events_occurred on public.relation_events(user_id,occurred_at desc,id desc);
create index relation_parties_person on public.relation_event_parties(user_id,person_id,event_id);
create trigger relation_people_set_updated_at before update on public.relation_people for each row execute function public.set_updated_at();
create trigger relation_events_set_updated_at before update on public.relation_events for each row execute function public.set_updated_at();
create trigger person_memory_notes_set_updated_at before update on public.person_memory_notes for each row execute function public.set_updated_at();

alter table public.relation_people enable row level security; alter table public.relation_events enable row level security;
alter table public.relation_event_parties enable row level security; alter table public.relation_event_items enable row level security;
alter table public.relation_event_flows enable row level security; alter table public.person_memory_notes enable row level security;
do $$ declare t text; begin foreach t in array array['relation_people','relation_events','relation_event_parties','relation_event_items','relation_event_flows','person_memory_notes'] loop
  execute format('create policy own_all on public.%I for all using (user_id=auth.uid()) with check (user_id=auth.uid())',t);
end loop; end $$;

create or replace function public.save_relation_event(p_event_id bigint,p_payload jsonb) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v_id bigint; p jsonb; i jsonb; f jsonb; v_party_ids jsonb='{}'::jsonb; v_from bigint; v_to bigint; v_total bigint; v_delta bigint; v_coverage bigint; v_advance bigint; v_repaid bigint;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if jsonb_array_length(p_payload->'parties')<2 or (select count(*) from jsonb_array_elements(p_payload->'parties') x where x->>'partyType'='self')<>1 then raise exception 'Exactly one self and at least one person are required'; end if;
  if (select count(*) from jsonb_array_elements(p_payload->'parties'))<>(select count(distinct x->>'key') from jsonb_array_elements(p_payload->'parties') x) then raise exception 'Party keys must be unique'; end if;
  if p_payload->>'eventType'='expense' then
    v_total=(p_payload->>'totalAmountMinor')::bigint;
    if v_total<0 or (select coalesce(sum((x->>'shareAmountMinor')::bigint),0) from jsonb_array_elements(p_payload->'parties') x)<>v_total or (select coalesce(sum((x->>'paidAmountMinor')::bigint),0) from jsonb_array_elements(p_payload->'parties') x)<>v_total then raise exception 'Expense total, shares, and paid amounts must balance'; end if;
    if jsonb_array_length(p_payload->'items')>0 and (select coalesce(sum((x->>'amountMinor')::bigint),0) from jsonb_array_elements(p_payload->'items') x)<>v_total then raise exception 'Expense items must sum to total'; end if;
    for p in select * from jsonb_array_elements(p_payload->'parties') loop
      v_delta=(p->>'paidAmountMinor')::bigint-(p->>'shareAmountMinor')::bigint;
      select coalesce(sum(case when x->>'fromKey'=p->>'key' then (x->>'amountMinor')::bigint when x->>'toKey'=p->>'key' then -(x->>'amountMinor')::bigint else 0 end),0) into v_coverage from jsonb_array_elements(p_payload->'flows') x where x->>'flowType' in('advance','treat');
      if v_delta<>v_coverage then raise exception 'Expense coverage does not match payment delta'; end if;
    end loop;
    if exists(select 1 from jsonb_array_elements(p_payload->'flows') x where x->>'flowType' not in('advance','treat')) then raise exception 'Invalid expense flow type'; end if;
  else
    if p_payload->'totalAmountMinor'<>'null'::jsonb or jsonb_array_length(p_payload->'items')>0 or exists(select 1 from jsonb_array_elements(p_payload->'parties') x where x->'shareAmountMinor'<>'null'::jsonb or x->'paidAmountMinor'<>'null'::jsonb) then raise exception 'Non-expense amounts must be null'; end if;
    if p_payload->>'eventType'='interaction' and jsonb_array_length(p_payload->'flows')<>0 then raise exception 'Interaction cannot have value flows'; end if;
    if p_payload->>'eventType'<>'interaction' and jsonb_array_length(p_payload->'flows')=0 then raise exception 'Value event requires a flow'; end if;
    if exists(select 1 from jsonb_array_elements(p_payload->'flows') x where x->>'flowType'<>p_payload->>'eventType') then raise exception 'Flow type must match event type'; end if;
  end if;
  if exists(select 1 from jsonb_array_elements(p_payload->'flows') x where (x->>'amountMinor')::bigint<=0 or x->>'fromKey'=x->>'toKey') then raise exception 'Flows require positive amounts and distinct parties'; end if;
  for f in select * from jsonb_array_elements(p_payload->'flows') where nullif(value->>'settlesFlowId','') is not null loop
    select amount_minor into v_advance from relation_event_flows where id=(f->>'settlesFlowId')::bigint and user_id=auth.uid() and flow_type='advance';
    if v_advance is null then raise exception 'Repayment can only settle an owned advance'; end if;
    select coalesce(sum(amount_minor),0) into v_repaid from relation_event_flows where settles_flow_id=(f->>'settlesFlowId')::bigint and user_id=auth.uid() and (p_event_id is null or event_id<>p_event_id);
    v_repaid=v_repaid+(select coalesce(sum((x->>'amountMinor')::bigint),0) from jsonb_array_elements(p_payload->'flows') x where x->>'settlesFlowId'=f->>'settlesFlowId');
    if v_repaid>v_advance then raise exception 'Repayment exceeds the advance'; end if;
  end loop;
  if p_event_id is null then
    insert into relation_events(user_id,event_type,title,note,occurred_at,occurred_has_explicit_time,currency,total_amount_minor,is_in_person)
    values(auth.uid(),p_payload->>'eventType',p_payload->>'title',p_payload->>'note',(p_payload->>'occurredAt')::timestamptz,(p_payload->>'occurredHasExplicitTime')::boolean,p_payload->>'currency',nullif(p_payload->>'totalAmountMinor','')::bigint,nullif(p_payload->>'isInPerson','')::boolean) returning id into v_id;
  else
    update relation_events set event_type=p_payload->>'eventType',title=p_payload->>'title',note=p_payload->>'note',occurred_at=(p_payload->>'occurredAt')::timestamptz,occurred_has_explicit_time=(p_payload->>'occurredHasExplicitTime')::boolean,currency=p_payload->>'currency',total_amount_minor=nullif(p_payload->>'totalAmountMinor','')::bigint,is_in_person=nullif(p_payload->>'isInPerson','')::boolean,updated_at=now() where id=p_event_id and user_id=auth.uid() returning id into v_id;
    if v_id is null then return null; end if;
    delete from relation_event_flows where event_id=v_id; delete from relation_event_items where event_id=v_id; delete from relation_event_parties where event_id=v_id;
  end if;
  for p in select * from jsonb_array_elements(p_payload->'parties') loop
    insert into relation_event_parties(user_id,event_id,party_type,person_id,share_amount_minor,paid_amount_minor) values(auth.uid(),v_id,p->>'partyType',nullif(p->>'personId','')::bigint,nullif(p->>'shareAmountMinor','')::bigint,nullif(p->>'paidAmountMinor','')::bigint) returning id into v_from;
    v_party_ids=jsonb_set(v_party_ids,array[p->>'key'],to_jsonb(v_from));
  end loop;
  for i in select * from jsonb_array_elements(p_payload->'items') loop insert into relation_event_items(user_id,event_id,label,amount_minor,sort_order) values(auth.uid(),v_id,i->>'label',(i->>'amountMinor')::bigint,(i->>'sortOrder')::integer); end loop;
  for f in select * from jsonb_array_elements(p_payload->'flows') loop
    v_from=(v_party_ids->>(f->>'fromKey'))::bigint; v_to=(v_party_ids->>(f->>'toKey'))::bigint;
    insert into relation_event_flows(user_id,event_id,from_party_id,to_party_id,flow_type,amount_minor,settles_flow_id,note) values(auth.uid(),v_id,v_from,v_to,f->>'flowType',(f->>'amountMinor')::bigint,nullif(f->>'settlesFlowId','')::bigint,f->>'note');
  end loop;
  return v_id;
end $$;
grant select,insert,update,delete on public.relation_people,public.person_memory_notes to authenticated;
grant select,delete on public.relation_events to authenticated;
grant select on public.relation_event_parties,public.relation_event_items,public.relation_event_flows to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on function public.save_relation_event(bigint,jsonb) to authenticated;
