begin;

alter table public.reminders add column if not exists note text not null default '';
alter table public.reminders add column if not exists lead_time_minutes integer not null default 0;
alter table public.reminders add column if not exists status text not null default 'scheduled';
alter table public.reminders add column if not exists sent_at timestamptz;
alter table public.reminders add column if not exists cancelled_at timestamptz;

do $$ begin
  if not exists (select 1 from pg_constraint where conname='reminders_status_check') then
    alter table public.reminders add constraint reminders_status_check check (status in ('scheduled','sent','cancelled','failed','completed'));
  end if;
  if not exists (select 1 from pg_constraint where conname='reminders_lead_time_check') then
    alter table public.reminders add constraint reminders_lead_time_check check (lead_time_minutes between 0 and 525600);
  end if;
end $$;

update public.reminders set status=case
  when not is_active and last_completed_at is not null then 'completed'
  when not is_active then 'cancelled'
  when last_notified_at is not null then 'sent'
  else 'scheduled'
end;

create table if not exists public.cat_routines (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  scope text not null check (scope in ('cat','household')),
  pet_id bigint,
  title text not null check (char_length(title) between 1 and 200),
  interval_value integer not null check (interval_value > 0),
  interval_unit text not null check (interval_unit in ('day','week','month')),
  first_due_at timestamptz not null,
  last_completed_at timestamptz,
  next_due_at timestamptz not null,
  reminder_lead_minutes integer not null default 0 check (reminder_lead_minutes between 0 and 525600),
  notes text not null default '' check (char_length(notes) <= 5000),
  enabled boolean not null default true,
  reminder_id bigint unique references public.reminders(id) on delete set null,
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now()),
  foreign key(pet_id,user_id) references public.pets(id,user_id) on delete restrict,
  check ((scope='cat' and pet_id is not null) or (scope='household' and pet_id is null)),
  unique(id,user_id)
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  reminder_id bigint references public.reminders(id) on delete set null,
  title text not null,
  source_type text,
  source_id bigint,
  target_type text not null check (target_type in ('cat','cat_household','tracker')),
  target_id bigint,
  scheduled_at timestamptz not null,
  sent_at timestamptz,
  status text not null check (status in ('sent','failed','cancelled')),
  created_at timestamptz not null default timezone('utc',now())
);

insert into public.cat_routines(user_id,scope,pet_id,title,interval_value,interval_unit,first_due_at,last_completed_at,next_due_at,reminder_lead_minutes,notes,enabled,reminder_id)
select r.user_id,case when r.target_type='cat' then 'cat' else 'household' end,r.target_id,r.title,r.interval_value,r.interval_unit,r.starts_at,r.last_completed_at,coalesce(r.next_due_at,r.starts_at),r.lead_time_minutes,r.note,r.is_active,r.id
from public.reminders r
where r.target_type in ('cat','cat_household') and r.schedule_type='interval' and r.interval_value is not null and r.interval_unit in ('day','week','month')
on conflict(reminder_id) do nothing;

update public.reminders r set source_type='cat_routine',source_id=cr.id,status=case when cr.enabled then 'scheduled' else 'cancelled' end
from public.cat_routines cr
where cr.reminder_id=r.id and (r.source_type is null or r.source_type='');

create index if not exists idx_cat_routines_user_scope on public.cat_routines(user_id,scope,enabled,next_due_at);
create index if not exists idx_cat_routines_user_pet on public.cat_routines(user_id,pet_id,enabled,next_due_at);
create index if not exists idx_notification_deliveries_user_time on public.notification_deliveries(user_id,created_at desc);
create index if not exists idx_reminders_user_status_due on public.reminders(user_id,status,is_active,next_due_at);

drop trigger if exists cat_routines_set_updated_at on public.cat_routines;
create trigger cat_routines_set_updated_at before update on public.cat_routines for each row execute function public.set_updated_at();

alter table public.cat_routines enable row level security;
alter table public.notification_deliveries enable row level security;

do $$ declare table_name text; operation text; begin
  foreach table_name in array array['cat_routines','notification_deliveries'] loop
    foreach operation in array array['select','insert','update','delete'] loop
      execute format('drop policy if exists %I on public.%I',table_name||'_owner_'||operation,table_name);
      if operation='insert' then
        execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid())=user_id)',table_name||'_owner_'||operation,table_name);
      elsif operation='update' then
        execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id)',table_name||'_owner_'||operation,table_name);
      else
        execute format('create policy %I on public.%I for %s to authenticated using ((select auth.uid())=user_id)',table_name||'_owner_'||operation,table_name,operation);
      end if;
    end loop;
  end loop;
end $$;

revoke all on public.cat_routines,public.notification_deliveries from anon;
grant select,insert,update,delete on public.cat_routines to authenticated;
grant select,insert on public.notification_deliveries to authenticated;
grant select,insert on public.notification_deliveries to service_role;
grant usage,select on sequence public.cat_routines_id_seq,public.notification_deliveries_id_seq to authenticated;
grant usage,select on sequence public.notification_deliveries_id_seq to service_role;

commit;
