begin;

create table if not exists public.menstrual_periods (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  started_on date not null,
  ended_on date,
  notes text not null default '' check (length(notes) <= 5000),
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now()),
  unique(id,user_id),
  check (ended_on is null or ended_on >= started_on)
);

create table if not exists public.menstrual_flow_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  period_id bigint,
  occurred_at timestamptz not null,
  occurred_has_explicit_time boolean not null default false,
  flow text not null check (flow in ('none','unspecified','light','medium','heavy')),
  is_cycle_start boolean not null default false,
  notes text not null default '' check (length(notes) <= 5000),
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now()),
  foreign key(period_id,user_id) references public.menstrual_periods(id,user_id) on delete restrict,
  check (not is_cycle_start or period_id is not null)
);

create table if not exists public.medication_presets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 200),
  default_dose_text text not null default '' check (length(default_dose_text) <= 200),
  min_reminder_interval_minutes integer not null check (min_reminder_interval_minutes between 1 and 43200),
  reminder_enabled boolean not null default false,
  period_link_enabled boolean not null default false,
  notes text not null default '' check (length(notes) <= 5000),
  archived_at timestamptz,
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now()),
  unique(id,user_id)
);

create table if not exists public.medication_dose_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  medication_preset_id bigint not null,
  period_id bigint,
  taken_at timestamptz not null,
  medication_name_snapshot text not null check (length(trim(medication_name_snapshot)) between 1 and 200),
  dose_text text not null default '' check (length(dose_text) <= 200),
  notes text not null default '' check (length(notes) <= 5000),
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now()),
  foreign key(medication_preset_id,user_id) references public.medication_presets(id,user_id) on delete restrict,
  foreign key(period_id,user_id) references public.menstrual_periods(id,user_id) on delete restrict
);

create index if not exists idx_menstrual_periods_user_started on public.menstrual_periods(user_id,started_on desc,id desc);
create unique index if not exists idx_menstrual_periods_one_open on public.menstrual_periods(user_id) where ended_on is null;
create index if not exists idx_menstrual_flow_user_occurred on public.menstrual_flow_records(user_id,occurred_at desc,id desc);
create index if not exists idx_menstrual_flow_period on public.menstrual_flow_records(user_id,period_id,occurred_at desc);
create unique index if not exists idx_menstrual_flow_cycle_start on public.menstrual_flow_records(user_id,period_id) where is_cycle_start and period_id is not null;
create index if not exists idx_medication_presets_user_active on public.medication_presets(user_id,archived_at,name);
create index if not exists idx_medication_doses_user_taken on public.medication_dose_events(user_id,taken_at desc,id desc);
create index if not exists idx_medication_doses_preset on public.medication_dose_events(user_id,medication_preset_id,taken_at desc);

drop trigger if exists menstrual_periods_set_updated_at on public.menstrual_periods;
create trigger menstrual_periods_set_updated_at before update on public.menstrual_periods for each row execute function public.set_updated_at();
drop trigger if exists menstrual_flow_records_set_updated_at on public.menstrual_flow_records;
create trigger menstrual_flow_records_set_updated_at before update on public.menstrual_flow_records for each row execute function public.set_updated_at();
drop trigger if exists medication_presets_set_updated_at on public.medication_presets;
create trigger medication_presets_set_updated_at before update on public.medication_presets for each row execute function public.set_updated_at();
drop trigger if exists medication_dose_events_set_updated_at on public.medication_dose_events;
create trigger medication_dose_events_set_updated_at before update on public.medication_dose_events for each row execute function public.set_updated_at();

alter table public.menstrual_periods enable row level security;
alter table public.menstrual_flow_records enable row level security;
alter table public.medication_presets enable row level security;
alter table public.medication_dose_events enable row level security;

create policy menstrual_periods_owner_all on public.menstrual_periods for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy menstrual_flow_records_owner_all on public.menstrual_flow_records for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy medication_presets_owner_all on public.medication_presets for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy medication_dose_events_owner_all on public.medication_dose_events for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);

revoke all on public.menstrual_periods,public.menstrual_flow_records,public.medication_presets,public.medication_dose_events from public,anon;
grant select,insert,update,delete on public.menstrual_periods,public.menstrual_flow_records,public.medication_presets,public.medication_dose_events to authenticated,service_role;
grant usage,select on sequence public.menstrual_periods_id_seq,public.menstrual_flow_records_id_seq,public.medication_presets_id_seq,public.medication_dose_events_id_seq to authenticated,service_role;

commit;
