begin;

create table if not exists public.media_series (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 200),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id)
);
create unique index if not exists idx_media_series_user_name on public.media_series(user_id, lower(name));

alter table public.media_items
  add column if not exists status text not null default 'completed',
  add column if not exists is_favorite boolean not null default false,
  add column if not exists series_id bigint,
  add column if not exists season_number integer,
  add column if not exists season_title text;

do $$ begin alter table public.media_items add constraint media_items_status_check check (status in ('planned','watching','completed','paused','dropped')); exception when duplicate_object then null; end $$;
do $$ begin alter table public.media_items add constraint media_items_season_number_check check (season_number is null or season_number between 1 and 999); exception when duplicate_object then null; end $$;
do $$ begin alter table public.media_items add constraint media_items_season_title_check check (season_title is null or char_length(season_title) <= 120); exception when duplicate_object then null; end $$;
do $$ begin alter table public.media_items add constraint media_items_season_type_check check ((season_number is null and season_title is null) or media_type in ('tv','anime')); exception when duplicate_object then null; end $$;
do $$ begin alter table public.media_items add constraint media_items_series_owner_fk foreign key (series_id, user_id) references public.media_series(id, user_id) on delete restrict; exception when duplicate_object then null; end $$;

create index if not exists idx_media_items_user_shelf on public.media_items(user_id, status, media_type, is_favorite, updated_at desc);
create index if not exists idx_media_items_user_series on public.media_items(user_id, series_id, season_number, id);
drop trigger if exists media_series_set_updated_at on public.media_series;
create trigger media_series_set_updated_at before update on public.media_series for each row execute function public.set_updated_at();

alter table public.media_series enable row level security;
drop policy if exists media_series_owner_select on public.media_series;
create policy media_series_owner_select on public.media_series for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists media_series_owner_insert on public.media_series;
create policy media_series_owner_insert on public.media_series for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);
drop policy if exists media_series_owner_update on public.media_series;
create policy media_series_owner_update on public.media_series for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists media_series_owner_delete on public.media_series;
create policy media_series_owner_delete on public.media_series for delete to authenticated using ((select auth.uid()) = user_id);
revoke all on table public.media_series from public, anon;
grant select, insert, update, delete on table public.media_series to authenticated;
revoke all on sequence public.media_series_id_seq from public, anon;
grant usage, select on sequence public.media_series_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('media-covers', 'media-covers', false, 4194304, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=false, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists evaorbit_media_covers_owner_select on storage.objects;
drop policy if exists evaorbit_media_covers_owner_insert on storage.objects;
drop policy if exists evaorbit_media_covers_owner_update on storage.objects;
drop policy if exists evaorbit_media_covers_owner_delete on storage.objects;
create policy evaorbit_media_covers_owner_select on storage.objects for select to authenticated using (bucket_id='media-covers' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy evaorbit_media_covers_owner_insert on storage.objects for insert to authenticated with check (bucket_id='media-covers' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy evaorbit_media_covers_owner_update on storage.objects for update to authenticated using (bucket_id='media-covers' and (storage.foldername(name))[1]=(select auth.uid())::text) with check (bucket_id='media-covers' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy evaorbit_media_covers_owner_delete on storage.objects for delete to authenticated using (bucket_id='media-covers' and (storage.foldername(name))[1]=(select auth.uid())::text);

commit;
