create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 300),
  notes text not null default '' check (char_length(notes) <= 10000),
  start_at text not null,
  end_at text not null,
  is_all_day boolean not null default false,
  timezone text,
  location text not null default '' check (char_length(location) <= 1000),
  status text not null default 'confirmed' check (status in ('confirmed','tentative','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_at > start_at),
  check ((is_all_day and start_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' and end_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$') or (not is_all_day and start_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T' and end_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T'))
);
create index if not exists idx_calendar_events_window on public.calendar_events(user_id,start_at,end_at);
drop trigger if exists set_calendar_events_updated_at on public.calendar_events;
create trigger set_calendar_events_updated_at before update on public.calendar_events for each row execute function public.set_updated_at();
alter table public.calendar_events enable row level security;
create policy calendar_events_owner_all on public.calendar_events for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
grant select,insert,update,delete on public.calendar_events to authenticated;
grant usage,select on sequence public.calendar_events_id_seq to authenticated;

create table if not exists public.eventkit_links (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  installation_id uuid not null,
  entity_type text not null check (entity_type in ('task','calendar_event')),
  eo_id bigint not null,
  eventkit_entity_type text not null check (eventkit_entity_type in ('reminder','event')),
  calendar_item_identifier text not null,
  external_identifier text,
  calendar_identifier text not null,
  source_identifier text not null,
  last_synced_hash text not null,
  last_synced_snapshot jsonb not null,
  apple_last_modified_at timestamptz,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,installation_id,entity_type,eo_id),
  unique(user_id,installation_id,eventkit_entity_type,calendar_item_identifier)
);
create index if not exists idx_eventkit_links_recovery on public.eventkit_links(user_id,installation_id,eventkit_entity_type,external_identifier,calendar_identifier,source_identifier);
drop trigger if exists set_eventkit_links_updated_at on public.eventkit_links;
create trigger set_eventkit_links_updated_at before update on public.eventkit_links for each row execute function public.set_updated_at();
alter table public.eventkit_links enable row level security;
create policy eventkit_links_owner_all on public.eventkit_links for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
grant select,insert,update,delete on public.eventkit_links to authenticated;
grant usage,select on sequence public.eventkit_links_id_seq to authenticated;

alter table public.task_reminders add column if not exists delivery_channel text not null default 'pwa' check(delivery_channel in ('pwa','apple_reminders'));
alter table public.tasks add column if not exists completed_at timestamptz;
