create table if not exists public.daily_journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  date date not null,
  content text not null check (char_length(content) between 1 and 10000),
  mood_score smallint check (mood_score between -2 and 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists daily_journal_entries_user_date_idx
  on public.daily_journal_entries(user_id, date desc, id desc);

alter table public.daily_journal_entries enable row level security;

create policy "Users manage their daily journal entries"
  on public.daily_journal_entries
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select, insert, update, delete on public.daily_journal_entries to authenticated;
grant usage, select on sequence public.daily_journal_entries_id_seq to authenticated;

create trigger daily_journal_entries_set_updated_at
  before update on public.daily_journal_entries
  for each row execute function public.set_updated_at();
