begin;

create table if not exists public.weight_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  occurred_at timestamptz not null,
  occurred_has_explicit_time boolean not null default true,
  weight_kg numeric(6,2) not null check (weight_kg between 20 and 500),
  source text not null default 'manual' check (source in ('manual','apple_health')),
  healthkit_sample_id uuid,
  healthkit_source_bundle text check (healthkit_source_bundle is null or length(healthkit_source_bundle) <= 255),
  healthkit_source_name text check (healthkit_source_name is null or length(healthkit_source_name) <= 255),
  healthkit_sync_identifier text check (healthkit_sync_identifier is null or length(healthkit_sync_identifier) <= 255),
  healthkit_sync_version integer not null default 1 check (healthkit_sync_version >= 1),
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now())
);

create index if not exists idx_weight_records_user_occurred on public.weight_records(user_id,occurred_at desc,id desc);
create unique index if not exists idx_weight_records_healthkit_sample on public.weight_records(user_id,healthkit_sample_id) where healthkit_sample_id is not null;
create unique index if not exists idx_weight_records_healthkit_sync on public.weight_records(user_id,healthkit_sync_identifier) where healthkit_sync_identifier is not null;

create table if not exists public.weight_settings (
  user_id uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  target_weight_kg numeric(6,2) check (target_weight_kg is null or target_weight_kg between 20 and 500),
  reminder_enabled boolean not null default false,
  reminder_time time not null default '08:00',
  updated_at timestamptz not null default timezone('utc',now())
);

alter table public.notification_deliveries drop constraint if exists notification_deliveries_target_type_check;
alter table public.notification_deliveries add constraint notification_deliveries_target_type_check check (target_type in ('cat','cat_household','tracker','food','health'));
create unique index if not exists idx_weight_notification_once on public.notification_deliveries(user_id,scheduled_at) where source_type='weight_missing';

drop trigger if exists weight_records_set_updated_at on public.weight_records;
create trigger weight_records_set_updated_at before update on public.weight_records for each row execute function public.set_updated_at();
drop trigger if exists weight_settings_set_updated_at on public.weight_settings;
create trigger weight_settings_set_updated_at before update on public.weight_settings for each row execute function public.set_updated_at();

alter table public.weight_records enable row level security;
alter table public.weight_settings enable row level security;
create policy weight_records_owner_select on public.weight_records for select to authenticated using ((select auth.uid())=user_id);
create policy weight_records_owner_insert on public.weight_records for insert to authenticated with check ((select auth.uid())=user_id);
create policy weight_records_owner_update on public.weight_records for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy weight_records_owner_delete on public.weight_records for delete to authenticated using ((select auth.uid())=user_id);
create policy weight_settings_owner_select on public.weight_settings for select to authenticated using ((select auth.uid())=user_id);
create policy weight_settings_owner_insert on public.weight_settings for insert to authenticated with check ((select auth.uid())=user_id);
create policy weight_settings_owner_update on public.weight_settings for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);

revoke all on public.weight_records,public.weight_settings from public,anon;
grant select,insert,update,delete on public.weight_records to authenticated;
grant select,insert,update on public.weight_settings to authenticated;
grant select,insert,update,delete on public.weight_records to service_role;
grant select on public.weight_settings to service_role;
grant usage,select on sequence public.weight_records_id_seq to authenticated;
grant usage,select on sequence public.weight_records_id_seq to service_role;

alter table public.native_devices drop constraint if exists native_devices_scopes_check;
alter table public.native_devices alter column scopes set default array['healthkit:energy:write','healthkit:body-mass:write']::text[];
update public.native_devices set scopes=array(select distinct unnest(scopes || array['healthkit:body-mass:write']::text[]));
alter table public.native_devices add constraint native_devices_scopes_check check (scopes <@ array['healthkit:energy:write','healthkit:body-mass:write']::text[]);

create or replace function public.register_native_device(p_installation_id uuid,p_token_hash text)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_token_hash !~ '^[0-9a-f]{64}$' then raise exception 'Invalid token hash'; end if;
  insert into public.native_devices(user_id,installation_id,token_hash,scopes,revoked_at)
  values(auth.uid(),p_installation_id,p_token_hash,array['healthkit:energy:write','healthkit:body-mass:write']::text[],null)
  on conflict(user_id,installation_id) do update set token_hash=excluded.token_hash,scopes=excluded.scopes,revoked_at=null,updated_at=timezone('utc',now());
end; $$;

create or replace function public.ingest_healthkit_body_mass_changes(p_user_id uuid,p_changes jsonb)
returns jsonb language plpgsql security invoker set search_path=public,pg_temp as $$
declare
  change jsonb;
  operation text;
  sample_id uuid;
  sync_id text;
  changed integer;
  accepted integer := 0;
begin
  if jsonb_typeof(p_changes)<>'array' or jsonb_array_length(p_changes)>100 then raise exception 'Invalid body mass batch'; end if;
  for change in select value from jsonb_array_elements(p_changes) loop
    operation:=change->>'operation';
    if operation not in ('upsert','delete') or (change->>'sampleId')!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then raise exception 'Invalid body mass change'; end if;
    sample_id:=(change->>'sampleId')::uuid;
    if operation='delete' then
      update public.weight_records set healthkit_sample_id=null where user_id=p_user_id and healthkit_sample_id=sample_id and source='manual';
      delete from public.weight_records where user_id=p_user_id and healthkit_sample_id=sample_id and source='apple_health';
    else
      if (change->>'occurredAt') is null or (change->>'weightKg')::numeric not between 20 and 500 then raise exception 'Invalid body mass sample'; end if;
      sync_id:=case when (change->>'syncIdentifier')~*'^evaorbit\.weight\.[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then change->>'syncIdentifier' else null end;
      if sync_id is not null and exists(select 1 from public.weight_records where user_id=p_user_id and healthkit_sync_identifier=sync_id) then
        update public.weight_records set occurred_at=(change->>'occurredAt')::timestamptz,occurred_has_explicit_time=true,weight_kg=(change->>'weightKg')::numeric,
          healthkit_sample_id=sample_id,healthkit_source_bundle=nullif(change->>'sourceBundle',''),healthkit_source_name=nullif(change->>'sourceName',''),
          healthkit_sync_version=greatest(healthkit_sync_version,coalesce((change->>'syncVersion')::integer,1))
        where user_id=p_user_id and healthkit_sync_identifier=sync_id;
      else
        insert into public.weight_records(user_id,occurred_at,occurred_has_explicit_time,weight_kg,source,healthkit_sample_id,healthkit_source_bundle,healthkit_source_name,healthkit_sync_identifier,healthkit_sync_version)
        values(p_user_id,(change->>'occurredAt')::timestamptz,true,(change->>'weightKg')::numeric,'apple_health',sample_id,nullif(change->>'sourceBundle',''),nullif(change->>'sourceName',''),sync_id,coalesce((change->>'syncVersion')::integer,1))
        on conflict(user_id,healthkit_sample_id) where healthkit_sample_id is not null do update set occurred_at=excluded.occurred_at,weight_kg=excluded.weight_kg,healthkit_source_bundle=excluded.healthkit_source_bundle,healthkit_source_name=excluded.healthkit_source_name;
      end if;
    end if;
    get diagnostics changed=row_count;
    accepted:=accepted+changed;
  end loop;
  return jsonb_build_object('accepted',accepted,'received',jsonb_array_length(p_changes));
end; $$;

revoke all on function public.ingest_healthkit_body_mass_changes(uuid,jsonb) from public,anon,authenticated;
grant execute on function public.ingest_healthkit_body_mass_changes(uuid,jsonb) to service_role;

commit;
