create table if not exists public.lucius_post_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  post_id bigint not null references public.lucius_posts(id) on delete cascade,
  author text not null check (author in ('user', 'lucius')),
  content text not null check (char_length(btrim(content)) between 1 and 2000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_lucius_post_comments_user_post_created
  on public.lucius_post_comments(user_id, post_id, created_at, id);

drop trigger if exists lucius_post_comments_set_updated_at on public.lucius_post_comments;
create trigger lucius_post_comments_set_updated_at before update on public.lucius_post_comments
for each row execute function public.set_updated_at();

alter table public.lucius_post_comments enable row level security;

drop policy if exists lucius_post_comments_owner_all on public.lucius_post_comments;
create policy lucius_post_comments_owner_all on public.lucius_post_comments for all to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) is not null
    and (select auth.uid()) = user_id
    and exists (
      select 1 from public.lucius_posts
      where lucius_posts.id = lucius_post_comments.post_id
        and lucius_posts.user_id = (select auth.uid())
    )
  );

grant select, insert, delete on table public.lucius_post_comments to authenticated;
grant update (content) on table public.lucius_post_comments to authenticated;
grant usage, select on sequence public.lucius_post_comments_id_seq to authenticated;
