create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 200),
  description text check (description is null or char_length(description) <= 5000),
  status text not null default 'active' check (status in ('active', 'paused', 'archived')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id)
);

create table if not exists public.project_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  project_id bigint not null,
  title text not null check (char_length(btrim(title)) between 1 and 300),
  description text check (description is null or char_length(description) <= 20000),
  type text not null default 'other' check (type in ('feature','bug','ui','migration','research','tech_debt','other')),
  status text not null default 'to_solve' check (status in ('to_solve','doing','blocked','done','verified','dropped')),
  module text check (module is null or char_length(module) <= 120),
  priority text check (priority is null or char_length(priority) <= 60),
  next_step text check (next_step is null or char_length(next_step) <= 5000),
  resolution text check (resolution is null or char_length(resolution) <= 10000),
  created_at timestamptz not null default timezone('utc', now()),
  started_at timestamptz,
  completed_at timestamptz,
  verified_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key (project_id, user_id) references public.projects(id, user_id) on delete restrict
);

create index if not exists idx_projects_user_updated on public.projects(user_id, status, updated_at desc, id desc);
create index if not exists idx_project_items_project_status on public.project_items(user_id, project_id, status, updated_at desc, id desc);
create index if not exists idx_project_items_chronicle on public.project_items(user_id, project_id, verified_at desc, completed_at desc, id desc);

create trigger projects_set_updated_at before update on public.projects for each row execute function public.set_updated_at();
create trigger project_items_set_updated_at before update on public.project_items for each row execute function public.set_updated_at();

alter table public.projects enable row level security;
alter table public.project_items enable row level security;

create policy projects_owner_all on public.projects for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy project_items_owner_all on public.project_items for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

grant select, insert on table public.projects, public.project_items to authenticated;
grant update (name, description, status, updated_at) on table public.projects to authenticated;
grant update (project_id, title, description, type, status, module, priority, next_step, resolution, started_at, completed_at, verified_at) on table public.project_items to authenticated;
grant usage, select on sequence public.projects_id_seq, public.project_items_id_seq to authenticated;
