begin;

create table public.food_places (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 200),
  branch text not null default '' check (length(branch) <= 160),
  category text not null default '' check (length(category) <= 100),
  rating text check (rating is null or rating in ('love','good','neutral','dislike')),
  status text not null default 'occasional' check (status in ('frequent','occasional','paused','avoid','closed')),
  notes text not null default '' check (length(notes) <= 4000),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(id,user_id)
);

create unique index idx_food_places_identity on public.food_places(user_id,lower(name),lower(branch));
create index idx_food_places_active on public.food_places(user_id,archived_at,status,updated_at desc);

create table public.food_dishes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  food_place_id bigint not null,
  name text not null check (length(trim(name)) between 1 and 200),
  category text not null default '' check (length(category) <= 100),
  rating text check (rating is null or rating in ('love','good','neutral','dislike')),
  recommended boolean not null default false,
  notes text not null default '' check (length(notes) <= 4000),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key(food_place_id,user_id) references public.food_places(id,user_id) on delete cascade,
  unique(id,user_id)
);

create unique index idx_food_dishes_identity on public.food_dishes(user_id,food_place_id,lower(name));
create index idx_food_dishes_place_active on public.food_dishes(user_id,food_place_id,archived_at,recommended desc,updated_at desc);

alter table public.food_logs
  add column food_place_id bigint,
  add column food_dish_id bigint,
  add constraint food_logs_food_place_owner_fk foreign key(food_place_id,user_id) references public.food_places(id,user_id) on delete set null (food_place_id),
  add constraint food_logs_food_dish_owner_fk foreign key(food_dish_id,user_id) references public.food_dishes(id,user_id) on delete set null (food_dish_id);

create index idx_food_logs_place_occurred on public.food_logs(user_id,food_place_id,occurred_at desc);
create index idx_food_logs_dish_occurred on public.food_logs(user_id,food_dish_id,occurred_at desc);

create trigger food_places_set_updated_at before update on public.food_places for each row execute function public.set_updated_at();
create trigger food_dishes_set_updated_at before update on public.food_dishes for each row execute function public.set_updated_at();

alter table public.food_places enable row level security;
alter table public.food_dishes enable row level security;

create policy food_places_owner_select on public.food_places for select to authenticated using ((select auth.uid()) = user_id);
create policy food_places_owner_insert on public.food_places for insert to authenticated with check ((select auth.uid()) = user_id);
create policy food_places_owner_update on public.food_places for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy food_places_owner_delete on public.food_places for delete to authenticated using ((select auth.uid()) = user_id);
create policy food_dishes_owner_select on public.food_dishes for select to authenticated using ((select auth.uid()) = user_id);
create policy food_dishes_owner_insert on public.food_dishes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy food_dishes_owner_update on public.food_dishes for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy food_dishes_owner_delete on public.food_dishes for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on public.food_places,public.food_dishes from anon;
grant select,insert,update,delete on public.food_places,public.food_dishes to authenticated;
grant select,insert,update,delete on public.food_places,public.food_dishes to service_role;
grant usage,select on sequence public.food_places_id_seq,public.food_dishes_id_seq to authenticated,service_role;

commit;
