begin;

create table if not exists public.ai_providers (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  provider_type text not null default 'openai-compatible',
  base_url text not null,
  api_key_ciphertext text,
  api_key_iv text,
  api_key_auth_tag text,
  enabled boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  check ((api_key_ciphertext is null and api_key_iv is null and api_key_auth_tag is null) or (api_key_ciphertext is not null and api_key_iv is not null and api_key_auth_tag is not null))
);

create table if not exists public.ai_model_configs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  provider_id bigint not null,
  model_id text not null check (char_length(model_id) between 1 and 200),
  display_name text not null check (char_length(display_name) between 1 and 120),
  enabled boolean not null default true,
  is_default boolean not null default false,
  capabilities jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider_id, model_id),
  unique (id, user_id, provider_id),
  foreign key (provider_id, user_id) references public.ai_providers(id, user_id) on delete cascade
);

create unique index if not exists idx_ai_models_one_default_per_user on public.ai_model_configs(user_id) where is_default;
create index if not exists idx_ai_models_provider on public.ai_model_configs(user_id, provider_id, enabled);

create or replace function public.set_ai_default_model(p_model_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  model_enabled boolean;
  provider_enabled boolean;
begin
  select m.enabled, p.enabled into model_enabled, provider_enabled
  from public.ai_model_configs m
  join public.ai_providers p on p.id=m.provider_id and p.user_id=m.user_id
  where m.id=p_model_id and m.user_id=(select auth.uid());
  if not found then raise exception '模型不存在'; end if;
  if not model_enabled or not provider_enabled then raise exception '只有已启用 Provider 下的已启用模型可以设为默认'; end if;
  update public.ai_model_configs set is_default=false where user_id=(select auth.uid()) and is_default;
  update public.ai_model_configs set is_default=true where id=p_model_id and user_id=(select auth.uid());
end;
$$;

insert into public.ai_providers (user_id, name, provider_type, base_url, api_key_ciphertext, api_key_iv, api_key_auth_tag, enabled, created_at, updated_at)
select s.user_id, s.provider_name, s.provider_preset, s.base_url, s.api_key_ciphertext, s.api_key_iv, s.api_key_auth_tag, s.enabled, s.updated_at, s.updated_at
from public.ai_settings s
where not exists (select 1 from public.ai_providers p where p.user_id=s.user_id);

insert into public.ai_model_configs (user_id, provider_id, model_id, display_name, enabled, is_default, created_at, updated_at)
select s.user_id, p.id, s.model, s.model, s.enabled, true, s.updated_at, s.updated_at
from public.ai_settings s
join lateral (select id from public.ai_providers where user_id=s.user_id order by id limit 1) p on true
where not exists (select 1 from public.ai_model_configs m where m.user_id=s.user_id);

alter table public.chat_sessions
  add column if not exists provider_id bigint,
  add column if not exists model_config_id bigint;
alter table public.chat_messages
  add column if not exists provider_id bigint,
  add column if not exists model_config_id bigint;

update public.chat_sessions s set
  provider_id=m.provider_id,
  model_config_id=m.id,
  model=coalesce(s.model,m.model_id)
from public.ai_model_configs m
where m.user_id=s.user_id and m.is_default and s.model_config_id is null;

update public.chat_messages msg set
  provider_id=m.provider_id,
  model_config_id=m.id
from public.ai_model_configs m
where m.user_id=msg.user_id and m.is_default and msg.role='assistant' and msg.model_config_id is null;

do $$ begin
  alter table public.chat_sessions add constraint chat_sessions_provider_fk foreign key (provider_id, user_id) references public.ai_providers(id, user_id) on delete restrict;
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.chat_sessions add constraint chat_sessions_model_fk foreign key (model_config_id, user_id, provider_id) references public.ai_model_configs(id, user_id, provider_id) on delete restrict;
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.chat_messages add constraint chat_messages_provider_fk foreign key (provider_id, user_id) references public.ai_providers(id, user_id) on delete restrict;
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.chat_messages add constraint chat_messages_model_fk foreign key (model_config_id, user_id, provider_id) references public.ai_model_configs(id, user_id, provider_id) on delete restrict;
exception when duplicate_object then null; end $$;

update public.ai_settings set api_key_ciphertext=null, api_key_iv=null, api_key_auth_tag=null
where api_key_ciphertext is not null or api_key_iv is not null or api_key_auth_tag is not null;

drop trigger if exists ai_providers_set_updated_at on public.ai_providers;
create trigger ai_providers_set_updated_at before update on public.ai_providers for each row execute function public.set_updated_at();
drop trigger if exists ai_model_configs_set_updated_at on public.ai_model_configs;
create trigger ai_model_configs_set_updated_at before update on public.ai_model_configs for each row execute function public.set_updated_at();

alter table public.ai_providers enable row level security;
alter table public.ai_model_configs enable row level security;

do $$
declare table_name text; operation text;
begin
  foreach table_name in array array['ai_providers','ai_model_configs'] loop
    foreach operation in array array['select','insert','update','delete'] loop
      execute format('drop policy if exists %I on public.%I', table_name || '_owner_' || operation, table_name);
      if operation='insert' then
        execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid())=user_id)', table_name || '_owner_' || operation, table_name);
      elsif operation='update' then
        execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id) with check ((select auth.uid()) is not null and (select auth.uid())=user_id)', table_name || '_owner_' || operation, table_name);
      else
        execute format('create policy %I on public.%I for %s to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id)', table_name || '_owner_' || operation, table_name, operation);
      end if;
    end loop;
  end loop;
end;
$$;

revoke all on public.ai_providers, public.ai_model_configs from anon;
grant select, insert, update, delete on public.ai_providers, public.ai_model_configs to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.set_ai_default_model(bigint) to authenticated;

commit;
