begin;

alter table public.reminders drop constraint if exists reminders_target_type_check;
alter table public.reminders add constraint reminders_target_type_check
  check (target_type in ('cat','cat_household','cat_food','tracker','health','subscription','task'));

alter table public.notification_deliveries drop constraint if exists notification_deliveries_target_type_check;
alter table public.notification_deliveries add constraint notification_deliveries_target_type_check
  check (target_type in ('cat','cat_household','cat_food','tracker','food','health','subscription','task'));

create table if not exists public.cat_food_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  brand text not null default '',
  category text not null default 'other' check (category in ('dry','wet','treat','supplement','other')),
  flavor text not null default '',
  notes text not null default '',
  low_stock_threshold_packages integer not null default 1 check (low_stock_threshold_packages >= 0),
  restock_interval_days integer check (restock_interval_days is null or restock_interval_days > 0),
  restock_lead_days integer not null default 7 check (restock_lead_days between 0 and 365),
  restock_reminder_time time,
  restock_reminder_id bigint unique references public.reminders(id) on delete set null,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(id,user_id),
  unique(user_id,name,brand,flavor)
);

create table if not exists public.cat_food_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  item_id bigint not null,
  purchased_on date not null,
  merchant text not null default '',
  package_count integer not null check (package_count > 0),
  remaining_package_count integer not null check (remaining_package_count >= 0 and remaining_package_count <= package_count),
  amount_per_package numeric not null check (amount_per_package > 0),
  amount_unit text not null check (amount_unit in ('g','ml','piece')),
  paid_amount_minor integer not null check (paid_amount_minor >= 0),
  currency text not null default 'CNY' check (currency = 'CNY'),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key(item_id,user_id) references public.cat_food_items(id,user_id) on delete cascade
);

create index if not exists idx_cat_food_items_active on public.cat_food_items(user_id,updated_at desc) where archived_at is null;
create index if not exists idx_cat_food_purchases_item_date on public.cat_food_purchases(user_id,item_id,purchased_on desc,id desc);

drop trigger if exists cat_food_items_set_updated_at on public.cat_food_items;
create trigger cat_food_items_set_updated_at before update on public.cat_food_items for each row execute function public.set_updated_at();
drop trigger if exists cat_food_purchases_set_updated_at on public.cat_food_purchases;
create trigger cat_food_purchases_set_updated_at before update on public.cat_food_purchases for each row execute function public.set_updated_at();

alter table public.cat_food_items enable row level security;
alter table public.cat_food_purchases enable row level security;

do $$
declare table_name text; operation text;
begin
  foreach table_name in array array['cat_food_items','cat_food_purchases'] loop
    foreach operation in array array['select','insert','update','delete'] loop
      execute format('drop policy if exists %I on public.%I', table_name || '_owner_' || operation, table_name);
      if operation = 'insert' then
        execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_owner_' || operation, table_name);
      elsif operation = 'update' then
        execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id) with check ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_owner_' || operation, table_name);
      else
        execute format('create policy %I on public.%I for %s to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_owner_' || operation, table_name, operation);
      end if;
    end loop;
  end loop;
end;
$$;

revoke all on public.cat_food_items,public.cat_food_purchases from anon;
grant select,insert,update,delete on public.cat_food_items,public.cat_food_purchases to authenticated;
grant usage,select on sequence public.cat_food_items_id_seq,public.cat_food_purchases_id_seq to authenticated;

commit;
