begin;

create table if not exists public.pets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  avatar_url text not null default '',
  sex text check (sex is null or sex in ('female','male','unknown')),
  birthday date,
  adoption_date date,
  notes text not null default '' check (char_length(notes) <= 5000),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique(id, user_id)
);

create table if not exists public.cat_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  pet_id bigint,
  event_type text not null check (event_type in ('deworming','grooming','care','note','cleaning','shared_note')),
  occurred_at timestamptz not null,
  title text not null check (char_length(title) between 1 and 200),
  note text not null default '' check (char_length(note) <= 5000),
  source_type text,
  source_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key(pet_id,user_id) references public.pets(id,user_id) on delete restrict
);

create table if not exists public.cat_symptoms (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  pet_id bigint not null,
  occurred_at timestamptz not null,
  title text not null check (char_length(title) between 1 and 200),
  severity text not null default '' check (char_length(severity) <= 60),
  description text not null default '' check (char_length(description) <= 5000),
  body_area text not null default '' check (char_length(body_area) <= 200),
  note text not null default '' check (char_length(note) <= 5000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key(pet_id,user_id) references public.pets(id,user_id) on delete restrict
);

create table if not exists public.vet_visits (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  pet_id bigint not null,
  occurred_at timestamptz not null,
  clinic text not null default '', doctor text not null default '',
  reason text not null check (char_length(reason) between 1 and 500),
  symptoms text not null default '', diagnosis text not null default '', examinations text not null default '',
  treatment text not null default '', prescriptions text not null default '',
  cost double precision check (cost is null or cost >= 0),
  follow_up_at timestamptz,
  notes text not null default '' check (char_length(notes) <= 5000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key(pet_id,user_id) references public.pets(id,user_id) on delete restrict
);

create table if not exists public.cat_medications (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  pet_id bigint not null,
  name text not null check (char_length(name) between 1 and 200),
  dose text not null default '', unit text not null default '', frequency_text text not null default '',
  started_at timestamptz not null, ended_at timestamptz,
  reason text not null default '', active boolean not null default true,
  notes text not null default '' check (char_length(notes) <= 5000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key(pet_id,user_id) references public.pets(id,user_id) on delete restrict,
  check (ended_at is null or ended_at >= started_at)
);

create table if not exists public.cat_measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  pet_id bigint not null,
  occurred_at timestamptz not null,
  measurement_type text not null check (char_length(measurement_type) between 1 and 80),
  value double precision not null, unit text not null check (char_length(unit) between 1 and 40),
  note text not null default '' check (char_length(note) <= 5000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key(pet_id,user_id) references public.pets(id,user_id) on delete restrict
);

create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  target_type text not null check (target_type in ('cat','cat_household','tracker')),
  target_id bigint,
  source_type text, source_id bigint,
  schedule_type text not null check (schedule_type in ('one_time','interval','course')),
  starts_at timestamptz not null,
  next_due_at timestamptz,
  interval_value integer check (interval_value is null or interval_value > 0),
  interval_unit text check (interval_unit is null or interval_unit in ('hour','day','week','month')),
  times_of_day jsonb not null default '[]'::jsonb,
  ends_at timestamptz,
  timezone text not null default 'Asia/Shanghai',
  is_active boolean not null default true,
  last_completed_at timestamptz,
  snoozed_until timestamptz,
  last_notified_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique(id,user_id),
  check ((target_type='cat' and target_id is not null) or target_type<>'cat'),
  check ((schedule_type='one_time') or (interval_value is not null and interval_unit is not null)),
  check (ends_at is null or ends_at >= starts_at)
);

create table if not exists public.reminder_occurrences (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  reminder_id bigint not null,
  action text not null check (action in ('completed','skipped')),
  scheduled_for timestamptz not null,
  acted_at timestamptz not null,
  created_event_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  foreign key(reminder_id,user_id) references public.reminders(id,user_id) on delete cascade
);

create index if not exists idx_pets_user_active on public.pets(user_id,is_active,updated_at desc);
create index if not exists idx_cat_events_user_pet_time on public.cat_events(user_id,pet_id,occurred_at desc);
create index if not exists idx_cat_symptoms_user_pet_time on public.cat_symptoms(user_id,pet_id,occurred_at desc);
create index if not exists idx_vet_visits_user_pet_time on public.vet_visits(user_id,pet_id,occurred_at desc);
create index if not exists idx_cat_medications_user_pet_time on public.cat_medications(user_id,pet_id,started_at desc);
create index if not exists idx_cat_measurements_user_pet_time on public.cat_measurements(user_id,pet_id,occurred_at desc);
create index if not exists idx_reminders_user_due on public.reminders(user_id,is_active,next_due_at);
create index if not exists idx_reminder_occurrences_user_reminder on public.reminder_occurrences(user_id,reminder_id,acted_at desc);

do $$ declare table_name text; begin
  foreach table_name in array array['pets','cat_events','cat_symptoms','vet_visits','cat_medications','cat_measurements','reminders'] loop
    execute format('drop trigger if exists %I on public.%I',table_name||'_set_updated_at',table_name);
    execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()',table_name||'_set_updated_at',table_name);
  end loop;
end $$;

do $$ declare table_name text; operation text; begin
  foreach table_name in array array['pets','cat_events','cat_symptoms','vet_visits','cat_medications','cat_measurements','reminders','reminder_occurrences'] loop
    execute format('alter table public.%I enable row level security',table_name);
    foreach operation in array array['select','insert','update','delete'] loop
      execute format('drop policy if exists %I on public.%I',table_name||'_owner_'||operation,table_name);
      if operation='insert' then
        execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid())=user_id)',table_name||'_owner_'||operation,table_name);
      elsif operation='update' then
        execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id) with check ((select auth.uid()) is not null and (select auth.uid())=user_id)',table_name||'_owner_'||operation,table_name);
      else
        execute format('create policy %I on public.%I for %s to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id)',table_name||'_owner_'||operation,table_name,operation);
      end if;
    end loop;
  end loop;
end $$;

revoke all on public.pets,public.cat_events,public.cat_symptoms,public.vet_visits,public.cat_medications,public.cat_measurements,public.reminders,public.reminder_occurrences from anon;
grant select,insert,update,delete on public.pets,public.cat_events,public.cat_symptoms,public.vet_visits,public.cat_medications,public.cat_measurements,public.reminders,public.reminder_occurrences to authenticated;
grant select,update on public.reminders to service_role;
grant select,delete on public.push_subscriptions to service_role;
grant usage,select on sequence
  public.pets_id_seq,
  public.cat_events_id_seq,
  public.cat_symptoms_id_seq,
  public.vet_visits_id_seq,
  public.cat_medications_id_seq,
  public.cat_measurements_id_seq,
  public.reminders_id_seq,
  public.reminder_occurrences_id_seq
to authenticated;

commit;
