"use client";

import { useState } from "react";
import Link from "next/link";
import { Icon } from "@/components/icons";
import { NativeNotificationControl } from "@/components/native-notification-control";
import { PageHeader } from "@/components/page-header";
import { PushNotificationControl } from "@/components/push-notification-control";
import type { CatRoutine, NotificationDelivery, Pet, Reminder, ScheduledNotification } from "@/lib/types";
import { ReminderEditor } from "../cats/reminder-editor";
import { RoutineEditor } from "../cats/routine-editor";
import { reconcileNativeNotifications } from "@/lib/native-bridge";

type Data = { upcoming: ScheduledNotification[]; routines: CatRoutine[]; reminders: Reminder[]; history: NotificationDelivery[] };
type Tab = "upcoming" | "rules" | "history";
const tabLabel:Record<Tab,string>={upcoming:"即将发生",rules:"规则",history:"记录"};
function dateTime(value: string) { return new Date(value).toLocaleString("zh-CN", { month: "short", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit" }); }
function reminderDate(reminder:Reminder){return reminder.nextDueAt?(reminder.dueHasExplicitTime?dateTime(reminder.nextDueAt):new Date(reminder.nextDueAt).toLocaleDateString("zh-CN",{month:"short",day:"numeric",year:"numeric"})):"没有下次日期";}
function month(value: string) { const date = new Date(value); const now = new Date(); if (date.toDateString() === now.toDateString()) return "今天"; return date.toLocaleDateString("zh-CN", { month: "long", year: "numeric" }); }

export function NotificationsView({ pets, initial }: { pets: Pet[]; initial: Data }) {
  const [data, setData] = useState(initial); const [tab, setTab] = useState<Tab>("upcoming"); const [panel, setPanel] = useState<"new" | "routine" | "reminder" | null>(null); const [selected, setSelected] = useState<ScheduledNotification | null>(null); const [editingRoutine, setEditingRoutine] = useState<CatRoutine>(); const [editingReminder, setEditingReminder] = useState<Reminder>(); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/notifications"); if (response.ok) { const next = await response.json() as Data; setData(next); try { await reconcileNativeNotifications(next.upcoming); } catch { /* Web Push remains the fallback if the native host rejects a sync. */ } } }
  async function cancel(reminder: Reminder) { const label = reminder.sourceType === "cat_routine" ? "Skip this occurrence? The routine will remain." : "Cancel this reminder?"; if (!confirm(label)) return; const response = await fetch(`/api/reminders/${reminder.id}`, { method: "DELETE" }); if (response.ok) { setSelected(null); setMessage(reminder.sourceType === "cat_routine" ? "Occurrence skipped" : "Reminder cancelled"); await load(); } }
  async function complete(reminder:Reminder){const response=await fetch(`/api/reminders/${reminder.id}/complete`,{method:"POST"});if(response.ok){setSelected(null);setMessage(reminder.sourceType==="cat_routine"?"Routine completed":"One-time task completed");await load();}}
  async function toggleReminder(reminder: Reminder) { const enabled = !reminder.isActive; const response = await fetch(`/api/reminders/${reminder.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isActive: enabled, status: enabled ? "scheduled" : "cancelled", cancelledAt: enabled ? null : new Date().toISOString() }) }); if (response.ok) await load(); }
  return <div className="page notifications-page"><PageHeader eyebrow="设置 · 通知" title="Notifications" description="统一管理原生与网页通知。" action={<div className="settings-page-actions"><Link className="settings-back-link" href="/settings">全部设置</Link><button className="button primary" onClick={() => setPanel("new")}><Icon name="plus"/>新增提醒</button></div>}/>{message && <p className="success-banner" role="status">{message}</p>}
    <div className="notification-channels"><NativeNotificationControl /><PushNotificationControl /></div>
    <nav className="notification-tabs" aria-label="通知分类">{(["upcoming", "rules", "history"] as Tab[]).map(value => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{tabLabel[value]}{value === "upcoming" && <span>{data.upcoming.length}</span>}</button>)}</nav>
    {panel === "new" && <ReminderEditor pets={pets} onCancel={() => setPanel(null)} onSaved={() => { setPanel(null); setMessage("Reminder created"); void load(); }}/>}
    {panel === "routine" && editingRoutine && <RoutineEditor pets={pets} editing={editingRoutine} onCancel={() => setPanel(null)} onSaved={value => { setPanel(null); setMessage(value); void load(); }}/>}
    {panel === "reminder" && editingReminder && <ReminderEditor pets={pets} editing={editingReminder} onCancel={() => setPanel(null)} onSaved={() => { setPanel(null); setMessage("Reminder updated"); void load(); }}/>}
    {tab === "upcoming" && <Upcoming items={data.upcoming} selected={selected} onSelect={setSelected} onEdit={item => { if (item.isRoutine) { const routine = data.routines.find(value => value.id === item.sourceId); if (routine) { setEditingRoutine(routine); setPanel("routine"); } } else { setEditingReminder(item); setPanel("reminder"); } }} onComplete={item=>void complete(item)} onCancel={item => void cancel(item)}/>}
    {tab === "rules" && <Rules routines={data.routines} reminders={data.reminders} onEditRoutine={routine => { setEditingRoutine(routine); setPanel("routine"); }} onEditReminder={reminder => { setEditingReminder(reminder); setPanel("reminder"); }} onToggleReminder={reminder => void toggleReminder(reminder)} onDeleteRoutine={async routine => { if (!confirm(`Delete routine “${routine.title}”?`)) return; if ((await fetch(`/api/cats/routines/${routine.id}`, { method: "DELETE" })).ok) { setMessage("Routine deleted"); await load(); } }}/>}
    {tab === "history" && <History items={data.history}/>}
  </div>;
}

function Upcoming({ items, selected, onSelect, onEdit, onComplete, onCancel }: { items: ScheduledNotification[]; selected: ScheduledNotification | null; onSelect: (item: ScheduledNotification | null) => void; onEdit: (item: ScheduledNotification) => void; onComplete:(item:ScheduledNotification)=>void; onCancel: (item: ScheduledNotification) => void }) { let current = ""; return <section className="notification-list">{items.length ? items.map(item => { const group = month(item.scheduledAt); const heading = group !== current; current = group; return <div key={item.id}>{heading && <h2>{group}</h2>}<article className={selected?.id === item.id ? "expanded" : ""}><button className="notification-row-main" onClick={() => onSelect(selected?.id === item.id ? null : item)}><time>{new Date(item.scheduledAt).toLocaleDateString("en-US", { month: "short", day: "numeric" })}<small>{item.dueHasExplicitTime?new Date(item.scheduledAt).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" }):"Date only"}</small></time><span><strong>{item.subjectLabel} · {item.title}</strong><small>{item.sourceLabel}{item.dueHasExplicitTime?(item.leadTimeMinutes ? ` · ${item.leadTimeMinutes / 60}h before` : " · At due time"):" · No push time"}</small></span><Icon name="arrow"/></button>{selected?.id === item.id && <div className="notification-detail"><dl><div><dt>Status</dt><dd>{item.status}</dd></div><div><dt>Due</dt><dd>{reminderDate(item)}</dd></div><div><dt>Source</dt><dd>{item.sourceLabel}</dd></div>{item.note && <div><dt>Note</dt><dd>{item.note}</dd></div>}</dl><div className="page-actions"><button className="button secondary" onClick={() => onEdit(item)}>{item.isRoutine ? "Edit routine" : "Edit"}</button><button className="button primary compact" onClick={()=>onComplete(item)}>Done</button><button className="text-button danger" onClick={() => onCancel(item)}>{item.isRoutine ? "Skip this reminder" : "Cancel reminder"}</button></div></div>}</article></div>; }) : <div className="notifications-empty"><Icon name="history"/><strong>Nothing scheduled</strong><p>Future reminders will appear here immediately after you create them.</p></div>}</section>; }

function Rules({ routines, reminders, onEditRoutine, onEditReminder, onToggleReminder, onDeleteRoutine }: { routines: CatRoutine[]; reminders: Reminder[]; onEditRoutine: (item: CatRoutine) => void; onEditReminder: (item: Reminder) => void; onToggleReminder: (item: Reminder) => void; onDeleteRoutine: (item: CatRoutine) => void }) { return <section className="notification-rules"><div className="section-heading compact"><span className="eyebrow">ROUTINES</span></div>{routines.map(item => <article key={`routine-${item.id}`}><div><strong>{item.scope === "household" ? "Household" : "Cats"} · {item.title}</strong><small>Every {item.intervalValue} {item.intervalUnit}{item.intervalValue === 1 ? "" : "s"} · {item.reminderLeadMinutes ? `${item.reminderLeadMinutes / 60}h before` : "At due time"}</small></div><span className={item.enabled ? "status-pill" : "status-pill disabled"}>{item.enabled ? "Enabled" : "Disabled"}</span><div><button className="text-button" onClick={() => onEditRoutine(item)}>Edit</button><button className="danger-icon" onClick={() => onDeleteRoutine(item)}><Icon name="trash"/></button></div></article>)}<div className="section-heading compact standalone-heading"><span className="eyebrow">ONE-OFF & LEGACY</span></div>{reminders.map(item => <article key={`reminder-${item.id}`}><div><strong>{item.title}</strong><small>{reminderDate(item)}</small></div><button className={item.isActive ? "status-pill" : "status-pill disabled"} onClick={() => onToggleReminder(item)}>{item.isActive ? "Enabled" : "Disabled"}</button><button className="text-button" onClick={() => onEditReminder(item)}>Edit</button></article>)}</section>; }

function History({ items }: { items: NotificationDelivery[] }) { return <section className="notification-history">{items.length ? items.map(item => <article key={item.id}><span className={`history-dot ${item.status}`}/><div><strong>{item.title}</strong><small>{item.sourceType?.replaceAll("_", " ") ?? "Notification"} · {dateTime(item.sentAt ?? item.createdAt)}</small></div><span className="status-pill">{item.status}</span></article>) : <div className="notifications-empty"><Icon name="history"/><strong>No delivery history yet</strong><p>Sent, failed, and cancelled notifications will be kept here.</p></div>}</section>; }
