"use client";

import { useCallback,useEffect,useState } from "react";
import { eventKitSupported,getNativeHostInfo,nativeCall } from "@/lib/native-bridge";
import { synchronizeEventKit,type EventKitModes,type EventKitReminderDomain,type EventKitReminderRoutes,type EventKitSource,type EventKitStatus,type EventKitSyncMode } from "@/lib/eventkit-sync";

const key="evaorbit.eventkit.sources.v1",routeKey="evaorbit.eventkit.routes.v1",lastKey="evaorbit.eventkit.last-sync.v1",domains:Array<[EventKitReminderDomain,string]>=[["tasks","Tasks"],["cats","Cats"],["cat_household","Cats · Household"],["trackers","Trackers"],["health","Health"],["subscriptions","Subscriptions"]];
function storedModes():EventKitModes{try{return JSON.parse(localStorage.getItem(key)??"{}") as EventKitModes;}catch{return{};}}
function storedRoutes(modes?:EventKitModes,lists:EventKitSource[]=[]):EventKitReminderRoutes{try{const saved=localStorage.getItem(routeKey);if(saved)return JSON.parse(saved) as EventKitReminderRoutes;const legacy=lists.find(source=>modes?.[source.identifier]==="two_way")?.identifier,routes=legacy?{tasks:legacy}:{};localStorage.setItem(routeKey,JSON.stringify(routes));return routes;}catch{return{};}}
export function AppleIntegrationSection(){const[status,setStatus]=useState<EventKitStatus|null>(null),[modes,setModes]=useState<EventKitModes>({}),[routes,setRoutes]=useState<EventKitReminderRoutes>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[lastSync,setLastSync]=useState<string|null>(null);
  const refresh=useCallback(async()=>{const info=await getNativeHostInfo();if(!eventKitSupported(info)){setStatus(null);return;}const nextStatus=await nativeCall<EventKitStatus>("eventkit.getStatus"),nextModes=storedModes();setStatus(nextStatus);setModes(nextModes);setRoutes(storedRoutes(nextModes,nextStatus.reminderLists));setLastSync(localStorage.getItem(lastKey));},[]);
  const sync=useCallback(async(silent=false)=>{if(!status)return;setBusy(true);if(!silent){setError("");setMessage("");}try{const result=await synchronizeEventKit(status,storedModes(),storedRoutes());setLastSync(result.lastSync);localStorage.setItem(lastKey,result.lastSync);if(!silent)setMessage(`完成：导入 ${result.imported}，写入 Apple ${result.exported}，合并 ${result.merged}${result.conflicts.length?`；${result.conflicts.length} 个冲突需处理`:""}`);}catch(cause){if(!silent)setError(cause instanceof Error?cause.message:"同步失败");}finally{setBusy(false);}},[status]);
  useEffect(()=>{const initial=window.setTimeout(()=>void refresh(),0),ready=()=>void refresh(),active=()=>void sync(true),changed=()=>void sync(true);window.addEventListener("evaorbit:native-ready",ready);window.addEventListener("evaorbit:native-active",active);window.addEventListener("evaorbit:eventkit-store-changed",changed);return()=>{window.clearTimeout(initial);window.removeEventListener("evaorbit:native-ready",ready);window.removeEventListener("evaorbit:native-active",active);window.removeEventListener("evaorbit:eventkit-store-changed",changed);};},[refresh,sync]);
  function setMode(source:EventKitSource,mode:EventKitSyncMode){const value=source.allowsContentModifications?mode:mode==="two_way"?"import":mode,next={...modes,[source.identifier]:value},nextRoutes=value==="two_way"?routes:Object.fromEntries(Object.entries(routes).filter(([,identifier])=>identifier!==source.identifier)) as EventKitReminderRoutes;setModes(next);setRoutes(nextRoutes);localStorage.setItem(key,JSON.stringify(next));localStorage.setItem(routeKey,JSON.stringify(nextRoutes));}
  function setRoute(domain:EventKitReminderDomain,identifier:string){const nextRoutes={...routes,[domain]:identifier||undefined},nextModes={...modes},previous=routes[domain];if(previous&&!Object.values(nextRoutes).includes(previous)&&nextModes[previous]==="two_way")nextModes[previous]="off";if(identifier)nextModes[identifier]="two_way";setRoutes(nextRoutes);setModes(nextModes);localStorage.setItem(routeKey,JSON.stringify(nextRoutes));localStorage.setItem(key,JSON.stringify(nextModes));}
  async function request(kind:"calendar"|"reminder"){setBusy(true);setError("");try{setStatus(await nativeCall<EventKitStatus>("eventkit.requestAccess",{kind}));}catch(cause){setError(cause instanceof Error?cause.message:"权限请求失败");}finally{setBusy(false);}}
  if(!status)return <section className="apple-health-section"><p className="apple-health-fallback">请在支持 EventKit 的 EvaOrbit iOS Host 中打开此页。</p></section>;
  return <section className="apple-health-section eventkit-section"><div className="apple-health-heading"><div><span className="eyebrow">EVENTKIT</span><h2>Apple Integration</h2><p>Off 只暂停同步并保留两侧数据。Calendar 可导入或双向同步；Reminder routes 只把 EO domain 写入指定 List，不导入其中无 EO 关联的私人提醒。默认只同步 Due，不创建 Apple alert。</p></div><span className="status-pill">Native Host</span></div>
    <Permission title="Calendar" permission={status.calendarPermission} disabled={busy} onRequest={()=>void request("calendar")}/><Sources kind="calendar" items={status.calendars} modes={modes} onMode={setMode}/>
    <Permission title="Reminders" permission={status.reminderPermission} disabled={busy} onRequest={()=>void request("reminder")}/><Sources kind="reminder" items={status.reminderLists} modes={modes} onMode={setMode}/><DomainRoutes items={status.reminderLists} routes={routes} onRoute={setRoute}/>
    {error&&<p className="form-error">{error}</p>}{message&&<p className="form-success">{message}</p>}<div className="apple-health-actions"><button className="button primary" disabled={busy} onClick={()=>void sync()}>{busy?"Syncing…":"Sync now"}</button><small>{lastSync?`Last sync ${new Date(lastSync).toLocaleString()}`:"Not synced yet"}</small></div>
  </section>;}
function Permission({title,permission,disabled,onRequest}:{title:string;permission:string;disabled:boolean;onRequest:()=>void}){const granted=["authorized","full_access"].includes(permission);return <div className="apple-health-heading"><div><h3>{title}</h3><p>Permission: {permission.replaceAll("_"," ")}</p></div>{!granted&&<button className="button secondary" disabled={disabled||permission==="denied"||permission==="restricted"} onClick={onRequest}>Request access</button>}</div>;}
function Sources({kind,items,modes,onMode}:{kind:"calendar"|"reminder";items:EventKitSource[];modes:EventKitModes;onMode:(source:EventKitSource,mode:EventKitSyncMode)=>void}){return <div className="apple-health-metrics eventkit-sources">{items.map(source=><div className="eventkit-source" key={source.identifier}><div className="eventkit-source-copy"><strong>{source.title}</strong><span>{source.sourceTitle} · {source.allowsContentModifications?"Read/write":"Read only"}</span></div><select aria-label={`${source.title} sync mode`} value={modes[source.identifier]??"off"} onChange={event=>onMode(source,event.target.value as EventKitSyncMode)}><option value="off">Off</option><option value="import">{kind==="reminder"?"Import all":"Import only"}</option>{source.allowsContentModifications&&<option value="two_way">{kind==="reminder"?"EO route enabled":"Two-way"}</option>}</select></div>)}</div>;}
function DomainRoutes({items,routes,onRoute}:{items:EventKitSource[];routes:EventKitReminderRoutes;onRoute:(domain:EventKitReminderDomain,identifier:string)=>void}){const writable=items.filter(item=>item.allowsContentModifications);return <><div className="apple-health-heading"><div><h3>EO → Reminder List</h3><p>每个 EO domain 可独立选择目标 List；未选择则不写入 Apple。</p></div></div><div className="apple-health-metrics eventkit-sources">{domains.map(([domain,label])=><label className="eventkit-source" key={domain}><span className="eventkit-source-copy"><strong>{label}</strong><span>Due only · no Apple alert</span></span><select aria-label={`${label} Apple Reminder List`} value={routes[domain]??""} onChange={event=>onRoute(domain,event.target.value)}><option value="">Not routed</option>{writable.map(source=><option value={source.identifier} key={source.identifier}>{source.title} · {source.sourceTitle}</option>)}</select></label>)}</div></>}
