"use client";

import { useCallback,useEffect,useState } from "react";
import { eventKitSupported,getNativeHostInfo,nativeCall } from "@/lib/native-bridge";
import { synchronizeEventKit,type EventKitModes,type EventKitSource,type EventKitStatus,type EventKitSyncMode } from "@/lib/eventkit-sync";

const key="evaorbit.eventkit.sources.v1",lastKey="evaorbit.eventkit.last-sync.v1";
function storedModes():EventKitModes{try{return JSON.parse(localStorage.getItem(key)??"{}") as EventKitModes;}catch{return{};}}
export function AppleIntegrationSection(){const[status,setStatus]=useState<EventKitStatus|null>(null),[modes,setModes]=useState<EventKitModes>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[lastSync,setLastSync]=useState<string|null>(null);
  const refresh=useCallback(async()=>{const info=await getNativeHostInfo();if(!eventKitSupported(info)){setStatus(null);return;}setStatus(await nativeCall<EventKitStatus>("eventkit.getStatus"));setModes(storedModes());setLastSync(localStorage.getItem(lastKey));},[]);
  const sync=useCallback(async(silent=false)=>{if(!status)return;setBusy(true);if(!silent){setError("");setMessage("");}try{const result=await synchronizeEventKit(status,storedModes());setLastSync(result.lastSync);localStorage.setItem(lastKey,result.lastSync);if(!silent)setMessage(`完成：导入 ${result.imported}，写入 Apple ${result.exported}，合并 ${result.merged}${result.conflicts.length?`；${result.conflicts.length} 个冲突需处理`:""}`);}catch(cause){if(!silent)setError(cause instanceof Error?cause.message:"同步失败");}finally{setBusy(false);}},[status]);
  useEffect(()=>{const initial=window.setTimeout(()=>void refresh(),0),ready=()=>void refresh(),active=()=>void sync(true),changed=()=>void sync(true);window.addEventListener("evaorbit:native-ready",ready);window.addEventListener("evaorbit:native-active",active);window.addEventListener("evaorbit:eventkit-store-changed",changed);return()=>{window.clearTimeout(initial);window.removeEventListener("evaorbit:native-ready",ready);window.removeEventListener("evaorbit:native-active",active);window.removeEventListener("evaorbit:eventkit-store-changed",changed);};},[refresh,sync]);
  function setMode(source:EventKitSource,mode:EventKitSyncMode){const next={...modes,[source.identifier]:source.allowsContentModifications?mode:mode==="two_way"?"import":mode};setModes(next);localStorage.setItem(key,JSON.stringify(next));}
  async function request(kind:"calendar"|"reminder"){setBusy(true);setError("");try{setStatus(await nativeCall<EventKitStatus>("eventkit.requestAccess",{kind}));}catch(cause){setError(cause instanceof Error?cause.message:"权限请求失败");}finally{setBusy(false);}}
  if(!status)return <section className="apple-health-section"><p className="apple-health-fallback">请在支持 EventKit 的 EvaOrbit iOS Host 中打开此页。</p></section>;
  return <section className="apple-health-section"><div className="apple-health-heading"><div><span className="eyebrow">EVENTKIT</span><h2>Apple Integration</h2><p>Off 不读取；Import only 只导入；Two-way 才会写回 Apple。只读来源固定为 Import only。</p></div><span className="status-pill">Native Host</span></div>
    <Permission title="Calendar" permission={status.calendarPermission} disabled={busy} onRequest={()=>void request("calendar")}/><Sources items={status.calendars} modes={modes} onMode={setMode}/>
    <Permission title="Reminders" permission={status.reminderPermission} disabled={busy} onRequest={()=>void request("reminder")}/><Sources items={status.reminderLists} modes={modes} onMode={setMode}/>
    {error&&<p className="form-error">{error}</p>}{message&&<p className="form-success">{message}</p>}<div className="apple-health-actions"><button className="button primary" disabled={busy} onClick={()=>void sync()}>{busy?"Syncing…":"Sync now"}</button><small>{lastSync?`Last sync ${new Date(lastSync).toLocaleString()}`:"Not synced yet"}</small></div>
  </section>;}
function Permission({title,permission,disabled,onRequest}:{title:string;permission:string;disabled:boolean;onRequest:()=>void}){const granted=["authorized","full_access"].includes(permission);return <div className="apple-health-heading"><div><h3>{title}</h3><p>Permission: {permission.replaceAll("_"," ")}</p></div>{!granted&&<button className="button secondary" disabled={disabled||permission==="denied"||permission==="restricted"} onClick={onRequest}>Request access</button>}</div>;}
function Sources({items,modes,onMode}:{items:EventKitSource[];modes:EventKitModes;onMode:(source:EventKitSource,mode:EventKitSyncMode)=>void}){return <div className="apple-health-metrics">{items.map(source=><div key={source.identifier}><strong>{source.title}</strong><span>{source.sourceTitle} · {source.allowsContentModifications?"Read/write":"Read only"}</span><select aria-label={`${source.title} sync mode`} value={modes[source.identifier]??"off"} onChange={event=>onMode(source,event.target.value as EventKitSyncMode)}><option value="off">Off</option><option value="import">Import only</option>{source.allowsContentModifications&&<option value="two_way">Two-way</option>}</select></div>)}</div>;}
