"use client";
import { ToastNotice } from "@/components/action-toast";

import { useCallback,useEffect,useState } from "react";
import { eventKitSupported,getNativeHostInfo,nativeCall } from "@/lib/native-bridge";
import { eventKitCalendarReadModes,synchronizeEventKit,type EventKitModes,type EventKitReminderDomain,type EventKitReminderRoutes,type EventKitSource,type EventKitStatus,type EventKitSyncMode } from "@/lib/eventkit-sync";
import { eventKitSourcesKey as key,eventKitRoutesKey as routeKey,eventKitLastSyncKey as lastKey,eventKitConfigChanged,eventKitSyncFinished,storedEventKitModes as storedModes,storedEventKitRoutes as storedRoutes } from "@/lib/eventkit-auto-sync";

const domains:Array<[EventKitReminderDomain,string]>=[["tasks","Tasks"],["cats","Cats"],["cat_household","Cats · Household"],["trackers","Trackers"],["health","Health"],["subscriptions","Subscriptions"]];
export function AppleIntegrationSection(){const[status,setStatus]=useState<EventKitStatus|null>(null),[modes,setModes]=useState<EventKitModes>({}),[routes,setRoutes]=useState<EventKitReminderRoutes>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[lastSync,setLastSync]=useState<string|null>(null);
  const refresh=useCallback(async()=>{const info=await getNativeHostInfo();if(!eventKitSupported(info)){setStatus(null);return;}const nextStatus=await nativeCall<EventKitStatus>("eventkit.getStatus"),nextModes=eventKitCalendarReadModes(nextStatus.calendars,storedModes());localStorage.setItem(key,JSON.stringify(nextModes));setStatus(nextStatus);setModes(nextModes);setRoutes(storedRoutes(nextModes,nextStatus.reminderLists));setLastSync(localStorage.getItem(lastKey));},[]);
  const sync=useCallback(async(silent=false)=>{if(!status)return;setBusy(true);if(!silent){setError("");setMessage("");}try{const result=await synchronizeEventKit(status,storedModes(),storedRoutes());setLastSync(result.lastSync);localStorage.setItem(lastKey,result.lastSync);if(!silent){const skipped=result.skippedEvents[0];setMessage(`完成：导入 ${result.imported}，写入 Apple ${result.exported}，合并 ${result.merged}${result.conflicts.length?`；${result.conflicts.length} 个冲突需处理`:""}${skipped?`；跳过 ${result.skippedEvents.length} 条时间异常事件：${skipped.calendarTitle} / ${skipped.title}（${skipped.startAt} → ${skipped.endAt}）`:""}`);}}catch(cause){if(!silent)setError(cause instanceof Error?cause.message:"同步失败");}finally{setBusy(false);}},[status]);
  useEffect(()=>{const initial=window.setTimeout(()=>void refresh(),0),ready=()=>void refresh(),finished=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.error)setError(detail.error);else{setError("");setLastSync(localStorage.getItem(lastKey));}};window.addEventListener("evaorbit:native-ready",ready);window.addEventListener(eventKitSyncFinished,finished);return()=>{window.clearTimeout(initial);window.removeEventListener("evaorbit:native-ready",ready);window.removeEventListener(eventKitSyncFinished,finished);};},[refresh]);
  useEffect(()=>{window.dispatchEvent(new Event(eventKitConfigChanged));},[modes,routes,status]);
  function setMode(kind:"calendar"|"reminder",source:EventKitSource,mode:EventKitSyncMode){const value=kind==="calendar"?mode==="off"?"off":"import":source.allowsContentModifications?mode:mode==="two_way"?"import":mode,next={...modes,[source.identifier]:value},nextRoutes=value==="two_way"?routes:Object.fromEntries(Object.entries(routes).filter(([,identifier])=>identifier!==source.identifier)) as EventKitReminderRoutes;setModes(next);setRoutes(nextRoutes);localStorage.setItem(key,JSON.stringify(next));localStorage.setItem(routeKey,JSON.stringify(nextRoutes));}
  function setRoute(domain:EventKitReminderDomain,identifier:string){const nextRoutes={...routes,[domain]:identifier||undefined},nextModes={...modes},previous=routes[domain];if(previous&&!Object.values(nextRoutes).includes(previous)&&nextModes[previous]==="two_way")nextModes[previous]="off";if(identifier)nextModes[identifier]="two_way";setRoutes(nextRoutes);setModes(nextModes);localStorage.setItem(routeKey,JSON.stringify(nextRoutes));localStorage.setItem(key,JSON.stringify(nextModes));}
  async function request(kind:"calendar"|"reminder"){setBusy(true);setError("");try{setStatus(await nativeCall<EventKitStatus>("eventkit.requestAccess",{kind}));}catch(cause){setError(cause instanceof Error?cause.message:"权限请求失败");}finally{setBusy(false);}}
  if(!status)return <section className="apple-health-section"><p className="apple-health-fallback">请在支持 EventKit 的 EvaOrbit iOS Host 中打开此页。</p></section>;
  return <section className="apple-health-section eventkit-section"><div className="apple-health-heading"><div><span className="eyebrow">EVENTKIT</span><h2>Apple Integration</h2><p>Off 只暂停同步并保留两侧数据。Calendar 从 2026-10-01 起只读 Apple 数据，EO 不会写入、修改或删除 Apple Event；Reminder routes 只把 EO domain 写入指定 List，不导入其中无 EO 关联的私人提醒。带明确时间的 Due 会创建普通到点通知。</p></div><span className="status-pill">Native Host</span></div>
    <p className="apple-health-fallback">已选来源会在启动、回到前台和 Apple 数据变化时自动同步；前台在线每 60 秒补偿同步，无需停留在此页。标题包含“续火花”的 Reminder 不参与同步，已有数据保留。App 不运行时不保证即时同步。</p>
    <Permission title="Calendar" permission={status.calendarPermission} disabled={busy} onRequest={()=>void request("calendar")}/><Sources kind="calendar" items={status.calendars} modes={modes} onMode={(source,mode)=>setMode("calendar",source,mode)}/>
    <Permission title="Reminders" permission={status.reminderPermission} disabled={busy} onRequest={()=>void request("reminder")}/><Sources kind="reminder" items={status.reminderLists} modes={modes} onMode={(source,mode)=>setMode("reminder",source,mode)}/><DomainRoutes items={status.reminderLists} routes={routes} onRoute={setRoute}/>
    {error&&<p className="form-error">{error}</p>}{message&&<ToastNotice message={message} onShown={() => setMessage("")} />}<div className="apple-health-actions"><button className="button primary" disabled={busy} onClick={()=>void sync()}>{busy?"Syncing…":"Sync now"}</button><small>{lastSync?`Last sync ${new Date(lastSync).toLocaleString()}`:"Not synced yet"}</small></div>
  </section>;}
function Permission({title,permission,disabled,onRequest}:{title:string;permission:string;disabled:boolean;onRequest:()=>void}){const granted=["authorized","full_access"].includes(permission);return <div className="apple-health-heading"><div><h3>{title}</h3><p>Permission: {permission.replaceAll("_"," ")}</p></div>{!granted&&<button className="button secondary" disabled={disabled||permission==="denied"||permission==="restricted"} onClick={onRequest}>Request access</button>}</div>;}
function Sources({kind,items,modes,onMode}:{kind:"calendar"|"reminder";items:EventKitSource[];modes:EventKitModes;onMode:(source:EventKitSource,mode:EventKitSyncMode)=>void}){return <div className="apple-health-metrics eventkit-sources">{items.map(source=><div className="eventkit-source" key={source.identifier}><div className="eventkit-source-copy"><strong>{source.title}</strong><span>{source.sourceTitle} · {kind==="calendar"||!source.allowsContentModifications?"Read only":"Read/write"}</span></div><select aria-label={`${source.title} sync mode`} value={modes[source.identifier]??"off"} onChange={event=>onMode(source,event.target.value as EventKitSyncMode)}><option value="off">Off</option><option value="import">{kind==="reminder"?"Import all":"Import only"}</option>{kind==="reminder"&&source.allowsContentModifications&&<option value="two_way">EO route enabled</option>}</select></div>)}</div>;}
function DomainRoutes({items,routes,onRoute}:{items:EventKitSource[];routes:EventKitReminderRoutes;onRoute:(domain:EventKitReminderDomain,identifier:string)=>void}){const writable=items.filter(item=>item.allowsContentModifications);return <><div className="apple-health-heading"><div><h3>EO → Reminder List</h3><p>每个 EO domain 可独立选择目标 List；未选择则不写入 Apple。</p></div></div><div className="apple-health-metrics eventkit-sources">{domains.map(([domain,label])=><label className="eventkit-source" key={domain}><span className="eventkit-source-copy"><strong>{label}</strong><span>Timed Due · standard Apple alert</span></span><select aria-label={`${label} Apple Reminder List`} value={routes[domain]??""} onChange={event=>onRoute(domain,event.target.value)}><option value="">Not routed</option>{writable.map(source=><option value={source.identifier} key={source.identifier}>{source.title} · {source.sourceTitle}</option>)}</select></label>)}</div></>}
